### ISSUE TITLE
Support for Rename Tokens + Original Title when using Manual Import and Release Group is Missing

### ISSUE THREAD

**Issue by SF4L** [Sonarr/Sonarr#5013] opened 2022-05-03 16:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Long story short -- My current naming scheme is: ```{Series CleanTitle} - S{season:00}E{episode:00} - {Episode CleanTitle} - [{Original Title}]``` and I've noticed that recently, Manual Import doesn't fill in the Original Title consistently, just leaves me with empty brackets.

I think being able to preserve the Original Title or Original Filename is valuable for a few reasons:
1) Re-seeding
2) Disambiguation
3) Ability to keep some level of sanity when folks move stuff around on TVDB

I think being able to combine it with other renaming tokens is essential for Plex & Sonarr (more on this a bit later).

Suppose we have a release of TV show "Show" with episodes "Alex" "Bob" "Charlie" "David" "Edgar" and "Frank"

On May 3rd, TVDB says the episodes are actually in order:
1. Alex 
2. Charlie
3. David
4. Frank
5. Edgar

And Bob is listed as a Special 0x01.

But a P2P group released them as a season pack with Show.S01E01.Alex.mkv, Show.S01E02.Bob.mkv, Show.S01E03.Charlie.mkv, Show.S01E04.David.mkv, Show.S01E05.Edgar.mkv, Show.S01E06.Frank.mkv

This show would pop up in my Manual Import queue, because there are 6 episodes in the folder but only 5 in Sonarr.

I used to be able to select the appropriate episodes for each file in the release, which would lead to my files being named something like:

Show - S01E01 - Alex - [Show.S01E01.Alex].mkv
Show - S01E02 - Charlie - [Show.S01E03.Charlie].mkv
Show - S01E03 - David - [Show.S01E04.David].mkv
Show - S01E04 - Edgar - [Show.S01E05.Edgar].mkv
Show - S01E05 - Frank - [Show.S01E06.Frank].mkv

Show - S00E01 - Bob - [Show.S01E02.Bob].mkv

Plex and Sonarr would pick these up perfectly, following along with TVDB -- it would show 5/5 episodes in Season 1, and 1/1 in Specials.

If TVDB then changes things around again, or something else happens, I'll be able to easily map them to whatever they should be, because I have the original filenames.

If I were to just keep the Original Title, Sonarr would be confused where "Bob" is and say I'm missing a Special, and all the other episodes would be off by 1. And Plex would not be able to have the proper metadata.

In recent versions, I've noticed that doing this "Manual Import" procedure actually leads to situations like this:
```Frasier - S10E01 - The Ring Cycle - [].mkv``` when importing a file called ```S11E01 No Sex, Please, We're Skittish (HD).mkv```

Interestingly, the previous seasons work fine for Manual Import, probably because it was able to automatically parse the original title and release group for S09, while it couldn't for the release it grabbed for S10?
```Frasier - S09E24 - Moons Over Seattle - [Frasier.S09E24.Moons.Over.Seattle.DVDRip.DD2.0.x264-XYZ].mkv```

So I think something is wonky with the Manual Import's ability to process Original Title in recent versions?

### Describe the solution you'd like

I would like the Original Title to be stored when doing Manual Imports even if it can't find the Release Group, and the subsequent Renaming from a Manual Import. 

My understanding is this functionality was introduced as part of an attempt to fix infinite recursion when Original Title was missing on import. 

### Describe alternatives you've considered

I've tried using the Trash guide's recommended naming schemes with release group, quality, etc... but I've run into several issues with mismatches between TheXEM, TVDB, and release groups leading to tons of confusion in what files actually represent what. Preserving the Original Title/Original Filename is the only way I can be confident in what the file actually is.

### Anything else?

I don't think so, I am happy to provide "real world" examples of releases from major trackers where sonarr/Plex get confused and the ability to keep Original Title is really valuable.

**Comment by markus101** [comment] 2022-05-04 01:36
Dupe of https://github.com/Sonarr/Sonarr/issues/5010

**Closed as completed by markus101** 2022-05-04 01:36 UTC
Labels: needs-triage
