### ISSUE TITLE
Season Title Prefix At End

### ISSUE THREAD

**Issue by steveyeu** [Sonarr/Sonarr#1254] opened 2016-04-20 22:50 UTC
Include renaming options for the season folder to be named with the prefix at the end for example:

`../Flash, The/..`

Instead of:
`
../The Flash/..
`

Forgive me if this is possible already but haven't been able to find a solution.

**Comment by markus101** [comment] 2016-04-20 23:00
Dupe of https://github.com/Sonarr/Sonarr/issues/371

**Closed by markus101** 2016-04-20 23:00 UTC
