### ISSUE TITLE
SimplyNZBs  Error getting response stream (ReadDoneAsync2): ReceiveFailure: 'https://simplynzbs.com/api?t=caps&apikey=(removed)

### ISSUE THREAD

**Issue by lushmana** [Sonarr/Sonarr#2584] opened 2018-05-23 12:05 UTC
**Describe the bug**
Error getting response stream,but I can manually post the url and get a response in the browser

I think this might be an internal error within the mono framework.

**Comment by markus101** [comment] 2018-05-23 15:25
Dupe of https://github.com/Sonarr/Sonarr/issues/2580

Looks like it may be an issue with simplynzbs. Please open a thread on the forums with the requested information.

**Closed by markus101** 2018-05-23 15:25 UTC
