### ISSUE TITLE
System.Data.SQLite.SQLiteException (0x80004005): database is locked (/config on NFS)

### ISSUE THREAD

**Issue by yamlCase** [Sonarr/Sonarr#2797] opened 2018-11-01 14:47 UTC
**Describe the problem**
Attempting to house the /config directory to  an NFS mount will result in many `database is locked` messages.  This is (likely) a result of sqlite file locking not playing nice with NFS.

Here is a description of the known issue with sqlite:
https://www.sqlite.org/faq.html#q5

**Describe any solutions you think might work**
Providing an option to disable locking of the database.  As described here: 
http://www.sqlite.org/c3ref/open.html#coreuriqueryparameters

> "nolock: The nolock parameter is a boolean query parameter which if set disables file locking in rollback journal modes. This is useful for accessing a database on a filesystem that does not support locking. Caution: Database corruption might result if two or more processes write to the same database and any one of those processes uses nolock=1."

**Additional context**
My specific setup is `linuxserver/sonarr` docker image hosted in kubernetes. NFS server is NFSv4.(1|2) on ReadyNAS.  Using Persistent Volume in Kubernetes.

**Comment by markus101** [comment] 2018-11-01 15:12
Dupe of 
https://github.com/Sonarr/Sonarr/issues/1886

**Closed by markus101** 2018-11-01 15:12 UTC
