### ISSUE TITLE
[Req] Replace Mono with .NET Core

### ISSUE THREAD

**Issue by ngosang** [Sonarr/Sonarr#3087] opened 2019-04-29 15:53 UTC
Recently, the [Jackett](https://github.com/Jackett/Jackett) project changed the package distribution for Linux replacing Mono with .NET Core. This has 2 advantages:
- There is no need to install Mono, the binary contains all dependencies. Can be tricky to install because it's not in the official repositories.
- We saw a 32% memory reduction in Jackett (and will be greater in the next major version of .NET Core) => https://github.com/Jackett/Jackett/issues/4720

I'm not a C# programmer so I can't help.
What do you think about?

PD: Could help to fix Mono-related bugs => https://github.com/Sonarr/Sonarr/labels/mono-bug
More info: https://stackoverflow.com/a/39740592

**Comment by markus101** [comment] 2019-04-29 16:08
Dupe of https://github.com/Sonarr/Sonarr/issues/948

**Closed by markus101** 2019-04-29 16:08 UTC
