### ISSUE TITLE
[Feature request] Extract rar files on download completion

### ISSUE THREAD

**Issue by moberg89** [Sonarr/Sonarr#4432] opened 2021-04-10 08:11 UTC
Lately i have had a few episodes of a series that came in multiple rar-files and i had to do a manual extract before import would take place.

BTW: You sonarr devs are the best. Thank you!

**Comment by markus101** [comment] 2021-04-10 08:12
Please search before opening issues and use the templates. Dupe of https://github.com/Sonarr/Sonarr/issues/784

**Closed by markus101** 2021-04-10 08:12 UTC
