### ISSUE TITLE
Anime search is broken

### ISSUE THREAD

**Issue by BadFlo** [Sonarr/Sonarr#4372] opened 2021-03-11 01:39 UTC
Hello,
Since v3, Anime search is less powerful for 2 reasons :
1. When a Series is set as Anime, the only episode value looked for is "$absolute" of episode. So when your Indexer is strict with search, it will not return "E$absolute".
2. When set as Anime, manual search will only search for $absolute, even when SxxExx exists for the episode.

I'm using Jackett to search on YGG and I know they changed their search to be more strict, but I'm easily finding my episodes via Jackett search.

Thanks in advance for your help regarding these two limitations.

P.S.
As a workaround for SnK, I set the Series as "Standard" and added anime categorie in Indexer under standard categories.
For RoH, as there is only one Season and it's labeled as E$absolute on YGG, I have to rely on RSS to grab them for me as manual search doesn't cut it.

**Comment by markus101** [comment] 2021-03-11 02:20
1. Sonarr does not control that limitation, it’s either Jackett or your indexer needs to allow for that. This has not changed in v3.
2. dupe of 531126

**Closed by markus101** 2021-03-11 02:20 UTC

**Comment by BadFlo** [comment] 2021-03-11 09:52
@markus101,
I don't see why you closed this and said #4153 is about the same issue as it's not.

Here is my issue :
Searching for "Attack on Titan - 4x13 (72)" :

2021-03-11 10:46:41 | Info | Torznab search in YGGtorrent for Attack on Titan 72 => Found 0 releases
2021-03-11 10:46:39 | Info | Torznab search in YGGtorrent for Ataque a los Titanes 72 => Found 0 releases
2021-03-11 10:46:36 | Info | Torznab search in YGGtorrent for Attack on Titan The Final Season 72 => Found 0 releases
2021-03-11 10:46:34 | Info | Torznab search in YGGtorrent for Attack on Titan S4 72 => Found 0 releases
2021-03-11 10:46:32 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin The Final Season 72 => Found 0 releases
2021-03-11 10:46:30 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin S4 72 => Found 0 releases
2021-03-11 10:46:28 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin 72 => Found 0 releases

Sonarr doesn't ask Jackett for S04E13 when series is set as Anime. Why ?
It's asking for it when set as Standard,  but then, I need to add Anime category in all my Indexers.

2021-03-11 10:51:00 | Info | Torznab search in YGGtorrent for Attack on Titan The Final Season S04E13 => Found 0 releases
2021-03-11 10:50:58 | Info | Torznab search in YGGtorrent for Attack on Titan S4 S04E13 => Found 0 releases
2021-03-11 10:50:56 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin The Final Season S04E13 => Found 0 releases
2021-03-11 10:50:54 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin S4 S04E13 => Found 0 releases
2021-03-11 10:50:52 | Info | Torznab search in YGGtorrent for Attack on Titan **S3 S03E13** => Found 0 releases
2021-03-11 10:50:51 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin Season **3 S03E13** => Found 0 releases
2021-03-11 10:50:37 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin **S3 S03E13** => Found 0 releases
2021-03-11 10:50:29 | Info | Torznab search in YGGtorrent for Attack on Titan **S2 S02E13** => Found 0 releases
2021-03-11 10:50:27 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin **Season 2 S02E13** => Found 0 releases
2021-03-11 10:50:25 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin **S2 S02E13** => Found 0 releases
2021-03-11 10:50:23 | Info | Torznab search in YGGtorrent for Attack on Titan S04E13 => Found 0 releases
2021-03-11 10:50:21 | Info | Torznab search in YGGtorrent for Ataque a los Titanes S04E13 => Found 0 releases
2021-03-11 10:50:19 | Info | Torznab search in YGGtorrent for Shingeki no Kyojin S04E13 => Found 5 releases

**Comment by bakerboy448** [comment] 2021-03-11 11:49
Info logs are completely useless for debugging

as far as why, as Markus says it’s based on what your indexer / Jackett say is supported

it’s a dupe as that is what you’re asking for

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for further discussion.

do not reply via GH
