### ISSUE TITLE
New qBittorrent Seed Limit (was part of #6266)

### ISSUE THREAD

**Issue by taw123** [Sonarr/Sonarr#6999] opened 2024-07-24 20:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It seems that the previous **enhancement** request [New qBittorrent Seed Limit #6266](https://github.com/Sonarr/Sonarr/issues/6266) was accidentally closed, when the LOGIC for properly processing torrents externally configured with inactive seeding were processed for deletion was revised. 

What was lost was from the ORIGINAL request was the option to SET the inactive seed time on a per indexer basis as shown in the mockup UI. 

Unfortunately there is no way (I have found) to RE-open a previous GitHub issue so thus refiling and linking to original with all history. Feel free to let me know if you want further information but thought previous posts were clear.

Thanks for the help.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by markus101** [comment] 2024-07-24 20:09
> Unfortunately there is no way (I have found) to RE-open a previous GitHub issue so thus refiling and linking to original with all history. Feel free to let me know if you want further information but thought previous posts were clear.

There absolutely is, but you can't because you're not a maintainer of the repository. (Imagine the chaos if anyone could open issues that were closed in a public repo). Instead of duplicating the issue you should have just commented on the issue.

Duplicate of #6266

**Closed by markus101** 2024-07-24 20:09 UTC
Labels: needs-triage

**Comment by taw123** [comment] 2024-07-24 20:16
Apologies for duplication. And yes after working for years in Radar (not radarr), I know how crazy it can be if ANYONE can reopen a bug ;)
