### ISSUE TITLE
Sonarr crashes every few days

### ISSUE THREAD

**Issue by kaipee** [Sonarr/Sonarr#4040] opened 2020-10-26 22:54 UTC
**Describe the bug**
Sonarr crashes every few days. The service will not restart as the original process crashes but leaves the socket open, meaning a new socket can not be created.

Obviously the only way to resolve the issue with a detached 'zombie' process is to reboot the entire machine.

**Logs**
```
systemctl status sonarr
● sonarr.service - Sonarr Daemon
   Loaded: loaded (/etc/systemd/system/sonarr.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-26 22:41:52 GMT; 3s ago
 Main PID: 11263 (mono)
    Tasks: 9
   Memory: 1.4G
      CPU: 3.201s
   CGroup: /system.slice/sonarr.service
           └─11263 /usr/bin/mono --debug /opt/NzbDrone/NzbDrone.exe -nobrowser

Oct 26 22:41:52 sonarr systemd[1]: Started Sonarr Daemon.
Oct 26 22:41:53 sonarr mono[11263]: [Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.5344
Oct 26 22:41:53 sonarr mono[11263]: [Info] Router: Application mode: Interactive
Oct 26 22:41:54 sonarr mono[11263]: [Info] MigrationLogger: *** Migrating data source=/home/nzbdrone/.config/NzbDrone/nzbdrone.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;ver
Oct 26 22:41:54 sonarr mono[11263]: [Info] MigrationLogger: *** Migrating data source=/home/nzbdrone/.config/NzbDrone/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version
Oct 26 22:41:54 sonarr mono[11263]: [Info] OwinHostController: Listening on the following URLs:
Oct 26 22:41:54 sonarr mono[11263]: [Info] OwinHostController:   http://*:8989/
Oct 26 22:41:54 sonarr mono[11263]: [Info] NancyBootstrapper: Starting Web Server
Oct 26 22:41:55 sonarr mono[11263]: [Fatal] ConsoleApp: Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 
Oct 26 22:41:55 sonarr mono[11263]: Press enter to exit...
```
```
netstat -tulpne                                                         
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:38000         0.0.0.0:*               LISTEN      999        24077       -               
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN      999        24022       -               
```
```
lsof | awk 'NR==1 || /24022/'                                           
COMMAND     PID  TID             USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
mono       2147 2163         nzbdrone   10u     IPv4              24022       0t0        TCP *:8989 (LISTEN)
```
```
ps -lf -p 2147
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 Z nzbdrone  2147     1  0  80   0 -     0 exit   Oct19 ?        00:07:35 [mono] <defunct>
```

**System Information**

 - Sonarr Version: [2.0.0.5344]
 - Operating System: [Linux 4.4.0-193-generic #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020 x86_64]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [Mono JIT compiler version 6.12.0.90]

**Additional context**
If any other information is required, let me know.

**Comment by markus101** [comment] 2020-10-26 22:56
Dupe of https://github.com/Sonarr/Sonarr/issues/3938

**Closed by markus101** 2020-10-26 22:56 UTC

**Comment by kaipee** [comment] 2020-10-26 23:18
Restarted server with service disabled.

Manually started Sonarr with stderr and stoud redirection to log file.

**Comment by kaipee** [comment] 2020-11-15 20:19
I have the stderr and stout log file. I notice the 'dupe' ticket still hasn't proceeded in troubleshooting - can this ticket be re-opened to investigate the log?

**Comment by markus101** [comment] 2020-11-15 22:17
Post the information and we can take a look.

**Comment by kaipee** [comment] 2020-11-16 10:26
Just need to prune it of any sensitive/identifiable data

**Comment by kaipee** [comment] 2020-11-20 23:22
/mnt/nas/zpool0/public_share/sonarr.log

**Comment by kaipee** [comment] 2020-11-20 23:23
[sonarr.log](https://github.com/Sonarr/Sonarr/files/5576586/sonarr.log)

**Comment by bakerboy448** [comment] 2020-11-20 23:26
I don't know what the hell you did but all I'm seeing are that you basically have sonarr locked in a prison with no file or network access.

**Comment by bakerboy448** [comment] 2020-11-20 23:30
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by kaipee** [comment] 2020-11-21 00:00
I have no idea why Sonarr is showing these issues, however I can say that:
 * Sonarr was accessible via Web UI for a number of days before becoming unresponsive
 * The server OS is absolutely able to communicate with local network, WAN and all configured storage

The process is back to showing in a 'detached' state with the port listening and is unresponsive to either Web UI nor curl from localhost.

```bash
netstat -tulpne | grep 8989
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN      999        17530       -
```
```bas
lsof | awk 'NR==1 || /17530/'
COMMAND     PID   TID             USER   FD      TYPE             DEVICE   SIZE/OFF       NODE NAME
mono       1699  1707         nzbdrone    5u     IPv4              17530        0t0        TCP *:8989 (LISTEN)
```
```bash
ps -lf -p 1699
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
0 Z nzbdrone  1699  1698 99  80   0 -     0 exit   Oct26 ?        31-08:14:00 [mono] <defunct>
```
```bash
curl -Ivvv http://127.0.0.1:8989
* Rebuilt URL to: http://127.0.0.1:8989/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8989 (#0)
> HEAD / HTTP/1.1
> Host: 127.0.0.1:8989
> User-Agent: curl/7.47.0
> Accept: */*
> 
```

**Comment by kaipee** [comment] 2020-11-21 00:42
I've rebooted the server and launched another instance with Trace logging enabled.

```
su nzbdrone -c '/usr/bin/mono --debug /opt/NzbDrone/NzbDrone.exe -nobrowser 2>&1 | tee -a /var/log/sonarr.log'

[Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.5344 
[Debug] ProcessProvider: Found 0 processes with the name: NzbDrone.Console 
[Debug] ProcessProvider: Found 1 processes with the name: NzbDrone 
[Debug] ProcessProvider:  - [1798] NzbDrone 
[Info] Router: Application mode: Interactive 
[Debug] Router: Tray selected 
[Info] MigrationLogger: *** Migrating data source=/home/nzbdrone/.config/NzbDrone/nzbdrone.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationLogger: Took: 00:00:00.2087477 
[Info] MigrationLogger: *** Migrating data source=/home/nzbdrone/.config/NzbDrone/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationLogger: Took: 00:00:00.0198004 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:8989/ 
[Debug] OwinAppFactory: Attaching NzbDroneVersionMiddleWare to host 
[Debug] OwinAppFactory: Attaching SignalRMiddleWare to host 
[Debug] OwinAppFactory: Attaching NancyMiddleWare to host 
[Info] NancyBootstrapper: Starting Web Server 
[Trace] EventAggregator: Publishing ApplicationStartedEvent 
[Trace] EventAggregator: ApplicationStartedEvent -> QualityDefinitionService 
[Debug] QualityDefinitionService: Setting up default quality config 
[Trace] EventAggregator: ApplicationStartedEvent <- QualityDefinitionService 
[Trace] EventAggregator: ApplicationStartedEvent -> ProgressMessageTarget 
[Trace] EventAggregator: ApplicationStartedEvent <- ProgressMessageTarget 
[Trace] EventAggregator: ApplicationStartedEvent -> ProfileService 
[Trace] EventAggregator: ApplicationStartedEvent <- ProfileService 
[Trace] EventAggregator: ApplicationStartedEvent -> NotificationFactory 
[Debug] NotificationFactory: Initializing Providers. Count 20 
[Trace] EventAggregator: ApplicationStartedEvent <- NotificationFactory 
[Trace] EventAggregator: ApplicationStartedEvent -> CommandExecutor 
[Trace] EventAggregator: ApplicationStartedEvent <- CommandExecutor 
[Trace] EventAggregator: ApplicationStartedEvent -> CommandQueueManager 
[Trace] CommandQueueManager: Orphaning incomplete commands 
[Trace] EventAggregator: ApplicationStartedEvent <- CommandQueueManager 
[Trace] EventAggregator: ApplicationStartedEvent -> Scheduler 
[Trace] EventAggregator: ApplicationStartedEvent <- Scheduler 
[Trace] EventAggregator: ApplicationStartedEvent -> TaskManager 
[Trace] ConfigService: Using default config value for 'rsssyncinterval' defaultValue:'15' 
[Trace] TaskManager: Initializing jobs. Available: 10 Existing: 10 
[Trace] EventAggregator: ApplicationStartedEvent <- TaskManager 
[Trace] EventAggregator: ApplicationStartedEvent -> MetadataFactory 
[Debug] MetadataFactory: Initializing Providers. Count 4 
[Trace] EventAggregator: ApplicationStartedEvent <- MetadataFactory 
[Trace] EventAggregator: ApplicationStartedEvent -> DownloadClientFactory 
[Debug] DownloadClientFactory: Initializing Providers. Count 15 
[Trace] EventAggregator: ApplicationStartedEvent <- DownloadClientFactory 
[Trace] EventAggregator: ApplicationStartedEvent -> IndexerFactory 
[Debug] IndexerFactory: Initializing Providers. Count 12 
[Trace] EventAggregator: ApplicationStartedEvent <- IndexerFactory 
[Trace] EventAggregator: ApplicationStartedEvent -> UserService 
[Trace] EventAggregator: ApplicationStartedEvent <- UserService 
[Trace] EventAggregator: ApplicationStartedEvent ~> HealthCheckService 
[Trace] EventAggregator: ApplicationStartedEvent ~> ConfigFileProvider 
[Trace] EventAggregator: ApplicationStartedEvent <~ ConfigFileProvider 
[Trace] ConfigService: Using default config value for 'downloadedepisodesfolder' defaultValue:'' 
[Trace] SymbolicLinkResolver: Checking path ######## for symlink returned error ENOENT, assuming it's not a symlink. 
[Trace] SymbolicLinkResolver: Checking path ######## for symlink returned error ENOENT, assuming it's not a symlink. 
[Trace] ConfigService: Using default config value for 'downloadedepisodesfolder' defaultValue:'' 
[Trace] ConfigService: Using default config value for 'downloadedepisodesfolder' defaultValue:'' 
[Debug] MonoVersionCheck: Mono version is 3.10 or better: 6.12.0.90 
[Trace] HttpClient: Req: [GET] http://services.sonarr.tv/v1/ping 
[Trace] ConfigService: Using default config value for 'proxybypasslocaladdresses' defaultValue:'True' 
[Trace] Http: Req: 1 [GET] /system/status 
[Trace] Http: Res: 1 [GET] /system/status: 200.OK (168 ms) 
...
```

I'll post the full Trace log once the server crashes again - as you can see, the server is responsive and can reach http://services.sonarr.tv

![image](https://user-images.githubusercontent.com/5189160/99862274-fde72100-2b90-11eb-9df6-95dc803cf0d1.png)
