### ISSUE TITLE
Import Fails: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by abhishekjain14** [Sonarr/Sonarr#2880] opened 2019-01-07 11:33 UTC
**Describe the bug**
The above error occurs when trying to manually import certain episodes of a TV show, interestingly even when I use different files for said episode.

**Logs**
```
19-1-7 03:23:58.8|Debug|VideoFileInfoReader|Getting media info from /downloads/mahabharat/Mahabharat Episode 1-WhC0lAXqnZs.mp4
19-1-7 03:23:58.8|Trace|MediaInfo|Read file offset 0-16384 (16384 bytes)
19-1-7 03:23:58.8|Trace|MediaInfo|Read file offset 126644762-128689075 (2044313 bytes)
19-1-7 03:23:58.8|Trace|MediaInfo|Read file offset 48-16432 (16384 bytes)
19-1-7 03:23:58.8|Trace|MediaInfo|Read file offset 128689075-128689075 (0 bytes)
19-1-7 03:23:58.8|Trace|MediaInfo|Read a total of 2077081 bytes (1.6%)
19-1-7 03:23:58.8|Debug|AggregateQuality|Using quality:  v1
19-1-7 03:23:58.8|Warn|ImportApprovedEpisodes|Couldn't import episode /downloads/mahabharat/Mahabharat Episode 1-WhC0lAXqnZs.mp4

[v2.0.0.5252] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Organizer.FileNameBuilder.AddQualityTokens (System.Collections.Generic.Dictionary`2[TKey,TValue] tokenHandlers, NzbDrone.Core.Tv.Series series, NzbDrone.Core.MediaFiles.EpisodeFile episodeFile) [0x00006] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Organizer\FileNameBuilder.cs:480 
  at NzbDrone.Core.Organizer.FileNameBuilder.BuildFileName (System.Collections.Generic.List`1[T] episodes, NzbDrone.Core.Tv.Series series, NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Organizer.NamingConfig namingConfig) [0x00164] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Organizer\FileNameBuilder.cs:135 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:74 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, System.Boolean copyOnly) [0x0017c] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:76 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x00272] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:107 

19-1-7 03:23:58.8|Trace|ManualImportService|Manually imported 1 files
```

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Running the docker container found here https://hub.docker.com/r/aront/sonarr/ - a fork of the linuxserver container
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by markus101** [comment] 2019-01-22 02:34
Based on the error it looks like one of two things:

- A quality wasn't selected in the UI
- The selected quality doesn't have a size/title definition

The latter should be fixed on restart.

**Comment by markus101** [comment] 2019-02-03 21:17
I haven't been able to reproduce this issue, though the two possibilities above are possible they're not cases we'd guard against here.

**Closed by markus101** 2019-02-03 21:17 UTC
