### ISSUE TITLE
Multiple icons on taskbar panel

### ISSUE THREAD

**Issue by pikachukaki** [Sonarr/Sonarr#4260] opened 2021-01-16 16:27 UTC
I'm not sure in which version it started but when i open my taskbar panel i saw 3-4 sonarr icons that disappear when i hover the cursor above them.
I'm not sure if i can find a log about this but i can post a SS when it will happen again.

**Comment by bakerboy448** [comment] 2021-01-16 16:39
Closing; not a bug

It's a windows thing. And not specific to Sonarr

**Closed** 2021-01-16 16:39 UTC

**Comment by Taloth** [comment] 2021-01-16 16:47
Just an annoyance, it happens when an app is terminated rather than closed normally. I'm not sure if that happens with the updater. But not really worth investigating.
