### ISSUE TITLE
Unmonitor Deleted Episodes broken

### ISSUE THREAD

**Issue by planetrocky** [Sonarr/Sonarr#6699] opened 2024-04-08 18:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When an existing show is deleted from disk, it should be unmonitored. Show stays monitored and then shows as missing after an episode is watched and deleted, causing it to be redownloaded again.

### Expected Behavior

Unmonitor Deleted Episodes

### Steps To Reproduce

Delete an existing episode file from a collection that is monitored.

### Environment

```markdown
- OS: Linux 4.4.302+
- Sonarr: 4.0.3.1413
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Any
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

2024-04-08 19:04:30.8|Info|RefreshSeriesService|Updating The Show
2024-04-08 19:04:30.9|Info|RefreshEpisodeService|Starting episode info refresh for: [71663][The Show]
2024-04-08 19:05:35.3|Info|RefreshEpisodeService|Finished episode refresh for series: [71663][The Show].
2024-04-08 19:05:35.3|Info|DiskScanService|Scanning The Show
2024-04-08 19:05:36.7|Error|RefreshSeriesService|Couldn't rescan series [71663][The Show]

[v4.0.3.1413] System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/tv/The Show (1900)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFiles(String path, Boolean recursive) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 163
   at NzbDrone.Core.MediaFiles.DiskScanService.GetNonVideoFiles(String path, Boolean allDirectories) in ./Sonarr.Core/MediaFiles/DiskScanService.cs:line 215
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Series series) in ./Sonarr.Core/MediaFiles/DiskScanService.cs:line 79
   at NzbDrone.Core.Tv.RefreshSeriesService.RescanSeries(Series series, Boolean isNew, CommandTrigger trigger) in ./Sonarr.Core/Tv/RefreshSeriesService.cs:line 196

### Anything else?

`Delete empty series and season folders during disk scan and when episode files are deleted` = True

**Comment by markus101** [comment] 2024-04-08 18:32
Duplicate of #6678

**Closed by markus101** 2024-04-08 18:32 UTC
Labels: needs-triage
