### ISSUE TITLE
Interactive search for series

### ISSUE THREAD

**Issue by SnowDrifterr** [Sonarr/Sonarr#4549] opened 2021-06-22 18:26 UTC
**Is your feature request related to a problem? Please describe.**
Search by season misses some larger 'full series' packs that are presented. Especially in discontinued series where individual episodes / seasons are not common, and the most common seeded data is the start-to-finish compilation of all episodes.

**Describe the solution you'd like**
Interactive search for entire season. e.g. search and find s01-s05 complete

**Describe alternatives you've considered**
Manually finding a full-series compilation, then manually importing

**Additional context**
Would have benefit in either discontinued shows, or in long-running shows where compilations to X date are frequent

**Comment by bakerboy448** [comment] 2021-06-22 18:27
Duplicate of https://github.com/Sonarr/Sonarr/issues/4268

Please search before posting

No plans to support series packs.

**Closed by bakerboy448** 2021-06-22 18:27 UTC
