### ISSUE TITLE
Not deleting from download client with different post-import category

### ISSUE THREAD

**Issue by cjmanca** [Sonarr/Sonarr#3745] opened 2020-05-13 03:17 UTC
**Describe the bug**
Using the qBittorrent "Post-Import Category" setting, downloads aren't removed automatically when they complete. This functionality works fine if I don't use the Post-Import category, or if I've already seeded enough prior to them finishing. I'm guessing that it's only monitoring the main tv-sonarr category for removals?

**System Information**

 - Sonarr Version: 3.0.3.803 (has been an issue for as long as I've been using, not version specific)
 - Operating System: Windows 10

**Comment by markus101** [comment] 2020-05-13 03:42
Dupe of https://github.com/Sonarr/Sonarr/issues/3659

**Closed by markus101** 2020-05-13 03:42 UTC
