### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#4179] opened 2020-12-20 05:48 UTC
**Describe the bug**
Sonarr is unable to bind to all interfaces, as in IPv6 included.
It does not work with Docker exposed port either over v6.

Sonarr container has internal port 8989 exposed on host as 27021, but it gives just Bad Request error.

You can get Sonarr to listen on v6 by manually editing config.xml's BindAddress in this format: `<BindAddress>[2001:DB8:1::1]</BindAddress>` but the 2nd image is the result.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/102705732-652ce980-4293-11eb-864b-18bc52372af7.png)
![image](https://user-images.githubusercontent.com/1703002/102705823-60b50080-4294-11eb-9fe6-3b587849ad08.png)

**Logs**
Not applicable.

**System Information**

 - Sonarr Version: 3.0.4.1026
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono v5.20.1.34
 - Branch: phantom-develop

**Additional context**
Possibly related to #4149 and #835

**Comment by bakerboy448** [comment] 2020-12-20 06:05
Duplicate of #835

**Closed by bakerboy448** 2020-12-20 06:05 UTC
