### ISSUE TITLE
Mutli = French  Or other language choices like Radarr on Indexers

### ISSUE THREAD

**Issue by maxtop51** [Sonarr/Sonarr#3009] opened 2019-03-24 18:48 UTC
Can setup Mutli = French for indexers or sonarr setting, I try Must Contain seting in french and english and dont work. 
Need Help

**Comment by markus101** [comment] 2019-03-24 20:33
Dupe of https://github.com/Sonarr/Sonarr/issues/2854

**Closed by markus101** 2019-03-24 20:33 UTC
