### ISSUE TITLE
Default sortKey for `/api/v3/wanted/missing`

### ISSUE THREAD

**Issue by johnynfulleffect** [Sonarr/Sonarr#4950] opened 2022-03-21 18:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching for missing episodes, Sonarr shows a Fatal Exception:

```
[Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/wanted/missing 

[v3.0.7.1477] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel] (System.String propertyName) [0x00019] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:32 
  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.OrderByClause[TModel] (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:11 
  at NzbDrone.Core.Tv.EpisodeRepository.GetMissingEpisodesQuery (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.DateTime currentTime, System.Int32 startingSeasonNumber) [0x0000d] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\EpisodeRepository.cs:216 
  at NzbDrone.Core.Tv.EpisodeRepository.EpisodesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Boolean includeSpecials) [0x0000d] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\EpisodeRepository.cs:111 
  at NzbDrone.Core.Tv.EpisodeService.EpisodesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\EpisodeService.cs:152 
  at Sonarr.Http.SonarrRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\SonarrRestModule.cs:43 
  at Sonarr.Api.V3.Wanted.MissingModule.GetMissingEpisodes (Sonarr.Http.PagingResource`1[TResource] pagingResource) [0x00210] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Wanted\MissingModule.cs:47 
  at Sonarr.Http.REST.RestModule`1[TResource].<set_GetResourcePaged>b__36_0 (System.Object options) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:139 
  at Nancy.NancyModule+<>c__DisplayClass14_0`1[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyModule+<>c__DisplayClass16_0`1[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
```

This was working fine up until about a week ago.  I believe it was the first time running 3.0.7, however, rolling back to 3.0.6 still has an issue.

### Expected Behavior

Fetches new episodes

### Steps To Reproduce

Kubernetes using Rancher K3S

### Environment

```markdown
- OS: Ubuntu 21.04
- Sonarr: 3.0.7
- Docker Install: containerd 1.5.9-k3s1
- Using Reverse Proxy: yes, traefik
- Browser: Chromium, Brave, Google Chrome
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/johnynfulleffect/33398a400b9e5eafa02a13ea31faa6c4

### Anything else?

Very similar to [#1452](https://github.com/Sonarr/Sonarr/issues/1452)

**Comment by bakerboy448** [comment] 2022-03-21 18:49
Likely not a Sonarr issue; your third party application is making a bad API call.

**Comment by markus101** [comment] 2022-03-21 19:00
The request is missing the `sortKey`, but at the same time we should have a default sort key when the request doesn't include it.

**Comment by johnynfulleffect** [comment] 2022-03-21 19:35
> Likely not a Sonarr issue; your third party application is making a bad API call.

I’m using the Sonarr UI/website to request updated episodes.  What other third party app would this be?

**Comment by johnynfulleffect** [comment] 2022-03-21 19:36
> The request is missing the `sortKey`, but at the same time we should have a default sort key when the request doesn't include it.

How does this get populated from the Sonarr UI?  I click the magnifying glass in sonar next to an episode that is missing.

**Comment by johnynfulleffect** [comment] 2022-03-21 20:11
@markus101 @bakerboy448 just tagging you here since I missed that in my comment.

**Comment by johnynfulleffect** [comment] 2022-03-21 20:47
Ok, so 

> > I’m using the Sonarr UI/website to request updated episodes. What other third party app would this be?
> 
> Something that's not Sonarr's UI, Sonarr's UI passes that as part of the request it makes.
> 
> > How does this get populated from the Sonarr UI?
> 
> It's part of the request URL.
> 
> > I click the magnifying glass in sonar next to an episode that is missing.
> 
> That's searching, it doesn't have anything to do with the missing episodes request.
> 
> > just tagging you here since I missed that in my comment.
> 
> That's unnecessary, it's just extra noise.

Ok, so I use Jackett and Transmission.  It would have to be one of those then?  When Sonarr starts up, it has these logs in the trace as well as when I search for missing episodes.

**Comment by bakerboy448** [comment] 2022-03-21 20:51
> Ok, so I use Jackett and Transmission.  It would have to be one of those then?  When Sonarr starts up, it has these logs in the trace as well as when I search for missing episodes.  

Whatever is using GuzzleHTTP. I believe users have always found this to be something unique to kubernetes making invalid api calls

```
2022-03-21 17:30:09.3|Trace|Http|Req: 10 [GET] /api/v3/wanted/missing?apikey=(removed) (from 10.42.2.0 GuzzleHttp/7)
```

**Comment by markus101** [comment] 2022-03-21 20:53
No, neither of those talk to Sonarr's API or have any reason to make that API request.

`2022-03-21 17:30:09.3|Trace|Http|Req: 10 [GET] /api/v3/wanted/missing?apikey=(removed) (from 10.42.2.0 GuzzleHttp/7)`

`GuzzleHttp` is a PHP client, Organizer is one client that uses that particular client.

If you want to continue digging into what is causing these errors, use one of the support channels, the cause isn't relevant to this issue.

**Comment by johnynfulleffect** [comment] 2022-03-21 20:58
Sorry, I am so confused.  I ended up redeploying all my apps: sonarr, radarr, transmission, jackett, and I do see that sonarr is getting new episodes now.  I thought it was related, but I guess not!  it seemed to me like this error was related.

Thanks for your help! @markus101

**Comment by stevietv** [comment] 2022-03-24 20:56
@johnynfulleffect  do you use Heimdall? I think that uses GuzzleHTTP - update your heimdall apps as I PR'd a fix for the missing sortkey into that

**Comment by johnynfulleffect** [comment] 2022-03-24 22:10
> @johnynfulleffect do you use Heimdall? I think that uses GuzzleHTTP - update your heimdall apps as I PR'd a fix for the missing sortkey into that

Omg that has to be the source of those errors, and not me in the Sonarr UI clicking search.  

I’ll update and see if it stops.  Thanks!

**Comment by johnynfulleffect** [comment] 2022-03-24 23:35
> @johnynfulleffect do you use Heimdall? I think that uses GuzzleHTTP - update your heimdall apps as I PR'd a fix for the missing sortkey into that

When did you PR this?

**Comment by stevietv** [comment] 2022-03-25 07:10
@johnynfulleffect https://github.com/linuxserver/Heimdall-Apps/pull/396 - it was merged in february.
In Heimdall go to the apps list and press update apps list:
![image](https://user-images.githubusercontent.com/1117625/160071903-4afdcfc5-bdd9-4e8d-ad75-54bc6d315bae.png)

it'll pull in the new app definitions

**Closed** 2022-03-29 00:34 UTC
Labels: suboptimal
