### ISSUE TITLE
Sonarr trying searching only season packs for "daily" show type

### ISSUE THREAD

**Issue by Auwen** [Sonarr/Sonarr#2348] opened 2017-12-24 15:38 UTC
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 2.0.0.5085

**Operating System:** Windows 10, 64 bit

**.net Framework (Windows) or mono (macOS/Linux) Version:** .Net 4.0

**Link to Log Files (debug or trace):**
Note: the name of the series has been changed to "Series Name" in the logs for privacy
Season search failures: https://pastebin.com/8cQwHM1i
Episode search success: https://pastebin.com/BewbNLrX

Reddit post regarding the issue: https://www.reddit.com/r/sonarr/comments/7ljpm6/sonarr_trying_season_download_for_daily_show_type/

**Browser (for UI bugs):** Chrome 63, 64 bit

### Additional Information

When trying to back fill a season of a daily type show, Sonarr _seems_ to only search by Season and not by episode after failing to find a season pack. However, when automatically searching by episode it successfully finds and downloads the episode. I'd prefer not to have to manually click the Episode auto-search for the 300+ I'm missing.

**Comment by markus101** [comment] 2017-12-24 22:55
Dupe of https://github.com/Sonarr/Sonarr/issues/755

**Closed by markus101** 2017-12-24 22:55 UTC
