### ISSUE TITLE
Episode upgrade issue with (v2 CF) and different release group (SonarrV4)

### ISSUE THREAD

**Issue by JonzaUK** [Sonarr/Sonarr#5262] opened 2022-12-01 14:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Download Release [RlsGroup1] Showname - 01 [English Dub] [CR WEB-DL 1080p] =Score 0
Import above release, fine.
New release appears [RlsGroup2] Showname - 01 [English Dub] [CR WEB-DL 1080p] =Score 602 - (Score 600 for Rlsgroup - Score 2 for v2)
Sonarr Rejects release group - Rlsgroup2 does not match exsisiting release group Rlsgroup1

### Expected Behavior

Download Release [RlsGroup1] Showname - 01 [English Dub] [CR WEB-DL 1080p] =Score 0
Import above release, fine.
New release appears [RlsGroup2] Showname - 01 [English Dub] [CR WEB-DL 1080p] =Score 602 - (Score 600 for Rlsgroup - Score 2 for v2)
Sonarr Aproves 2nd release
Import release 2

### Steps To Reproduce

Download: [Yameii] Chainsaw Man - 01 [English Dub] [CR WEB-DL 1080p] [12B9AEB3]

Once imported Manual search same episode, [sam] Chainsaw Man - 01v2 (WEB 1080p EAC-3) [Dual-Audio] should appear and should be a upgrade based on CF scoring of Rlsgroups and v2 etc.

Release will be rejeceted "sam does not match exsisiting release group Yameii"

### Environment

```markdown
- OS: unRaid
- Sonarr: V4
- Docker Install: Yes
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?ccf41db912203110#FEs2rtXocP7hNXzfKjL9utuMaG9w8nogoit4rFMPLNY6

### Anything else?

If logs are required I'll provide them when I get home, just out at work at the moment.

![image](https://user-images.githubusercontent.com/21015102/205083667-dc6d30a5-4e4b-4d5f-879d-0f1e38807e12.png)

**Comment by markus101** [comment] 2022-12-01 15:30
This is a dupe of https://github.com/Sonarr/Sonarr/issues/4468

**Closed by markus101** 2022-12-01 15:30 UTC
Labels: needs-triage
