### ISSUE TITLE
Use grabber information when importing a single file

### ISSUE THREAD

**Issue by albertodiazsaez** [Sonarr/Sonarr#4529] opened 2021-06-07 10:40 UTC
**Is your feature request related to a problem? Please describe.**
The torrent trackers I use have sub-optimal naming conventions, (my main language is not english and trackers are fewer than for english) so 99% of the time I have to manually specify data when importing an episode, and this is very annoying when there is only one file, because Sonarr "knows" what he asked the download client to get: https://i.imgur.com/Gwo441f.png but does not fill the data due to a "Parsing Error": https://i.imgur.com/zhg4gy3.png I can understand not all naming conventions can be implemented, taking into account the amount of languages in the world is not possible, so this only annoys me in single file downloads, which are 99% of the downloads I make.

**Describe the solution you'd like**
I would like Sonarr to share the info he has about the episode he asked, and use it on downloads on which there is only one file to grab (one video file) on downloads that cannot be parsed. This option should be optional, and maybe by tracker, so you can choose only the trackers you know the parsing is not ideal. Furthermore, in the Activity page when a parsing error (or invalid episode or other "parsing like" errors) has occurred, if the tracker is not marked to use the grabber info, to have a button to use it in the act.

**Describe alternatives you've considered**
If the importer can't have the grabber info about the episode he has asked, (becouse they are like "two black boxes" for what I can tell), the grabber could generate a file in json format or someting, on which the info of the episode he downloaded is written, then the importer can check this file for importing (and delete it not to leave the drive full of files).

**Additional context**
I have never used anything else than Torrent Trakckers, so I don't know (for example) how Tornazb works, but this should work as well for them. And again, only for single file downloads, I understand is impossible for Sonarr to parse without the name a full season for example.

I'm myself a developer (not a C# main developer, but I have worked with it in the past) so I don't mind working in this issue, but first I would like to brainstorm the idea to first have the best possible solution, compatible as I said with all the types of trackers, and if possible migratable to Radarr, because I have the same issue there.

**Comment by bakerboy448** [comment] 2021-06-07 11:25
Duplicate of https://github.com/Sonarr/Sonarr/issues/2632

**Closed by bakerboy448** 2021-06-07 11:25 UTC

**Comment by albertodiazsaez** [comment] 2021-06-07 11:35
I cannot belive I missed that Github Issue, I feel like an idiot, sorry!! >.< I will contact ivanbeldad as he seems  to managed to fix this with an external tool and API.

And again, so sorry about the duplicate issue... :(
