### ISSUE TITLE
Catalina: Not asking for permission to access drives

### ISSUE THREAD

**Issue by jchhenderson** [Sonarr/Sonarr#3465] opened 2019-12-19 11:19 UTC
**Describe the bug**
- **Unable** to access files and folders when running from the app icon; app does not request access.
- **Able** to access files and folders when running from MacOS Terminal; terminal **asks** for access (and so it was given).

**Screenshots**
- Terminal's access rights (having requested it)
![Screenshot 2019-12-19 at 11 07 28](https://user-images.githubusercontent.com/34644672/71169009-e2bcb480-224f-11ea-95ee-8be1497e1bc3.png)

**Logs**
- I have been running "normally" and from terminal, so the logs might be hot mess.
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3983290/sonarr.txt)

**System Information**

 - Sonarr Version: [3.0.3.668 ]
 - Operating System: [MacOS Catalina 10.15.2]
 - mono (macOS) Version: [6.4.0.198]

**Additional context**
- It seems that when running Sonarr in terminal, it asks for the appropriate access, but when running "normally" (clicking on the icon), it doesn't.
- Manually giving Sonarr "full disk access" doesn't solve the problem.

Command to run from terminal:
`/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono --debug /Applications/Sonarr.app/Contents/MacOS/Sonarr.exe`

**Comment by markus101** [comment] 2019-12-19 15:42
Dupe of https://github.com/Sonarr/Sonarr/issues/3168

**Closed by markus101** 2019-12-19 15:42 UTC

**Comment by jchhenderson** [comment] 2019-12-20 12:46
apologies - I thought this was different because I manually gave the app "full disk access" and it still would not work.
