### ISSUE TITLE
Individual Qualities for different profiles

### ISSUE THREAD

**Issue by Supergamer1337** [Sonarr/Sonarr#2902] opened 2019-01-21 18:55 UTC
I think it would be a good idea to add the ability to change the file size restrictions for individual profiles. For example, what may work well for anime, doesn't work well for live action. And since the files sizes for different lenghts are tied, there's even less that you can do. Therefore I think this feature would be a serious help for optimizing downloaded files.

**Comment by markus101** [comment] 2019-01-21 19:03
Dupe of https://github.com/Sonarr/Sonarr/issues/613

**Closed by markus101** 2019-01-21 19:03 UTC
