### ISSUE TITLE
unmapped media files in series/season folder

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#6645] opened 2024-03-22 20:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

lets say you have s00e09 and then tvdb data changes and that episode is removed... you then have this file sitting in your season folder unmapped. sonarr then silently ignores it..

### Describe the solution you'd like

would be nice if sonarr just showed the list of files unmapped media files (think of it like a 'season' section under specials) where a user could then manage said files. which might be remapping to existing s#e# / moving to another series / deleting them / just being aware they even exist..

### Describe alternatives you've considered

 none

### Anything else?

none

**Comment by markus101** [comment] 2024-03-22 20:16
This already exists under Manage Episodes, but ultimately a duplicate of https://github.com/Sonarr/Sonarr/issues/286 no plans to expose this at the series level without opening Manage Episodes.

**Closed by markus101** 2024-03-22 20:16 UTC
Labels: needs-triage
