### ISSUE TITLE
Ignore watched episodes

### ISSUE THREAD

**Issue by MrPlow254** [Sonarr/Sonarr#4537] opened 2021-06-13 12:50 UTC
Issue #6 has not been implemented. It would be super useful to ignore episodes i have already watched. This is a feature on duckieTV. This could be easily added to the import list settings section and just added a checkbox if the list should be a list for ignoring or adding episodes.

It takes way more work using sonarr vs duckieTV so it seems I will be leaving this project until this is added.

I don't want to add a new series and have to uncheck every season i don't want to download since i already watched it.

**Comment by bakerboy448** [comment] 2021-06-13 13:14
Duplicate of https://github.com/Sonarr/Sonarr/issues/314

**Closed by bakerboy448** 2021-06-13 13:14 UTC
