### ISSUE TITLE
Profile Grouping

### ISSUE THREAD

**Issue by hitnrun30** [Sonarr/Sonarr#2276] opened 2017-11-08 15:08 UTC
This is an enhancement request, a way to group profiles.  I prefer any type of say 720p (WebDL, Bluray, HDTV) but since i dont care, all 3 are in the list.  In my list BluRay is at the bottom, then HDTV and then WebDL.  So if the BluRay comes out and there are none of the other 2, Sonarr will down load that, then if one of the other 2 come along, Sonarr will download that as well.  Personally I dont care which  so my suggestion is to somehow group the qualities in a profile.

**Comment by markus101** [comment] 2017-11-08 16:08
Dupe of https://github.com/Sonarr/Sonarr/issues/1781

**Closed by markus101** 2017-11-08 16:08 UTC
