### ISSUE TITLE
Impossible to upgrade to latest release through Ubuntu repository

### ISSUE THREAD

**Issue by tmortagne** [Sonarr/Sonarr#4621] opened 2021-08-10 16:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you install Sonarr using the Ubuntu repository you end up with a package which have version 3.0.6 instead of the complete version (for example `3.0.6.1196`). The problem is that this means that if you install the Debian package before 3.0.6.1264 you cannot really upgrade to latest version.

### Expected Behavior

The Debian packages should have the complete version and the repository should contain all the 3.0.6.x versions.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1196
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firefox 90.0.2
```

### What branch are you running?

Main

### Anything else?

Not really

**Comment by bakerboy448** [comment] 2021-08-10 16:30
Duplicate of #4617

Non-issue

**Closed by bakerboy448** 2021-08-10 16:30 UTC
Labels: needs-triage

**Comment by Taloth** [comment] 2021-08-11 08:42
There are two apt repositories, one with built in updater enabled (which automatically upgrades to latest after install), and one with the built in updater disabled. Links are on the website.

**Comment by tmortagne** [comment] 2021-08-11 12:33
> Links are on the website.

I checked again on https://sonarr.tv/#downloads-v3-linux-ubuntu but I can only see one repository documented (for a given version of Ubuntu).

**Comment by bakerboy448** [comment] 2021-08-11 13:27
Look under alternatives for advanced users.

**Comment by gudvinr** [comment] 2021-11-07 11:46
I was trying to update Sonarr and found this issue. It is rather interesting choice of default update method for system that has native package management capabilities. Automatic updates _on top of_ system-wise updates are considered bad practice for pretty much any distro.

It makes sense for standalone generic package and for systems that don't have package managers. But this definitely should not be recommended way to update packages on GNU/Linux systems. Consistency is one of the main conveniences of package management.

Application should not mess with `/usr` hierarchy by itself because it is intended to be handled by package manager only.  Generally speaking, user should not touch anything there by hand too unless there's very good reason (or rather bad reason which is the only option left).

It has very noticeable consequences in containerized environments where system image is often frozen after creation. Thus after restarting container everything that were updated in runtime will be gone. Unless update is installed into data directory which isn't really good practice either.
