### ISSUE TITLE
search all cutoff unmet

### ISSUE THREAD

**Issue by ggwptyvm** [Sonarr/Sonarr#921] opened 2015-11-08 16:42 UTC
Hi,

I would absolutely love a "search all cutoff unmet" button, similar to what "search all missing" does. This way I could search all in one swift button press instead of wading through hundreds of pages manually. 

The search all missing button works fantastic for me (10k+ missing, 7 indexers) so I dont see the reason to limit this fantastic button to one set of searches.

Cheers!

**Comment by markus101** [comment] 2015-11-09 06:46
I find it ironic that this is about searching... dupe of: https://github.com/Sonarr/Sonarr/issues/576

**Closed by markus101** 2015-11-09 06:46 UTC
