### ISSUE TITLE
Local Service account and Permission errors

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3145] opened 2019-06-02 17:15 UTC
**Describe the bug**
V3 is installed as Windows service using the Local Service account instead of System (v2).
This causes a change of permission behavior that many users are not ready for. System has much broader permissions and the user might find himself in a situation where Sonarr cannot write to library and require permission or service account changes.

We should default to Tray Task instead of Windows Service. It's what most apps do and circumvents the majority of permission issues Windows users experience.
Additionally we should consider giving the user a choice between System, Local Service, specific account right in the installer.

Additionally, a Root Folder health check should be added that verifies acl permissions (without writing test files).

Finally, we must improve the error message for AccessDenied exceptions, especially for move. It should include the owners involved and our own user.
Ergo we must explain to the user _why_ Sonarr can't move something, instead of only what.

**System Information**

 - Sonarr Version: 3.0.1.503
 - Operating System: Windows Server 2019

**Comment by skidaddl3** [comment] 2019-11-17 23:26
I'm having a strange permissions issue when sonarr is switched on (not sure if it is also to do with the Windows 10 v1909 update) where my root folder stops having permission to access network wide (even on the local server via shared path). Any ideas?
Sonarr then says after a minute or two running, that it cannot find that same root folder.
I have left Sonarr shut down until it is rectified, as I can access the shared folder while Sonarr is off.

**Comment by skidaddl3** [comment] 2019-12-01 14:21
I have updated my Intel l350 LAN drivers from version 21.x.x.x to version 24.3.0.6 and it seems to have stabilised and no longer causing the issue, as per a suggestion about driver relation on the Discord Support channel.
Still, I'm not sure why it was isolated to Sonarr...?

**Comment by skidaddl3** [comment] 2019-12-01 15:10
Actually... nope. It has happened again, after working for a longer time however.

**Comment by skidaddl3** [comment] 2019-12-03 04:04
It seems to occur after some import(s)

**Comment by skidaddl3** [comment] 2019-12-09 11:02
Any support on this please? Or does it need a separate issue opened, as this one has been tagged V3?

**Comment by skidaddl3** [comment] 2019-12-10 03:39
Also corrupts files, terminated mid-transfer by this issue.

**Comment by markus101** [comment] 2019-12-10 04:12
This issue is specific to v3 with the change to the local service account. You need to use the forums for support, not an issue on github.

**Comment by skidaddl3** [comment] 2019-12-10 06:41
The OP says for V3, however the title is broad and my issue is with the ACL permissions running as a windows service... Thought I could help. Fair enough re. Forum, didn't know it existed TBH. I'll start a new Topic on the Forum

**Comment by psxlover** [comment] 2020-03-15 10:45
Was about to create a post in the forums, about version 3 having issues with unicode names in folders.

I was getting messages about `Multiple root folders are missing...` and `No files found are eligible for import...` and when I tried to change the path of one of my series I saw that Sonarr couldn't see anything below `C:\Users\Αλέξανδρος\` folder, so I though it was due to the greek characters.

Then when I saw the actual error message in the log `Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder` it got me thinking that it might be the permissions and after searching a bit more I got here.

I've now added full access permissions for LOCAL SERVICE to my user folder and it seems to be working (at least I can see the folder when changing directories from Sonarr's page. But I doubt many would figure out what the issue is, let alone know how to "fix" it.

There should at least be a warning in the download page, and a link to a wiki page describing how to give proper access to the download folder and destination folders.

**Comment by Taloth** [comment] 2020-03-15 11:10
In such cases it's better to run as sys tray app rather than service. Which is what we made the default a while back in the windows installer.

**Comment by psxlover** [comment] 2020-03-15 11:19
> Which is what we made the default a while back in the windows installer.

When you upgrade from v2 does it default to sys tray or to whatever you were using in v2?
I don't remember if I changed it in the installer to use a service.
At least when I rerun the setup for v3 it seems to default to the previous selected options.

**Comment by Taloth** [comment] 2020-03-15 11:48
Possibly, I should check that out. But in v2 we ran as System user rather than the safer Local Service.

**Comment by psxlover** [comment] 2020-03-15 11:58
> System user rather than the safer Local Service

Yes, the problem is I updated from v2 yesterday which removed the previous nbz service and installed the new Sonarr service which runs as on LOCAL SERVICE user, causing my setup to stop working without a warning, which got me thinking there was a bug/regrassion in v3

**Comment by markus101** [comment] 2024-02-17 00:39
Closing as this hasn't been a substantial issue with the default being set to tray now.

**Closed by markus101** 2024-02-17 00:39 UTC
Labels: suboptimal
