### ISSUE TITLE
Before Import Notification

### ISSUE THREAD

**Issue by DavidReinberger** [Sonarr/Sonarr#4934] opened 2022-03-07 13:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Have an ability to trigger notification **before** import starts with the same arguments as import/upgrade.

### Describe alternatives you've considered

1. Currently using the import/upgrade event
2. Issue a Pull Request, however C# is way over my head.

### Anything else?

The reasoning behind this event is my current setup.
1. Download with sonarr/radarr
2. Add to .plexignore with when the file is imported
3. Transcode with Tdarr
4. Remove from .plexignore
5. Ask Plex to scan the folder

However a race condition might happen, when a file is imported and Tdarr triggers a folder scan.

**Comment by markus101** [comment] 2022-03-07 15:40
This is a dupe of https://github.com/Sonarr/Sonarr/issues/791

**Closed by markus101** 2022-03-07 15:40 UTC
Labels: needs-triage
