### ISSUE TITLE
Its non-English language support is poor compared to Radarr, which boasts global language support.

### ISSUE THREAD

**Issue by mapleshadow** [Sonarr/Sonarr#7471] opened 2024-12-10 01:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Could Sonarr adopt Radarr's more user-friendly media management settings? Radarr simply requires a format like {Movie Title:ZH} for direct Chinese language support (and similarly for other languages), making it very convenient. However, Sonarr fails to recognize this format, or its equivalent {Series Title:ZH} for TV series.

### Describe the solution you'd like

Can it recognize formats such as `{Series Title:ZH}`?

### Describe alternatives you've considered

Can it recognize formats such as `{Series Title:ZH}`?

**Comment by markus101** [comment] 2024-12-10 01:40
Duplicate of #269

**Closed by markus101** 2024-12-10 01:40 UTC
Labels: needs-triage
