### ISSUE TITLE
FR - Series Folder format

### ISSUE THREAD

**Issue by kingy444** [Sonarr/Sonarr#2404] opened 2018-02-11 12:24 UTC
### What problem are you looking to solve? When a new series is added, it is added in the format ‘SeasonName’ I would like to be able to create the folder in the format ‘SeasonName (ReleaseYear)’

While I’m happy for this to be hard coded, I’m sure some others have other preferences, so perhaps an option to choose the format similar to what we can do for episode titles.

**Comment by markus101** [comment] 2018-02-11 15:42
Dupe of https://github.com/Sonarr/Sonarr/issues/393

**Closed by markus101** 2018-02-11 15:42 UTC
