### ISSUE TITLE
Sonarr recognize 4 digits absolute number as S10E01

### ISSUE THREAD

**Issue by king8084** [Sonarr/Sonarr#4382] opened 2021-03-15 14:39 UTC
can easily be tested with detective conan, sonarr cant recognize episodes higher than 999

**Comment by bakerboy448** [comment] 2021-03-15 14:40
Closing; template not followed (Third party apps ignore templates FYI)

Duplicate of #4367

Fixed in develop/nightly

**Closed by bakerboy448** 2021-03-15 14:40 UTC
