### ISSUE TITLE
Manual Torrent search options.

### ISSUE THREAD

**Issue by n3tR1pper** [Sonarr/Sonarr#2649] opened 2018-07-05 18:32 UTC
I'm finding a lot of situations with anime shows not being found and downloaded and I think these are related to the translation of the title.  It would be nice if the "manual search" option would allow me to modify the string that Sonarr is passing to the indexers.  This would let me modify the show title to try alternate spellings or use the Japanese title, etc.

For example, I want to download a series that Sonarr has called "Mr. TONEGAWA Middle Management Blues" but the actual show title is "Chuukan Kanriroku Tonegawa" which is sometimes translated to "The Chronicles of Middle Manager Tonegawa".  If I could tweak the search string (maybe even shortening it to "tonegawa") then I might have better luck finding a torrent.

In general I prefer to "cast a wide net" with searches and get more results, then weed through those for something to download.

**Comment by markus101** [comment] 2018-07-05 18:46
Sounds like a dupe of https://github.com/Sonarr/Sonarr/issues/1128

No plans for customizing it outside of that at this time.

**Closed by markus101** 2018-07-05 18:46 UTC
