### ISSUE TITLE
Grab single episode releases when existing file contains 2 or more episodes

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#734] opened 2015-08-09 06:15 UTC
Finales/premieres occasionally are multi-part episodes, spanning two time slots. HDTV releases will contain the two episodes in one file, but WEBDL releases will usually only have one episode in the file. We could potentially allow the single episode WEBDLs to be grabbed (assuming both are posted) and let the user manually import the episodes (we shouldn't automatically delete a two episode file to import one episode), as it stands right now the user needs to manually search for both episodes then manually import both episode files.

**Comment by fryfrog** [comment] 2018-07-17 16:21
This finally got me, I had a multipart episode of The Expanse and it took a few moments to figure out why I couldn't get it to become Bluray.

A minor improvement could start w/ a simple indicator to show an episode is a multi episode file.

**Comment by napoleonsmith** [comment] 2018-07-18 20:19
Just had this as well, also with The Expanse. Worse, though, was that it deleted the new files. Fortunately I noticed in time to retrieve them from the recycle bin, but this can't be the intended behaviour.

**Comment by Diggity42** [comment] 2019-01-10 05:17
Season 3 of "The Good Place" has this issue where it downloads episode 01-02, but labels it as episode 01.  Then if you manually search for Episode 02, it searches for 03.  If you search for episode 05, it searches for 06.  And so on.  All the episodes are off by 1 episode.

**Comment by fryfrog** [comment] 2019-01-10 06:31
The Good Place is all fucked up because tvdb has it one way and scene is doing it another way. :(

**Comment by bakerboy448** [comment] 2020-11-17 23:59
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR

Interactive search exists...this would be nice to have, but resources are better spent elsewhere

**Closed by bakerboy448** 2020-11-17 23:59 UTC
Labels: enhancement, priority:low, proposal
