### ISSUE TITLE
Feature request: Series Title, The

### ISSUE THREAD

**Issue by SWu** [Sonarr/Sonarr#1677] opened 2017-02-13 02:55 UTC
Would it be possible to add a variant of Series Title which puts leading ['A', 'An', 'The'] at the end with a comma (e.g. 'Americans, The')?

**Comment by markus101** [comment] 2017-02-13 05:13
Dupe of https://github.com/Sonarr/Sonarr/issues/371

**Closed by markus101** 2017-02-13 05:13 UTC
