### ISSUE TITLE
V3 Import Lists Failing

### ISSUE THREAD

**Issue by johnkennyuk** [Sonarr/Sonarr#4100] opened 2020-11-16 14:07 UTC
**Describe the bug**
I have been trying to use Trakt lists in Sonarr V3, they do work with Limit of 100 +/- few but the lists ive been trying to use have entries in 1000 and above range.  But when setting the limit to 250 it seems the import crashes and fails to add any new entries.  I assumed that using low limits which work like 100 would allow me to use these large lists as I assumed that Sonarr would import 100 new shows every run but its not its just importing the first 100 and then the first 100 every run after that??? So that wont work for my needs I need to be able to run Lists with limits 1000 up???

**Screenshots**
![image](https://user-images.githubusercontent.com/64958468/99261700-f8967900-2814-11eb-8be5-2e07924c820b.png)

**Logs**
https://gist.github.com/johnkennyuk/eb2702e793d6f18435e3b6909a4fd464
https://gist.github.com/johnkennyuk/eb050e6ce5a95f2ae8977dc651f5f8a4
**System Information**

 - Sonarr Version: 3.0.4.1006
Package Version 3.0.4.1006-ls77 by linuxserver.io

 - Operating System: Ubuntu server 18.04 LTS
 - Mono Version 5.20.1.34

**UI Bugs:**
NA

**Additional context**

**Comment by bakerboy448** [comment] 2020-11-16 14:36
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

It looks like it is hitting a duplicate show on the list or the same show is twice?

Given the error is SQL complaining that the requirement for the titleslug to be unique is being violated

**Comment by johnkennyuk** [comment] 2020-11-16 14:38
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
> 
> It looks like it is hitting a duplicate show on the list or the same show is twice?
> 
> Given the error is SQL complaining that the requirement for the titleslug to be unique is being violated

So i assume that means Sonarr is unable to deal with lists trying to add duplicate shows??  Cant it just ignore the duplicate and carry on??

**Comment by bakerboy448** [comment] 2020-11-16 15:02
Reopening.

Suboptimal; we should handle duplicate titles in a list gracefully

**Comment by johnkennyuk** [comment] 2020-11-16 19:26
just attempted on clean Sonarr v3 deployment but the same list hit the same error when the Library was empty so its got to be something other than duplicate titleslugs unless its duplicate within the list only but surely trakt (what im using) wouldnt let a duplicate be added to start with????

**Comment by bakerboy448** [comment] 2020-11-16 19:29
Can you link the list here?

I'll skim it for dupes real quick

**Comment by johnkennyuk** [comment] 2020-11-16 19:32
https://trakt.tv/users/sflix/lists/anime-english-dubbed

**Comment by bakerboy448** [comment] 2020-11-16 22:50
Just tested that entire list on my dev install with a 10,000 limit 
FYI there are a few entries on that list that are removed on TVDB

Reproduced the error:

```20-11-16 16:45:36.8|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/375927: 200.OK (244 ms)
20-11-16 16:45:36.8|Trace|Owin|SQLite error (2067): abort at 62 in [truncated....]```

your logs

```20-11-16 14:18:51.1|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/78777: 200.OK (75 ms)
20-11-16 14:18:51.5|Trace|Owin|SQLite error (2067): abort at 74 in [INSERT INTO [Series]  [truncated.....,.]```

**Comment by bakerboy448** [comment] 2020-11-17 01:33
@johnkennyuk  figured out the cause!

**Root Cause 1** Trakt is using old tvdb ids that are dupes and merged.
**Root Cause 1.1** TVDB sucks....
**Root Cause 2** Still a bug as we should handle that gracefully...already discussing fixes

tvdb Ids
85230 redirects to 77773 both slug to star-blazers
103051 redirects to 78975 both slug to ragnarok-the-animation
282240 redirects to 262954  both slug to jojos-bizarre-adventure-2012

we'll work on a fix

**Comment by johnkennyuk** [comment] 2020-11-17 10:56
> @johnkennyuk figured out the cause!
> 
> **Root Cause 1** Trakt is using old tvdb ids that are dupes and merged.
> **Root Cause 1.1** TVDB sucks....
> **Root Cause 2** Still a bug as we should handle that gracefully...already discussing fixes
> 
> tvdb Ids
> 85230 redirects to 77773 both slug to star-blazers
> 103051 redirects to 78975 both slug to ragnarok-the-animation
> 282240 redirects to 262954 both slug to jojos-bizarre-adventure-2012
> 
> we'll work on a fix

Your a star many many thanks for all your help keep me posted, next time my Brave Browser pays out ill Send over Tips OK!!!

**Comment by bakerboy448** [comment] 2020-11-18 16:51
@johnkennyuk keep an eye on the PR https://github.com/Sonarr/Sonarr/pull/4101
when that is merged this should be fixed :)

I _think_ I have it to the point where markus will merge it today/tomorrow, still learning, so took a bit!

it comes with some nice pretty debug logging now too 🤣

**Comment by johnkennyuk** [comment] 2020-11-18 16:55
will give it a try thanks

**Comment by johnkennyuk** [comment] 2020-11-18 17:14
looks good so far it made it through my offending list and with limit set at 1250 so ill keep trying it but i was never able to get anywhere near where it just managed to get this time round..

**Closed** 2020-11-26 00:51 UTC
Labels: bug, suboptimal
