### ISSUE TITLE
Request: preference for contained text

### ISSUE THREAD

**Issue by rrdrummer** [Sonarr/Sonarr#1047] opened 2016-01-05 15:52 UTC
I know there are filters to ignore things, I'd love one to PREFER things. Specifically 5.1 coded tv. So when sonarr is filtering it will select those, all else being equal.

**Comment by markus101** [comment] 2016-01-07 06:33
Duplicate of: https://github.com/Sonarr/Sonarr/issues/385

**Closed by markus101** 2016-01-07 06:33 UTC
