### ISSUE TITLE
qBittorrent Labels now called Categories in 3.3.5

### ISSUE THREAD

**Issue by silentsharing** [Sonarr/Sonarr#1347] opened 2016-06-21 12:07 UTC
qBittorrent has renamed labels as categories in version 3.3.5 and it appears to be causing downloads to not be assigned to the appropriate label and thus to not be detected by Sonarr.

**Comment by markus101** [comment] 2016-06-21 18:10
They just added it too... I'm certainly unhappy how they released this, though there is a chance this is non-breaking because they're API happily returns successful responses even when it failed to set the label.

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#set-torrent-label

**Comment by obelisk3847** [comment] 2016-06-21 21:47
Until this is resolved you need to remove the "label" entry in Sonarr as Sonarr does not think it owns the download. It works fine though without a label/category.

**Comment by hennning** [comment] 2016-06-22 07:41
I can confirm labeling from Sonarr stopped working in latest update to qBittorrent.
I'm dependent on using labels since I need to put different files in different folders to separate movies and tv series.

**Comment by vintage81** [comment] 2016-06-26 09:00
A fix for this is in the works, in the meantime the easiest solution is to revert back to 3.3.4 while updates are being made. Just downloading the binary for 3.3.4 and installing automatically removes the current version and installs 3.3.4 whilst keeping all your settings and torrents. You can find the old binary on the official site or filehippo, etc.

**Comment by JourneyOver** [comment] 2016-06-27 03:45
Could this be the reason as to why when sonarr does it's rss stuff/search it adds two different downloads (the downloads are not completely the same since the the names of the torrents have slight changes like different release groups or some parts of the words are lowercase that are uppercase in the second torrent but sonarr still decides to download them both at the same time) of the same show/episode at the same time to qbittorrent instead of it only grabbing and downloading it once? or is my problem not related to this issue at all?

**Comment by Ptgtp** [comment] 2016-06-27 06:22
I experienced the same thing @JourneyOver describes, but in my case it added 5 separate downloads for the same episode. Reverting back to 3.3.4 does fix both issues.

**Comment by vintage81** [comment] 2016-06-27 08:37
Yes, looks like this is related to the same issue. Trying to set a label and failing causes Sonarr to assume the torrent couldn't be added and so adds another matching one, and so on.

**Closed** 2016-06-30 01:48 UTC
