### ISSUE TITLE
only scans first 100 episodes of anime

### ISSUE THREAD

**Issue by danielb2** [Sonarr/Sonarr#3206] opened 2019-07-13 04:21 UTC
**Describe the bug**

Doesn't  pick up sequential anime after episode 100

**Screenshots**
 

<details>
<summary>112 episodes in total.</summary>
<img width="644" alt="Screen Shot 2019-07-12 at 21 14 43" src="https://user-images.githubusercontent.com/26678/61166873-20235600-a4ea-11e9-90c3-7e245e704f7a.png">
</details>

<details>
<summary>Only 100 are picked up</summary>

<img width="1142" alt="Screen Shot 2019-07-12 at 21 15 28" src="https://user-images.githubusercontent.com/26678/61166884-519c2180-a4ea-11e9-835d-d1254762f962.png">

</details>

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: freebsd 12.0
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.10.1.57

**Additional context**

Series type is marked as anime.

"11.8 GB 100 files"  it says in the series detail overview, so it's clear it only sees 100 episodes.

**Comment by markus101** [comment] 2019-07-13 06:52
Dupe of https://github.com/Sonarr/Sonarr/issues/3117

**Closed by markus101** 2019-07-13 06:52 UTC

**Comment by danielb2** [comment] 2019-07-13 16:41
@markus101   this is not a duplicate. The other ticket is about parsing a string as an absolute episode number. This ticket is about having problems parsing 101 and more.

**Comment by markus101** [comment] 2019-07-14 01:24
No it’s exactly the same, 101 gets parsed as s01e01 instead of abs 101 and so on.
