### ISSUE TITLE
Write Authentication Events to the Log File

### ISSUE THREAD

**Issue by dannyhanes** [Sonarr/Sonarr#3323] opened 2019-10-02 18:12 UTC
**Description:**
Please consider writing information about user authentication to the log file. Ideally the following should be logged. 

* User [username] logged in
* Incorrect password for user [username]
* Failed login  for username: [username] not found

I am using Zabbix to monitor my other servers and I am parsing the logs to get notifications about failed / successful logins. This would help ensure that if there is a break-in attempt, I am notified.

**Comment by markus101** [comment] 2019-10-02 18:29
Dupe of https://github.com/Sonarr/Sonarr/issues/2760

**Closed by markus101** 2019-10-02 18:29 UTC

**Comment by dannyhanes** [comment] 2019-10-02 18:33
@markus101 Thanks for the info. Will this be added to v2, or only v3? And is v3 ready for prime-time? I am still running v2.

**Comment by markus101** [comment] 2019-10-02 18:50
At this point things are v3 only, unless it's a critical bug.

Lots of people using v3, still beta and may have some breaking changes (mostly an issue if you're on an ancient .net or mono version), but it's a lot like `develop` was in v2.

**Comment by dannyhanes** [comment] 2019-10-02 18:51
@markus101 Nice. Is there an upgrade path from v2 to v3? Or is it better to do a fresh install?

**Comment by dannyhanes** [comment] 2019-10-02 19:06
Ah, ignore me, found it - https://sonarr.tv/#downloads-v3-linux
