### ISSUE TITLE
Download skipped due to incorrect language, because it has 'spanish' in the title.

### ISSUE THREAD

**Issue by systemmonkey42** [Sonarr/Sonarr#2589] opened 2018-05-26 11:37 UTC
My apologies if this has been covered before, but in the TV series I am downloading, an episode has the word 'spanish' in the title.   The file to download has the word spanish in the filename as part of the title, however Sonarr is deciding the material is a spanish language version and chooses to exclude it.

[Screenshot](https://i.imgur.com/IGEB4t4.png)

If I had to suggest a fix, I would probably recommend removing the words that make up the title from the filename before attempting to divine quality/language/encoding/subtitles/etc from what is left, to prevent conflicts with episodes which have those words in the title.

This amazingly has only affected me once in over 5500 episode downloads, so I'm pretty impressed.  Also there is a chance there is something unusual about the episode or the filename I'm not seeing. Let me know if you have any questions.

Otherwise, fantastic software, and excellent work!
Thanks

**Comment by markus101** [comment] 2018-05-26 16:01
Dupe of https://github.com/Sonarr/Sonarr/issues/861

**Closed by markus101** 2018-05-26 16:01 UTC
