### ISSUE TITLE
Per show specific naming format

### ISSUE THREAD

**Issue by Hiren-Z** [Sonarr/Sonarr#2970] opened 2019-02-25 20:24 UTC
**Describe the problem**
Some anime series (such as Fairy Tale or Dragon Ball) download as multiple seasons however this confuses Plex since anidb has them as a single season.  

**Describe any solutions you think might work**
We can already have them download to a single folder, however the ability to have an alternate naming schema per series or an additional series type could solve the issue.

**Additional context**
Using Absolute Series Scanner and HamaTv for my plex scanner and metadata agent.

**Comment by markus101** [comment] 2019-02-25 20:25
Please search before opening issues, this is a dupe of https://github.com/Sonarr/Sonarr/issues/926

**Closed by markus101** 2019-02-25 20:25 UTC

**Comment by Hiren-Z** [comment] 2019-02-25 20:29
Not trying to be disrespectful, but I did search.  They ware only wanting to rename certain series, I requested a way to apply a different naming schema to certain series.

**Comment by markus101** [comment] 2019-02-25 20:44
Sorry, an idea I've chatted about regarding that issue, but not documented there apparently was to have rename profiles that would be linked to series, so you could rename a particular series one way and another a different way instead of just on or off. For now at least they're the same.

Right now if it's anime vs standard/daily you can opt to use the original title for all anime, if it's more specific then that won't work.
