### ISSUE TITLE
Manually changing task intervals

### ISSUE THREAD

**Issue by luizfeliperc** [Sonarr/Sonarr#4603] opened 2021-08-02 13:40 UTC
**Is your feature request related to a problem? Please describe.**
Guys, good morning.

For some time I've been noticing that because of the update time series I've been facing some google API errors using rclone.
As much as I have disabled sonarr video analysis, due to the amount of files in my library, errors are frequent.
A way out of this problem would be like 12 hours as the default system, but with an option of manual change by the user for as long as he/she deems necessary.

**Describe the solution you'd like**
Keep the default of 12 hours but with the option of manual change to a time chosen by the user.

**Comment by bakerboy448** [comment] 2021-08-02 13:41
Duplicate of https://github.com/Sonarr/Sonarr/issues/4325

and several others; no plans

**Closed by bakerboy448** 2021-08-02 13:41 UTC
