### ISSUE TITLE
Custom filters from Series view are not accessible in Mass Editor

### ISSUE THREAD

**Issue by flying-sausages** [Sonarr/Sonarr#4000] opened 2020-10-06 01:56 UTC
**Describe the bug**
I created a filter to only show daily shows in the series viewer. That filter is not available in the mass editor

**Screenshots**
Series view:
![image](https://user-images.githubusercontent.com/23618693/95150252-18536f80-0788-11eb-813f-b11ae62eabe1.png)

Mass editor:
![image](https://user-images.githubusercontent.com/23618693/95150283-27d2b880-0788-11eb-8aae-133b5a273223.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.3.938
 - Operating System: Ubuntu 20.04
 - .net Framework (Windows) or mono (macOS/Linux) Version:  6.8.0.105

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox 
 - Version: 81.0.1

**Additional context**

**Comment by markus101** [comment] 2020-10-06 02:23
Dupe of https://github.com/Sonarr/Sonarr/issues/3548

**Closed by markus101** 2020-10-06 02:23 UTC
