### ISSUE TITLE
Jackett Full Automation

### ISSUE THREAD

**Issue by DavideCampagna** [Sonarr/Sonarr#3766] opened 2020-05-20 22:13 UTC
This link in Jackett:
ip:9117/jackett/api/v2.0/indexers/all/results/torznab/api?apikey=API&t=indexers&configured=true

Returns an xml file containing all configured indexers, with their categories and so on, here is an example:

````
<indexers> 
        <indexer id="anidex" configured="true"> 
                <title>Anidex</title> 
                <description> Anidex is a Public torrent tracker and indexer, primarily for English fansub groups of anime </description>
                <link>https://anidex.info/</link> 
                <language>en-us</language> 
                <type>public</type> 
                <caps> 
                        <server title="Jackett" /> 
                        <searching> 
                                <search available="yes" supportedParams="q" /> 
                                <tv-search available="yes" supportedParams="q,season,ep" /> 
                                <movie-search available="no" supportedParams="q" /> 
                                <music-search available="no" supportedParams="" /> 
                                <audio-search available="no" supportedParams="" /> 
                        </searching>
                        <categories> 
                                <category id="100010" name="♫ - Lossless" /> 
                                <category id="100009" name="♫ - Lossy" /> 
                                <category id="100011" name="♫ - Video" /> 
                                <category id="100015" name="Adult Video" /> 
                                <category id="100003" name="Anime - Dub" /> 
                                <category id="100002" name="Anime - Raw" /> 
                                <category id="100001" name="Anime - Sub" /> 
                                <category id="100013" name="Applications" /> 
                                <category id="100012" name="Games" /> 
                                <category id="100005" name="LA - Raw" /> 
                                <category id="100004" name="LA - Sub" /> 
                                <category id="100006" name="Light Novel" /> 
                                <category id="100008" name="Manga - Raw" /> 
                                <category id="100007" name="Manga - TLed" /> 
                                <category id="100016" name="Other" /> 
                                <category id="100014" name="Pictures" /> 
                                <category id="5070" name="TV/Anime" /> 
                        </categories> 
                </caps> 
        </indexer> 
        (continues with the other configured indexers...) 
</indexers>
````

Since I've discovered this I've been wondering if is possible to add a new feature. My idea is that the user should just provide the ip:port/baseurl address and the api of Jackett and then Sonarr should parse that xml in order to automatically add all the indexers from Jackett. Maybe it can even check periodically Jackett in order to add/remove indexers according to the changes made in Jackett.
Hope you'll like this and thanks for your amazing job.

**Comment by markus101** [comment] 2020-05-20 23:38
Dupe of https://github.com/Sonarr/Sonarr/issues/3530

**Closed by markus101** 2020-05-20 23:38 UTC
