### ISSUE TITLE
Edit Restrictions, add Preferred contain keywords option

### ISSUE THREAD

**Issue by wdaniel526** [Sonarr/Sonarr#1588] opened 2016-12-15 21:20 UTC
![tbirpo8](https://cloud.githubusercontent.com/assets/1734051/21242108/8c8ef1e4-c2c7-11e6-886e-9ea6a44cad34.png)

Add the ability to setup Preferred keywords with Must contain keywords for anime that come out in Japanese and then English a bit later

**Comment by markus101** [comment] 2016-12-15 21:28
Dupe of https://github.com/Sonarr/Sonarr/issues/385

We haven't commit to upgrading episodes on disk if more preferred words are in a new release.

**Closed by markus101** 2016-12-15 21:28 UTC
