### ISSUE TITLE
Sonarr replacing hypen with empty space creating false title name

### ISSUE THREAD

**Issue by Zerwin** [Sonarr/Sonarr#2936] opened 2019-02-03 21:02 UTC
**Describe the bug**
I tried to find Episodes from a Series ( Kaguya-sama: Love is War) but the indexer (Jackett) didn't return any results. I digged a bit deeper and found that Sonarr would replace the hypen between Kaguya and sama with a %20 aka an empty space, which Jackett couldn't find any results for, only for Kaguyasama or Kaguya-sama.

**Logs**
Sonarr Trace Log: https://pastebin.com/b9bBD0Hb
Jackett Log: https://pastebin.com/mKJBL3aT
(replaced some stuff like ip,etc)

**System Information**

 - Sonarr Ver. 2.0.0.5301
 - Operating System: Debian 9 Stretch
 - Mono: 5.18.0.240

**Comment by markus101** [comment] 2019-02-03 21:04
Dupe of https://github.com/Sonarr/Sonarr/issues/1225

**Closed by markus101** 2019-02-03 21:04 UTC
