### ISSUE TITLE
One importation Notification when a Season is grabbed 

### ISSUE THREAD

**Issue by devIlluSioN** [Sonarr/Sonarr#3515] opened 2020-01-14 12:45 UTC
**Describe the problem**
When a season his grabbed I receive a notification, and after I got a notification by episode when its import.

**Describe any solutions you think might work**
Add the possibility to get one notification when the entire season is imported and not for each episode.

**Comment by markus101** [comment] 2020-01-14 18:46
Dupe of https://github.com/Sonarr/Sonarr/issues/363

**Closed by markus101** 2020-01-14 18:46 UTC
