### ISSUE TITLE
NZBGet Treat `Delete:Copy` as failed

### ISSUE THREAD

**Issue by j2ghz** [Sonarr/Sonarr#919] opened 2015-11-08 11:08 UTC
When NZBGet already failed to download an episode ![image](https://cloud.githubusercontent.com/assets/1708197/11019885/e7e31428-860d-11e5-8c05-09ca82842172.png), and Sonarr tries to download nzb with same content, NZBGet sets this status ![image](https://cloud.githubusercontent.com/assets/1708197/11019891/06d61cd6-860e-11e5-8c4f-ab508bb11aa9.png) which i guess Sonarr doesn't recognize.
So there's lots of hanging downloads in activity with this warning: ![image](https://cloud.githubusercontent.com/assets/1708197/11019872/7da21aaa-860d-11e5-862d-48f99c487c7e.png) `Download warning: check download client for more details`, waiting for me to click Remove from download client > Blacklist episode > Ok

Tried to get some log entries but there are none in Sonarr, and NZBGet has just this one line `Skipping duplicate <download name>, found in history <download name> with exactly same content`

`Sonarr 2.0.0.3530`
`NZBGet 16.2`

**Comment by markus101** [comment] 2015-11-14 18:40
The difference is in how nzbget reports it, `Delete: Health` is considered an error, where `Delete: Copy` is informational (to both Sonarr and nzbget). The issue here is two different duplicate check mechanisms conflicting, Sonarr doesn't consider the second release a duplicate of the first, but nzbget does. I don't know how nzbget's duplicate check makes its decision, but its something we have wanted to test (https://github.com/Sonarr/Sonarr/issues/505).

We're going to need to make a decision to see if we want to include `Delete: Copy` as a failed state so it gets automatically blacklisted and determine what the implications of it are.

**Closed** 2016-04-09 18:32 UTC
Labels: suboptimal

**Comment by danialmoghaddam** [comment] 2019-07-07 10:48
Is this not handled in v3? Because I am seeing that nzbget is marking as DELETE: COPY but Sonarr history shows no sign of marking it as fail.

Version
3.0.1.527
Mono Version
5.20.1.19

**Comment by jalmansor** [comment] 2019-07-07 14:51
I've noticed this very recently, but I thought maybe it had something to do with using nzbhydra and how copies are being determined.

Either way, I had one show I was trying to grab yesterday that I had to manually tell nzbget to try them anyway until I either got one that worked or I got through all the copies so it would move on to the next best release.

**Comment by danialmoghaddam** [comment] 2019-07-07 14:59
The issue here is not about if nzbget falsely marking items as duplicate. Sonarr needs to respect the status set by nzbget and either take automatic action (e.g. mark as failed and try another release) or show the status in activity for manual action
