### ISSUE TITLE
[Feature request] Set profiles at the season level

### ISSUE THREAD

**Issue by ClarSco** [Sonarr/Sonarr#1608] opened 2017-01-01 20:54 UTC
For long running series, it is common for early seasons to be filmed at lower resolutions than newer/current seasons.

By setting the series profile to 1080p (for example), Sonarr will mark older seasons as "Cutoff unmet" even though the highest possible resolution for the earlier seasons is 480p (for example).

Alternatively, setting the series profile to 480p will then prevent Sonarr from fetching the 1080p releases of the newer seasons.

I, therefore, propose that the profile should be adjustable at the season level.

**Comment by markus101** [comment] 2017-01-01 21:50
Dupe of https://github.com/Sonarr/Sonarr/issues/319 (though it's not currently a priority). You can unmonitor older seasons if you don't want them to appear in cutoff unmet if that's the only concern.

**Closed by markus101** 2017-01-01 21:50 UTC
