### ISSUE TITLE
Files are not removed from Sonarr when the folder that contains the files is deleted

### ISSUE THREAD

**Issue by cospking** [Sonarr/Sonarr#6693] opened 2024-04-07 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

1: Sonarr downloads file
2: User deletes folder that contains downloaded file
3: Press **Update all** in Sonarr or **Refresh & Scan** on series page.
3: Sonarr keeps thinking the file is still there

### Expected Behavior

**After user deletes the folder containing the files, it should:**
1: Remove the mention of that episode in the Sonarr database.
2a: Simply Unmonitor episodes
2b: Or add a setting under **Media Management** that toggles whether deleting a folder, which makes it non existent means it should unmonitor (on) or not unmonitor (off), this might be helpful if people change paths of their files.

### Steps To Reproduce

1: Download file with Sonarr
2: Delete the entire folder, in my example this is (D:\Downloads\Anime\Ninja Kamui)
3: Press **Update all** in Sonarr or **Refresh & Scan** on series page.

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.3.1413
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14896880/sonarr.trace.txt)
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/14896878/sonarr.trace.0.txt)
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/14896879/sonarr.trace.1.txt)

### Anything else?

![firefox_z3g7aQHsH4](https://github.com/Sonarr/Sonarr/assets/108274310/bf30ae73-0474-49a7-8487-bd2fc167501e)
![firefox_4n5ZIxOsG1](https://github.com/Sonarr/Sonarr/assets/108274310/aaf9fb26-637d-416a-a675-840a2b5b55fc)

Screenshots are taken AFTER removing the folder.

**Relevant settings:**

**Media Management:** 
Create Empty Series Folders: OFF
Delete Empty Folders: ON
Unmonitor Deleted Episodes: ON
Rescan Series Folder after Refresh: ON

**Comment by stevietv** [comment] 2024-04-07 11:19
It looks like Sonarr Root folder protection is kicking in here:
`2024-04-07 12:57:52.1|Warn|DiskScanService|Series' root folder (D:\Downloads\Anime\) is empty.`

When Sonarr sees an empty root folder it won't make any changes to the DB as it assumes that it could be a network drive that disconnected or such. for this reason the show is not altered or unmonitored. If you have an empty text file in that root folder the protection won't kick in.

Also, you should NOT be using your downloads folder as your root folder. Downloads are for messy, unorganised, unimported downloads. Root folder is your organised media library where Sonarr imports the media to and renames it in a good structured format.

**Comment by augustuen** [comment] 2024-04-07 11:20
This looks to be intended behaviour.

> 13:03:07.3|Warn|DiskScanService|Series' root folder (D:\Downloads\Anime\) is empty.

According to your log, your root folder is empty. In which case, Sonarr assumes it's a temporary disconnect, so it doesn't update the status of your files. If you put anything inside your root folder, Sonarr should realise that the folder has actually been _deleted_ and remove the file from its Database.

**Comment by cospking** [comment] 2024-04-07 11:34
> It looks like Sonarr Root folder protection is kicking in here: `2024-04-07 12:57:52.1|Warn|DiskScanService|Series' root folder (D:\Downloads\Anime\) is empty.`
> 
> When Sonarr sees an empty root folder it won't make any changes to the DB as it assumes that it could be a network drive that disconnected or such. for this reason the show is not altered or unmonitored. If you have an empty text file in that root folder the protection won't kick in.
> 
> Also, you should NOT be using your downloads folder as your root folder. Downloads are for messy, unorganised, unimported downloads. Root folder is your organised media library where Sonarr imports the media to and renames it in a good structured format.

This folder is a **self-created** Downloads folder, not the one that's allocated per user account such as 
C:\Users\USERNAME\Downloads
They're also not linked in any way, I only have a separate drive for my multimedia (Games/Series/Movies/Music etc)


> This looks to be intended behaviour.
> 
> > 13:03:07.3|Warn|DiskScanService|Series' root folder (D:\Downloads\Anime) is empty.
> 
> According to your log, your root folder is empty. In which case, Sonarr assumes it's a temporary disconnect, so it doesn't update the status of your files. If you put anything inside your root folder, Sonarr should realise that the folder has actually been _deleted_ and remove the file from its Database.

Yeah I noticed that warning in the logs and adding an empty text file to the Root folder has Sonarr correctly remove it from the database as I just tried.

But unless you're utilizing a ton of Symbolic links yourself outside of Sonarr, Sonarr assuming it's a temporary disconnect would mean it should not be able to access the drive in the first place.

Wouldn't a better method be: 
1: Sonarr attempts to access drive 
2a: Sonarr can't access drive > Disconnect > Do nothing unless user manually overrides.
2b: Sonarr can access drive but root folder is empty > Remove files from database and optionally unmonitor if setting is set.

**Comment by stevietv** [comment] 2024-04-07 11:38
> This folder is a self-created Downloads folder, not the one that's allocated per user account such as C:\Users\USERNAME\Downloads

That isn't what I was implying. Your DL client should download to `D:\Downloads` - Sonarr should import to `D:\media\tv` (as crude examples)

>But unless you're utilizing a ton of Symbolic links yourself outside of Sonarr, Sonarr assuming it's a temporary disconnect would mean it should not be able to access the drive in the first place.

not necessarily - there are plenty of times when a network drive is mounted to a folder, when the network is down the folder appears empty. This is very common in Linux cases. The handling in Sonarr is optimal.

Closing the issue.

Feel free to drop by one of our support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Closed by stevietv** 2024-04-07 11:38 UTC
Labels: needs-triage

**Comment by cospking** [comment] 2024-04-07 11:44
> > This folder is a self-created Downloads folder, not the one that's allocated per user account such as C:\Users\USERNAME\Downloads
> 
> That isn't what I was implying. Your DL client should download to `D:\Downloads` - Sonarr should import to `D:\media\tv` (as crude examples)
> 
> > But unless you're utilizing a ton of Symbolic links yourself outside of Sonarr, Sonarr assuming it's a temporary disconnect would mean it should not be able to access the drive in the first place.
> 
> not necessarily - there are plenty of times when a network drive is mounted to a folder, when the network is down the folder appears empty. This is very common in Linux cases. The handling in Sonarr is optimal.
> 
> Closing the issue.
> 
> Feel free to drop by one of our support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Sonarr**
![firefox_DyE1dS7qqG](https://github.com/Sonarr/Sonarr/assets/108274310/1b038d4d-d6c3-4e72-b305-42974dfcc02d)

**Qbittorrent**
![qbittorrent_l5NZIqLZZj](https://github.com/Sonarr/Sonarr/assets/108274310/42221f26-dc2b-429f-80ea-bb3cfedaf1c4)

Not sure but that's the way it's set-up.

Isn't there an _easy_ way inside both Linux and Windows to differentiate between a regular physical drive inside the PC and a network drive?

**Comment by stevietv** [comment] 2024-04-07 11:48
So your root folders in sonarr are sub-folders of your Downloads folder.
What if a download contained a subfolder `Anime` - then it would end up in your sonarr folder before being imported by sonarr.
This is not an optimal setup.
