### ISSUE TITLE
Please stop importing 0 byte files

### ISSUE THREAD

**Issue by CurlyFlow** [Sonarr/Sonarr#6686] opened 2024-04-03 11:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

For whatever reason tdarr sometimes spits 0 byte files out. But thats another problem.

**Sonarr makes it worse because it auto checks 0 byte files.**

### Expected Behavior

Please dont auto check 0 byte files.

I have to uncheck every day around 200-300 files, which is very annoying.

### Steps To Reproduce

1. have 0 byte file
2. do manual import

### Environment

```I dont think that matters.
```

### What branch are you running?

Main

### Trace Logs?

I dont think thats neccessarry.

### Anything else?
![1](https://github.com/Sonarr/Sonarr/assets/43281991/171a1943-9c18-4a86-9b82-f5d92385a6bc)

**Comment by stevietv** [comment] 2024-04-03 15:57
Please expand on what you mean by 'auto checks' 0 byte files, Do you mean on an import screen.
In a good setup you shouldn't need to be manually importing on a regular basis. Why not just set up a script that deletes 0 byte files.
skipping the environment section and the trace logs section of a bug report is also not acceptable.

**Comment by stevietv** [comment] 2024-04-04 09:24
> In a good setup? with all due respect, all those apps are build only for english speaking people, maybe for those it works without manual intervention, but for other languages? Try to walk in our shoes! We even startet to build our own translation layer because of lacking support. https://github.com/PCJones/UmlautAdaptarr

Interesting project. Sonarr currently has an alias request system to request foreign aliases - details can be found [here](https://wiki.servarr.com/en/sonarr/faq#why-cant-sonarr-import-episode-files-for-series-x-why-cant-sonarr-find-releases-for-series-x). It is indeed a limitation of the TVDB API that only english titles are currently available to Sonarr, something that we hope at some point can be improved upon. Sonarr being an open source free project means that choices have to be made as to where development time is allocated for the most win. I hope that at some point that project you linked becomes obsolete!

> anyway, there are some people having the same problem with tdarr. [HaveAGitGat/Tdarr#978](https://github.com/HaveAGitGat/Tdarr/issues/978)

I understand that this is indeed a Tdarr issue. you are now asking multiple projects to implement fixes due to a problem with another piece of software. We may consider deselecting the 0bytes at some point.

> I already posted pictures what i mean. There are checkboxes, which gets automatically checked, did you even looked at my picture? or my description????

Clearly I asked for more information as it was not clear to me. That is the point of the discussions here. I wanted to check my assumption was correct.

> 
> > I have to uncheck every day around 200-300 files, which is very annoying.
> 
> > Why not just set up a script that deletes 0 byte files.
> 
> Why not just stop wanting to import 0 byte files?
> 
> > skipping the environment section and the trace logs section of a bug report is also not acceptable.
> 
> If you dont want to make this app better, keep closing, i wont provide uneccessary logs. **Or should it not check 0 byte files on its own?**

We always want to make improvements to this app. The assumption that we don't and the unwillingness to work with us in a simple discussion is incredible. Check your attitude.

A simple solution for you for now:

* sort the manual import column by size.
* shift click the first and the last that are 0bytes - all will be unselected between the two that you click.

**Comment by bakerboy448** [comment] 2024-04-04 13:14
> suggested multiple times over years and then the custom crap came which is way more complicated (for new users) and which ALSO not works for multi lingual

See sonarr's support or trash guides for help with this rant in addition to the faq entry below

- https://wiki.servarr.com/sonarr/faq-v4#where-have-language-profiles-gone

works perfectly fine. 

=========

And your rants have no relevance to the details that are REQUIRED and NOT OPTIONAL for bug reports. For all anyone knows you're using an ancient pre-stable v4 beta or custom version since the required information was not provided.

**Comment by bakerboy448** [comment] 2024-04-04 14:14
Quality can easily be merged together and all rankings and scoring handles with CFs...as the docs clearly indicate. But again, that's a support issue and unrelated to Sonarr rejecting (for an unknown reason) yet still selecting the 0 byte files.

given you stated version doesn't matter then this can never be fixed as versions don't matter and bug fixes can only happen in new versions ;)

not sure why you need to be hostile but every continued hostile, unproductive interaction simply results in this niche issue caused by a third party bug further down the todo list.  Why would anyone want to fix something for someone who cannot provide required info, is hostile, and thinks they know everything?

Perhaps the sonarr team will keep this open, but given it's an invalid bug report due to missing required information who knows

**Comment by stevietv** [comment] 2024-04-04 14:32
I'm not going to close an issue for a bad attitude. This had better been placed as a FEATURE REQUEST instead of a BUG REPORT. This is not a bug as its currently functioning as intended.

For all reports we decide that you need to provide the information requested, this is not for you to determine. We have seen a hundred times people reporting bugs or requesting features that were already implemented or fixed.

The hostility needs to stop. We understand that Sonarr isn't working as you want it, but you also have to understand that how you are using it is currently an edge case, and development times goes to the big wins quicker than the smaller wins.

**Comment by Roxedus** [comment] 2024-04-04 15:19
> It always ends like this.

And the common factor seem to be you.

**Comment by TRaSH-** [comment] 2024-04-04 15:36
> We even startet to build our own translation layer because of lacking support. https://github.com/PCJones/UmlautAdaptarr

I'm working together with him and a few others to create a German quality profile. 
I also asked them if the 0 bytes thing was a common thing with German releases.
Their comment was, no it isn't. And they think it might be related to tdarr if you're using that.

Not saying it's a non existing issue, but if it's related to tdarr then the workflow should be changed. And this issue is not related to German releases but a common thing when people use tdarr and don't use a optimal workflow.

**Comment by TRaSH-** [comment] 2024-04-04 16:50
I don't think it's a unRAID issue, it's a tdarr issue and the lack of a proper API support from their side.
A perfect example how it should be done is unpackarr.

But I do understand how annoying it could be in your case.

**Comment by TRaSH-** [comment] 2024-04-05 10:20
If setup correctly you should only have 1 share added to Sonarr, Radarr, download client, tdarr etc. so you get a move vs a copy 
Adding multiple shares result in a slower copy + delete

**Comment by TRaSH-** [comment] 2024-04-05 11:06
My cache is also a diffe rent drive, but it all comes to the point if you setup your share optimal or not. 
There is a written guide how to setup a optimal share setup, found [here](https://trash-guides.info/Hardlinks/How-to-setup-for/Unraid/)
In general I don't do personal support any more, especially when tdarr comes in to place. 
The guide has a dedicated support discord where you can ask any questions related to the guide or anything else related to it.
But I talked to someone that used to use tdarr and he said that this sometimes happens if the file gets copied and not moved. 

The actual issue is tdarr and you're trying to let Sonarr fix tdarr short coming.
(Even that it would be nice that Sonarr or Radarr won't auto select 0 byte files)

I hope that if you setup a proper path and share setup it solves most of your issues.

But I will leave this github issue as it is, because we're going offtopic, I'm just trying to come with a work around to your actual issue. 
So any questions related to these suggestions I suggest you join the guide discord and ask your question there in their support channel. 
(Keep in mind they aren't a big fan of tdarr etc apps if it's used to re-encode your media, they actually suggest to get another quality source to start with)

**Closed** 2024-04-28 01:07 UTC
Labels: enhancement, priority:low, ui-only, up-for-grabs
