### ISSUE TITLE
Force download of "unknown series"

### ISSUE THREAD

**Issue by danielb2** [Sonarr/Sonarr#3135] opened 2019-05-24 17:13 UTC
**Describe the problem**

Doing a manual search results in a valid result but Sonarr tells me it's an "unknown series" and doesn't offer me the option to force download.

**Describe any solutions you think might work**

Just allow the button to add to queue like all other rejected downloads.

**Additional context**

So far I've dealt with added rejected results by manually getting the nzb and it's been a good one every time. Seems this is an easy fix.

I've only seen this happen with anime.

**Comment by markus101** [comment] 2019-05-24 17:14
Dupe of https://github.com/Sonarr/Sonarr/issues/395

**Closed by markus101** 2019-05-24 17:14 UTC

**Comment by danielb2** [comment] 2019-05-24 17:23
Thank you @markus101 

I realize this is github issue, but I want you to know that people aren't bad at searching when trying to find this befor filing a duplicate. I searched and as you can see, there was no match:

<img width="1113" alt="Screen Shot 2019-05-24 at 10 21 40" src="https://user-images.githubusercontent.com/26678/58345724-e13c2280-7e0d-11e9-88ca-dacab585c0d9.png">

I'm sure there is some annoyance to deal with dupes, so hopefully you see it's not due to a lack of effort that I filed this.
