### ISSUE TITLE
Jellyfin Connect does not work

### ISSUE THREAD

**Issue by flosoft** [Sonarr/Sonarr#7095] opened 2024-08-14 05:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the Emby / Jellyfin Connect option, Jellyfin errors out:

See logs below.

### Expected Behavior

It should do a partial refresh of the library.
The endpoint that should be used is the following: `/Library/Media/Updated`
https://api.jellyfin.org/#tag/Library/operation/PostUpdatedMedia

### Environment

```markdown
- OS: Synology DSM 7.2 / Docker
- Sonarr: 4.0.8.1874
- Docker Install: Yes
- Using Reverse Proxy: Yes (not applicable here as it connects directly to Jellyfin)
- Browser: Firefox
```

### What branch are you running?

Main

### Trace Logs?

```
[v4.0.8.1874] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [POST] at [http://X.X.X.X:8096/Notifications/Admin]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 363
   at NzbDrone.Core.Notifications.Emby.MediaBrowserProxy.ProcessRequest(HttpRequest request, MediaBrowserSettings settings) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs:line 146
   at NzbDrone.Core.Notifications.Emby.MediaBrowserProxy.Notify(MediaBrowserSettings settings, String title, String message) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs:line 35
   at NzbDrone.Core.Notifications.Emby.MediaBrowserService.Notify(MediaBrowserSettings settings, String title, String message) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserService.cs:line 36
   at NzbDrone.Core.Notifications.Emby.MediaBrowser.OnImportComplete(ImportCompleteMessage message) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowser.cs:line 54
   at NzbDrone.Core.Notifications.NotificationService.Handle(DownloadCompletedEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 243
```

**Comment by markus101** [comment] 2024-08-14 13:28
>  I have searched the existing open and closed issues

Not sure what you searched for, but if you searched for "Jellyfin" you'd have seen a couple results at the very top about this. There is also a recent PR https://github.com/Sonarr/Sonarr/pull/7048

Duplicate of #5828
Duplicate of #7042

**Closed by markus101** 2024-08-14 13:28 UTC
Labels: needs-triage
