### ISSUE TITLE
Trigger event when download is missing for X amount of time

### ISSUE THREAD

**Issue by brianjmurrell** [Sonarr/Sonarr#6219] opened 2023-11-29 15:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes a download fails to get found and I need to search for it manually.  But I don't know this is the case unless I happen to be observing Sonarr and notice it.

### Describe the solution you'd like

I would like an event to be triggered through the event framework when a download is still missing after a definable amount of time.  Personally I would probably set this to 1-2 days.

### Describe alternatives you've considered

There aren't any I can think of.

**Comment by bakerboy448** [comment] 2023-11-30 14:28
Likely duplicate of https://github.com/Sonarr/Sonarr/issues/3327

**Comment by bakerboy448** [comment] 2023-11-30 15:24
Same issue / root cause - the releases do / did not appear on your RSS feeds even when Sonarr paged back

**Comment by brianjmurrell** [comment] 2023-11-30 16:04
But the action is completely different.  I don't want torrents to be the result of that.  I want an event in the event framework that I can code to do whatever I want when it happens.

So to simply resolve #3327 as described in it, that being a hard-coded fallback to torrents when a release goes a certain amount of time without being downloaded does not resolve this ticket in any way.  If the scope of #3327 is expanded to include triggering an event in the event framework, then perhaps this is a duplicate.

But most importantly #3327 has been closed as completed and locked.

**Comment by bakerboy448** [comment] 2023-11-30 17:33
Torrents vs. usenet same thing

sonarr pages back in rss up to 1000 results. if your  rss interval is too long or your indexers have too many results then things may be missed.  Events filtered for warnings will show you if there were gaps in your rss feeds and if a search is required.

3327 and this have the same issue and same solution: nothing was grabbed for an episode after X days for the release date so automatic search.

Given the entire point of sonarr is to avoid hammering indexers and trackers with continual searches and thus not be banned by them - this request is highly unlikely.

also you can write a script that uses the api to do this as well with Wanted => Missing, getting the air date and comparing to todays date

**Comment by markus101** [comment] 2023-12-09 19:46
The problem is this would also be polling on Sonarr's side, whenever that task runs it would need to check for all episodes without files that aired more than X hours/days then decide whether it should send a notification about that and then track whether it did or not.

Additionally it would need logic (and probably more options) around what to do with newly added series with missing episodes as well as how long ago to scape back.

While this is an interesting idea/request it's not something we're going to implement, but a bespoke tool could be made to send notifications, likely using the wanted/missing API: https://sonarr.tv/docs/api/#/Missing/get_api_v3_wanted_missing

**Closed by markus101** 2023-12-09 19:46 UTC
Labels: needs-triage
