### ISSUE TITLE
Sonarr v3 can't import downloaded release

### ISSUE THREAD

**Issue by SuberSeb** [Sonarr/Sonarr#3697] opened 2020-04-23 05:50 UTC
**Describe the bug**
Sonarr grabbed new episode from torrent, but after downloading Sonarr can't import that release. Error is like "File is not an upgrade" or similar. But there are no any files for that episode at all. Strange behaviour. It started after past 2-3 updates. 

**System Information**

 - Sonarr Version: 3.0.3.770
 - Package Version: 3.0.3.770-ls9 by linuxserver.io

**Comment by markus101** [comment] 2020-04-23 06:04
At the very minimum we need debug logs, trace logs would be preferred.

**Comment by SuberSeb** [comment] 2020-04-23 06:11
https://pastebin.com/u78XpJkJ

Look at Roswell, New Mexico and 9-1-1.

**Comment by markus101** [comment] 2020-04-23 06:31
You'll need to enable debug or trace logging and post those, info logs don't show enough details.

**Comment by SuberSeb** [comment] 2020-04-24 05:56
[sonarr.debug.7.txt](https://github.com/Sonarr/Sonarr/files/4526899/sonarr.debug.7.txt)

Look for "The Resident" here. Same bug - it was downloaded but I can't remove in from the queue.

**Comment by SuberSeb** [comment] 2020-04-24 06:57
Here look for "Better Call Saul".
[sonarr.debug.0.txt](https://github.com/Sonarr/Sonarr/files/4527185/sonarr.debug.0.txt)
[sonarr.debug.1.txt](https://github.com/Sonarr/Sonarr/files/4527187/sonarr.debug.1.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4527189/sonarr.debug.txt)

**Comment by markus101** [comment] 2020-04-25 21:14
The underlying issue is the grabbed release says it's one quality, but at import time Sonarr found a different quality, it's left in the queue to be managed manually, this is expected. Once imported manually through the queue it should be automatically untracked, but I found one issue with multi-episode files there and found that when removed they would reappear because ignored releases weren't being skipped properly.

Both issues will be fixed in an upcoming release.

**Closed** 2020-04-25 21:15 UTC
Labels: bug

**Comment by SuberSeb** [comment] 2020-04-26 08:34
@markus101 it was fixed in 3.0.3.771?

**Comment by SuberSeb** [comment] 2020-04-26 10:38
Episodes from torrent still can't import automatically. Is it possible to add the option which completely disable that check - "The underlying issue is the grabbed release says it's one quality, but at import time Sonarr found a different quality, it's left in the queue to be managed manually, this is expected. "?

**Comment by markus101** [comment] 2020-04-26 16:39
Why does the indexer say it’s one quality, but the file name doesn’t? Sonarr doesn’t know which one is correct.

**Comment by SuberSeb** [comment] 2020-04-26 16:41
Obviously file name... Not the all indexers naming their releases properly. This option really can help. For example "Prefer file name quality".

**Comment by markus101** [comment] 2020-04-26 16:45
Then you’d get Sonarr trying to redownload the same episode multiple times.

The indexer said it was WEB-DL 720p, but when the file was downloaded it was detected as HDTV 720p, if it just imports it then the next time it sees a WEB-DL 720p release it’ll try to grab it (assuming the cutoff hasn’t been met).

I don’t see an option being a good thing to deal with a shitty indexer.

**Comment by SuberSeb** [comment] 2020-04-26 16:49
We don't have not "shitty" indexers... This option can really help.
What about "Has the same name as before grabbed release" error? Maybe Sonarr don't grab same release again?

**Comment by markus101** [comment] 2020-04-26 17:30
> We don't have not "shitty" indexers...

Yeah, that's pretty much the nail on the head (at least in the torrent world).

We actually already have that check, which definitely will help against that exact release, but the issue is usually with other releases. I'm discussing with Taloth and the Radarr devs on what we should do.

**Comment by SuberSeb** [comment] 2020-04-28 05:03
Is there any news about my problem?

**Comment by markus101** [comment] 2020-04-28 15:04
https://github.com/Sonarr/Sonarr/pull/3708

**Comment by SuberSeb** [comment] 2020-04-28 15:10
@markus101 it was added in 3.0.3.777 or it will be added in future release?

**Comment by markus101** [comment] 2020-04-28 15:18
It's still open, it will be in a future release.

**Comment by SuberSeb** [comment] 2020-04-28 15:20
@markus101 thank you.

**Comment by SuberSeb** [comment] 2020-05-05 05:07
Any news?

**Comment by SuberSeb** [comment] 2020-05-11 06:28
Hello!
I see that pull request is still open. Will it be merged into phantom-develop?

**Comment by markus101** [comment] 2020-05-11 06:29
When it's done it will be.
