### ISSUE TITLE
Metadata Language

### ISSUE THREAD

**Issue by ZIZNAH** [Sonarr/Sonarr#5386] opened 2023-01-21 18:32 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I tried to perfect my viewing experience using servarr series tools + emby.
In the last few downloads, I feel there is a bit of a problem area, I think a product that good should be well known all over the world, but I have a problem in the recent Metadata Language, it keeps showing as English, but it is not my native language, so the overall viewing experience makes me a bit less satisfied, I found in radarr that he has in his Metadata I found in radarr that his Metadata has the option of Metadata Language, but sonarr does not.
![image](https://user-images.githubusercontent.com/47733889/213881697-cac28e2a-df97-4085-ba03-e3e98b40c76f.png)

### Describe the solution you'd like

I hope to add the Metadata Language function.
I asked about metadata for themoviedb before, but I heard that adding it would require refactoring, which is equivalent to new software, so I only thought of this language issue for now.

### Describe alternatives you've considered

Not available at the moment

### Anything else?

I was wondering if you guys have thought about a tool that integrates sonarr and radarr, he won't replace them, just on top of one can use both sonarr and radarr.

**Comment by markus101** [comment] 2023-01-21 18:49
Dupe of https://github.com/Sonarr/Sonarr/issues/269

**Closed by markus101** 2023-01-21 18:49 UTC
Labels: needs-triage

**Comment by ZIZNAH** [comment] 2023-01-21 19:01
After posting this question, I searched for the issue, and generally read that everyone has such a need, all dating back to 2015, this is dependent on the api provided by metadata is it? It's really quite a pity, I have also seen the problem of sonarr scraper selection on the forum before, everyone is spitting thetvdb difficult to use, there are also many people are also maintaining thetvdb, I hope everyone can build it better instead of spitting, the internationalization of the language is really more convenient for users, thank you for your reply. I choose to turn off the nfo scraping, only scraping images, and give the metadata scraping burden to emby. Thanks again.

@markus101 Thank you
