### ISSUE TITLE
Asian Drama Support

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#1973] opened 2017-06-12 09:28 UTC
Asian dramas are just one season long so release with episode number only usually EP01 EP02 etc. 

1. I was hoping for a new category for them different from daily and normal so when searching for an episode or the whole drama the season is not added in the search terms that would at least allow to get manual search results.
2. At import the season prefix should be ignored as well. But he files should be renamed with season like normal as tvdb and kodi do not support no season shows.

**Comment by markus101** [comment] 2017-06-12 15:22
Dupe of https://github.com/Sonarr/Sonarr/issues/1604

Currently depending how the series is added to TheTVDB selecting `Anime` for the series type should work at least for grabbing via RSS.

**Closed by markus101** 2017-06-12 15:22 UTC
