### ISSUE TITLE
[Feature request] Language Profile  "Original Language"

### ISSUE THREAD

**Issue by GeoCookie** [Sonarr/Sonarr#4016] opened 2020-10-14 11:16 UTC
Hi,

I have an idea regarding the management of language profiles that I would like to share with you.

Since some websites (Trakt and IMDB) list the language of the TV shows, it would be nice to be able to create an “Original Language” profile, allowing Sonarr to download the show in its original language. For people, like me, who like to watch a show in its native language, it can simplify the process of adding a new series, from Sonarr and other tools (like Ombi).

What do you think of this idea, and is it something doable?

Thank you for your hard work! Cheers

**Comment by markus101** [comment] 2020-10-14 14:21
Dupe of https://github.com/Sonarr/Sonarr/issues/3843

**Closed by markus101** 2020-10-14 14:21 UTC
