### ISSUE TITLE
Using qbittorent/deluge subcategories for pre sorting file downloads for hardlinks

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#4847] opened 2022-01-09 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently when all downloads are sent to the sonarr category. They are downloaded to the same place.  Now if you have 1 storage pool that is okay your files get hard-linked quickly and you are good to go. But if your different show episode files have to be moved to different storage pools or different disks. Then you have to manually move the torrent to the disk/pool you want then reimport it into sonarr so the files are hard linked and you are not wasting space. This kills the automation point of sonarr. I have 3 different pools 1 for US/UK TV shows 2 for Asian TV shows 3 for anime so would prefer the downloads to be presorted. Previously I was using 2 instances of sonarr but I think adding more sonarr instances for something that is already built into torrent clients is just a waste.

### Describe the solution you'd like

The solution I have thought of are 2. 

1. Just use the Root folders of the show as the subcategory to use. So the episode files of each show are downloaded to the subcategory and as you can define which disk/pool torrents in a sub category will be downloaded it automatically downloads to the correct place.
2.  Or you use sonarr tags for tv shows to define which sub category you want the episodes to be downloaded to.

### Describe alternatives you've considered

Running multiple instances of sonarr

### Anything else?

if the 1st solution is implemented need to check if root folders have the same name if not differentiate between categories. 
If the change category after import used move to the subcategory of that.

**Comment by markus101** [comment] 2022-01-09 16:47
Close enough to a dupe of https://github.com/Sonarr/Sonarr/issues/402 where tags are used to control which client is used.

**Closed by markus101** 2022-01-09 16:47 UTC
Labels: needs-triage
