### ISSUE TITLE
Adding usage statistics about indexer

### ISSUE THREAD

**Issue by al13nus** [Sonarr/Sonarr#4497] opened 2021-05-18 10:52 UTC
Hey,

I would love to have an additional view/statistic about used "Indexers". Especelly interesting it would be to know: 
- which indexer provides how much downloads
- which indexer provides how much fails/bad downloads
- ... downloads per quality (which one provides best quality e.g.)

having some pie charts or staked charts would be totally enough for the beginning.

The problem I'm trying to solve is that I have more then 5 indexers and I don't really know which one provides the most downloads, so I have to pay for subscription to all of them.

**Comment by Qstick** [comment] 2021-05-18 11:05
Ref #323 also #1119 that never materialized

**Comment by bakerboy448** [comment] 2021-05-18 12:26
Dupe of previous and no plans this is something that should be in hydra/equivalent

**Closed by bakerboy448** 2021-05-18 12:26 UTC
