### ISSUE TITLE
Compare Release Date with Air Date

### ISSUE THREAD

**Issue by kanine** [Sonarr/Sonarr#3111] opened 2019-05-12 10:15 UTC
There are a few shows that have a tendency to have mixed up Season and Episode numbers. Whilst this is largely taken care of with mappings it would be great to compare the release date with the air date to avoid obvious errors. eg The Gadget Show in the UK right now.

**Comment by markus101** [comment] 2019-05-12 15:36
Dupe of https://github.com/Sonarr/Sonarr/issues/969

**Closed by markus101** 2019-05-12 15:36 UTC
