### ISSUE TITLE
Support for downloads that contain multiple series

### ISSUE THREAD

**Issue by RebelliousPebble** [Sonarr/Sonarr#3839] opened 2020-06-28 00:04 UTC
One issue with sonarr is when downloading a multi show series, sonarr will find and download torrents that contain multiple series of a show but only utilise the download for the series it is trying to download. For example, when trying to download the inbetweeners, to download the first season, sonarr will trigger the download for a torrent that contains all 3 seasons of the show, but only take the first season and then queue up different torrents for the other seasons. This requires unnecessary bandwith and storage, and could be eliminated

This could be achieved by checking the file list of a torrent to check for folders such as 'Season 1', 'Season 2' and then organising the download and sorting of files accordingly. The torrent name could also be used to detect how many series of a show came in a torrent in order to process accordingly.

This would be a good change to implement, especially for users that use the 'All episodes' feature when adding shows, as it would lead to faster downloads with less wasted bandwith for users on metered connnections

**Comment by markus101** [comment] 2020-06-28 00:57
Dupe of https://github.com/Sonarr/Sonarr/issues/3826

Sonarr doesn’t support multi-season downloads, there are no plans to though there is a fix linked to that issue.

**Closed by markus101** 2020-06-28 00:57 UTC
