### ISSUE TITLE
Subtitles with country attribute are incorrectly renamed, language is lost.

### ISSUE THREAD

**Issue by wsegatto** [Sonarr/Sonarr#4556] opened 2021-06-26 21:19 UTC
Hi,

I would like to bring out the issue raised in 2018 [here](https://github.com/Sonarr/Sonarr/issues/2639) because that is still a problem for me.

Quote:

> For subtitles that contain the country attribute like pt-BR (Portuguese Brazilian) it is being removed when the Sonarr renames the file.
> 
> Before:
> 
> The.Walking.Dead.S01E01.XXXXXXXX.mkv
> The.Walking.Dead.S01E01.XXXXXXXX.pt-BR.srt
> After:
> 
> The.Walking.Dead.S01E01.mkv
> The.Walking.Dead.S01E01.srt
> It should be renamed to The.Walking.Dead.S01E01.pt-BR.srt
> For cases that don't contain the country attribute, it works fine.

That is still the case. The one that sets our subtitles to "pt-BR" is Bazarr, so it makes sense that Sonarr should maintain - and not lose - this critical information, specially when maintaining multiple language subtitles. I don't understand why Sonarr would care about the _language of the subtitle_ at all, it's not a Subtitle Provided or anything. It should take it as an extra file and just keep it. In case of renaming, well, it should parse it, of course, but bearing in mind that after that last hyphen a language/country code is to be kept.

I would like to hear your comments. I'm sure I'm not the only one with this issue.

**Comment by markus101** [comment] 2021-06-26 21:21
Dupe of https://github.com/Sonarr/Sonarr/issues/2570

**Closed by markus101** 2021-06-26 21:21 UTC
