### ISSUE TITLE
Only keep last XX episodes aired and/or only keep episodes aired in the last XX days/months?

### ISSUE THREAD

**Issue by c010rb1indusa** [Sonarr/Sonarr#1064] opened 2016-01-15 20:51 UTC
IMO this is a big missing feature from Sonarr that even cable company DVRs have.

This feature would be perfect for 'daily episode' shows as it would keep the last 5 episode or last weeks or months worth etc etc. Having to do delete files manually isn't ideal.

This feature would also be great a great way to catalogue and download recently aired television you might have not been interested in, without the shows taking up precious storage space. If someone is interested in something that's aired in the last month, it could be there automatically...

The uses for this simple feature are great and numerous!

**Comment by markus101** [comment] 2016-01-15 20:53
Dupe of https://github.com/Sonarr/Sonarr/issues/314

**Closed by markus101** 2016-01-15 20:53 UTC
