### ISSUE TITLE
Add ability uncheck problem episodes to the Manual Import dialog

### ISSUE THREAD

**Issue by gimpyestrada** [Sonarr/Sonarr#3794] opened 2020-06-03 22:29 UTC
**Describe the problem**
When running a manual import from the Wanted tab sometimes I'm importing a hundred or more new episodes and sprinkled throughout are various ones that have problems (i.e. the little red exclamation mark icon).  It is a pain to have to manually go through and de-select all of them.

**Describe any solutions you think might work**
A few options that I can see:
1. add a box that functions as "only select upgrades"
2. add a box that functions as "only deselect problems"
3. allow the list to be sorted by column and then a shift-click on a range of red ones would also accomplish it, though less elegantly

I'm currently running V3 fwiw.

**Comment by markus101** [comment] 2020-06-04 18:23
Dupe of https://github.com/Sonarr/Sonarr/issues/1127

**Closed by markus101** 2020-06-04 18:23 UTC
