### ISSUE TITLE
Import to the episode where download is initiated

### ISSUE THREAD

**Issue by dotjaz** [Sonarr/Sonarr#5364] opened 2023-01-12 07:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually download an episode where Sonarr failed to identify the series, Sonarr will decided to import it back to the wrong season.

For example I downloaded "Bofuri S02 - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]" from S02E01 search, Sonarr later decided to import it as S01E01 deleting the correct file in the process. despite the title being clearly "S02" and the download initiated from S02E01 search. 

### Expected Behavior

If I started a download from S02E01, Sonarr should remember and import to S02E01 instead of trying to parse later.

### Environment

```markdown
- OS: Synology DSM 7.1
- Sonarr:3.0.9.1549-ls172 by linuxserver.io
- Docker Install: Synology 20.10.3-1308
- Using Reverse Proxy: Yes
- Browser:Firefox
```

### What branch are you running?

Main

### Trace Logs?

2023-01-12 18:16:05.1|Info|ReleaseSearchService|Searching indexers for [BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense. : S02E01 (01)]. 13 active indexers
2023-01-12 18:16:09.1|Info|RssSyncService|Starting RSS Sync
2023-01-12 18:16:12.7|Warn|Torznab|Indexer The Pirate Bay (Prowlarr) rss sync didn't cover the period between 1/12/2023 6:20:12 AM and 1/12/2023 7:07:00 AM UTC. Search may be required.
2023-01-12 18:16:40.7|Info|DownloadDecisionMaker|Processing 612 releases
2023-01-12 18:16:49.4|Info|RssSyncService|RSS Sync Completed. Reports found: 612, Reports grabbed: 0
2023-01-12 18:17:06.0|Info|DownloadDecisionMaker|Processing 101 releases
2023-01-12 18:22:13.8|Info|DownloadService|Report sent to qBittorrent. [Lilith-Raws] æ€•ç—›çš„æˆ‘ï¼ŒæŠŠé˜²ç¦¦åŠ›é»žæ»¿å°±å°äº† / Bofuri S02 - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
2023-01-12 18:24:00.6|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /downloads/anime/ç—›ã„ã®ã¯å«Œãªã®ã§é˜²å¾¡åŠ›ã«æ¥µæŒ¯ã‚Šã—ãŸã„ã¨æ€ã„ã¾ã™/Season 01/BOFURI - I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense. - S01E01 - Defense and First Battle.mkv
2023-01-12 18:24:06.6|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /downloads/anime/ç—›ã„ã®ã¯å«Œãªã®ã§é˜²å¾¡åŠ›ã«æ¥µæŒ¯ã‚Šã—ãŸã„ã¨æ€ã„ã¾ã™/Season 01/BOFURI - I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense. - S01E01 - Defense and First Battle.chi.ass
2023-01-12 18:29:01.6|Info|SceneMappingService|Updating Scene mappings
2023-01-12 18:29:07.0|Info|RefreshSeriesService|Updating BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense.
2023-01-12 18:29:07.9|Info|RefreshEpisodeService|Starting episode info refresh for: [373679][BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense.]
2023-01-12 18:29:08.0|Info|RefreshEpisodeService|Finished episode refresh for series: [373679][BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense.].
2023-01-12 18:29:08.7|Info|DiskScanService|Scanning BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense.
2023-01-12 18:29:08.7|Info|DiskScanService|Completed scanning disk for BOFURI: I Donâ€™t Want to Get Hurt, so Iâ€™ll Max Out My Defense.

**Comment by markus101** [comment] 2023-01-12 07:58
Dupe of https://github.com/Sonarr/Sonarr/issues/5073

**Closed by markus101** 2023-01-12 07:58 UTC
Labels: needs-triage
