### ISSUE TITLE
Group notifications (Pushbullet)

### ISSUE THREAD

**Issue by domgregori** [Sonarr/Sonarr#2042] opened 2017-07-11 22:07 UTC
When adding a new series and all the episodes are found at once you are bombarded with notifications. Would be a great option to group notifications into one, either by time or by series.

**Comment by markus101** [comment] 2017-07-11 22:08
Dupe of https://github.com/Sonarr/Sonarr/issues/1396

**Closed by markus101** 2017-07-11 22:08 UTC
