### ISSUE TITLE
Feature request: notifications for system status

### ISSUE THREAD

**Issue by MaartenMol96** [Sonarr/Sonarr#2174] opened 2017-09-15 05:38 UTC
In the system page there is showed if an indexer is not available or any other problems. I really like to see if we can also get these by notification from the connect settings. Like telegram! 

Is this possible?

**Comment by Renegade605** [comment] 2017-09-16 00:04
+1. If there's an issue with the configuration it would be great to know right away instead of after a couple days of no downloads.

**Comment by markus101** [comment] 2017-09-16 19:43
Dupe of https://github.com/Sonarr/Sonarr/issues/1798

**Closed by markus101** 2017-09-16 19:43 UTC
