### ISSUE TITLE
Change episode ordering

### ISSUE THREAD

**Issue by ticky13** [Sonarr/Sonarr#3937] opened 2020-09-05 11:20 UTC
Is there any way to have an option in Sonarr use the DVD or absolute ordering info from TVDB for specific seasons like Plex does? There are numerous TV shows that were aired in the incorrect order but released in the correct order on DVD.

**Comment by markus101** [comment] 2020-09-05 15:32
Please search before opening new issues this is a dupe of https://github.com/Sonarr/Sonarr/issues/255

**Closed by markus101** 2020-09-05 15:32 UTC

**Comment by ticky13** [comment] 2020-09-05 18:54
A dupe that is closed to commenting, so how exactly am I supposed to comment on it?

**Comment by Thirrian** [comment] 2020-09-06 05:40
You give a thumbs up to the original request to show that you'd like it fixed too, because everyone was making "hurrr I have this issue too" comments which don't add any value so the sonarr devs had to lock it.
That's generally the reason any old open items are locked for commenting...

I don't mean you were going to do just that, mind you.

**Comment by atg22896** [comment] 2020-12-01 05:02
> You give a thumbs up to the original request to show that you'd like it fixed too, because everyone was making "hurrr I have this issue too" comments which don't add any value so the sonarr devs had to lock it.
> That's generally the reason any old open items are locked for commenting...
> 
> I don't mean you were going to do just that, mind you.

You can't thumbs up a locked post. And it's telling that it is a 6 year old request, that the Devs have yet to respond to it and give any insight. Medusa has this feature and has been in existence for a long time.

**Comment by bakerboy448** [comment] 2020-12-01 05:13
the devs have responded to it there via the labels
![image](https://user-images.githubusercontent.com/55419169/100699868-b36c5e00-3361-11eb-8ab6-6426b1bbb390.png)

similarly the various dupes have been responded to

comments like yours are why threads get locked

they are mare noise.

**Comment by atg22896** [comment] 2020-12-01 05:26
> the devs have responded to it there via the labels
> ![image](https://user-images.githubusercontent.com/55419169/100699868-b36c5e00-3361-11eb-8ab6-6426b1bbb390.png)
> 
> similarly the various dupes have been responded to
> 
> comments like yours are why threads get locked
> 
> they are mare noise.

Enhancement was added in 2015. 
![chrome_2020-12-01_00-15-37](https://user-images.githubusercontent.com/33287665/100700092-a9029200-336a-11eb-883a-b0c8b7d4712b.png)
Blocked by skyhook in 2017
![chrome_2020-12-01_00-15-27](https://user-images.githubusercontent.com/33287665/100700116-b455bd80-336a-11eb-9acf-9517be209dac.png)
Last "response" was in April
![chrome_2020-12-01_00-16-06](https://user-images.githubusercontent.com/33287665/100700136-c3d50680-336a-11eb-86aa-99673dcdb1ae.png)
There has yet to be a response anywhere from someone like @markus101 about either why this cannot be implemented, or why it has been decided to not be implemented. The API from TVDB does return DVD order, and has for a long time. The least they can do is give a legitimate response about this - it makes the tool completely useless for multiple shows.
