### ISSUE TITLE
Remove and Blacklist torrent download after X time in any status 

### ISSUE THREAD

**Issue by LostPoE** [Sonarr/Sonarr#3528] opened 2020-01-19 16:29 UTC
Remove and Blacklist torrent download after X time in any status. I generally will see a bunch of torrents trying to download for days but nothing downloads. Need the ability to auto-delete and blacklist them no matter what state after X time.

Thanks!

**Comment by markus101** [comment] 2020-01-19 16:54
Dupe of https://github.com/Sonarr/Sonarr/issues/958

**Closed by markus101** 2020-01-19 16:54 UTC
