### ISSUE TITLE
Wanted - Manual Import > Unexpected renaming 

### ISSUE THREAD

**Issue by thisis-mental** [Sonarr/Sonarr#4129] opened 2020-11-28 18:01 UTC
### System Information/Logs

**Sonarr Version:** 3.0.4.1021

**Operating System:** Linux

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.20.1.34

**Link to Log Files (debug or trace):**

Hello there
Just noticied an issue today while trying to use the Manual Importer inside Wanted.
```EpisodeFileMovingService|Hardlinking episode file: /media/Downloads/tv/Rome.iNTEGRALE.MULTi.1080p.BluRay.x264-AiRTV (aaa) /Rome.S02.MULTi.1080p.BluRay.x264-AiRTV/Rome.S02E10.FiNAL.MULTi.1080p.BluRay.x264-AiRTV/airtv-rome.s02e10.final_1080p.mkv to /media/TV/Rome/Season 02/Rome.S02.MULTi.1080p.BluRay.x264-AiRTV.mkv```

### Additional Information
My rename settings is set to keep the original filename but while using Wanted - Manual Import it tries to rename and put the season folder name as episode name for all of them

**Comment by markus101** [comment] 2020-11-28 19:59
Dupe of https://github.com/Sonarr/Sonarr/issues/3056

**Closed by markus101** 2020-11-28 19:59 UTC
