### ISSUE TITLE
Add custom filters in wanted/missing tab

### ISSUE THREAD

**Issue by HATEME2** [Sonarr/Sonarr#4974] opened 2022-04-07 08:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The wanted/missing tab allows you to filter out by monitored or unmonitored, but all the custom filters don't apply in this section. Searching all seems to miss a huge block of missing episodes because it's on one side of the search that is past api limits or indexer failure. Other times, I think it just times out on really old shows that have have a one in a million chance of ever seeing the light of day. I figured it would eventually be noticed and someone would add it, but now I'm asking, please add this.

### Describe the solution you'd like

Add the ability to create custom filters in wanted/missing section, or sync the already created custom filters in the series section.

### Describe alternatives you've considered

Add a search all function to the series section that only applies to currently filtered series.

### Anything else?

not much else to say

**Comment by bakerboy448** [comment] 2022-04-07 13:14
Duplicate of #3657

**Closed** 2022-04-07 13:14 UTC
