### ISSUE TITLE
The TVDB API Issues (Deleted shows and wrong posters)

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3415] opened 2019-11-20 21:16 UTC
Sonarr is showing the following error for shows apparently deleted from TVDB - when they still exist on TVDB

![image](https://user-images.githubusercontent.com/27241813/69278705-93726c80-0c2e-11ea-880f-f9cc232babd5.png)

![image](https://user-images.githubusercontent.com/27241813/69278729-a08f5b80-0c2e-11ea-982a-ab00100fd5ca.png)

SONARR VERSION:
![image](https://user-images.githubusercontent.com/27241813/69278809-c3217480-0c2e-11ea-9508-139c2201f004.png)

**Comment by markus101** [comment] 2019-11-20 21:21
Their API is returning invalid data (similar to it being deleted), it's going to continue to happen until they fix all the API issues they introduced over the last week.

**Comment by antigravity83** [comment] 2019-11-20 23:03
Thanks @markus101 - so best to ignore these warnings for now and Sonarr will still pick up new content for these shows?

**Comment by markus101** [comment] 2019-11-21 03:38
Likely it'll be fine by the next refresh.

**Comment by mirolm** [comment] 2019-11-25 08:32
Another one that showed today for me.

Series Cautious Hero: The Hero Is Overpowered but Overly Cautious (tvdbid 369048) was removed from TheTVDB

Version 3.0.3.658
Package Version 3.0.3.658
Mono Version 6.4.0.198

I checked that "Shinchou Yuusha" is not deleted in TheTVDB and shows in their site.

**Comment by M0UL** [comment] 2019-11-25 10:46
i got a few that says there are deleted when they are not.
![image](https://user-images.githubusercontent.com/5436726/69533931-1837f000-0f79-11ea-876d-639d6f85a854.png)

**Comment by mirolm** [comment] 2019-11-25 17:24
Cautious Hero got fixed and does not show ad deleted anymore. 

I noticed that season posters does not download anymore. I deleted some of them from shows i follow and they do not get redownloaded after a refresh.

**Comment by Lonli-Lokli** [comment] 2019-11-25 20:25
Is is related that search by tvdbid is broken?
I was trying to add new show with search tvdb:359111 but it fails
But show exists- https://www.thetvdb.com/series/httpswwwthemoviedborgtv82701season1languageru-ru

**Comment by markus101** [comment] 2019-11-25 20:53
No, it needs an English translation, this is in the FAQ.

**Comment by BRTPOB** [comment] 2019-12-03 11:11
This just happened for me with American Horror Story. I went and deleted the series then attempted to re-add it using the TVDB ID and it failed. Any idea if/when this will get fixed on their end?

**Comment by Dnkhatri** [comment] 2019-12-03 16:46
> This just happened for me with American Horror Story. I went and deleted the series then attempted to re-add it using the TVDB ID and it failed. Any idea if/when this will get fixed on their end?

should not have deleted it. As it automatically clears up after a while. Tvdb have a lot of bugs because of the new website and api update probably could take weeks for all the bugs to be ironed out.

**Comment by GlennMillerNZ** [comment] 2020-01-10 08:10
Tried searching for 'Diesel Brothers' today and couldn't be found using the title or tvdb id.
Out of interest tried requesting the show in Ombi, which was able to find the series, but upon requesting the show it failed.
Tried updating my container to the latest version also as per screen.

<img width="326" alt="Screen Shot 2020-01-10 at 9 05 47 PM" src="https://user-images.githubusercontent.com/47721519/72136308-62701600-33ed-11ea-815b-6545010616ec.png">
<img width="1245" alt="Screen Shot 2020-01-10 at 9 06 58 PM" src="https://user-images.githubusercontent.com/47721519/72136312-6734ca00-33ed-11ea-8cab-560fb15d0429.png">
<img width="944" alt="Screen Shot 2020-01-10 at 9 07 24 PM" src="https://user-images.githubusercontent.com/47721519/72136317-6b60e780-33ed-11ea-9034-5b244771ccba.png">

**Comment by Reconos87** [comment] 2020-01-10 08:31
So was this issue never resolved? :( Just woke up to this:
![image](https://user-images.githubusercontent.com/20089266/72137873-e98ca200-338b-11ea-8cd0-ef6aa7404da9.png)

What can i do to fix this?

**Comment by guzmi89** [comment] 2020-01-10 09:43
the same happens to me, I don't know how to fix it

**Comment by bkonings** [comment] 2020-01-10 11:16
Same issue, maybe this is the cause?

https://forums.thetvdb.com/viewtopic.php?f=3&t=61687

**Comment by 1aTa** [comment] 2020-01-10 17:04
Same happened to me last night.

**Comment by t3knical** [comment] 2020-01-10 19:26
TheTVDB API Updated they removed legacy SSL support <- most likely the issue and will require sonarr dev team to implement updates on the way they call to the API, lets all be patient, cause i can tell you this, a project the size of Sonarr and TheTVDB are no small project and require a lot of time and effort to keeps thing in tip top shape, so lets just all relax and stop blowing up the sonarr's github issue section, time will fix this issue weather it's TVDB's fault or changes sonarr has to implement themselves. Once again Sonarr dev team is aware of the issue, so lets just be patient, also don't remove your shows, once the issue is fixed the error will clear out by itself.

**Comment by gnoling** [comment] 2020-01-10 19:41
> TheTVDB API Updated they removed legacy SSL support <- most likely the issue and will require sonarr dev team to implement updates on the way they call to the API, lets all be patient, cause i can tell you this, a project the size of Sonarr and TheTVDB are no small project and require a lot of time and effort to keeps thing in tip top shape, so lets just all relax and stop blowing up the sonarr's github issue section, time will fix this issue weather it's TVDB's fault or changes sonarr has to implement themselves. Once again Sonarr dev team is aware of the issue, so lets just be patient, also don't remove your shows, once the issue is fixed the error will clear out by itself.

If you go over TheTVDB's forums (their developer forum in particular) you'll find this isn't the case, their API is currently broke-broken for everyone returning either no _or_ "bad" results. I do see other places where people are pointing at the SSL announcement just because that announcement was made (which to anyone reading it, say's they're removing it _soon_), which had really unfortunate timing on their end. I do wish people would verify that sort of issue (it's enough enough to check SSL protocol support) before saying "this is it!"

**Comment by t3knical** [comment] 2020-01-10 20:09
I did say it was most likely the issue not that it was the issue cause i did go on to say "time will fix this issue weather it's TVDB's fault or changes sonarr has to implement themselves"

**Comment by thezoggy** [comment] 2020-01-10 23:14
>  Well when i run the API for quite a few shows, they return empty (not using skyhook). This has already be done numerous times by numerous developers and is a known issue with tvdb. 

sonarr devs just need to handle this shit scenario to handle it more gracefully. tvdb's api has been beyond buggy for the last few months and seems to be getting worse as they try to bandaid patch stuff :(

**Comment by Lonli-Lokli** [comment] 2020-01-11 08:37
Well, in normal world API V3 release does not mean that API V2 should be removed. Do their team still support it?

**Comment by t3knical** [comment] 2020-01-11 09:23
well all in all, everything is back to normal all series again now find-able.

**Comment by Routhinator** [comment] 2020-01-21 02:19
Is there any way to tell Sonarr to prefer results from Trakt or something else instead? Doesn't seem like this is going to be fixed at any time in the near future.

**Comment by Dnkhatri** [comment] 2020-01-21 07:20
> Is there any way to tell Sonarr to prefer results from Trakt or something else instead? Doesn't seem like this is going to be fixed at any time in the near future.
> 
> Things come back but not fully. I have shows that come back with only the second season even though both season 1 and 2 are on TVDB.. There are other metadata sites out there..
> 
> Example show with broken season return: tvdb:350126

Even trakt gets its info from tvdb so you can't even add a show in trakt if it doesn't exist in tvdb. We have 2 options wait for tvdb apis to get stable or build your own tv show database. Tvdb still is the largest database and most of the other websites don't even come close.

**Comment by Routhinator** [comment] 2020-01-21 15:46
Thanks for clarifying.

**Comment by Lonli-Lokli** [comment] 2020-02-25 08:09
Can smbd clarify - I have a Goof Troop tv show and it's listed in Sonarr with s01e01, while on thetvdb it's listed ad s01e28
https://www.thetvdb.com/series/goof-troop/episodes/276343

Why does it happens?

**Comment by Lonli-Lokli** [comment] 2020-02-25 19:41
Ok I understand. Thetvdb updates their naming scheme for this tv show. So now I've refreshed metadata for Goofy and have an issue - old imported s01e01 Will become new episode, as I see in details.

What are the possible options for such cases?

**Comment by bt61** [comment] 2020-06-09 13:00
No fix for this?  Yet no one has been asking for a few months?  I'm confused.  All series already in Sonarr are working fine, but I can't add a new series, I get **"There Was An Error Searching For '**show-name**'.**
In the logs:    

> Error: ConnectFailure (Connection refused): 'http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=**show-name**': Error: ConnectFailure (Connection refused): 'http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=**show-name**'

**Comment by Taloth** [comment] 2020-06-09 13:03
This is actually an old resolved tvdb issue.

search for shows work fine here. If you have trouble, post on discord or our forums with the show title and someone will check if it's just you, just that show or something generic.

**Closed by Taloth** 2020-06-09 13:03 UTC
Labels: skyhook/services

**Comment by mboerma** [comment] 2020-06-09 13:13
Not resolved for shows which some would call “foreign”. Many still do not show up while being available, including the number, on TVDB.

**Comment by Taloth** [comment] 2020-06-09 13:15
Sonarr never supported non-english shows. This issue was about tvdb api being borked during the v3 site update and reporting shows as deleted randomly.

**Comment by bt61** [comment] 2020-06-09 13:16
> Not resolved for shows which some would call “foreign”. Many still do not show up while being available, including the number, on TVDB.

Thanks, but I can't get ANY show to be found. I started trying the most common shows in the world, nothing. Using 'dvdb:######' fails the same way too.

**Comment by mboerma** [comment] 2020-06-09 13:19
That could be a firewall issue or something like Pi-hole blocking traffic. For me it works for most shows. Just doesn’t for some.

**Comment by mboerma** [comment] 2020-06-09 13:22
> Sonarr never supported non-english shows (shows without english metadata). This issue was about tvdb api being borked during the v3 site update and reporting shows as deleted randomly.

It does work for many non-English shows. If this was by design this “feature” should be on the top of the new features list! Why limit Sonarr to English series??

**Comment by bt61** [comment] 2020-06-09 13:25
> That could be a firewall issue or something like Pi-hole blocking traffic. For me it works for most shows. Just doesn’t for some.

I thought it might be that as well, but no pi-hole, and pretty 'vanilla' router, (dietpi) server, and sonarr setup. I suspected my ISP might be doing some weird blocking, but even with connecting my router to PIA VPN I get the same results.

**Comment by mboerma** [comment] 2020-06-09 13:28
So even if you post that skyhook link in a browser it fails to get results?

**Comment by bt61** [comment] 2020-06-09 13:41
> So even if you post that skyhook link in a browser it fails to get results?

Hmm, good question, it does seem to open fine in a browser on my computer or phone on the same network (just a long all text page with relevant show info, so I assume that’s right).

Any idea what to check next?

**Comment by mboerma** [comment] 2020-06-09 13:52
The long text is the, I believe, JSON response which should be picked up by Sonarr. 

I would have a clue where to look next. Maybe follow the advise of the other person responding and post on the Sonarr forum or their Discord channel.

**Comment by bt61** [comment] 2020-06-09 13:55
@mboerma thanks, I’ll try taking it over to Discord

**Comment by thezoggy** [comment] 2020-06-09 22:32
have you tried turning your computer off then back on?
