### ISSUE TITLE
Grab smallest file size over larger ones

### ISSUE THREAD

**Issue by localgamerz** [Sonarr/Sonarr#3741] opened 2020-05-10 18:14 UTC
Hello, I am trying to get Sonarr to grab the smallest file size possible, I don't much care for the quality of the show at all. Would it be possible to add in the ability to get the smallest shows possible, or add a transcoder into sonarr that can convert the file size lower? also, the smallest limit you can set on Sonarr V3 is 600mb per hour, could we have the option to set that even lower?

**Comment by markus101** [comment] 2020-05-10 18:17
Dupe of https://github.com/Sonarr/Sonarr/issues/724

> or add a transcoder into sonarr that can convert the file size lower?

There are other apps that do this, Sonarr isn't going to do this for you.

> the smallest limit you can set on Sonarr V3 is 600mb per hour, could we have the option to set that even lower?

No, it's 60MB per hour.

**Closed by markus101** 2020-05-10 18:17 UTC
