### ISSUE TITLE
Manual Search for Seasons

### ISSUE THREAD

**Issue by bippum** [Sonarr/Sonarr#2655] opened 2018-07-10 01:09 UTC
I'd like to be able to manually search for a season pack for shows. A solution I can think of for this would be simply adding a manual search button next to the automatic search button on the season:

![click](https://o.lol-sa.me/ac94a2.png)

I know that the automatic search for a whole show does search for season packs, so I'd assume (very carefully) that it would be somewhat trivial. Knowing software dev though, it probably isn't.

**Comment by markus101** [comment] 2018-07-10 02:45
Dupe of https://github.com/Sonarr/Sonarr/issues/266 with almost the same title...

**Closed by markus101** 2018-07-10 02:45 UTC
