### ISSUE TITLE
Override and grab release doesn't actually work (?)

### ISSUE THREAD

**Issue by nirurin** [Sonarr/Sonarr#6303] opened 2024-01-04 19:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If you select override and grab release, and then set the corrected season number and episode name (because the listed one on the search is incorrect for whatever reason) it adds the file to the download queue... but it uses the OLD season and episode numbers, and not the new ones that were set in the override window. When the file finishes downloading it gets removed from the download queue, but just sits in the 'completed' folder and never gets added to any season folders (incorrect or correct)

### Expected Behavior

The override values for season/episode should be the ones used in the download window, and the file should automatically be renamed and added to the correct season/episode folder locations. 

### Environment

```markdown
- OS: Docker
- Sonarr: 4.0.0.748
- Docker Install: linuxserver.io
- Using Reverse Proxy: yes (irrelevant)
- Browser: Edge (irrelevant)
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/13834414/sonarr.trace.0.txt)
[sonarr.trace.1.txt](https://github.com/Sonarr/Sonarr/files/13834415/sonarr.trace.1.txt)
[sonarr.trace.2.txt](https://github.com/Sonarr/Sonarr/files/13834416/sonarr.trace.2.txt)
[sonarr.trace.3.txt](https://github.com/Sonarr/Sonarr/files/13834417/sonarr.trace.3.txt)
[sonarr.trace.4.txt](https://github.com/Sonarr/Sonarr/files/13834418/sonarr.trace.4.txt)

### Anything else?

![Screenshot 2024-01-04 185632](https://github.com/Sonarr/Sonarr/assets/3751273/b345cd55-dba6-48b4-85f3-1f2f82ce4c90)
![Screenshot 2024-01-04 185939](https://github.com/Sonarr/Sonarr/assets/3751273/8bb00bbd-5428-4479-8964-7cb1a4b70741)

**Comment by markus101** [comment] 2024-01-04 19:17
This is a duplicate of #6147.

**Closed by markus101** 2024-01-04 19:17 UTC
Labels: needs-triage
