### ISSUE TITLE
Sorting not workingin the activity section

### ISSUE THREAD

**Issue by Phil57** [Sonarr/Sonarr#5553] opened 2023-04-13 18:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to sort by any field in the activity section it doesn't work.
Tried on Windows, Android, IOS with Chrome, Firefox and Edge.

(Works fine on radar)

Similar to https://github.com/Sonarr/Sonarr/issues/5184

### Expected Behavior

Line to be sorted

### Steps To Reproduce

Try to sort on activity tab

### Environment

```markdown
- OS: Docker
- Sonarr: 3.0.10.1567-ls186 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes, Cloudflare and Nginx (but tested directly without them)
- Browser: Chrome, FF, Edge
```

### What branch are you running?

Main

### Trace Logs?

```
2023-04-13 20:12:22.3|Trace|Http|Req: 825 [GET] /api/v3/queue?page=1&pageSize=20&sortDirection=descending&sortKey=series.sortTitle&includeUnknownSeriesItems=true (from 162.*.*.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36)
2023-04-13 20:12:22.3|Trace|Http|Res: 825 [GET] /api/v3/queue?page=1&pageSize=20&sortDirection=descending&sortKey=series.sortTitle&includeUnknownSeriesItems=true: 200.OK (3 ms)
2023-04-13 20:12:22.3|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=descending&sortKey=series.sortTitle&includeUnknownSeriesItems=true: 200.OK (3 ms)
```

**Comment by markus101** [comment] 2023-04-13 18:25
Screenshots comparing what the UI shows as well as what the logs and response (from dev tools) are necessary in this case.

**Comment by Phil57** [comment] 2023-04-13 18:39
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/10242493/231852829-d4e63e54-5921-444d-a948-87ed984e1e88.png">

https://gist.github.com/Phil57/a1dd8b244fc2d2dec5575b0284b54968

Seems that the response from the API is correcly ordered, but the display doesn't refresh as such

**Comment by markus101** [comment] 2023-04-13 20:36
I see the same thing with everything working correctly, it's expected. Changing the queue size changes the items in the queue so it needs to fetch the matching episodes. Just changing the sort order doesn't change the items in the queue (when smaller than the page size) so it doesn't refetch the episodes, sorting when the total size is larger than the page size will almost certainly result in the items changing and the episodes being refetched.

**Comment by markus101** [comment] 2023-04-14 00:16
I've dug into this a bit more and found that I can reproduce it in v3, but not in v4. While there isn't a fix for this directly this was fixed with https://github.com/Sonarr/Sonarr/commit/51b1ba13c1b9dc9e26469c728e3871d4b7da0788 which landed after v3 development stopped.

As mentioned before the page size being less than the number of items in the queue works because the episodes also change, which causes a slightly different update. This won't be fixed in v3, but is fixed in the v4 beta and eventual v4 release.

**Closed by markus101** 2023-04-14 00:16 UTC
Labels: waiting-for-info, needs-triage

**Comment by Phil57** [comment] 2023-04-14 03:54
Thanks 👏
