### ISSUE TITLE
Renaming files doesn't affect external subtitles

### ISSUE THREAD

**Issue by feld** [Sonarr/Sonarr#1727] opened 2017-03-02 16:47 UTC
I'm not sure if this is Sonarr's responsibility, but it would be nice if it recognized external subtitles.

I recently had a show which needed renaming because some files were outside of the Season folders. Renaming worked great, but the external subtitles were left behind. Recognizing the subtitles and renaming and moving as appropriate would be greatly appreciated!

**Comment by markus101** [comment] 2017-03-02 16:48
Dupe of https://github.com/Sonarr/Sonarr/issues/459

**Closed by markus101** 2017-03-02 16:48 UTC
