### ISSUE TITLE
convert to netcore

### ISSUE THREAD

**Issue by robertbaker** [Sonarr/Sonarr#2774] opened 2018-10-18 04:25 UTC
Is your feature request related to a problem? Please describe.
Mono is dead, long live .netcore.

Describe the solution you'd like
.netstandard makes it possible to target multiple platforms while sharing as much as you can.
.netcore is faster than mono, so many other benefits, do I need to explain!?

I have experience converting fullframework to netstandard/netcore. The conversion to netstandard / new csjproj format is digestible and easier than people think (to me at this point anyway).
Describe alternatives you've considered?
None

Additional context
It's a good resume booster too :).

**Comment by markus101** [comment] 2018-10-18 11:06
Dupe of https://github.com/Sonarr/Sonarr/issues/948

**Closed by markus101** 2018-10-18 11:06 UTC

**Comment by Taloth** [comment] 2018-10-18 21:57
FYI, there are a couple of reasons why we're not doing netcore yet. Dependencies is one thing, platform support another (good luck running it on synology or qnap).   
It's possible to move some things to netstandard, but if you do that you're better off splitting Sonarr into more modules, like indexers, download clients etc, anything less would be wasted effort. If you want to 'do it right' you have to sink in more time without immediate return.   

Our main focus is to increase the maturity of v3. Which doesn't include something as fundamental as netcore. Hence the v4 milestone in the linked issue.

**Comment by robertbaker** [comment] 2018-10-19 00:00
makes sense, thanks for the reply.

**Comment by xaviergxf** [comment] 2020-06-02 15:26
Hi @Taloth, it seems this is no longer valid... Do you have plans to migrate to .net core? How can the community help?
