### ISSUE TITLE
Directory-name parsing from Vuze still not working correctly

### ISSUE THREAD

**Issue by andbir** [Sonarr/Sonarr#2761] opened 2018-10-04 19:08 UTC
Sonarr 2.0.0.5228 will still not get directory names correctly from Vuze, erronously adding the torrent name at the end of the download directory and throwing Import failed, path does not exist or is not accessible by Sonarr

Example: Sonarr tries to access
Z:\TVshows\The.Strain.S01E07.For.Services.Rendered.1080p.WEB-DL.DD5.1.H.264-CtrlHD[rarbg]\The.Strain.S01E07.For.Services.Rendered.1080p.WEB-DL.DD5.1.H.264-CtrlHD[rartv]\ but this directory does not exist; the correct path is Z:\TVshows\The.Strain.S01E07.For.Services.Rendered.1080p.WEB-DL.DD5.1.H.264-CtrlHD[rarbg]\ in which multiple files reside, one of which is the correct episode file.

**Comment by markus101** [comment] 2018-10-04 19:10
Dupe of https://github.com/Sonarr/Sonarr/issues/2571 we need to get a new release out for it.

**Closed by markus101** 2018-10-04 19:10 UTC
