### ISSUE TITLE
Handle "X (Season Y) - ZZ" release naming format

### ISSUE THREAD

**Issue by rcombs** [Sonarr/Sonarr#4377] opened 2021-03-13 18:30 UTC
**Is your feature request related to a problem? Please describe.**
`[DameDesuYo] ReZero kara Hajimeru Isekai Seikatsu (Season 2) - 33 (1280x720 10bit EAC3) [42A12A76].mkv` currently isn't recognized, as Xem doesn't have an alias for "ReZero kara Hajimeru Isekai Seikatsu (Season 2)".

**Describe the solution you'd like**
Xem should be able to recognize that "ReZero kara Hajimeru Isekai Seikatsu (Season 2)" refers to season 2 of the show with alias "ReZero kara Hajimeru Isekai Seikatsu".

**Describe alternatives you've considered**
I've submitted a draft to add a suitable alias to Xem, but it's not guaranteed that one will always be there, and in this case one actually did previously exist and was _removed_ by a different editor, so it probably shouldn't be relied on.

**Additional context**
<img width="670" alt="image" src="https://user-images.githubusercontent.com/819638/111040290-efe73580-83f7-11eb-8f42-23e7150f5610.png">

**Comment by bakerboy448** [comment] 2021-03-13 18:36
Sonarr doesn’t control the content of XEM, so asking sonarr to control the context of XEM doesn’t make sense; closing

**Closed by bakerboy448** 2021-03-13 18:36 UTC

**Comment by rcombs** [comment] 2021-03-13 18:41
Sorry, I typoed that; I meant that _Sonarr_ should be able to handle this format without requiring Xem to.

**Comment by markus101** [comment] 2021-03-13 19:10
The issue is if Sonarr used `ReZero kara Hajimeru Isekai Seikatsu` as the alias from TheXEM.de and parsed (season 2) separately it’d be used to find the 33rd episode in season 2, which doesn’t exist, since Sonarr has no way to know that in this particular case season 2 is meaningless information, but in another series it could be.

If TheXEM adds an alias for this series it’d be at the series level, so even thing in season 1 would be searched with it, which will likely yield no results.

In this case Sonarr needs TheXEM to have the alias to make sense of the awkward release name.

**Comment by rcombs** [comment] 2021-03-13 19:15
There was previously an alias for this linked to season 2, and that worked for previous episodes (33 is an absolute index, and both Xem and TVDB have the absolute numbers for this series).
