### ISSUE TITLE
Prefer Torrent not working

### ISSUE THREAD

**Issue by MrRobot12** [Sonarr/Sonarr#1876] opened 2017-04-28 13:03 UTC
I have Prefer Torrent selected, but when doing an automatic search for missing episodes in a series it usually downloads from usenet even when a torrent is available and seeded.

Is this a bug?

I only have 30 days retention on my usenet provider, so this is causing all kinds of issues with older files.

**Comment by Taloth** [comment] 2017-04-28 13:14
Quality still wins over the preferred protocol. Do a manual search for the episode, and see the prioritization that Sonarr applies.

You should set the Retention limit in Settings->Indexers.

**Comment by MrRobot12** [comment] 2017-04-28 13:15
They are the exact same file.

**Comment by Taloth** [comment] 2017-04-29 14:35
But did you do a manual search to check? Make a screenshot of the results. Take particular note of the red exclamation icons on the right side of each row. It contains the rejection reasons for individual releases.

**Comment by MrRobot12** [comment] 2017-04-29 16:28
Quality is set to 1080p web-dl, and custom tags of webrip and ntb were added. As you can see from image 1, it is showing matching releases available on both torrent and usenet, but downloads from usenet (image 2).

I think I was able to pinpoint the bug. If you do an automatic search for missing episodes using the magnifying glass in images 3 and 4, it chooses usenet. If you do an automatic search with the magnifying glass next to the episode name (image 5) then it correctly chooses torrent.

I ran this test multiple times, clearing out the history so it was a fresh run every time. Every time it followed the logic stated above.

http://imgbox.com/g/3NBMBQh2Cl

<a href="http://imgbox.com/2yMYKWIa" target="_blank"><img src="https://5-t.imgbox.com/2yMYKWIa.jpg" alt="image host"/></a> <a href="http://imgbox.com/WJrfSWVI" target="_blank"><img src="https://7-t.imgbox.com/WJrfSWVI.jpg" alt="image host"/></a> <a href="http://imgbox.com/mT3StHLa" target="_blank"><img src="https://9-t.imgbox.com/mT3StHLa.jpg" alt="image host"/></a> <a href="http://imgbox.com/blW0XKQc" target="_blank"><img src="https://5-t.imgbox.com/blW0XKQc.jpg" alt="image host"/></a> <a href="http://imgbox.com/gJemVqoS" target="_blank"><img src="https://9-t.imgbox.com/gJemVqoS.jpg" alt="image host"/></a>

**Comment by Taloth** [comment] 2017-04-29 16:55
Could it be that the torrent indexer isn't returning the episode for a Season level search?
You can see the exact query url in Debug level logs. But'll be along the line of `/api?t=tvsearch&cat=...&q=The%20Leftovers&season=3&apikey=...`

**Comment by MrRobot12** [comment] 2017-04-29 17:24
Is this what I'm looking for?

17-4-29 13:16:18.0|Debug|Torznab|Downloading Feed http://(ip address redacted)/torznab/morethantv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Leftovers&season=3

If so it looks like it's searching properly, no?

**Comment by Taloth** [comment] 2017-04-29 17:27
Yes, that's the url, but query the url and see the results. Then do another but append `&ep=1`. Compare the results.
My bet is that Jackett doesn't return the torrent for the season level search.

**Comment by MrRobot12** [comment] 2017-04-29 17:37
When I go to the full url only full seasons of S01 and S02 are available. No individual episodes.

If I add &ep=1 then all S03E01 torrents are showing, including the matching release I'm looking for.

Am I SOL or is there anything I can do to fix this? I think the Jackett project has been abandoned.

**Comment by Taloth** [comment] 2017-04-29 17:58
> Am I SOL or is there anything I can do to fix this?

Report it to Jackett as an issue. Since it's apparent they're not returning the requests results, but in all likeliness is caused by limitations on the MTTV website. (Did I mention how much I hate website scraping? This is why real sites have api's)

> I think the Jackett project has been abandoned.

The last commit was 3 days ago, I don't know where you're getting the impression that it's been abandoned.
I was assuming you were using Jackett but you could've been using Cardigan as well. Either way, this is a problem with the indexer/Jackett, so I'll be closing the issue as this is something that should be addressed by them.

**Closed by Taloth** 2017-04-29 17:58 UTC
