### ISSUE TITLE
Add the Year to upcoming series

### ISSUE THREAD

**Issue by fadiajlil** [Sonarr/Sonarr#6646] opened 2024-03-22 22:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

A way to add the "Year" to upcoming series like "Fallout (2024)" instead of "Fallout(0)" this problem happen because there is no announced year for the series at the time of adding it to the library 
<img width="1917" alt="Screenshot 2024-03-22 221841" src="https://github.com/Sonarr/Sonarr/assets/60059903/ff802a87-6054-4e30-8f23-dcb38b152fb3">

### Describe the solution you'd like

it need to a way to get auto-renamed and add the year when it update on the database of [TVDB]

### Describe alternatives you've considered

the only thing i can do right know is manually renaming this shows with the year when available

**Comment by markus101** [comment] 2024-03-22 22:31
Duplicate of https://github.com/Sonarr/Sonarr/issues/6179

Ultimately this falls under https://github.com/Sonarr/Sonarr/issues/1118

**Closed by markus101** 2024-03-22 22:31 UTC
Labels: needs-triage
