### ISSUE TITLE
Viewing series info does not default to top view.

### ISSUE THREAD

**Issue by bengalih** [Sonarr/Sonarr#2153] opened 2017-08-30 04:03 UTC
When clicking on a series name from the "Series" area the view that is presented is based on where the series was listed - as in how far down the list that particular series is.

For example, if the first series in my list was "Alias" and I clicked on it I would be presented with the Alias info page with the show summary at top.  However, if I needed to scroll down the equivalent of a few screens to look at "Narcos" or all the way down for "The Walking Dead", my view of those series would be somewhere near the middle or the end of the season listings for those shows.  I would have to click on the "Back to the top!" button to go to the very top.

I believe this is a bug and at the very least the series should always pull up with the summary and latest season in focus.  Especially because one is usually concerned about managing the latest episodes and the way it works now the oldest episodes are brought into focus for most shows (those not at the very top of the series list).

Ideally, there would be some smart logic like always bringing into focus the latest season/episode that is being monitored, or the next unaired, etc.

**Comment by markus101** [comment] 2017-09-01 03:35
I cannot reproduce this in Chrome.

Which browser and version of Sonarr do you see this with?
Do you see it in other browsers or incognito/private browsing (to disable extensions)?

**Comment by bengalih** [comment] 2017-09-01 17:54
I am seeing this with Chrome on two different systems.
One is Win 7x64 and the other Win 10x64
Both are running:
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

This happens in incognito/private mode as well.

The issue does not happen on IE or Edge.

Alas, I prefer to use Chrome so it is an issue.

Let me know what else you might need info-wise or want me to try.

**Comment by thezoggy** [comment] 2017-09-01 22:52
can you post screen shot.. would help to know if the url being augmented / proxy  / etc

**Comment by bengalih** [comment] 2017-09-02 02:34
Attached are two pictures.
One is my series list, where you can see "Preacher" falls a little more than half way down (not scroll bar on right).  The second is when I go into the Preacher series.  You can see it is scrolled down in the season list instead of being up on the season summary.  How far down this is scrolled depends on a) how far down I had to scroll on the main screen to reach that season and b) how many seasons are in the show title.

I have done this on two different systems with all my extensions disabled.  I have ESET A/V and Malwarebytes running and both systems are clean.

You can also see the particular system these shots are from is the local system where Sonarr is installed and i am accessing it directly - so no url modifications, etc.

![preacher-scroll](https://user-images.githubusercontent.com/1746583/29992270-43facca6-8f5d-11e7-8e2e-0eb0d190682b.png)
![series-list](https://user-images.githubusercontent.com/1746583/29992271-43fb16de-8f5d-11e7-9a2d-1e68abcaaddc.png)

**Comment by dan-the-man-nz** [comment] 2017-09-03 22:06
mine is doing the same on some series   Chrome 60.0.3112.113 (Official Build) (64-bit) + 2.0.0.4977/develop on Win10 64  - 

also, same thing happens on latest Chrome on android 7.0  (galaxy note 5)

-mastyman

**Comment by Renegade605** [comment] 2017-09-16 00:11
I can reproduce it in Chrome Version 60.0.3112.113 (Official Build) (64-bit).

Although I had never really noticed before now. I'm sure it's going to really bother me going forward, so thanks for that.

**Comment by markus101** [comment] 2017-10-08 00:34
Tried to reproduce this again and I haven't been able to, not going to spend more time on it. If it's still an issue in v3 (when it's released), we can open up the issue again, but closing it now.

**Closed by markus101** 2017-10-08 00:34 UTC
