### ISSUE TITLE
Feature Request : Archived status

### ISSUE THREAD

**Issue by Ninjouz** [Sonarr/Sonarr#1926] opened 2017-05-14 18:50 UTC
Hey guys,

In order to reduce api calls on external cloud storage services, it would be nice to have an archived status for episodes / seasons that will prevent the automated RefreshSeriesService from scanning for files and analyzing them daily.

Or consider that a "Downloaded" episode with cutoff met should not be scanned / analyzed.
Or even maybe dont do that for unmonitored episodes.

Thanks ;)

**Comment by markus101** [comment] 2017-05-14 20:59
Dupe of https://github.com/Sonarr/Sonarr/issues/315

> In order to reduce api calls on external cloud storage services, it would be nice to have an archived status for episodes / seasons that will prevent the automated RefreshSeriesService from scanning for files and analyzing them daily.

They would only be analyzed if they're a new file to Sonarr during that scan, so either a brand new file or one that was previously untracked because it was missing. The extent of the scan in Sonarr just gets the list of files, determines if any are new and stops tracking any that are missing.

**Closed by markus101** 2017-05-14 20:59 UTC
