### ISSUE TITLE
simple variable substitution in the category name

### ISSUE THREAD

**Issue by grozan** [Sonarr/Sonarr#3537] opened 2020-01-22 23:36 UTC
**Describe the problem**
Right now, all downloads sent to a given download client share the same category.
I use tags/labels for a lot of things in my workflow. I'd like to use them for ratio group assignment as well.
For that, I'd need to have the name of the tracker included in the category name which gets passed to my download client.

**Describe any solutions you think might work**
I think a simple string substitution in the Category field would be just fine.
There would just be a special string, like `{indexer}` say which, if present, gets replaced by the name of the indexer the file comes from.
so instead of having the category set to just `tv`, one could decide to set the Category to `tv-{indexer}` for example.
That change would have no impact on existing configs.

**Comment by markus101** [comment] 2020-01-22 23:52
Dupe of https://github.com/Sonarr/Sonarr/issues/2163

**Closed by markus101** 2020-01-22 23:52 UTC
