### ISSUE TITLE
Show titles with Diacritical Marks show up under unmappedFolders

### ISSUE THREAD

**Issue by rr0ss0rr** [Sonarr/Sonarr#6727] opened 2024-04-15 00:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I was trying out the "/api/v3/rootfolder" api call and noted that 2 shows are coming up as unmappedFolders:

```
[
  {
    "path": "/Users/richard/mnt/Synology-Public/TVShows",
    "accessible": true,
    "freeSpace": 9810131148800,
    "unmappedFolders": [
      {
        "name": "Carnivàle",
        "path": "/Users/richard/mnt/Synology-Public/TVShows/Carnivàle",
        "relativePath": "Carnivàle"
      },
      {
        "name": "Shōgun (2024)",
        "path": "/Users/richard/mnt/Synology-Public/TVShows/Shōgun (2024)",
        "relativePath": "Shōgun (2024)"
      }
    ],
    "id": 1
  }
]
```
Both shows show up fine in Sonarr.  `Carnivàle THETVDB.COM SERIES ID70860` is wonkers.  Sonarr thinks the episodes aren't imported so it tries to download them again and again.  Shōgun has no issues but I was surprised that it was listed as an unmapped folder.

### Expected Behavior

Shogun should not be listed as unmapped.

### Steps To Reproduce

Add a show that contains Diacritical Marks in the title

### Environment

```markdown
- OS: MacOS 14.4.1
- Sonarr: 4.0.4.1491
- Docker Install: none
- Using Reverse Proxy: none
- Browser: 
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

NA

### Anything else?

Both shows have tvdb aliases without Diacritical Marks if that helps

**Comment by markus101** [comment] 2024-04-15 01:22
Duplicate of https://github.com/Sonarr/Sonarr/issues/6657

**Closed by markus101** 2024-04-15 01:22 UTC
Labels: needs-triage
