### ISSUE TITLE
Appostrophe search for torrents

### ISSUE THREAD

**Issue by evlo** [Sonarr/Sonarr#4543] opened 2021-06-17 17:45 UTC
Currntly the kinda hot show od Clarkson's farm, however torrent names Are missing the ' So IT Is clarksons farm, yes, not correct, however it would ve nic to Havel feature when there Is no hit And title contains kinda special character sonare would try to search one more time with these characters removed.

**Comment by markus101** [comment] 2021-06-17 17:46
Dupe of https://github.com/Sonarr/Sonarr/issues/1225

**Closed by markus101** 2021-06-17 17:46 UTC
