### ISSUE TITLE
Sonarr fails to load when directly navigating to a subpage via the URL

### ISSUE THREAD

**Issue by Stanzilla** [Sonarr/Sonarr#2532] opened 2018-04-27 03:18 UTC
### System Information/Logs

**Sonarr Version:** 2.0.0.5169

**Operating System:** DSM 6.1

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.8.0.108

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):** Chrome 67.0.3396.18 (Official Build) beta (64-bit / Firefox 61a

### Additional Information

When you go directly to the calendar view of Sonarr (/calendar) after having cleared your browser cache, Sonarr will fail to load, with a synchronous XMLHttpRequest deprecation notice at the loading spinner animation.

```
jquery.js:9625 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js:9625
ajax @ jquery.js:9215
$.ajax @ jquery.ajax.js:21
get @ ApiData.js:7
22 @ UiSettingsModel.js:27
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
20 @ FormatHelpers.js:3
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
16 @ DateTime.js:3
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
13 @ backbone.marionette.templates.js:3
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
11 @ backbone.marionette.js:4
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
0 @ vendor.js:33
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
0 @ bootstrap baaf0fd75373247a910e:93
(anonymous) @ bootstrap baaf0fd75373247a910e:93
main.js:31 starting application
SignalRBroadcaster.js:9 starting signalR
piwikCheck.js:11 GET http://piwik.sonarr.tv/piwik.js 404 (Not Found)
(anonymous) @ piwikCheck.js:11
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
(anonymous) @ main.js:20
__webpack_require__ @ bootstrap baaf0fd75373247a910e:50
webpackJsonpCallback @ bootstrap baaf0fd75373247a910e:21
(anonymous) @ main.js?h=JFBTfdG5WEEc6yjb/bOWwA:1
backbone.signalr.mixin.js:15 sync received, re-fetching collection
backbone.signalr.mixin.js:15 sync received, re-fetching collection
backbone.signalr.mixin.js:15 sync received, re-fetching collection
```

somes there is also:

```
TypeError: window.NzbDrone is undefined[Learn More]  vendor.js:23010:6
```

when you then go to the main sonarr page via just the IP, Sonarr loads just fine, yet still showing the deprecation notice in the console. 

It also tries to load http://piwik.sonarr.tv/piwik.js which is 404. Also your jQuery version is from 2015 :(

Not sure what to make of this all, at first I thought it's a caching problem and /pages need a pre populated cache to work and that only happens when you go to the main page once.

**Comment by markus101** [comment] 2018-04-28 00:52
I'm not able to reproduce Sonarr failing to load when a subpage is loaded.

`window.NzbDrone` is set when `index.html` is loaded.

The synchonous request and jQuery will be addressed in v3.

**Closed by markus101** 2018-04-28 00:52 UTC
