### ISSUE TITLE
Add more search engine options

### ISSUE THREAD

**Issue by PrzemekSkw** [Sonarr/Sonarr#4344] opened 2021-02-25 10:48 UTC
**Is your feature request related to a problem? Please describe.**
Sonarr don't search for some TV Shows because on TVDB many Shows are missing.

**Describe the solution you'd like**
Add more search engine indexers like [TV Maze](https://www.tvmaze.com/), [TMDB](https://www.themoviedb.org/).

**Describe alternatives you've considered**
I migrate to Sonarr from Medusa and there was no problem because Medusa search engine search from many indexing websites like TV Maze, TMdb, TVDB.

Regards,
Przemek

**Comment by bakerboy448** [comment] 2021-02-25 13:28
Dupe #1752
Dupe #1324
Dupe #3301 

dupe of several others as well

Please use the search function next time.

no plans to add multiple meta providers.

**Closed by bakerboy448** 2021-02-25 13:28 UTC

**Comment by viggy96** [comment] 2021-04-05 21:12
Has the recent news of TVDB going paid changed Sonarr's stance on this? Heck, even trakt.tv has officially switched its metadata provider to TMDB.

**Comment by bakerboy448** [comment] 2021-04-05 22:00
No.
https://www.reddit.com/r/sonarr/comments/jx6tkn/our_current_status_with_thetvdb/
