### ISSUE TITLE
qBittorrent on Linux, error when adding as downloader.

### ISSUE THREAD

**Issue by icenine9** [Sonarr/Sonarr#1012] opened 2015-12-19 03:06 UTC
Upon attempting to install qBittorrent as a downloader on the latest develop build (2.0.0.3660), I receive the following message:

Unknown exception: REST request failed: [400] [GET] at [http://hostname:65001/version/api]

qBittorrent is compiled as version 3.31 (qt5) on Ubuntu. Access to the web interface via browsing to http://hostname:65001 works as intended and username/password are confirmed to be correct.

**Comment by markus101** [comment] 2015-12-20 00:10
Are you going through a reverse proxy?
I don't see any issues connecting to qBittorrent 3.3.1 on Windows directly.

**Comment by icenine9** [comment] 2015-12-20 01:12
No reverse proxy. However, I did change the default port for the webui to 65001 obviously - not sure if that has anything to do with it.

**Comment by markus101** [comment] 2015-12-20 04:24
Sonarr is still able to communicate with it, qBittorrent just doesn't like the request for some reason although Sonarr is requesting a pretty simple URL.

**Comment by mishac** [comment] 2015-12-20 20:17
I'm having the same issue on windows, with the default webui port (8080).

**Comment by markus101** [comment] 2015-12-22 00:37
@mishac Please open a thread on the forums with trace logs so we can diagnose further.

**Comment by MikeRatcliffe** [comment] 2016-01-08 23:42
I have the same problem... It seems that only qBittorrent v3.2.4 and above are supported.

http://myhost:8080/version/api returns 4.

This takes us into:
https://github.com/Sonarr/Sonarr/pull/779/files#diff-32028ac4ac029a79eed58ab908a366afR188

16-1-8 23:14:51.2|Debug|RestSharpExtensions|Validating Responses from [GET] [http://192.168.1.188:8080/version/api] status: [BadRequest]
16-1-8 23:14:51.2|Warn|RestSharpExtensions|[GET] [http://myhost:8080/version/api] Failed. [BadRequest]
16-1-8 23:14:51.2|Error|QBittorrent|REST request failed: [400] [GET] at [http://myhost:8080/version/api]

NzbDrone.Core.Rest.RestException: REST request failed: [400] [GET] at [http://myhost:8080/version/api]
  at NzbDrone.Core.Rest.RestSharpExtensions.ValidateResponse (IRestResponse response, IRestClient restClient) <0x80ff87600 + 0x006b0> in <filename unknown>:0
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetVersion (NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) <0x80ff86140 + 0x000a6> in <filename unknown>:0
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection () <0x80ff85800 + 0x000e3> in <filename unknown>:0


16-1-8 23:14:51.2|Trace|NzbDroneErrorPipeline|Handling Exception
16-1-8 23:14:51.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:
 -- Unknown exception: REST request failed: [400] [GET] at [http://myhost:8080/version/api]

**Comment by markus101** [comment] 2016-01-21 03:31
Found the cause, a sneaking `Content-Length: 0` header for GET requests, only under mono.

Closing this issue in favour of a more direct issue: https://github.com/Sonarr/Sonarr/issues/1081

**Closed by markus101** 2016-01-21 03:31 UTC

**Comment by blindguy** [comment] 2016-02-28 15:44
I'm getting this same exact error with sonar version 2.0.0.3732 do I have to go to the dev branch to fix adding a qBittorrnet client?

**Comment by blindguy** [comment] 2016-02-28 15:48
I switched to the dev branch and now it says I'm still at 2.0.0.3872 but I still can't add qBittorent as a downloader.  

Any help is appreciated.

**Comment by darkcloud784** [comment] 2016-03-05 17:02
Thi issue doesn't seem to be fixed, unsure why it was closed?

**Comment by Taloth** [comment] 2016-03-05 17:05
@darkcloud784 : https://github.com/Sonarr/Sonarr/issues/1012#issuecomment-173440111

**Comment by mjmac85** [comment] 2016-03-09 22:32
Any word on this?

**Comment by nkali** [comment] 2016-03-27 21:04
This is still an issue, the reasons for closing this are unclear.

**Comment by markus101** [comment] 2016-03-27 21:06
@nkali another issue was opened, see [my comment] (https://github.com/Sonarr/Sonarr/issues/1012#issuecomment-173440111) above, that issue has been closed as this has been resolved in develop.

**Comment by nkali** [comment] 2016-03-27 21:08
@markus101 Thanks!
