### ISSUE TITLE
Importing Lists ?

### ISSUE THREAD

**Issue by hongkongkiwi** [Sonarr/Sonarr#3758] opened 2020-05-17 14:12 UTC
Hi there,

Is there a plan for adding a Lists feature like in Radarr?

Right now I'm using Traktarr to import Trakt lists into Sonarr, but it would be great to have this feature natively from IMDB lists and Trakt.

I'd regularly like to import new shows from lists with some filters, e.g. rating.

**Comment by Taloth** [comment] 2020-05-17 14:17
Please search first when posting new items. Dupe of #276.

**Closed by Taloth** 2020-05-17 14:17 UTC

**Comment by hongkongkiwi** [comment] 2020-05-17 14:28
This is true, but the thread was locked, so I couldn't add suggestions there or see any updates.
