### ISSUE TITLE
Synology downloader connection failing when items are in download queue

### ISSUE THREAD

**Issue by FrankGNL** [Sonarr/Sonarr#1758] opened 2017-03-13 17:58 UTC
Sonarr version:  2.0.0.4645
Synology: DSM 6.1-15047 Update 1

I have setup the torrent synology download client in Sonarr, this is working. 
If i test this with the test button i get a succeeded message. During this process no items are in the download queue.

Searching for an episode and pushing it to the synology download client is working correctly, but as soon as there is an item in the queue Sonarr is unable to connect to the download client. I get a 160 error message. It does not matter if Sonarr or myself are adding an item to the queue.

The user used for this has admin right on the whole system and all shares 

Logging:

FileStationProxy:
```
Failed to get info of /download. Reason: 160 - Unknown error
```

SharedFolderResolver:
```
Failed to get shared folder /download from Disk Station 127.0.0.1:5000: Failed to get info of /download. Reason: 160 - Unknown error
```
```
NzbDrone.Core.Download.Clients.DownloadClientException: Failed to get info of /download. Reason: 160 - Unknown error
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, System.Collections.Generic.Dictionary`2[TKey,TValue] arguments, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings, System.String operation, NzbDrone.Common.Http.HttpMethod method, System.Int32 retries) [0x000f8] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:90 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetInfoFileOrDirectory (System.String path, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00062] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:50 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetSharedFolderMapping (System.String sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:32 
  at NzbDrone.Core.Download.Clients.DownloadStation.SharedFolderResolver.GetPhysicalPath (NzbDrone.Common.Disk.OsPath sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\SharedFolderResolver.cs:33 
```

DownloadMonitoringService:
```
Unable to retrieve queue and history items from synology: Failed to get info of /download. Reason: 160 - Unknown error
```
```
NzbDrone.Core.Download.Clients.DownloadClientException: Failed to get info of /download. Reason: 160 - Unknown error
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, System.Collections.Generic.Dictionary`2[TKey,TValue] arguments, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings, System.String operation, NzbDrone.Common.Http.HttpMethod method, System.Int32 retries) [0x000f8] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:90 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetInfoFileOrDirectory (System.String path, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00062] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:50 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetSharedFolderMapping (System.String sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:32 
  at NzbDrone.Core.Download.Clients.DownloadStation.SharedFolderResolver.GetPhysicalPath (NzbDrone.Common.Disk.OsPath sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\SharedFolderResolver.cs:33 
```

As soon as all the items are out of the queue Sonarr can connect to the synology download client again, but autoprocessing is not working.

**Comment by margaale** [comment] 2017-03-13 21:56
Hi. I'm using it myself with the exact same setup and versions. Could you please post here the config parameters you enter when adding the client? 
Did you reset you DiskStation?

**Comment by margaale** [comment] 2017-03-13 22:00
@Taloth could be related to #1700

**Comment by FrankGNL** [comment] 2017-03-14 13:49
My settings for the synology torrent download client:
Name: synology
Host: 127.0.0.1
Port: 5000
username: <my username>
password: <my password>
Category and Directory are empty, i tried to use one 1 these but i doesn't matter what i fill in it will always fail.
ssl: off

Strange thing is, as long as there is no item in the download queue i can connect to the client, but if there is 1 or more items in the queue, i get the error 160

**Comment by Taloth** [comment] 2017-03-15 05:43
@margaale That issue dealt with the error being unknown and causing an exception. In this case the error is reported as 160. Which isn't a known error code, but still just an error reported by the syno.

**Comment by margaale** [comment] 2017-03-15 09:28
Ni it is not, it's unknown. The "fix" for that error was to return 'code -
Unknown error' and that is what we are getting here

**Comment by Taloth** [comment] 2017-03-15 18:27
That's what I meant, #1700 would've prevented you from getting the error code, but it doesn't cause the issue. In that respect it's unrelated.

**Comment by Indigo744** [comment] 2017-09-25 10:54
No update on this? It seems I have the exact same issue.
Adding DownloadStation client and testing works great.
But after a while (and I guess it seems related to the queue, as @FrankGNL says), the connection to the client fails.

Here is my setup: 
127.0.0.1:8001 with SSL enabled.
```
17-9-25 12:33:12.8|Error|FileStationProxy|Failed to get info of /download. Reason: 160 - Unknown error
17-9-25 12:33:12.9|Warn|SharedFolderResolver|Failed to get shared folder /download from Disk Station 127.0.0.1:8001

[v2.0.0.4949] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to get info of /download. Reason: 160 - Unknown error
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000d2] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:120 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:66 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetInfoFileOrDirectory (System.String path, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x0003d] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:41 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetSharedFolderMapping (System.String sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:28 
  at NzbDrone.Core.Download.Clients.DownloadStation.SharedFolderResolver.GetPhysicalPath (NzbDrone.Common.Disk.OsPath sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\SharedFolderResolver.cs:33 

17-9-25 12:33:13.3|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from DownloadStation

[v2.0.0.4949] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to get info of /download. Reason: 160 - Unknown error
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000d2] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:120 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:66 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetInfoFileOrDirectory (System.String path, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x0003d] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:41 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetSharedFolderMapping (System.String sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:28 
  at NzbDrone.Core.Download.Clients.DownloadStation.SharedFolderResolver.GetPhysicalPath (NzbDrone.Common.Disk.OsPath sharedFolder, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\DownloadStation\SharedFolderResolver.cs:33 
```

It's driving me crazy... :-/

**Comment by Indigo744** [comment] 2017-09-27 19:32
I can attest after some tries: "160 - Unknown error" when there are some file downloading in DownloadStation.
When files are finished download, if I click on "Clear completed items" which remove all files (the DownloadStation is then empty), the connection works again....

**Comment by galli-leo** [comment] 2018-02-07 19:05
@Taloth According to a user on the Radarr issue, he managed to fix this by giving the Radarr user FileStation Access next to giving it DiskStation Access. Maybe that's the error code for insufficient access?

**Comment by Indigo744** [comment] 2018-02-07 20:06
Giving the corresponding user the File Station access seems to work. I cannot reproduce the "160 - Unknown error" anymore even with files downloading and some completed.

I'll report here if any error come back.

**Comment by Taloth** [comment] 2018-02-07 20:20
@galli-leo It's certainly possible, but the 160 error came intermittently which doesn't really support a hard access permission issue. We'll see if that solution works for everyone.

**Comment by margaale** [comment] 2018-02-07 20:33
Mmmm, gonna give it a try tonight... @Taloth wasn't 119 the one that was
giving us trouble?

On Feb 7, 2018 17:20, "Taloth" <notifications@github.com> wrote:

@galli-leo <https://github.com/galli-leo> It's certainly possible, but the
160 error came intermittently which doesn't really support a hard access
permission issue. We'll see if that solution works for everyone.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sonarr/Sonarr/issues/1758#issuecomment-363897535>, or mute
the thread

**Comment by Taloth** [comment] 2018-02-07 20:53
Ah, right... damn, two different errors. Then nvm :smile: 119 was intermittent not 160.

**Comment by margaale** [comment] 2018-02-08 00:54
I was able to reproduce it, but I had to explicitly  deny access to the user to trigger this error. By doing that i wasn't able to pass the test to add diskstation as a client....

**Comment by markus101** [comment] 2018-05-03 07:09
Closing since the linked PR is merged.

**Closed by markus101** 2018-05-03 07:09 UTC
