### ISSUE TITLE
Archived status for episode

### ISSUE THREAD

**Issue by sebeksd** [Sonarr/Sonarr#5777] opened 2023-07-03 13:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now I'm using Medusa (previously SickRage, SickChill) and I heavily use "Archived" flag for episodes.
I would like to convert to Sonarr because Medusa is extremely slow (order of magnitude slower then Sonarr, at least in my case).
Unfortunately Sonarr lacks few major function (without them I will not be able to convert to Sonarr).
Most important one is lack of "Archived" status that could be set per episode (already downloaded episode or not). 

I use this feature for two things:
1. when I delete episode to recover some space, I still want to see this episode as "Downloaded/Watched" even if file is not there (this is typical use case for this flag as name suggests)
2. as virtual "watched" flag, for example I watch some TV series on Netflix, I still want to add it to Medusa/Sonarr so I have it in my "database", and I want that show to appear on Calendar (Medusa = Schedule), if show stop being aired on "my" streaming platform I can quickly enable download In Medusa for all feature episodes  

### Describe the solution you'd like

Be able to select "Archived" for any episode.
Archived episode should stop being monitored, if file does not exist before or after selecting of Archived flag it should still be counted as downloaded in any UI counter that show downloaded episodes (e.g. progress 2/4).
For example after importing show from current library that has show Directory but has no episodes files should still allow user to select "Archived" for all missing episodes files.

### Describe alternatives you've considered

I don't see alternative to this. Episodes that are not monitored are not counted as downloaded.

### Anything else?

This feature was requested few times before but it was closed every time.

Example show that I watched few episodes off on Netflix than dropped:

![image](https://github.com/Sonarr/Sonarr/assets/18705953/cde133bb-5a33-44ea-912c-5adfcad66276)

![image](https://github.com/Sonarr/Sonarr/assets/18705953/0e7ed3fa-6124-4f5a-958e-52557b5c0911)

**Comment by thezoggy** [comment] 2023-07-03 13:57
In sonarr it's simply monitored or not. If you delete an episode content sonarr can auto mark it as unmonitored. Monitoring status can be set at episode/season/series level.

**Comment by sebeksd** [comment] 2023-07-03 14:04
Yes, I know, but this will not count on progress, it show "0/0" (all episodes are unmonitored, can't set which ones was archived/watched):

![image](https://github.com/Sonarr/Sonarr/assets/18705953/f4983ae7-e90c-43e2-b410-cca4a060dc85)

**Comment by thezoggy** [comment] 2023-07-03 14:29
The count only shows what you have monitored. As that's the only thing tracked

**Comment by sebeksd** [comment] 2023-07-03 14:35
Yes, I would like it to also count Archived like I described in feature request.

**Comment by markus101** [comment] 2023-07-06 19:27
Duplicate of #1926, #4973

It's not something we have plans to add support for.

**Closed by markus101** 2023-07-06 19:27 UTC
Labels: needs-triage

**Comment by sebeksd** [comment] 2023-07-07 05:12
For me this is basic functionality for this kind of software so I'm curious why you are hesitant to implement it, is it hard to do or there are some other things that make it impossible to implement?
Could you please explain what reason there is to not add it? This was requested few times already, and there are some threads in the wild where people ask about it.

**Comment by markus101** [comment] 2023-07-07 16:02
We opted for two states in regards to files, it's either there or it isn't. We've suggested in the past that if someone wants to achieve an archive like state that they could add add an empty file in place of a real video file.

Based on the small number of requests and comments over the years we don't think adding the functionality is important enough to commit to.
