### ISSUE TITLE
 Feature Request - Centralized authentication (LDAP) and SSO (SAML/OATH) #2477 

### ISSUE THREAD

**Issue by Wh1t3Rose** [Sonarr/Sonarr#4857] opened 2022-01-16 17:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Support for centralized authentication (i.e. LDAP) and SSO (i.e. SAML/OATH) provides several benefits:

    Multiple user accounts without password sharing
    Don't store admin credentials in plaintext config
    Use same credentials/sessions across apps in this space ( i.e Radarr, NZBGet, Tautulli, etc)
    Opens the door for user permissions (authorization) down the road
    Improve security by offloading AuthN/AuthZ to services designed for these purposes

### Describe alternatives you've considered

N/A

### Anything else?

Integration with Authelia SSO would be appreciated

**Comment by bakerboy448** [comment] 2022-01-16 17:15
Duplicate of https://github.com/Sonarr/Sonarr/issues/2477

**Comment by bakerboy448** [comment] 2022-01-16 17:16
> > Is there an existing issue for this?
> I have searched the existing issues

Either you didn't actually search or you only searched open issues. Please put more effort into searching next time.
Ref - https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+ldap

Also related to https://github.com/Sonarr/Sonarr/issues/1682

**Closed by bakerboy448** 2022-01-16 17:16 UTC
Labels: needs-triage
