### ISSUE TITLE
Sonarr beta won't update

### ISSUE THREAD

**Issue by BRTPOB** [Sonarr/Sonarr#2994] opened 2019-03-13 19:58 UTC
**Describe the bug**
Attempting to update Sonarr to the latest dev build fails. Logs attached.

**Logs**
https://linx.eskimomafia.com/trace.txt

**System Information**

Version
    3.0.1.363
Mono Version
    5.18.0.240
AppData directory
    /home/offspring/.config/Sonarr
Startup directory
    /usr/lib/sonarr
Mode
    Console

**Comment by markus101** [comment] 2019-03-13 19:59
Please search (including closed issues before posting new issues).

Dupe of https://github.com/Sonarr/Sonarr/issues/2991

**Closed by markus101** 2019-03-13 19:59 UTC
