### ISSUE TITLE
Web Notifications as "Connection"

### ISSUE THREAD

**Issue by sparksis** [Sonarr/Sonarr#3050] opened 2019-04-15 01:25 UTC
**Describe the problem**
I would like my Sonarr server to act as a native [Web Notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) provider.  This would allow allow me to receive notifications such as those provided by push-bullet/growl without the use of third party service or special notification provider.

**Describe any solutions you think might work**

The current push-bullet and growl interfaces both provide nearly what I'd like to see feature wise however they require additional applications or third party services to run.  As I typically am interfacing with Sonarr using Chrome it would be preferable to receive notifications through Chrome.

**Comment by markus101** [comment] 2019-04-15 01:27
Dupe of https://github.com/Sonarr/Sonarr/issues/364

**Closed by markus101** 2019-04-15 01:27 UTC

**Comment by sparksis** [comment] 2019-04-15 01:47
Thanks @markus101 I couldn't find the original request as it is incorrectly title "desktop notifications".  The feature description is related to "Web Notifications".  Desktop Notifications would be those provided to Windows/GTK natively while Web Notifications are those that are provided to a consuming browser.

Regardless, I've added comments on the topic, if you're have a chance please review them and provide any feedback regarding what the UX of such a feature would take.

Cheers,
