### ISSUE TITLE
Sonarr should keep language codes when renaming subtitles

### ISSUE THREAD

**Issue by fabiorzfreitas** [Sonarr/Sonarr#4939] opened 2022-03-09 15:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Whenever media files are moved/renamed via "reorganize", the subtitles are moved/renamed accordingly. However Sonarr always loses track of language codes in the subtitle when doing this, e.g.:

```
Filename.mkv
Filename.pt-BR.srt
```

become

```
NewFilename.mkv
NewFilename.srt
````

### Describe the solution you'd like

The proper way of handling this would be keeping the language codes, which perhaps could be done by detecting the difference between the media and srt files. If a srt is indeed being loaded (which Sonarr doesn't need to check, this should be on the user, I personally let Bazarr handle my subs) with that media file, then the different part must be a valid language code.

### Describe alternatives you've considered

Whenever I have reorganized files, I ended up having to apply some sort of batch renaming to the subtitles, which is slow.

### Anything else?

I guess I could add I use regex for my manual renaming, but there's probably better ways to do that with more robust programming.

**Comment by markus101** [comment] 2022-03-09 15:56
Dupe of https://github.com/Sonarr/Sonarr/issues/2570

**Closed by markus101** 2022-03-09 15:56 UTC
Labels: needs-triage
