### ISSUE TITLE
Visible HDR (type) status and profiles

### ISSUE THREAD

**Issue by Avamander** [Sonarr/Sonarr#5071] opened 2022-07-03 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It's currently very difficult to get an overview which series or episodes are HDR (or are they Dolby Vision or HDR10+). It's also difficult to initiate or limit searches to only find those releases.

For users without DV-compatible device(s) it is also relatively annoying to avoid incompatible releases.

### Describe the solution you'd like

I would like HDR and it's types to become an optional clear step (or ceiling) in "Quality Profiles" list (potentially as "Dynamic Range Profiles" list). This would be significantly better than just being preferred using a custom release profile.

Primarily though, I'd like the solution to show me "Dynamic Range" the same way "Language" and "Quality" is displayed.

### Describe alternatives you've considered

Manually adding release profiles to increase the score of those releases, but that doesn't provide good enough overview.

**Comment by markus101** [comment] 2022-07-03 19:39
Showing HDR is a duplicate of https://github.com/Sonarr/Sonarr/issues/4963

We do not have plans to have HDR as part of quality profiles.

**Closed by markus101** 2022-07-03 19:39 UTC
Labels: needs-triage

**Comment by Avamander** [comment] 2022-07-04 07:08
@markus101

But as a separate profile list? The current system is really rather tedious sometimes.

Also what aboue an UI element/column to show the status alongside quality?
