### ISSUE TITLE
Vuze category renames downloaded file

### ISSUE THREAD

**Issue by Makere** [Sonarr/Sonarr#1986] opened 2017-06-19 16:54 UTC
If I set a category (in this case "automatic"), Sonarr will start the download with "automatic" as the filename. 

So that I will end up with a file named "automatic", and if another download starts before I notice it, it will overwrite the downloaded file.

The operating system is Ubuntu 16.04, and Vuze version is 5.7.5.0, I am using Sonarr version 2.0.0.4753.

Debug log: https://pastebin.com/Zsn0VWqG

**Comment by markus101** [comment] 2017-06-21 04:38
I'm not able to reproduce this with Vuze 5.7.5.0 running under windows.

What is your `Default Directory` for downloading set to? (Under `Files` in settings).

We'll also need Trace logs to the request and response from Vuze.

**Comment by Makere** [comment] 2017-06-21 18:52
Default directory is:
/media/raid5/Unsorted

Here's the trace log:
[automatic-dbs88-trace.txt](https://github.com/Sonarr/Sonarr/files/1092563/automatic-dbs88-trace.txt)

**Comment by markus101** [comment] 2017-07-03 05:30
`17-6-21 21:44:03.5|Trace|HttpClient|Response content (325 bytes): {"result":"success","arguments":{"torrents":[{"eta":1827387392,"status":4,"downloadDir":"\/media\/raid5\/Unsorted","totalSize":558848226,"errorString":"","leftUntilDone":558848226,"name":"[HorribleSubs] Dragon Ball Super - 88 [1080p].mkv","isFinished":false,"id":6,"hashString":"8292BD729806CAE0E0FB971EF03F0FE29AF57933"}]}}`

`downloadDir` should include the `automatic` subfolder as well, like so:

`17-7-2 22:08:39.8|Trace|HttpClient|Response content (397 bytes): {"result":"success","arguments":{"torrents":[{"eta":1827387392,"status":4,"downloadDir":"C:\\Test\\Torrents\\sonarr\\Mr.D.S06E10.720p.HDTV.x264-KILLERS[rarbg]","totalSize":670186045,"errorString":"","leftUntilDone":437140029,"name":"Mr.D.S06E10.720p.HDTV.x264-KILLERS[rartv]","isFinished":false,"id":3,"hashString":"9F903F1C5FB7CD055DC532003D99811EAA525F7B"}]}}`

Are you setting the `Category` or `Directory` in Sonarr's Vuze settings?

![image](https://user-images.githubusercontent.com/413544/27779172-ead4a32a-5f75-11e7-9565-b461153261c6.png)

**Comment by Makere** [comment] 2017-07-03 20:31
I am settings the category and leaving directory empty.

**Comment by markus101** [comment] 2017-07-10 04:34
I'm not able to reproduce any issue with single or multi-file releases, the release is put in the correct job folder. In your logs I see that the only download is not in a category folder, it's directly in the download directory.

I'm not sure what could be causing it, possibly a setting in Vuze?

Closing as I'm not able to reproduce, if you can provide definitive reproduction steps then we can take another look.

**Closed by markus101** 2017-07-10 04:34 UTC

**Comment by Taloth** [comment] 2017-07-10 14:28
@markus101 You checked it with a magnet link?

**Comment by Makere** [comment] 2017-07-10 16:58
I managed to fix it for myself, I created the automatic folder manually.
I also created automatic-category in vuze manually, but that alone didn't help.

**Comment by elisionducoeur** [comment] 2020-11-16 21:56
Was able to reproduce this. How did you fix it? When I create the automatic folder manually, it just gets overwritten and turned into the file the torrent is trying to download...

**Comment by Makere** [comment] 2020-11-16 22:05
> Was able to reproduce this. How did you fix it? When I create the automatic folder manually, it just gets overwritten and turned into the file the torrent is trying to download...

Sadly I can't really remember much about this issue and I don't have vuze anymore to check (I migrated to deluge).
Try putting in the download directory to be the "automatic" instead of "unsorted", and make sure trailing slashes are properly everywhere.
