### ISSUE TITLE
Unable to open Activity - Queue: Failed to load Queue

### ISSUE THREAD

**Issue by iammortimer** [Sonarr/Sonarr#3656] opened 2020-04-01 14:09 UTC
**Describe the bug**
Clicking Activity - Queue returns "Failed to load Queue" 

**Screenshots**
![image](https://user-images.githubusercontent.com/44798984/78145458-33d46b00-7431-11ea-88ad-1d1985f2c173.png)

**Logs**
Events: Component: SonarrErrorPipeline
Message: 
```
Request Failed. GET /api/v3/episode: Expected query to return 2 rows but returned 1
```
Exception:
```
System.ApplicationException: Expected query to return 2 rows but returned 1
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 96
   at NzbDrone.Core.Tv.EpisodeService.GetEpisodes(IEnumerable`1 ids) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\EpisodeService.cs:line 63
   at Sonarr.Api.V3.Episodes.EpisodeModule.GetEpisodes() in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Episodes\EpisodeModule.cs:line 54
   at Sonarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:line 123
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()
```
**System Information**

 - Sonarr Version: 3.0.3.750
 - Operating System: Windows 10 1909 18363.720
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8

**Comment by markus101** [comment] 2020-04-01 14:56
Dupe of https://github.com/Sonarr/Sonarr/issues/3565

Restarting Sonarr will work around the issue.

**Closed by markus101** 2020-04-01 14:56 UTC
