### ISSUE TITLE
Autosearch and faster syncing for small lists, limited to prevent a lot of API hits

### ISSUE THREAD

**Issue by solvingtonight** [Sonarr/Sonarr#5155] opened 2022-09-15 08:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Big lists used to import a lot of content rightfully limit searching to prevent banning, this issue isn't present for small lists where users are individually choosing shows.
With many users using watchlists for show finder services and their media centers, lists aren't useful if you want to start watching those shows straight away when added, and require using sonarr directly for each show when managing show downloads from dedicated show finder or media center programs would be better.

### Describe the solution you'd like

Watchlists, which by design involve the user individually selecting a show should have an option to auto search, and have frequent refreshes. To prevent abuse those lists could be limited to 1 or 2 shows added per sync.
If Plex / Trakt style watchlists had the option to auto add, users could choose to download a show directly from the media center or show finder.
If shows removed from a watchlist also deleted that series, users could manage adding/removing shows in sonarr.

### Describe alternatives you've considered

*

### Anything else?

*

**Comment by bakerboy448** [comment] 2022-09-15 12:07
Lists are not and have never been intended as "add it now" they are "add it eventually"

Duplicate of https://github.com/Sonarr/Sonarr/issues/5011

**Comment by markus101** [comment] 2022-09-15 14:30
We do not have plans to remove series when items are removed from a list or limited the number of additions that occur each time.

**Closed by markus101** 2022-09-15 14:30 UTC
Labels: needs-triage
