### ISSUE TITLE
Manual Import - Scroll Bug

### ISSUE THREAD

**Issue by reloxx13** [Sonarr/Sonarr#3865] opened 2020-07-12 13:57 UTC
**Describe the bug**
On a not auto matching download click on he yellow icon to manually import/match the download.
Now select all (eg. a complete season 22episodes)
Click on select,.. -> series

now SCROLL DOWN to the matching series

After that ull have a lot of checkboxes without namings/data under the 22 episodes.

===> modal content height bugged

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14855001/87248167-32ff9c00-c458-11ea-8092-3d7016657901.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.3.899
 - Operating System: Win10x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: show this info in sytem info tab if u want users to post this.

**UI Bugs:**
 - Browser: Latest Firefox

**Additional context**

**Comment by markus101** [comment] 2020-07-12 16:36
Dupe of https://github.com/Sonarr/Sonarr/issues/3816

**Closed by markus101** 2020-07-12 16:36 UTC
