### ISSUE TITLE
Sonarr erases subtitles extensions when renaming episodes

### ISSUE THREAD

**Issue by dbarkar** [Sonarr/Sonarr#6498] opened 2024-02-10 06:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

This is bug report for V4.

When renaming episodes, Sonarr also renames associated external subtitles.
If subtitles extension is not just country code, Sonarr erases it.
Examples:

```
01.ru-st_whisper-dfnet.srt -> Wellington Paranormal - S04E01 - Bird Woman Bluray-1080p.1.srt
01.ru-st_whisper-vad.srt -> Wellington Paranormal - S04E01 - Bird Woman Bluray-1080p.2.srt
01.ru-st_whisper-vad-dfnet.srt -> Wellington Paranormal - S04E01 - Bird Woman Bluray-1080p.3.srt
```

What's the reasong behind this? Sonarr didn't create these files, why is it deleting important information?
I believe this shouldn't happen, or at least there must be an option in the settings.

Other software (KODI, jellyfin) can properly detect country code and additional information for such subtitles.

### Expected Behavior

Only file names of the associated subtitles should be changed, extensions must be preserved.

### Steps To Reproduce

Add any TV show, add episodes manually
Add subtitle with extension `en-extra-info.srt`
Ask Sonarr to rename episodes
See that new subtitles extension is `1.srt`

### Environment

```markdown
- OS: Linux
- Sonarr: Sonar 4.0.1.929
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 
- Database:
```

### What branch are you running?

Main

**Comment by markus101** [comment] 2024-02-10 07:46
Duplicate of https://github.com/Sonarr/Sonarr/issues/6494

**Closed by markus101** 2024-02-10 07:46 UTC
Labels: needs-triage
