### ISSUE TITLE
Break Manual Import into smaller steps

### ISSUE THREAD

**Issue by hukasu** [Sonarr/Sonarr#4023] opened 2020-10-20 11:59 UTC
Opening the Manual Import menu takes too long due to me having too many files on the download folder, I use hardlinks so to leave the torrents seeding, so my download folder has every file i ever downloaded.

Break the Manual Import into smaller steps, i believe that most of the wait when opening the Manual Import menu is Sonarr running the title detection on every file on the folder/subfolders.
Have a step where you first select the files you want to import and then have the title detection run on just those files.

This would work best when these are already implemented.
#1127 
#1142

**Comment by markus101** [comment] 2020-10-20 14:35
This is a dupe of #1142 with a different approach to achieve it, please add your suggestion there.

**Closed by markus101** 2020-10-20 14:35 UTC
