### ISSUE TITLE
No Results Found with show title with "-"

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3383] opened 2019-11-06 02:58 UTC
**Describe the bug**
Searching for The X-Files episodes returns no results despite plenty being available on indexers. Shows without a "-" seem to work as expected

**Logs**
[logs.txt](https://github.com/Sonarr/Sonarr/files/3812308/logs.txt)

 - Sonarr Version: 3.0.3.653
 - Operating System: Ubuntu 18.04
 - Mono 5.20.1.34

**Comment by antigravity83** [comment] 2019-11-06 05:51
Actually. It seems to affect other shows. 

Same error occurs when searching for House episodes also. Doesn't matter how old the episode is.

**Comment by markus101** [comment] 2019-11-06 05:52
Your logs show plenty of results coming back...

**Comment by markus101** [comment] 2019-11-06 05:54
How exactly is it failing if there are results coming back?

Are they not displaying in a manual search, like this issue that was right at the top of the list? https://github.com/Sonarr/Sonarr/issues/3377

**Comment by antigravity83** [comment] 2019-11-06 05:54
> Your logs show plenty of results coming back...

They don't appear in Sonarr when attempting a search, the error that appears towards the bottom of the log may be the cause?

**Comment by markus101** [comment] 2019-11-06 05:57
Yeah, a dupe of that issue.

**Comment by antigravity83** [comment] 2019-11-06 05:57
> Yeah, a dupe of that issue.

Apologies, didn't see that before posting. 

Cheers

**Closed by markus101** 2019-11-06 05:57 UTC
