### ISSUE TITLE
Episode Naming Format Name Tokens should support language code just like radarr {Series Title:DE}

### ISSUE THREAD

**Issue by tinymins** [Sonarr/Sonarr#5221] opened 2022-11-04 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In our media system, series folder and files should be named in local language for the media player system.

For example, `Person of Interest` should be renamed to `疑犯追踪`.

### Describe the solution you'd like

In `Standard Episode Format` configure, use:

```
{Series Title:ZH} S{season:00}E{episode:00} - {Quality Title} {MediaInfo Simple} {Release Group}
```

![image](https://user-images.githubusercontent.com/1808990/199936265-aec76c13-2d4f-4a3b-b91e-4423b6e3fbfa.png)

This format string works well in radarr:

![image](https://user-images.githubusercontent.com/1808990/199935595-0bfd3331-ef3f-4fec-92ad-b64d1678c605.png)

But not available in sonarr:

![image](https://user-images.githubusercontent.com/1808990/199936738-6243a7c8-e2ec-4eae-8d1a-18c423e38b0f.png)

### Describe alternatives you've considered

No good idea.

### Anything else?

`Movie Naming` pattern on radarr wiki:

https://wiki.servarr.com/radarr/settings

![image](https://user-images.githubusercontent.com/1808990/199935525-ac5074c8-ace1-4d8f-8a3b-0f7d715fd54c.png)

`File Name Tokens` document in radarr UI:

![image](https://user-images.githubusercontent.com/1808990/199935878-e90d2e7d-ec42-4522-a291-82ac9674d9c0.png)

**Comment by bakerboy448** [comment] 2022-11-04 12:24
Duplicate of https://github.com/Sonarr/Sonarr/issues/269

**Closed** 2022-11-04 14:27 UTC
Labels: needs-triage

**Comment by tinymins** [comment] 2022-11-04 15:21
> Duplicate of #269

Emmmm, it means this feature has been delayed for 6 years already? Is this feature in progress, or not started yet? 

I'v cloned sonarr and radarr source code, and read them this whole day. If I'm able to figure out how to implement, should I write code and create pull request in the future?

**Comment by HernandoR** [comment] 2023-01-04 10:10
I noticed that TVDB v4 API would require a monthly payment for end users (the company path is unsuitable for open-source projects). And the v3 API would be removed when the switch is done ( refer to their Facebook on [16th of March 2021](https://www.facebook.com/TheTVDB/) 

> Due to a myriad of issues with the v4 API, we will be extending the cutoff date for all of our older APIs. The new cutoff date will now be October 1, 2021.
> On that date, API access for all legacy keys will be removed, and a v4 API key will be the only way to access our metadata from that point forward.

There has been discussion about the alternatives of  TVDB in [hama](https://github.com/ZeroQI/Hama.bundle/issues/457)

There should be a discussion of either waiting for TVDB v4 API or migrating to another.
