### ISSUE TITLE
Configure label for season search

### ISSUE THREAD

**Issue by LoicAuge** [Sonarr/Sonarr#3988] opened 2020-10-01 16:07 UTC
**Describe the problem**
I want to search 1st seson of a TV show, but the search is like Showname + S01, but in the index, this is Showname + Season 1 (this is the idea, i think there the same issue with different languages)

**Describe any solutions you think might work**
I think add a setting to change this "S01" for "Season 1" or "Saison 1" or whatever.

**Comment by markus101** [comment] 2020-10-01 16:08
Dupe of https://github.com/Sonarr/Sonarr/issues/3934

**Closed by markus101** 2020-10-01 16:08 UTC
