### ISSUE TITLE
Use tvDbEpisodeId instead of Id for Kodi episode metadata

### ISSUE THREAD

**Issue by MarcoSmeulders** [Sonarr/Sonarr#4792] opened 2021-12-10 11:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some Kodi plugins (for example WatchedList) expect an IMDB or TVDB uniqueId in the episode metadata in order to function. This is missing in the NFO file metadata.

### Describe the solution you'd like

Sonarr creates a metadata NFO file including the internal Sonar id as an uniqueId but this id is not used outside Sonarr. Replacing this with the TVDB episode id, or adding an extra uniqueId entry with the TVDB episode id, will avoid problems with Kodi.

### Describe alternatives you've considered

Kodi can create and overwrite the Sonarr created NFO file with information from other scrapers, but this will remove the benefit of Sonarr creating the file.

### Anything else?

It appears using tvDbEpisodeId instead of seriesId would do the trick, but I'm not familiar enough with the Sonarr code to understand why Episode object properties are used in the code where EpisodeFile object properties are expected.

Kodi episode metadata documentation: 
https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags_2

Sonarr API documentation:
https://github.com/Sonarr/Sonarr/wiki/Episode
https://github.com/Sonarr/Sonarr/wiki/EpisodeFile

Related uniqueId bugfix:
https://github.com/Sonarr/Sonarr/commit/ffccc3be38e32b76f1b4d9b61373273969d0fda4

**Comment by markus101** [comment] 2021-12-10 15:53
This is a dupe of https://github.com/Sonarr/Sonarr/issues/3773 but the reason we don't have a unique TVDB ID for episodes is outlined here https://github.com/Sonarr/Sonarr/issues/3062

> I'm not familiar enough with the Sonarr code to understand why Episode object properties are used in the code where EpisodeFile object properties are expected.

Not sure I understand what you mean here, what properties are you referring to?

**Comment by MarcoSmeulders** [comment] 2021-12-12 10:22
> 

It appeared in the code an EpisodeFile is expected, but an Episode is used. I probably misread it as I don't code .Net :-)

I do agree that season and episode numbers won't change much (unless it's re-ordered by the network) when determining a unique episode. However, adding an extra uniqueid (with "default" to "false") of the resource used for the metadata information, possibly next to the Sonarr id, should not interfere with that behavior. Besides Sonarr I use other download software too and haven't experienced any problems with those NFO files yet, despite the files of long-running shows sometimes had multiple id's (TVDB, IMDB) for years.

I think information providers are much more stable nowadays than ten years ago, so maybe it's up for re-consideration today ;-)

**Closed** 2022-02-22 06:59 UTC
Labels: enhancement
