### ISSUE TITLE
Using Back button in browser

### ISSUE THREAD

**Issue by davidpearce** [Sonarr/Sonarr#1661] opened 2017-02-05 01:13 UTC
When going from the series list to a show, and then back to the series list using the back button in the browser, is it possible for page to be positioned where it was previously?

I.e. if I have scrolled half way down my series list, click on The Simpsons, then click back, the page should be at or near The Simpsons.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by meffect** [comment] 2017-02-05 02:27
Chrome seems to remember the previous position... well... most of the time. What browser are you using? Interesting article I found https://brigade.engineering/maintaining-scroll-positions-in-all-browsers-a280d49bffca#.q8o05w1b0  . Just thinking quickly about it, not using JavaScript but somehow query string anchors (to not take you to the exact position you were at, but the series you clicked on) would be least messy and least conflict with existing or future browser solutions

**Comment by markus101** [comment] 2017-02-05 02:57
Dupe of: https://github.com/Sonarr/Sonarr/issues/1533

**Closed by markus101** 2017-02-05 02:57 UTC
