### ISSUE TITLE
Allow filtering by reject reason in manual/interactive search

### ISSUE THREAD

**Issue by gsingh93** [Sonarr/Sonarr#4132] opened 2020-11-30 18:52 UTC
**Describe the problem**

When doing a manual search, I sometimes see releases that are rejected because they're the wrong episode, and the reject reason is: "Episode wasn't requested". I don't want these to show up in the list.

**Describe any solutions you think might work**

The current filters only allow filtering based on the rejection count (the number of rejection reasons), but it would also be useful to be able to reject if any rejection reason contained a particular keyword or phrase, like the "Episode wasn't requested".

**Comment by bakerboy448** [comment] 2020-11-30 18:55
What's the use care here?

**Comment by gsingh93** [comment] 2020-11-30 19:07
There's a lot of information shown on the screen when selecting a release manually. I'm glancing at the quality, the number of seeders, the language, the titles to pick out the video encoding (x264 vs. x265), the audio encoding, the number of channels, etc. to find the best release I want.

Having episodes I didn't request mixed into the results makes the above process more difficult. For example, if I want to prioritize having more seeders, I'd like to just click the button to sort by seeders and go down the list one by one. But having a bunch of different releases mixed in makes it difficult.

**Comment by markus101** [comment] 2020-12-22 19:19
> Having episodes I didn't request mixed into the results makes the above process more difficult.

Unless this is a scene vs TheTVDB mapping issue, this is something your indexer should correct.

At this time we don't have plans for filtering on rejection reason, it's something we'll likely revisit in the future though.

**Comment by zpanderson** [comment] 2021-09-29 21:43
Another use-case for this is that I cannot find a way to filter out just the blacklisted releases as the only thing that identifies it as blacklisted is the rejection reason.

**Comment by bakerboy448** [comment] 2021-09-29 21:45
> Another use-case for this is that I cannot find a way to filter out just the blacklisted releases as the only thing that identifies it as blacklisted is the rejection reason.

also the same as a duplicate of this issue 
https://github.com/Sonarr/Sonarr/issues/4140

**Comment by markus101** [comment] 2024-06-02 15:32
This will require additional information to be passed back with the rejections, since those are just strings in the API another property would make the most sense without a breaking change to the API.

**Comment by markus101** [comment] 2024-07-14 16:37
Closing in favour of https://github.com/Sonarr/Sonarr/issues/6960

**Closed by markus101** 2024-07-14 16:37 UTC
Labels: enhancement
