### ISSUE TITLE
Memory usage climbs over time under mono

### ISSUE THREAD

**Issue by smcpeck** [Sonarr/Sonarr#2296] opened 2017-11-19 15:21 UTC
## Bug Report
I'm running all of my home media automation apps on a 2GB VM and get memory alerts from it about every other day.  NzbDrone starts getting to the point of eating up a lot of memory that isn't getting released back to the system.

### System Information/Logs

**Sonarr Version:** 2.0.0.5054
**Operating System:** Ubuntu 16.04.3
**mono Version:** 5.4.1.6

### Log File Snippet
```
17-11-18 06:52:49.2|Info|RssSyncService|RSS Sync Completed. Reports found: 250, Reports grabbed: 0
17-11-18 06:55:47.5|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from NZB Get

[v2.0.0.5054] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
  at System.Net.WebConnectionStream.EndWrite (System.IAsyncResult r) [0x00097] in <50d80b08c1a5449282b22aedf03ce925>:0 
  at System.Net.WebConnectionStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x00053] in <50d80b08c1a5449282b22aedf03ce925>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000d2] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:59 
  at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000b5] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:53 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request) [0x0007e] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:119 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:55 
  at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T] (NzbDrone.Core.Download.Clients.Nzbget.NzbgetSettings settings, System.String method, System.Object[] parameters) [0x00047] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:232 
  at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.GetQueue (NzbDrone.Core.Download.Clients.Nzbget.NzbgetSettings settings) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:130 
  at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetQueue () [0x00012] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:56 
  at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetItems () [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:184 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (NzbDrone.Core.Download.IDownloadClient downloadClient) [0x0000c] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:89 
```
This error is in the logs quite frequently, sometimes as often as once every 10 minutes.

Wouldn't think that a memory leak would be caused by a disposed object error, but if the referencing code isn't cleaning up properly, maybe.  Just wanted to be forthcoming that the stacktrace may not actually capture the root cause of what I'm seeing.

Happy to provide more logs, but there's nothing really of interest there.

### Additional Information
FWIW, Radarr is suffering from the same issue, so the problem may lie within shared code.  I see the same stacktrace in its logs as posted above, though not as frequently.

### Other Information

- NzbGet version:
```
$ /usr/bin/nzbget -V
Request sent
server returned: 19.1
```
- VM is running on FreeNas 11 via BHYVE

**Comment by markus101** [comment] 2017-11-19 16:12
The stack trace is due to a bug in mono, introduced in 4.6 or 4.8 IIRC, it's since been fixed, but hasn't found its way to a release yet.

As for the memory leak, we haven't seen this behavior on Windows, so it looks to be something in mono, whether caused by us or not I'm not sure.

**Comment by thezoggy** [comment] 2018-01-23 01:12
try downgrading mono to an older more stable version or deal with the buggy mono version by having a cron job to restart sonarr every x days?

**Comment by JReming85** [comment] 2018-09-30 14:52
I just had just killed sonarr for using 67GB of vram and bringing my server system to a crawl.

The weird thing is my server only has 8GB of RAM, and 4GB of swap and those reported in the normal range (FreeNAS)

**Comment by dancii** [comment] 2018-10-19 19:53
Having the same issue as @JReming85, latest Sonarr (v2.0.0.5250) and mono version 5.10.1.57. I've read that mono 5.10 introduced a memory leak and they have fixed it in the latest release version 5.16.0. I can not upgrade it on my Freenas jail. I just have to wait until the pkg updates it cause I can not find any information how to build mono from scratch in a jail.

**Comment by zero77** [comment] 2018-12-01 14:53
@markus101 
This may be similar or the same, as the memory leak that's happening with Radarr.
https://github.com/Radarr/Radarr/issues/1580

**Comment by realies** [comment] 2018-12-17 13:34
Any progress on this?

**Comment by thezoggy** [comment] 2018-12-17 17:48
for those having the problem.. do you use ombi?

**Comment by dancii** [comment] 2018-12-17 19:09
@realies It seems to be a mono bug. What OS are you using and mono version?

**Comment by dancii** [comment] 2018-12-17 19:09
> for those having the problem.. do you use ombi?

I don't, why?

**Comment by JReming85** [comment] 2018-12-17 19:52
@dancii I no longer have this issue yet I dont remember what I did to resolve it.

Few of the things that I did do was ended up offloading a few of my servers to the cloud (couchpotato -> VPS Radarr, Transmission -> VPS ruTorrent, TVheadend -> VPS) and feel that may have helped a bit (at least with lowering my RAM usage.

I have read about people also having this issue while using transmission, although I rarely used torrents and 99% of my downloads were from usenet transmission might have been the cause.

**Comment by Mange** [comment] 2019-01-01 22:16
> are you using bazarr with sonarr ?

I am.

**Comment by thezoggy** [comment] 2019-01-02 01:00
Taloth was able to track this down to how the sqlite cache was initialized and fixed in latest. Please update to latest and confirm.

**Comment by Taloth** [comment] 2019-01-02 17:52
There are still other issues, that's why I haven't commented yet.

**Comment by Taloth** [comment] 2019-01-10 19:31
Ok guys, lemme know if there are any remaining leaks as of 2.0.0.5296

**Comment by d1slact0r** [comment] 2019-01-18 23:43
Please see this as ref too: 
https://github.com/Radarr/Radarr/issues/1580#issuecomment-455721931

**Comment by dancii** [comment] 2019-01-19 14:12
@thezoggy I don't use Bazarr, but have a plan to implement it actually.

BUT!

Trying not to jinx it here, but, I've updated my jail where sonarr is installed (mono was one of those packages that was updated). It seems to have fixed the issue. I will report back in a day or two to be sure. It seems promising since I could not have sonarr running more than 30 minutes before eating several GBs of ram. Everybody running Sonarr in a jail, update update the packages and restart the jail. That may fix your issue.

**Comment by JReming85** [comment] 2019-01-19 16:39
@dancii if it starts acting up again, you need to downgrade the sqlite pkg and lock it so it wont update

**Comment by dancii** [comment] 2019-01-20 00:50
@JReming85 It started acting up again (just not as fast). I checked the logs which spewed out hundreds of rows per minute of errors regarding import and not being able to find some files. I cleaned up the download dir (removed empty dirs, sample files etc), cleared the sonarr logs and now the memory leakage has stopped. I guess that this problem will come up again if I don't clean my download dir regularly. Do you think that a lock on a specific sqlite version will make it stop or does this have to do with the implementation of saving logs in the db? I've checked out the PRs that have been mentioned in this issue and some of them seems to tackle the implementation of it.

**Comment by JReming85** [comment] 2019-01-20 01:12
The sqlite downgrade & lock resolved the above issues on my install.  I got the idea from Radarr's guide

https://github.com/Radarr/Radarr/wiki/Installation#manually-update-radarr-from-within-jail
# workaround for sqlite "fdatasync" error that occurs on recent versions (> 3.18?) of sqlite3 

It cleared more then the fdatasync for me atleast so I would give it a try since Sonarr/Radarr are pretty much the same thing just sort of reskinned.

**Comment by dancii** [comment] 2019-01-20 16:32
It was not enabled. I've enabled it now, hopefully this fixes the issue. Thanks for the suggestion!

**Comment by bakerboy448** [comment] 2020-11-18 01:42
This bug/issue seems stale.  Please check and see if it is still an issue on the recent v3 builds.  If it is an issue please open a new GHI with logs and full detail.

**Closed by bakerboy448** 2020-11-18 01:42 UTC
Labels: bug, mono-bug
