### ISSUE TITLE
Ability to sort/rearrange Custom Filters 

### ISSUE THREAD

**Issue by pcxdrone** [Sonarr/Sonarr#6334] opened 2024-01-11 16:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When adding a custom filter, the new filter is always placed at the bottom of the list of available Custom Filters.

### Describe the solution you'd like

Adding the ability to rearrage/sort the Custom Filters list so that similar filters can be grouped together and so newly added filters don't appear at bottom of list by default.

### Describe alternatives you've considered

If changing the order of the Custom Filters isn't feasible, sorting them alphabetically by default could be helpful as the user could group like filters by name.

**Comment by markus101** [comment] 2024-01-11 16:44
This was mentioned on discord to you before you opened the issue, but you should always search before opening new issues. Dupe of https://github.com/Sonarr/Sonarr/issues/5905

**Comment by markus101** [comment] 2024-01-11 16:50
Ordering them alphabetically would make sense, but custom sort is taking it too far.

**Closed** 2024-01-16 05:53 UTC
Labels: enhancement, up-for-grabs
