### ISSUE TITLE
Not sure proper name.

### ISSUE THREAD

**Issue by hexed** [Sonarr/Sonarr#3420] opened 2019-11-24 04:56 UTC
implement a selection like order of operations. So have it check index 1 before checking index 2
But force index 1 if no content that matches check index 2

**Comment by markus101** [comment] 2019-11-24 05:04
No plans to check one before another, but prefer results from one over the other. Duplicate of https://github.com/Sonarr/Sonarr/issues/320

**Closed by markus101** 2019-11-24 05:04 UTC
