### ISSUE TITLE
MySQL Option for k8 users!

### ISSUE THREAD

**Issue by darkcloud784** [Sonarr/Sonarr#4373] opened 2021-03-11 16:42 UTC
**Is your feature request related to a problem? Please describe.**
Yes, lots of bug reports have been opened for the sqlite database being locked due to sqlite not liking external storage/network storage.

**Describe the solution you'd like**
Implement a mysql external db option, I know this has been rejected before but it would REALLY REALLY be beneficial for the k8s community as well as others to be able to not have to worry about sqlite db corruption.

**Describe alternatives you've considered**
force local storage - issue is that those like me that run multi-node k8 cluster this is obviously not an option.
improve external storage speeds - The issue here is not the speed but the iops. I as well as many others can't spend $923740297492347 on NVME drives for my nas.
find some way to rsync the db between nodes - problem with this is that it still poses a problem with db corruption while copying the db between nodes.

**Additional context**
I completely understand that this has been rejected multiple times before but I really think it would be a benefit for not only myself  but the growing population of homelabers that use k8s as their container orchestration. This should also cut down on the bug reports for db corruption issues as well as the issues seen with the db being locked.

**Comment by bakerboy448** [comment] 2021-03-11 16:44
Duplicate of #1669
Duplicate of #4372 

Please use the search function and do not post duplicates.
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for questions.

**Closed by bakerboy448** 2021-03-11 16:44 UTC

**Comment by acjohnson** [comment] 2021-04-27 17:04
mysql and postgres support would be awesome in the Servarr apps. Thanks for these great tools, keep up the good work!
