### ISSUE TITLE
Skyhook | Failed to load search results.

### ISSUE THREAD

**Issue by blurb2m** [Sonarr/Sonarr#3412] opened 2019-11-19 17:25 UTC
**Describe the bug**
Unable to search for some shows. Searching for "breaking" will return results, but searching for "thunder" returns: "Failed to load search results, please try again.
Search for 'thunder' failed. Invalid response received from SkyHook."

**Screenshots**

**Logs**
Link to debug or trace log files.
https://pastebin.com/iGszTmRu

**System Information**

 - Sonarr Version: 3.0.3.655
 - Operating System: unRAID - Docker container
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
Version
3.0.3.655
Package Version
3.0.3.655-ls150 by linuxserver.io
Mono Version
5.20.1.34
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment] 2019-11-19 17:27
Dupe of https://github.com/Sonarr/Sonarr/issues/3410

**Closed by markus101** 2019-11-19 17:27 UTC
