### ISSUE TITLE
Preferred words were used to match individual files

### ISSUE THREAD

**Issue by yegle** [Sonarr/Sonarr#5295] opened 2022-12-13 03:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a preferred word `/\bS\d+E\d+(E\d+)?\b/i` with a `-1000` score. The intention is that if there's a season pack and an individual episodes, always prefer the season pack.

This works fine when downloading a TV show for the first time: assuming there's a season pack containing the following files:

```
Foo.S01.GRP/Foo.S01E01.GRP.mkv
Foo.S01.GRP/Foo.S01E02.GRP.mkv
```
Downloading this torrent is preferred because the preferred words are used to match `Foo.S01.GRP` and will not get a negative score.

But the next time Sonarr find a new release, say a torrent file with the same quality by a different group:

```
Foo.S01.GRP-new/Foo.S01E01.GRP-new.mkv
Foo.S01.GRP-new/Foo.S01E01.GRP-new.mkv
```

Sonarr's current logic is:
- Check the existing _file_ `Foo.S01E01.GRP.mkv`, get a score of `-1000`.
- Check the new _torrent name_ `Foo.S01.GRP-new`, get a score of `0`.
- Download the new torrent since it has a higher score.

So in the end, as long as I have the specific preferred word set to negative value, Sonarr would repeatedly "upgrade" to newer releases.

### Expected Behavior

I think this logic will make more sense:

- Check the existing _file_ `Foo.S01E01.GRP.mkv`, recall this file is from a torrent with name `Foo.S01.GRP`, get a score of `0`.
- Check the new _torrent name_ `Foo.S01.GRP-new`, get a score of `0`.
- Do not download since they have the same score and in the same quality group.

### Steps To Reproduce

1. Add `/\bS\d+E\d+(E\d+)?\b/i` preferred word with a negative score.
2. Wait until the same TV show has a newer release in the same quality group.

### Environment

```markdown
- OS: Linux
- Sonarr: 3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome Android
```

### What branch are you running?

Main

### Trace Logs?

Oops, I forgot to enable the trace level, but the debug level logs already demonstrate the issue.

```
2022-12-13 02:27:21.6|Debug|DownloadDecisionMaker|Processing release '13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb' from 'FileList (Prowlarr)'
2022-12-13 02:27:21.6|Debug|Parser|Parsing string '13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb'
2022-12-13 02:27:21.6|Debug|Parser|Episode Parsed. 13 Reasons Why - Season 04 
2022-12-13 02:27:21.6|Debug|Parser|Language parsed: English
2022-12-13 02:27:21.6|Debug|QualityParser|Trying to parse quality for 13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb
2022-12-13 02:27:21.6|Debug|Parser|Quality parsed: WEBRip-1080p v1
2022-12-13 02:27:21.6|Debug|Parser|Release Group parsed: NTb
2022-12-13 02:27:21.6|Debug|AcceptableSizeSpecification|Beginning size check for: 13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb
2022-12-13 02:27:21.6|Debug|AcceptableSizeSpecification|Item: 13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb, meets size constraints
2022-12-13 02:27:21.6|Debug|AlreadyImportedSpecification|Performing already imported check on report
2022-12-13 02:27:21.6|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.6|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.7|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|CutoffSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|FullSeasonSpecification|Checking if all episodes in full season release have aired. 13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb
2022-12-13 02:27:21.8|Debug|LanguageSpecification|Checking if report meets language requirements. English
2022-12-13 02:27:21.8|Debug|MaximumSizeSpecification|Maximum size is not set.
2022-12-13 02:27:21.8|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2022-12-13 02:27:21.8|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBRip-1080p v1
2022-12-13 02:27:21.8|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: 13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb
2022-12-13 02:27:21.8|Debug|ReleaseRestrictionsSpecification|[13.Reasons.Why.S04.1080p.NF.WEBRip.DDP5.1.x264-NTb] No restrictions apply, allowing
2022-12-13 02:27:21.8|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.8|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradeAllowedSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:21.9|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:21.9|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:22.0|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:22.0|Debug|UpgradeDiskSpecification|Comparing file quality and language with report. Existing file is WEBDL-1080p v1 - English
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|Comparing preferred word score. Current: -1000 New: 0
2022-12-13 02:27:22.0|Debug|UpgradableSpecification|New item has a better preferred word score
2022-12-13 02:27:22.0|Debug|SceneMappingSpecification|No applicable scene mapping, skipping.
2022-12-13 02:27:22.0|Debug|SeriesSpecification|Checking if series matches searched series
2022-12-13 02:27:22.0|Debug|DelaySpecification|QualityProfile does not require a waiting period before download for Torrent.
2022-12-13 02:27:22.0|Debug|HistorySpecification|Skipping history check during search
2022-12-13 02:27:22.0|Debug|DeletedEpisodeFileSpecification|Skipping deleted episodefile check during search
2022-12-13 02:27:22.0|Debug|DownloadDecisionMaker|Release accepted
```

**Comment by markus101** [comment] 2022-12-13 03:29
This is a dupe of https://github.com/Sonarr/Sonarr/issues/3562

**Closed by markus101** 2022-12-13 03:29 UTC
Labels: needs-triage

**Comment by yegle** [comment] 2022-12-13 03:38
Hmm, are they the same issue? I feel like this is a separate bug, in that: we check the torrent folder name against the preferred words when **downloading**, but check the on-disk filename against the preferred words when **refreshing**.

The fact that the preferred word I used happens to be used to prefer a season pack, which is the only connection between this and #3562.

**Comment by markus101** [comment] 2022-12-13 04:25
Yeah, it's not exactly the same, so perhaps dupe was a bad choice, but you're seeing the result of trying to fix that issue, but they're so intertwined that both need to be resolved at the same time.

**Comment by yegle** [comment] 2022-12-13 04:50
Fair enough, yes I can see that the current implementation of preferred words needs rework to solve both bugs.
