### ISSUE TITLE
Option to specify when a 2nd part of a season started

### ISSUE THREAD

**Issue by zp33dy** [Sonarr/Sonarr#7205] opened 2024-09-13 18:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Example title:
```
[Erai-raws] NieR-Automata Ver1_1a Part 2 - 10 [1080p][Multiple Subtitle] [ENG][POR-BR][SPA-LA][SPA][ARA][FRE][GER][ITA][RUS]
```
This is S01 E22 of the Anime "NieR-Automata Ver1.1a", but sonarr currently doesn't find it. The 13–24 Episodes are released 1 year later, hence the Part 2. This is generally often done.

### Describe the solution you'd like

A settings menu for anime, where for example the beginning episode of a second corse could be specified. So in this case, it would be E13. Goal is, that sonarr then also searches for <Anime> Part 2 <Episode - 2nd corse start> as well as <Anime> <Episode>

### Describe alternatives you've considered

The only really alternative currently is adding it manually.

**Comment by thezoggy** [comment] 2024-09-13 18:13
dupe of asked before, sonarr does not do partial seasons... crudely to fix something like this we could use xem to deal with `NieR-Automata Ver1_1a Part 2` being viewed as a season alias.. but the issue is that not ever group did this. and xem is already setup for groups that didnt reset abs for this new season or those that just use standard numbering. so in the end just dont use this groups release but instead someone like SubsPlease or anyone else that released it as expected.

**Comment by stevietv** [comment] 2024-09-13 18:17
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Closed by stevietv** 2024-09-13 18:17 UTC
Labels: needs-triage
