### ISSUE TITLE
TVDB source options

### ISSUE THREAD

**Issue by celnan** [Sonarr/Sonarr#6289] opened 2024-01-02 13:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've added some web series available only in italian.

The titles in Sonarr are all "TBA".

### Describe the solution you'd like

It would be useful to have the possibility to choose the language of the series, so that sonarr can download the correct information.

### Describe alternatives you've considered

Alternatively, I think that if there is no informations in English, Sonarr should retrieve those in the original language of the series.

**Comment by stevietv** [comment] 2024-01-02 13:12
This is a dupe of #269

**Closed by stevietv** 2024-01-02 13:12 UTC
Labels: needs-triage
