### ISSUE TITLE
Feature Request: Preferred tags/release groups/codecs

### ISSUE THREAD

**Issue by matmuilwijk** [Sonarr/Sonarr#2256] opened 2017-10-30 09:16 UTC
## Feature Request

It would be amazing if we'd be able to set preferred tags, next to the current restrictions.

Right now, we can only use the restrictions with must contain, and may not contain, and this is a bit limiting. 

I know this was discussed before, but there was no clear answer to why this wouldnt be possible.

Example:

Must contain: -

Must not contain: xvid, x265, h265

Preferred: EZTV, H264, X264

**Comment by M0UL** [comment] 2017-10-30 10:22
duplicate of #385

**Closed** 2017-10-30 13:32 UTC
