### ISSUE TITLE
Quality Profile Groups

### ISSUE THREAD

**Issue by soulvoid86** [Sonarr/Sonarr#2211] opened 2017-10-05 17:33 UTC
The ability to group Qualities together, so Sonarr/Radarr isn't double or triple downloading new, but unnecessary releases.

Example:
I download an episode at HDTV720, but a WEBDL720 release is found. I'm not concerned enough about the very slight quality difference I might get, to waste storage space or download credit on my tracker to worry about that second release. I'd rather wait until a 1080 release is available to redownload that episode. But at the same time, I want to allow all three 720 options because I don't want to miss a release if it's not available in a higher quality just yet.

Basically, add the option to simplify quality down to just 720, 1080, 2k, for those who would like it. The system is great as it is, just would be nice to have both options.

Screenshots: https://imgur.com/PVq6kGc

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment] 2017-10-05 18:19
Dupe of https://github.com/Sonarr/Sonarr/issues/1781

**Closed by markus101** 2017-10-05 18:19 UTC
