### ISSUE TITLE
When grabbing entire seasons, push notifications kill phones. Please delay and merge.

### ISSUE THREAD

**Issue by flying-sausages** [Sonarr/Sonarr#2534] opened 2018-04-29 11:40 UTC
So this happens every time I add a season pack:
https://streamable.com/n4cag

Some push platforms want you to pay when you push more, so I'd be surprised if that didn't previously become an issue.

To decrease usage and annoyance for users, please delaying notifications for the same season a little and then push them together as one "20 episodes were grabbed from $show season $nr" notification.

**Comment by markus101** [comment] 2018-04-29 18:01
Dupe of https://github.com/Sonarr/Sonarr/issues/363

**Closed by markus101** 2018-04-29 18:01 UTC
