### ISSUE TITLE
Offical Slack intergration to Sonarr

### ISSUE THREAD

**Issue by sconnery** [Sonarr/Sonarr#1110] opened 2016-01-30 13:49 UTC
I would like Sonarr have a correct intergration with slack notifications like with couch potato when there is a movie completed I get a notification on Slack with the imdb link , That would be perfect for sonar as well . I am far from a DEV but I think this is a great idea as I have tried to guides online for a connect "fix" but has not worked at all! I am happy to donate financially to the cause as well!

**Comment by markus101** [comment] 2016-01-30 18:01
Dupe of: https://github.com/Sonarr/Sonarr/issues/1002

We don't do features based on donations.

**Closed by markus101** 2016-01-30 18:01 UTC
