### ISSUE TITLE
Feature: Free text / Keyword - Manual search

### ISSUE THREAD

**Issue by Centril** [Sonarr/Sonarr#1736] opened 2017-03-05 08:18 UTC
## The Problem
Let's assume that, at the episodes view for a specific season, the **`Manual search`** button was pressed and **no results were found.**

In this case, one could:
1. [Request a new mapping](https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x)
2. Add the torrent (assuming torrent client) to the client manually and label it under the label used by sonarr...

The first solution helps the community but takes time...
The second takes one away from sonarr and into the torrent client ui, which one preferably shouldn't have open. Then one has to go to the trackers website and find the torrent file, download it, give it to the torrent client, and then label it.

## A better solution
When the `Manual search` button yields no results, then, instead of saying `No results found`, it says: "No results found. Try a free text search?". Below that text, there is a text field which one can use to input the free text search terms. On pressing enter, the query is sent to the relevant indexers and returned formatted as a normal manual search would be formatted.

**Comment by markus101** [comment] 2017-03-06 02:57
Dupe of https://github.com/Sonarr/Sonarr/issues/1128

**Closed by markus101** 2017-03-06 02:57 UTC
