### ISSUE TITLE
Blacklisted data in Show or Episode Title

### ISSUE THREAD

**Issue by kfulgham** [Sonarr/Sonarr#1290] opened 2016-05-10 17:39 UTC
I've had some issues where episodes were not downloaded because there is a rule to ignore a release because a blacklisted word is listed in the episode name. Unfortunately any release that includes the episode name becomes blacklisted because a blacklisted word is included in the episode name.

Example:
![image](https://cloud.githubusercontent.com/assets/15936373/15156201/32bfee14-16a3-11e6-9a33-93664fb2eca7.png)

Can the engine that determines to download an episode be modified so that if a blacklisted word is included in the episode name then that word is whitelisted just for that episode?

Example in the above case:

1. Scan Episode information and determine that "greek" occurs in the episode title.
2. Search the indexers for what is available.
3. Modify the blacklist to exclude any releases per normal unless it only contains the word "greek".

**Comment by markus101** [comment] 2016-05-10 18:22
Duplicate of https://github.com/Sonarr/Sonarr/issues/861

**Closed by markus101** 2016-05-10 18:22 UTC
