### ISSUE TITLE
Send one notification per download

### ISSUE THREAD

**Issue by drkdragonarcher** [Sonarr/Sonarr#2747] opened 2018-09-25 13:55 UTC
When downloading season packs, it doesn't import each episode as the episode has finished but imports the whole season once it's done. It would make more sense to send one message instead of a message for each episode that was in the pack. For reference, I've got mine set up using Telegram to alert on download and upgrade to send a message to a group chat.

Not sure what he best way to fix this is. When looking at the activity it shows the individual episodes too so maybe it's not reading that it's one torrent? I'm not really familiar with the backend.

**Comment by markus101** [comment] 2018-09-25 15:48
Dupe of https://github.com/Sonarr/Sonarr/issues/363

**Closed by markus101** 2018-09-25 15:48 UTC
