### ISSUE TITLE
Manual Import Stops Scrolling

### ISSUE THREAD

**Issue by wcomartin** [Sonarr/Sonarr#1226] opened 2016-04-07 11:58 UTC
if you open the Manual Import Dialog, then open a Episode Select Dialog (that has enough content to scroll), once closed the Manual Import Dialog will no longer scroll instead the page behind scrolls.

**Comment by markus101** [comment] 2016-04-07 18:10
Dupe of https://github.com/Sonarr/Sonarr/issues/745

**Closed by markus101** 2016-04-07 18:10 UTC
