### ISSUE TITLE
Incorrect release date for the series Shrinking

### ISSUE THREAD

**Issue by mryx007** [Sonarr/Sonarr#7301] opened 2024-10-16 11:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I noticed that the date for the Shrinking series is shifted by one day. 

### Expected Behavior

![Screenshot 2024-10-16 132509](https://github.com/user-attachments/assets/825399e1-1205-4822-99b3-8257d966b4c3)
![Screenshot 2024-10-16 132547](https://github.com/user-attachments/assets/c85ed4e4-1559-4746-9fd9-865a8030964d)
![Screenshot 2024-10-16 132639](https://github.com/user-attachments/assets/866584b0-f153-467a-a732-74a62d117eb1)

### Environment

```markdown
- OS: Windows 11
- Sonarr: 
- Browser: Edge
```

### What branch are you running?

Main

### Trace Logs?

no

**Comment by thezoggy** [comment] 2024-10-16 19:30
there is no timezones on tvdb with its data. so when it says it airs on "tuesday at 930pm" for the series that doesnt really tell ya much...  sonarr takes that time and makes assumption based on network what that will be to get the time in utc, so per skyhook it is 1:30am on the 17th
![firefox_2024-10-16_14-28-19](https://github.com/user-attachments/assets/4b93df85-1833-4bb5-89e9-e66f28a6eacf)

then your sonarr instance applies your local os timezone to offset that to be 3:30am

now what timezone is 'correct' for shows like netflix/apple+/etc where are globally accessed and not like a typical broadcaster that only air in x market at x time. is the dilemma you are seeing what is being done. this is to be expected as you cant make it 100% perfect for everyone

**Comment by mryx007** [comment] 2024-10-16 19:44
ah ok I see. and you can't adjust it manually?

**Comment by thezoggy** [comment] 2024-10-16 21:25
> ah ok I see. and you can't adjust it manually?

the series info? i mean you could change the data on tvdb but that would impact everyone.  but youd have to see if the data on tvdb needs to be changed or not.. and run the wrath of making others made if you change it incorrectly.

**Comment by markus101** [comment] 2024-10-22 20:55
Closing as this is not a bug, but how things are displayed if you're ahead of the originating timezone.

**Closed by markus101** 2024-10-22 20:55 UTC
Labels: needs-triage
