### ISSUE TITLE
Add Preferred Download Client for Indexers

### ISSUE THREAD

**Issue by jpaige5408** [Sonarr/Sonarr#3734] opened 2020-05-04 19:16 UTC
As it relates to torrents, currently there is no way to prefer a specific download client based on the indexer in use. More specifically, it would be nice to be able to send torrents pulled from a private indexer specifically up to my seedbox, while all the public indexers can be sent to my local torrent client. 

i'd propose adding a dialog box with a drop down arrow of available clients in each indexer's settings page, to override default client priorities.

On behalf of everyone out there spending money on seedboxes, please help us ration our traffic and storage by including this option. thanks!

**Comment by markus101** [comment] 2020-05-04 20:20
Dupe of https://github.com/Sonarr/Sonarr/issues/1215

**Closed by markus101** 2020-05-04 20:20 UTC
