### ISSUE TITLE
Add Romanian as a language option

### ISSUE THREAD

**Issue by barrelltitor** [Sonarr/Sonarr#5494] opened 2023-03-17 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I want to have versions for certain Series in Romanian

### Describe the solution you'd like

A Romanian option for languages

### Describe alternatives you've considered

The ability to add custom language options

**Comment by markus101** [comment] 2023-03-17 19:25
We need example release names (and file names if they are different) in order to do this.

**Comment by markus101** [comment] 2023-03-23 00:06
If that's the case then it's a duplicate of https://github.com/Sonarr/Sonarr/issues/269

Closing, but will reopen if @barrelltitor can confirm what they are looking for and can provide a variety of examples.

**Closed by markus101** 2023-03-23 00:06 UTC
Labels: waiting-for-info, needs-triage
