### ISSUE TITLE
Sonarr detect Multi as english but is french (YggTorrent)

### ISSUE THREAD

**Issue by devIlluSioN** [Sonarr/Sonarr#3100] opened 2019-05-06 09:47 UTC
**Describe the bug**
Sonarr detects that the episode is in English while it is in French.

**Screenshots**
<img width="1001" alt="Capture d’écran 2019-05-06 à 11 32 36" src="https://user-images.githubusercontent.com/35778025/57217657-845e0100-6ff3-11e9-8ff5-2865ada6832c.png">

<img width="1068" alt="Capture d’écran 2019-05-06 à 11 32 47" src="https://user-images.githubusercontent.com/35778025/57217655-83c56a80-6ff3-11e9-8e22-3f1e715693fb.png">

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: W7
 - Jackett : 0.11.279.0

**Comment by markus101** [comment] 2019-05-06 11:42
Please search before opening a new issue... dupe of https://github.com/Sonarr/Sonarr/issues/2854

**Closed by markus101** 2019-05-06 11:42 UTC
