### ISSUE TITLE
Moving 'The' to the end of a showname in rename function

### ISSUE THREAD

**Issue by Mandosm** [Sonarr/Sonarr#1481] opened 2016-09-30 07:18 UTC
Would it be possible to add support for moving "The" to the end of shownames? 

So 'The 100' would be renamed as '100, The' for example. 

With large collections having a huge number of shows collect under T can make it hard to find the files you are looking for and manually cleaning the episodes up is fairly time consuming.

**Comment by markus101** [comment] 2016-09-30 07:45
Duplicate of: https://github.com/Sonarr/Sonarr/issues/371

In the meantime For series you can update the folder name outside of Sonarr and then update the path by editing the series in Sonarr. It won't work for newly added shows, but it should get you by until it's added.

**Closed by markus101** 2016-09-30 07:45 UTC
