### ISSUE TITLE
Episode placed in wrong season

### ISSUE THREAD

**Issue by cjmanca** [Sonarr/Sonarr#4722] opened 2021-10-28 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Show: Demon Slayer
I checked thexem and don't see anything there that would cause this.

S02E03 was placed into S03E03 for some reason, however it even knew it was season 2, and renamed it S02E03, which is extra strange. 
![image](https://user-images.githubusercontent.com/6020593/139325385-8615c9ca-1215-49b5-b878-14e57d879740.png)
![image](https://user-images.githubusercontent.com/6020593/139325446-ff233532-08ef-4850-ae51-506fb8ddda76.png)

### Expected Behavior

I'd expect it to place the episode in the right season

### Environment

```markdown
- OS: Windows 10 x64
- Sonarr: 3.0.6.1342
- Docker Install:
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Anything else?

I searched in the log files and don't see anything related to importing of episodes. I would probably have needed debug/trace logging on, and I don't know that I'd be able to replicate the issue after turning these on.

**Comment by Gamertech** [comment] 2021-10-31 14:27
Someone was playing around with the TVDB database earlier and kept moving the new eps between S2, 3 & Specials. Seems like they've calmed down on that though.

That'd likely be why Sonarr was confused. Now that the db's stopped changing and Sonarr's updated, it wont move the ep again.

**Comment by markus101** [comment] 2021-11-02 03:24
This would be caused by the absolute episode number moving to a new season, which looks like happened after the original import.

**Closed by markus101** 2021-11-02 03:24 UTC
Labels: waiting-for-info, needs-triage
