### ISSUE TITLE
Exclude from name

### ISSUE THREAD

**Issue by mikeywaldron** [Sonarr/Sonarr#3777] opened 2020-05-26 20:55 UTC
Hello there would it be possible to add a exclude characters when renaming e.g . , !"£ 
i've specifically noticed on agents of S.H.I.E.L.D  would be nice to be able to make it just agents of shield if possible i've tried cleantitle etc... and cant seem to get it to work. Even if we could change it to an alternative title as agents of shield is in there. 
Thanks guys

**Comment by markus101** [comment] 2020-05-26 21:56
Dupe of https://github.com/Sonarr/Sonarr/issues/2028

No plans to support renaming to an alias.

**Closed by markus101** 2020-05-26 21:56 UTC
