### ISSUE TITLE
Add "Device" option for Pushover connection

### ISSUE THREAD

**Issue by ceptonit** [Sonarr/Sonarr#2707] opened 2018-08-14 07:04 UTC
## Feature Request
Add the "Device" option for Pushover connections

### What problem are you looking to solve?
If you have multiple devices on your Pushover account, using the "Device" option lets us choose on which device(s) we'd like to receive the Sonarr notifications.
Without this option, all the devices will receive the notifications.

### Other Information
Pushover has the device API option already set up.
To push a notification, Pushover API requires token, user, title and message; device is optional, but if specified, the specified device(s) only, will get the notifications.
[https://pushover.net/api#messages](https://pushover.net/api#messages)

So maybe add an extra field under the "User Key" field named "Device(s) (optional)" for Pushover connections?

**Comment by markus101** [comment] 2018-08-14 07:08
Dupe of https://github.com/Sonarr/Sonarr/issues/1171

**Closed by markus101** 2018-08-14 07:08 UTC
