### ISSUE TITLE
Allow selection of download client to be used, on a per-show basis

### ISSUE THREAD

**Issue by Ron3011** [Sonarr/Sonarr#3644] opened 2020-03-25 07:56 UTC
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### What problem are you looking to solve?
Using Sonarr with multiple directories
### Other Information
I currently have 2 hard drives with shows on both, but having my download client move the right show to the right directory is not straightforward. Instead, I've set up the same download client in sonarr twice, using a different category for each. I've then setup different directories in the download client settings, for each category. This requires that I only enable the download client that I want to use for each specific show, but is a manual process and will break down if I'm not manually monitoring and starting the download. By allowing me to pick which download client I would like to use for each specific show added, it can be categorised correctly, and the client can handle the rest.

**Comment by markus101** [comment] 2020-03-25 15:03
Dupe of https://github.com/Sonarr/Sonarr/issues/402

**Closed by markus101** 2020-03-25 15:03 UTC

**Comment by m-lant** [comment] 2020-03-26 09:29
> having my download client move the right show to the right directory
Why have your download client do this? Use sonarr's capabilities to pick up and sort the series into the folders you want...

**Comment by Ron3011** [comment] 2020-03-26 09:51
> Why have your download client do this? Use sonarr's capabilities to pick up and sort the series into the folders you want...

That works perfectly. Thanks!
