### ISSUE TITLE
suggestion on how to improve the search in other languages

### ISSUE THREAD

**Issue by jadsongmatos** [Sonarr/Sonarr#5391] opened 2023-01-22 02:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

search function is not very efficient for searching in other language like portuguese

### Describe the solution you'd like

use default language title instead of using original title

### Describe alternatives you've considered

"

**Comment by PearsonFlyer** [comment] 2023-01-22 02:21
Dupe of #269 https://github.com/Sonarr/Sonarr/issues/269

**Comment by markus101** [comment] 2023-01-22 03:46
For other languages an alias is going to be required, even using other language's title won't guarantee a match because there are conflicts between series names .

**Closed by markus101** 2023-01-22 03:46 UTC
Labels: needs-triage

**Comment by jadsongmatos** [comment] 2023-01-22 03:57
> For other languages an alias is going to be required, even using other language's title won't guarantee a match because there are conflicts between series names .

there will always be conflicts

**Comment by jadsongmatos** [comment] 2023-01-22 04:06
on IMDB on the releaseinfo page there is a table called Also Known As (AKA) which has a list of names in different languages

https://www.imdb.com/title/tt0460681/releaseinfo?ref_=tt_dt_aka#akas

**Comment by Thirrian** [comment] 2023-01-22 05:56
sonarr doesn't use imdb for metadata.

**Comment by jadsongmatos** [comment] 2023-01-25 01:35
Radarr has a list as the movie name in each language
