### ISSUE TITLE
Please add multi-language support in Profiles (eg.: ENG-HUN)

### ISSUE THREAD

**Issue by gurabli** [Sonarr/Sonarr#730] opened 2015-08-06 06:45 UTC
As most of the tv shows are released with dual language dub, it would be great to have this option to select two languages under profile.
Most commonly English and the local language. Many of the multi-language people are missing this feature.
Thanks!

**Comment by markus101** [comment] 2015-08-06 07:25
Please search first, this is a duplicate of: https://github.com/Sonarr/Sonarr/issues/274

**Closed by markus101** 2015-08-06 07:25 UTC
