### ISSUE TITLE
Play button?

### ISSUE THREAD

**Issue by dmzoneill** [Sonarr/Sonarr#5058] opened 2022-06-15 10:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Am i missing something or is there no 'play button' on radarr/sonarr/lidarr ?
For local usage, it would be nice to open a player for the given media file.
I resorted to writing a crude plugin for chrome that adds vlc icon to the media files.
it actually uses xdg-open, so the player associated with the file type opens.
https://github.com/dmzoneill/sodarr-chrome-plugin

### Describe the solution you'd like

I would like to see this as a built in feature.

### Describe alternatives you've considered

https://github.com/dmzoneill/sodarr-chrome-plugin

### Anything else?

nope

**Comment by bakerboy448** [comment] 2022-06-15 13:07
Duplicate of #2253

Won't ever be added.

**Comment by markus101** [comment] 2022-06-15 15:47
There are a lot of pieces that need to align for this to be possible for any given user, it's not something we're going to do, we'll leave this to the tools that already handle it well.

**Closed by markus101** 2022-06-15 15:47 UTC
Labels: needs-triage
