### ISSUE TITLE
Language should not be detected from the episode title

### ISSUE THREAD

**Issue by glitch452** [Sonarr/Sonarr#5397] opened 2023-01-29 22:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The language detection for a file is currently picking up the wrong language when the title of an episode has a language in it. 

Here are a couple examples:
![image](https://user-images.githubusercontent.com/894128/215359151-2cf81fe4-82c5-4941-81d6-5afe43b8fd66.png)
![image](https://user-images.githubusercontent.com/894128/215359196-f4e9f2e2-62f4-47a3-bb81-8168e5f2a21d.png)

### Expected Behavior

The language detection should use the language names in episode titles to determine the language of a file. 

### Steps To Reproduce

Import an episode with a language (I.e `french` or `Italian`) in the title.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 3.0.9.1549-ls173 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome Version 109.0.5414.119 (Official Build) (x86_64)
- Language Profiles: English (default setup from fresh install)
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

See screenshots in 'current behaviour' section.

**Comment by markus101** [comment] 2023-01-29 22:40
Dupe of https://github.com/Sonarr/Sonarr/issues/861

**Closed by markus101** 2023-01-29 22:40 UTC
Labels: needs-triage
