### ISSUE TITLE
VOSTFR is considered english

### ISSUE THREAD

**Issue by moi15moi** [Sonarr/Sonarr#4763] opened 2021-11-26 22:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a release is name like that: `TITLE - EPISODE_NUMBER VOSTFR 1080p WEB x264 -TAG`, it should be considered like a french release.

VOSTFR means: Version Originale Sous-titrée en Français so Original Version Subtitled in French.

### Expected Behavior

It is considered like a english release.

### Steps To Reproduce

Example
1. Add Nyaa indexers
2. Add Meikyuu Black Company anime series
3. Manually search for the episode 1
4. NanDesuka release will be listed, but it will be listed like a english release

### Environment

```markdown
- OS: Synology
- Sonarr:3.0.6.1342
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

I am not sure if you need one, but if yes, simply warn me.

### Anything else?

![image](https://user-images.githubusercontent.com/80980684/143659403-4704d4bf-4031-4761-b09c-16baf9cfcce1.png)

**Comment by bakerboy448** [comment] 2021-11-26 22:47
duplicate of https://github.com/Sonarr/Sonarr/issues/3977

VOSTFR does not indicate audio.

**Closed by bakerboy448** 2021-11-26 22:47 UTC
Labels: needs-triage
