### ISSUE TITLE
Support for non-english metadata

### ISSUE THREAD

**Issue by kikonou** [Sonarr/Sonarr#2688] opened 2018-07-27 17:52 UTC
**Describe the problem**
Some series don't have English metadata on TheTVDB and is imposible to find it

**Describe any solutions you think might work**
Sonarr needs to support getting metadata in other languages

**Comment by markus101** [comment] 2018-07-27 17:55
You're kidding right? You commented on an issue that was closed as a duplicate of another issue (#269).

No there isn't an update, #269 will be updated when there is an update.

**Closed by markus101** 2018-07-27 17:55 UTC
