### ISSUE TITLE
Sonarr V3 update fail on QNAP NAS

### ISSUE THREAD

**Issue by theChaosCoder** [Sonarr/Sonarr#4359] opened 2021-03-06 12:43 UTC
**Describe the bug**
Update fails (previous updates worked)

**To Reproduce**
Perform update

**Platform Information (please complete the following information):**
 - OS: qnap linux
 - Docker: no
 - .net Framework : mono 6.8.0.105
 - Sonarr Version: 3.0.4.1083
 - Sonarr Branch: phantom-develop

**Trace Logs**
Trace log does not show any usefull info. The relevant part is here:
```
/share/CACHEDEV1_DATA/.qpkg/Qmono/bin/mono  --debug /share/CACHEDEV1_DATA/.qpkg/QSonarr3/Sonarr/Sonarr.exe /data=/share/CACHEDEV1_DATA/SONARR3_CONFIG
[Info] Bootstrap: Starting Sonarr - /share/CACHEDEV1_DATA/.qpkg/QSonarr3/Sonarr/Sonarr.exe - Version 3.0.4.1083
[Info] AppFolderInfo: Data directory is being overridden to [/share/CACHEDEV1_DATA/SONARR3_CONFIG]
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=/share/CACHEDEV1_DATA/SONARR3_CONFIG/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=/share/CACHEDEV1_DATA/SONARR3_CONFIG/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:8989/
[Info] SonarrBootstrapper: Starting Web Server
[Info] InstallUpdateService: Deleting old update files
[Info] InstallUpdateService: Downloading update 3.0.4.1132
[Info] InstallUpdateService: Verifying update package
[Info] InstallUpdateService: Update package verified successfully
[Info] InstallUpdateService: Extracting Update package
[Info] InstallUpdateService: Update package extracted successfully
[Info] BackupService: Starting Backup
[Info] InstallUpdateService: Preparing client
[Info] InstallUpdateService: Starting update client /opt/tmp/sonarr_update/Sonarr.Update.exe
[Info] InstallUpdateService: Sonarr will restart shortly.
[Error] CommandExecutor: Error occurred while executing task ApplicationUpdate

[v3.0.4.1083] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /opt/tmp/sonarr_update/Sonarr.Update.exe 25098 /opt/tmp/sonarr_update /share/CACHEDEV1_DATA/.qpkg/QSonarr3/Sonarr/Sonarr.exe /data=/share/CACHEDEV1_DATA/SONARR3_CONFIG', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in /SRC/mono-6.8.0.105/mcs/class/System/System.Diagnostics/Process.cs:778
  at System.Diagnostics.Process.Start () [0x0003a] in /SRC/mono-6.8.0.105/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2006
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.Processes.ProcessProvider.Start (System.String path, System.String args, System.Collections.Specialized.StringDictionary environmentVariables, System.Action`1[T] onOutputDataReceived, System.Action`1[T] onErrorDataReceived) [0x00187] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Processes\ProcessProvider.cs:181
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x00258] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:149
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x00013] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:261
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x0011e] in /SRC/mono-6.8.0.105/external/corefx/src/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs:1874
  at (wrapper delegate-invoke) System.Action`4[System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,System.Object,NzbDrone.Core.Messaging.Commands.CommandModel].invoke_void_T1_T2_T3_T4(System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41
```

**Comment by bakerboy448** [comment] 2021-03-06 12:46
Closing pending template being followed;

also, as usual, this is likely not a bug...

Info logs are useless for debugging; trace are required

for updater issues, the update logs are required

https://wiki.servarr.com/Sonarr_Troubleshooting#Logging_and_Log_Files

**Closed by bakerboy448** 2021-03-06 12:46 UTC

**Comment by Taloth** [comment] 2021-03-06 12:56
> [v3.0.4.1083] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /opt/tmp/sonarr_update/Sonarr.Update.exe 25098 /opt/tmp/sonarr_update /share/CACHEDEV1_DATA/.qpkg/QSonarr3/Sonarr/Sonarr.exe /data=/share/CACHEDEV1_DATA/SONARR3_CONFIG', CurrentDirectory='', Native error= Cannot find the specified file

Looks to me like it can't run `mono` (probably not on the path), or `/opt/tmp/sonarr_update/Sonarr.Update.exe` doesn't exist, I'm not sure what error occurs in either situation.
It's possibly qnap specific, so I recommend you check the qnap package maintainer on the qnap community forums.

And yeah, like bakerboy said, support issue.

**Comment by theChaosCoder** [comment] 2021-03-06 13:13
Trace log https://pastebin.com/5zK5EbLg

Can I somehow trigger an update for a different version?

**Comment by Taloth** [comment] 2021-03-06 13:17
It's not a bug in the update package. The trace log shows that Sonarr.Update.exe exists, so it's probably that mono isn't on Path. Please ask for support on the qnap community forums. We do not maintain the QSonarr package.

**Comment by theChaosCoder** [comment] 2021-03-06 13:29
That was the problem. Added mono to PATH and now it works as it should. Thank you very much for the tip.

**Comment by Taloth** [comment] 2021-03-06 13:39
Can you please report that to the QSonarr maintainer (where you got the package from)?

**Comment by theChaosCoder** [comment] 2021-03-06 13:40
I think I need to report it to the Qmono maintainer.

**Comment by Taloth** [comment] 2021-03-06 13:42
Not necessarily so, coz it just needs to be on the PATH in the qsonarr package. But quite possibly it's the same maintainer, so it might not matter whom you contact.
