### ISSUE TITLE
Ability to change to Netflix season/episode listing

### ISSUE THREAD

**Issue by yoobi** [Sonarr/Sonarr#5100] opened 2022-08-03 17:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This issue [#2621](https://github.com/Sonarr/Sonarr/issues/2621) describes well what is needed, as stated in [#3661](https://github.com/Sonarr/Sonarr/issues/3661#issuecomment-634413477)

Good news is that TVDB is now in V4 and according to [this issue on their repo](https://github.com/thetvdb/v4-api/issues/133) this feature has been added in 4.5.0

### Describe the solution you'd like

Pick up what's needed from tvdb API

### Describe alternatives you've considered

NA

### Anything else?

Nope

**Comment by bakerboy448** [comment] 2022-08-03 17:13
Duplicate of the referenced issues....

**Comment by markus101** [comment] 2022-08-03 17:44
Closing as we don't need another issue for this, when we're able to use TVDB v4 and implement the changes required to support alternate orders #255 will be closed, you can follow that issue for updates.

**Closed by markus101** 2022-08-03 17:44 UTC
Labels: needs-triage
