### ISSUE TITLE
[Feature Request] Further customization of notifications

### ISSUE THREAD

**Issue by jtrosper** [Sonarr/Sonarr#2424] opened 2018-02-22 13:11 UTC
Hello,

I use Pushover for notifications from Sonarr.  As you can imagine, this can get quite chatty if the series in question has a lot of episodes.

Could you add a feature that only notifies me if Sonarr has completed grabbing or downloading a complete season or entire show?

**Comment by markus101** [comment] 2018-02-22 16:05
Dupe of https://github.com/Sonarr/Sonarr/issues/1396

**Closed by markus101** 2018-02-22 16:05 UTC
