### ISSUE TITLE
Indexers Unavailable due to failures

### ISSUE THREAD

**Issue by djskycapt** [Sonarr/Sonarr#3070] opened 2019-04-22 21:18 UTC
**Describe the bug**
I am using Sonarr in a docker container in conjunction with Jackett (also in a docker container) on Unraid. My Torznab indexers fail on a daily basis causing me to get three error messages:

All indexers are unavailable due to failures
All rss-capable indexers are temporarily unavailable due to recent indexer errors
All search-capable indexers are temporarily unavailable due to recent indexer errors

I check Jackett and test every indexer that Sonarr uses. All tests successful. I test all indexers within sonarr. All test successful and then the error messages are cleared. This has become a daily routine for me right now. I also am using Radarr in a docker container and pulling indexers from the same Jackett container as Sonarr and never have any issues. Any suggestions?

**Screenshots**
![image](https://user-images.githubusercontent.com/49884431/56531543-3a204e80-6522-11e9-9666-f5550c1a3638.png)

![image](https://user-images.githubusercontent.com/49884431/56531582-4c01f180-6522-11e9-9864-082043d861bf.png)

**Logs**
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/3104904/sonarr.txt)

**System Information**
 - Sonarr Version: 2.0.0.5322
 - Operating System: Unraid 6.6.7
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
I have tried increasing the RSS Sync Interval to 30 minutes instead of the default, but that has had no effect. I have also tried different docker builds of Sonarr and Jackett, neither of those have solved my issue.

If any more information is needed, please let me know how I can help.

**Comment by markus101** [comment] 2019-04-22 22:06
Dupe of #2802

**Closed by markus101** 2019-04-22 22:06 UTC
