### ISSUE TITLE
Add tvdb seasons by id

### ISSUE THREAD

**Issue by rustamzh** [Sonarr/Sonarr#7197] opened 2024-09-09 17:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Anime Re: ZERO, Starting Life in Another World ([tvdb](https://www.thetvdb.com/series/re-zero-starting-life-in-another-world)) has an alternative ordering of the episodes - director's cut. It was published after the original airing. Currently, Sonarr is unable to detect the alternative ordering or allow users to customize the seasons attached to the series.

### Describe the solution you'd like

Ability to modify the season's tvdb id so that it would be possible to substitute the current airing order with an alternative. For a more complete feature set, it would require a separate window with a list of currently fetched seasons as well as the ability to add season by tvdb id, delete season, and change the ordering of seasons. 

### Describe alternatives you've considered

The current alternative is to avoid Sonarr import entirely

**Comment by stevietv** [comment] 2024-09-09 17:55
This is essentially a request for alternate ordering, and so is a dupe of #255

**Closed by stevietv** 2024-09-09 17:55 UTC
Labels: needs-triage
