### ISSUE TITLE
Request to force media files resolution and size to update upon demand or custom timer.

### ISSUE THREAD

**Issue by jjjonesjr33** [Sonarr/Sonarr#4299] opened 2021-02-04 10:37 UTC
**Media file resolution/size not updating**
This was a issue I seen posted on a similar issue _Media file resolution not updating #3633_

The request it to have a simple option to do a full refresh and scan of files for a series so that it may pull the correct info. This is mainly in regards to when a user adds/updates a show themself without using the sonarr function.

**Describe any solutions you think might work**
Add a option in the automatic task to do a full system check regardless of file name if a series is monitored to update the size and the quality of the video file.

**Comment by bakerboy448** [comment] 2021-02-04 12:11
Duplicate of #3366

currently it only rescan if the file name is changed externally from sonarr

**Closed by bakerboy448** 2021-02-04 12:11 UTC
