### ISSUE TITLE
ability to handle "single episode torrent with season name"

### ISSUE THREAD

**Issue by trim21** [Sonarr/Sonarr#7459] opened 2024-12-06 15:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There are some release group release single episodes with full season name as torrent name.

For example, a TV show with 12 episodes and TV network releases a new episode once a week, the release group will release 12 torrents and for each episodes, it will use episodes name `Show.A.S01E01....-Group` as rss item name **but use full season name `Show.A.S01....-Group` as torrent name** with only single episode in it and named as normal episode name `Show.A.S01E01....-Group.mkv` or `Show.A.S01E03....-Group.mkv`.

So at the end of the season, release group will just create a new full season torrent with all episodes and downloaders won't need to move file manully.

But this pattern confuses sonarr because it assume this download contain full season, and most of this episodes from this download are missing, and requies users to manually import it.

I'm hoping sonarr could have the ability to handle this case.

### Describe the solution you'd like

Not sure, maybe use rss item/search result item name over download name in some case.

### Describe alternatives you've considered

Not sure

### Anything else?

no

**Comment by markus101** [comment] 2024-12-06 15:31
This issue is already open and related to this issue. https://github.com/Sonarr/Sonarr/issues/6378 It also lists issues that this issue is a duplicate of.

**Closed by markus101** 2024-12-06 15:31 UTC
Labels: needs-triage

**Comment by trim21** [comment] 2024-12-06 15:38
> This issue is already open and related to this issue. #6378 It also lists issues that this issue is a duplicate of.

Sorry, this is not a duplicate of #6378.

In this case, sonarr don't think the torrent I mentioned is season pack at grabing time.

The release group use **single torrent name** as title, so sonarr grab them as single episode.

**Comment by markus101** [comment] 2024-12-06 17:23
What's the name in the download client though? It sounds like RSS/release name is singular, but the torrent/folder name may be seasonal? Could be just the folder, but that's going to lead to a lot of confusion if there are more files than Sonarr expects too.

**Comment by trim21** [comment] 2024-12-06 17:26
> What's the name in the download client though? It sounds like RSS/release name is singular, but the torrent/folder name may be seasonal? Could be just the folder, but that's going to lead to a lot of confusion if there are more files than Sonarr expects too.

Rss name/Interactive search result title: `Show.A.S01E03....-Group`
Torrent name/Download name:  `Show.A.S01....-Group`
Torrent Files single file:
- `Show.A.S01E03....-Group.mkv`

**Comment by bakerboy448** [comment] 2024-12-06 17:58
So the torrent name indicates it's a season pack, but the release name and file are singular episodes?

**Comment by trim21** [comment] 2024-12-06 17:59
> So the torrent name indicates it's a season pack, but the release name and file are singular episodes?

Yes

> So at the end of the season, release group will just create a new full season torrent with all episodes and seeders won't need to move file manully.
