### ISSUE TITLE
Graceful handling of abandoned torrents

### ISSUE THREAD

**Issue by Dulanic** [Sonarr/Sonarr#4030] opened 2020-10-23 14:24 UTC
**Describe the problem**
I'd love to see sonarr gracefully handle upgraded episode torrents that are never processed. I have my torrent client update the label/category once complete. However, in cases where sonarr finds a upgrade reasonably quickly and hasn't yet imported the download, it will add both torrents and then leave the original behind. 

**Describe any solutions you think might work**
I'd like to see sonarr have an option to change the label for upgraded episodes that have abandoned torrents. At least, if the original has not yet completed. An option for abandoned torrents would be great.

**Additional context**
As can be seen here, the original file was as 720p file. About 20 minutes later it grabbed a 1080p version, but it never did anything with the 720p version. It was left behind and still showed under activity. This adds manual handling I need to do to cleanup after. I have automation setup for my completed torrents, but if the label is soanrr, it won't handle these as they are basically "active".

https://dulanic.com/files/sonarr.log

![image](https://user-images.githubusercontent.com/2948206/97015316-09ebae80-1511-11eb-8671-bfa28897fdb6.png)

**Comment by markus101** [comment] 2020-10-23 14:56
Dupe of https://github.com/Sonarr/Sonarr/issues/370

**Closed by markus101** 2020-10-23 14:56 UTC

**Comment by Dulanic** [comment] 2020-10-23 14:57
Thanks! I missed that one! I searched and didn't see it.
