### ISSUE TITLE
EPIC FAIL: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Stinky78** [Sonarr/Sonarr#1554] opened 2016-11-18 10:19 UTC
Hi there,

since about a week my Sonarr dies randomly and pretty often. Sonarr was the current version, i have updated mono just for good measure, but it did not work. It was running on an Mac mini with the latest macOS Sierra (and ran with it fine for months, even in public beta).

Then i thought "f.. it, i move it to my pi", set everything up but the same problem here too.

The error messages in the debug log are:

16-11-18 11:08:40.9|Fatal|GlobalExceptionHandlers|EPIC FAIL: Specified argument was out of the range of valid values.

[v2.0.0.4389] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
  at System.Array.IndexOf (System.Array array, System.Object value, System.Int32 startIndex, System.Int32 count) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.ArrayList.IndexOf (System.Object value) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.ArrayList.Remove (System.Object obj) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Org.Mentalis.Proxy.Listener.RemoveClient (Org.Mentalis.Proxy.Client client) [0x00006] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.Dispose () [0x0005f] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.OnClientReceive (System.IAsyncResult ar) [0x00043] in <ff452107cff34c04be416b0baae96a56>:0 
  at System.Net.Sockets.SocketAsyncResult+<Complete>c__AnonStorey0.<>m__0 (System.Object _) [0x00000] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00019] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 

16-11-18 11:08:40.9|Fatal|GlobalExceptionHandlers|EPIC FAIL: Index was outside the bounds of the array.

[v2.0.0.4389] System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at System.Collections.ArrayList.RemoveAt (System.Int32 index) [0x0005f] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.ArrayList.Remove (System.Object obj) [0x0000f] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Org.Mentalis.Proxy.Listener.RemoveClient (Org.Mentalis.Proxy.Client client) [0x00006] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.Dispose () [0x0005f] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.OnRemoteReceive (System.IAsyncResult ar) [0x00043] in <ff452107cff34c04be416b0baae96a56>:0 
  at System.Net.Sockets.SocketAsyncResult+<Complete>c__AnonStorey0.<>m__0 (System.Object _) [0x00000] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00019] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 

And then Sonarr is dead.

Its currently running on:
Raspbian GNU/Linux 8 \n \l
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:43:54 UTC 2016)
Sonarr Version 2.0.0.4389

Help would be extremely appreciated.

bye
S

**Comment by Stinky78** [comment] 2016-11-18 10:34
Just an observation. After i have disabled the socks5 proxy, it seems to run more stable now, but i really would prefer to use it. :/

**Comment by markus101** [comment] 2016-11-27 21:21
It is related to the proxy, but not sure where the issue lies with it. We'll need to have logs that include line number in the stack traces (mono needs to be running with the `--debug` switch) for further investigation.

**Comment by smmalis37** [comment] 2016-11-29 18:27
Got some line numbers! Unfortunately it seems like I didn't get the line numbers in the one place that mattered...

16-11-28 20:04:36.2|Fatal|GlobalExceptionHandlers|EPIC FAIL: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

[v2.0.0.4409] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.ArrayList.RemoveAt (System.Int32 index) [0x0006d] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/collections/arraylist.cs:606 
  at System.Collections.ArrayList.Remove (System.Object obj) [0x0000f] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/collections/arraylist.cs:589 
  at Org.Mentalis.Proxy.Listener.RemoveClient (Org.Mentalis.Proxy.Client client) [0x00006] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.Dispose () [0x0005f] in <ff452107cff34c04be416b0baae96a56>:0 
  at Org.Mentalis.Proxy.Client.OnClientReceive (System.IAsyncResult ar) [0x00043] in <ff452107cff34c04be416b0baae96a56>:0 
  at System.Net.Sockets.SocketAsyncResult+<Complete>c__AnonStorey0.<>m__0 (System.Object _) [0x00000] in /build/mono/src/mono-4.6.1/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:150 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00019] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1277 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:854 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /build/mono/src/mono-4.6.1/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1209

**Comment by markus101** [comment] 2016-12-01 02:02
I was thinking this was something we had pulled into our code base, but we're relying on an external library which is why we're not seeing line numbers for the Proxy.

@lloydsparkes any thoughts on this one?

Repo (for future us): https://github.com/lloydsparkes/SocksWebProxy

**Comment by lloydsparkes** [comment] 2016-12-01 22:30
Hmmm this looks interesting. I'll take a deeper look at the weekend

**Comment by Taloth** [comment] 2016-12-01 22:59
@lloydsparkes It's actually a bit worse. We got a memory dump of a user whose Sonarr CPU usages goes wild. Upon inspection we found 108 active proxylisteners.
The proxy used was on dns name and rotating IPs. Although I'm not sure how fast the IPs are rotating.
SocksWebProxy needs an IDisposeable and finalizer pattern to clean up those old proxylisteners and the static list needs locking against concurrent access issues.

**Comment by lloydsparkes** [comment] 2016-12-03 12:42
So I have taken a look at these issues.

I have made the following changes to the libraries that make up SocksWebProxy:

[SocksWebProxy changes](https://github.com/lloydsparkes/SocksWebProxy/commit/b7bed704119b735aad15e40fccf3ae59b9f8e1dd)

I have published a new version of the dependency.

I have done some quick testing, and everything seems to be working fine still. But I couldn't reproduce the issues. 

I'll create a PR to update the nuget version to pull the fixes into the main code base.

The first set of changes will definitely work to solve the issues around thread-unsafe modification of the arraylist. 

Hopefully the implementation of the IDisposable on SocksWebProxy will help reduce issues with ProxyListener instances hanging around. 

Although if you have more information on that issue, I maybe able to reproduce it.

**Comment by Taloth** [comment] 2016-12-03 13:19
@lloydsparkes Tnx for looking at it on such short notice, I do have a few comments though.

> Hopefully the implementation of the IDisposable on SocksWebProxy will help reduce issues with 
ProxyListener instances hanging around.

It won't, coz nothing is gonna call Dispose, not without a finalizer pattern. And more importantly, it will dispose all listeners due to the static, so disposing one SocksWebProxy instance would dispose all listeners, even those created by other SocksWebProxy instances.

As for reproduction, the issue with lingering proxylisteners is that the users uses a domain name, which resolves to dozens of different IPs (think vpn provider). So each time the IP changes, one proxylistener gets left behind and a new one is created. You should be able to reproduce it by creating 100 SocksWebProxy instances with different HttpPorts, and then releasing all but one.

There are some ways to solve it, one would be by reference counting, explicitly disposing the ProxyLIstener when the last reference is gone. Alternative would be to change the `listeners` static list into a list of WeakReferences AND store the ProxyListener for the SocksWebProxy in an instance field. like:
```
private static List<WeakReference> listeners;
private ProxyListener listener;
```

_Personally I find the whole Org.Mentalis and SockWebProxy libraries badly designed, I could point out half a dozen cases where it would go wrong. But that's just inherited code, not on you._

**Comment by lloydsparkes** [comment] 2016-12-03 13:42
Ahh yes, I completely missed that they are static fields. 

Ok, taking a proper look at the code, it should create a listener for every local proxy port. 

Of which there should only ever be one. But we use a new local port every time, creating a new listener (because while the listener is open the port is not free). ManagedWebProxyFactory.GetNextFreePort() causes this.

This means to fix the library we simply need to just remove the static state, then when SocksWebProxy goes out of scope everything will clean up correctly (Listener has a finaliser)

_I agree I do not like these libraries. I do have it on the bottom of my todo list to rewrite them._

**Comment by lloydsparkes** [comment] 2016-12-03 14:20
Ok, the latest changes should resolve this. 

ProxyListeners get cleaned up immediately.

**Comment by Taloth** [comment] 2016-12-03 15:34
Nope, they don't. The AsyncCallback keep em alive. See https://github.com/lloydsparkes/SocksWebProxy/blob/master/Org.Mentalis/Proxy/Listener.cs#L113
You really need a Dispose+Finalizer pattern on SocksWebProxy to appropriately call dispose on the listener.
And yes, the Finalizer on the Listener doesn't do jack shit as long as the listener isn't stopped.

**Comment by lloydsparkes** [comment] 2016-12-03 15:46
Ok, agreed and done

**Comment by Taloth** [comment] 2016-12-03 16:28
C'mon, now i'm getting frustrated... It's trivial to test the scenario and discover it ain't working: Create a SocksWebProxy. release the reference. run the GC. Check memory snapshot.
This isn't a traditional 'dispose native resources' `Dispose(bool disposeManaged)` pattern. You should call the ProxyListener.Dispose from the SocksWebProxy finalizer as well. Otherwise the SocksWebProxy instances goes away but the ProxyListener stays around.

**Comment by lloydsparkes** [comment] 2016-12-03 16:59
Sorry, I should have done this when I had the time to do it, and test it properly.

Anyway, now that I have. In the [latest commit](https://github.com/lloydsparkes/SocksWebProxy/commit/5ed1614ebde40d2f2aed6b096b14a7565a3a2298)

I modified the test program to test it. And now we get a stack track from the SocksWebProxy Finaliser to the ProxyListener.Dispose method, and then its all cleaned up

**Closed** 2016-12-20 20:35 UTC
