### ISSUE TITLE
Feature Request: Selective Renaming

### ISSUE THREAD

**Issue by DjRicko** [Sonarr/Sonarr#4499] opened 2021-05-19 02:54 UTC
**Is your feature request related to a problem? Please describe.**
The option to turn on renaming only for certain shows, like MythBusters, Tanked and other shows where scene numbering is f***ed up. Every other show just import with original scene file name.

**Comment by bakerboy448** [comment] 2021-05-19 02:56
Duplicate of #926
Duplicate of #2970

Please search next time

**Closed by bakerboy448** 2021-05-19 02:56 UTC

**Comment by jaenster** [comment] 2021-05-19 14:30
To be fair, he did comment on #2970 in november and #926 is closed
