### ISSUE TITLE
Can you add Put.IO to one of the download clients?

### ISSUE THREAD

**Issue by GJB85641** [Sonarr/Sonarr#4848] opened 2022-01-09 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Prevent copywrite complaint issues with US based internet providers

### Describe the solution you'd like

Add Put.IO to available download options

### Describe alternatives you've considered

VPN

### Anything else?

Currently using download station in Synology with VPN, but it is slow.

**Comment by bakerboy448** [comment] 2022-01-09 17:55
Duplicate of https://github.com/Sonarr/Sonarr/issues/1972

**Closed** 2022-01-09 17:55 UTC
Labels: needs-triage
