### ISSUE TITLE
After moving to ZFS Sonarr API (and System Status page) no longer report disk space (or mount point)

### ISSUE THREAD

**Issue by taw123** [Sonarr/Sonarr#5529] opened 2023-04-02 21:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Closest issues I could find revolve around the issue of potential DUPLICATED storage reporting (which I previously experienced for quite a while before moving to ZFS) and others related to FreeBSD's out dated Sonarr build.

Simply put the Service works fine (all aspects) except for the reporting of mounts/disk space. I came upon this will tracing back an issue with an issue with [Home Assistant- Sonarr Integration](https://github.com/home-assistant/core/issues/84318#issuecomment-1493436187)

I can provide diagnostics and debug capabilities if desired but now a days I SUSPECT there are enough of us out on ZFS that someone should have come across this issue thus far (or at least come up with a workaround to "hot-wired" the filesystem layout sufficiently to "trick" Sonarr into seeing what it already can clearly find and manipulate. 

In my case I have my containers deployed in one storage pool (backed by 2 mirrored M.2 disks) with Docker persistent data shared folder(aka volume) and may Media shared folder(aka Volume) both backed by a second storage pool composed of HDD (RAIDz2).

FYI: Radarr (which I BELEVE is based/forked(?) from earlier code base) DOES correctly report Disk space (and multiple "mount points") for each of the SAME disks (see attached screenshots) 

Please let me know if I can provide any further info or diagnostics.
Thanks!
<img width="1542" alt="sonarr system status" src="https://user-images.githubusercontent.com/10588252/229379440-c5226491-3a29-4e06-a5e0-dfa2e3b47515.png">
<img width="1541" alt="radarr system status" src="https://user-images.githubusercontent.com/10588252/229379444-c5f8cc1d-178a-42bc-95f2-9f4907457e96.png">

--T   

### Expected Behavior

Expected the Media shared folder/volume to be displayed in system status and reported by API

### Steps To Reproduce

see above ZFS config

### Environment

```markdown
- OS: NA
- Sonarr: 3.0.10.1567
- Docker Install: release-54faa31 by hotio
- Using Reverse Proxy: NA
- Browser: NA
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment] 2023-04-02 21:34
Looks like this is a dupe of https://github.com/Sonarr/Sonarr/issues/5247 which is already fixed in the v4 beta.

**Closed by markus101** 2023-04-02 21:34 UTC
Labels: needs-triage
