### ISSUE TITLE
Filter options missing on mass editor

### ISSUE THREAD

**Issue by g4m3r7ag** [Sonarr/Sonarr#4188] opened 2020-12-23 20:27 UTC
**Describe the bug**
There are a number of different options for creating a filter on the series page but most of those are missing on the mass editor page. Seems like there should be parity between these options. Year was also added as a sortable column on the series page, would be beneficial if that was also a filter option on both series and mass editor.

**Screenshots**
Filters options on series page 

![Screenshot from 2020-12-23 15-04-12](https://user-images.githubusercontent.com/46694420/103034570-2b7a0e00-4533-11eb-9ed6-cd8d342f0d85.png)

Filter options on mass editor page

![Screenshot from 2020-12-23 15-04-26](https://user-images.githubusercontent.com/46694420/103034579-32088580-4533-11eb-826e-4499fd4fd470.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 3.0.4.1033
 - Operating System: Docker on Ubuntu 18.04 (hotio)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.10.0.104
 - Branch: nightly

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment] 2020-12-23 20:29
Please filter (search) before opening issue, this is a dupe of https://github.com/Sonarr/Sonarr/issues/3548 which already has a PR open https://github.com/Sonarr/Sonarr/pull/4186

**Closed by markus101** 2020-12-23 20:29 UTC
