### ISSUE TITLE
Rename override for individual shows

### ISSUE THREAD

**Issue by DjRicko** [Sonarr/Sonarr#4109] opened 2020-11-21 11:52 UTC
**Describe the problem**
Some of us prefer to keep scene names of releases, but some shows like mythbusters have completely fucked up naming, like ep01 for season one on scene, and seasons not matching thetvdb at all. Would be nice to have a override to toggle on renaming for individual shows, but keep it off for everything else.

**Comment by markus101** [comment] 2020-11-24 17:21
Dupe of https://github.com/Sonarr/Sonarr/issues/926

**Closed by markus101** 2020-11-24 17:21 UTC
