### ISSUE TITLE
Feature: Use tags to assign to download client

### ISSUE THREAD

**Issue by drtcode** [Sonarr/Sonarr#3451] opened 2019-12-09 18:23 UTC
Apologies if this is already suggested, I couldn't find in existing list.
**Describe the problem**
To control ISP data usage (X GB/TB per month), for ultra high-quality episodes, I wish to have them added to Download Client in a paused state to await my "approval". Yet, for all other default downloads, I want them to start automatically.
The problem is: you can only have one download client settings. If I want to have "Add Paused"=No by default, but other specific items be "Add Paused"=Yes, there is no way to handle this.

**Describe any solutions you think might work**
Since tags are so powerful in other areas of the project, I would suggest adding a Tags field to the Download Client settings. Upon successful search, new item gets sent to a Download Client with matching Tag, and if no match, default to a client without tags set.
Almost exactly the same logic that is used in "Connections" for "Filter Series Tags" on Telegram notifications (and other similar tag functions in the project).

e.g. Series set with tag "AddPaused" + Download Client set with tag "AddPaused" which has custom settings for that use case (e.g. Add Paused=Yes, Category="Awaiting Approval", priority settings, etc.).

**Additional context**

**Comment by markus101** [comment] 2019-12-09 18:24
Dupe of https://github.com/Sonarr/Sonarr/issues/402

**Closed by markus101** 2019-12-09 18:24 UTC
