### ISSUE TITLE
"No indexers available with Automatic Search enabled" triggers main menu notification badge

### ISSUE THREAD

**Issue by reinisb** [Sonarr/Sonarr#7435] opened 2024-11-30 07:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The "No indexers available with Automatic Search enabled" message triggers a notification badge next to the `Status` menu item. Having a notification badge in main menu does not make sense for users who use such indexers w/o search, because the user cannot change the way the particular indexer works. As a result this notification badge in the main menu is always there and distracting from real solvable issues. This is simply bad UX.

<img width="1295" alt="Screenshot 2024-11-30 at 09 34 14" src="https://github.com/user-attachments/assets/68564761-73a0-4189-a489-0ad083c2e654">

### Expected Behavior

"No indexers available with Automatic Search enabled" message shall not trigger a notification badge in main menu. At least enable the user to dismiss this.

### Environment

```markdown
- OS: Raspbery Pi OS
- Sonarr: 4.0.11.2680
```

### What branch are you running?

Main

### Trace Logs?

No trace log available

**Comment by markus101** [comment] 2024-11-30 07:58
Ultimately a duplicate of #481 which we do not have current plans to address.

**Closed by markus101** 2024-11-30 07:58 UTC
Labels: needs-triage

**Comment by reinisb** [comment] 2024-12-05 11:12
This is such a bad UX pattern. Every time users like me open Sonarr they see the notification badge, which is totaly irrelevant for the user. Just please go in and fix this, it should take very little time.
