### ISSUE TITLE
Symlink

### ISSUE THREAD

**Issue by danillopanta** [Sonarr/Sonarr#6792] opened 2024-05-06 13:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Today it is not possible to manually import as symlink

### Describe the solution you'd like

Enable the option to import as symlink

### Describe alternatives you've considered

Enable this option

**Comment by augustuen** [comment] 2024-05-06 13:12
Duplicate of #967

**Comment by markus101** [comment] 2024-05-06 13:17
We have no plans to support symlinks, but you could use `Import Using Script` to have that functionality.

**Closed by markus101** 2024-05-06 13:17 UTC
Labels: needs-triage
