### ISSUE TITLE
Sonarr removing Release Group, replacing with "Sonarr" revisited

### ISSUE THREAD

**Issue by reruem** [Sonarr/Sonarr#4338] opened 2021-02-19 20:46 UTC
Using Sonarr v3

The previous issue was closed [3949](https://github.com/Sonarr/Sonarr/issues/3949) , but I am looking for more information as to why this is an acceptable issue. The issue virtually defeats the purpose of `{Release Group}`

This is my format `{Series Title} - S{season:00}E{episode:00} - {Episode Title} - {Release Group} - {MediaInfo Simple} - {Quality Title} `

![Snipaste_2021-02-19_12-33-39](https://user-images.githubusercontent.com/58284478/108558861-66888b80-72af-11eb-9c46-551df0248fc3.png)

As seen in the picture, this happens a lot. Sometimes Sonarr will remember the release group and sometimes it wont. What is the reason for this happening and can it be fixed?

**Comment by bakerboy448** [comment] 2021-02-19 20:48
Duplicate of #3949

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Closed by bakerboy448** 2021-02-19 20:48 UTC

**Comment by reruem** [comment] 2021-02-19 20:49
Why is this not worthy of a bug to be fixed?

**Comment by bakerboy448** [comment] 2021-02-19 20:50
It’s not a bug.
Refer to the other GHI.

**Comment by markus101** [comment] 2021-02-19 20:51
Sonarr can't parse the release group out of the middle of the file name. Not being able to parse it out of some random location isn't a bug.

> Sonarr no longer has the release group stored (and it’s not preceded by a dash so Sonarr can’t parse it).

Same reason, it either needs to be at the very end of the file for Sonarr to parse it `-RlsGroup.mkv` or following the anime format of `[RlsGroup]` usually at the beginning, sometimes at the end of the file name.

**Comment by reruem** [comment] 2021-02-19 20:55
@markus101 Oh I see, I'll play around with it. Thanks!
