### ISSUE TITLE
Sonarr search not finding shows with apostrophe

### ISSUE THREAD

**Issue by kat953162** [Sonarr/Sonarr#2529] opened 2018-04-25 16:55 UTC
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Linux

**.net Framework (Windows) or mono (macOS/Linux) Version:** no idea

**Link to Log Files (debug or trace):** none

**Browser (for UI bugs):** Chrome latest (but same issue on other browsers)

### What problem are you looking to solve?
titles such as "The Handmaid's Tale" don't appear in manual search because of the apostrophe ( ' ). If the apostrophe is not included in the title, it will appear. It pulls the file from RSS, however.

**Comment by markus101** [comment] 2018-04-25 17:42
Dupe of https://github.com/Sonarr/Sonarr/issues/1225

**Closed by markus101** 2018-04-25 17:42 UTC
