### ISSUE TITLE
Edit Metadata Source

### ISSUE THREAD

**Issue by Freaksed** [Sonarr/Sonarr#7383] opened 2024-11-14 05:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

For me this is specifically a problem for the show Firefly but it could apply to others out there. The airdate order and dvd order of episodes is not the same. I have the episodes in the dvd order, but sonarr only looks at the airdate order from tvdb. 

### Describe the solution you'd like

It would be nice if we could select which to use if a show has multiple episode orders listed.

### Describe alternatives you've considered

detect the order that you have them and compare to the lists in tvdb automatically

**Comment by augustuen** [comment] 2024-11-14 06:35
Duplicate of #7023, #6499, #4136 , #3937, #321, and #255.

#255 even mentions Firefly specifically.

Please search for related issues before you check the "I have searched the existing open and closed issues" checkbox.

**Closed** 2024-11-14 07:01 UTC
Labels: needs-triage

**Comment by Freaksed** [comment] 2024-11-14 17:21
oh thanks, i searched for "metadata" and didnt see anything. it didnt occur to me to search for "tvdb"
