### ISSUE TITLE
Season and episode numbers not detected when unknown series

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#3091] opened 2019-05-02 04:25 UTC
When manually importing a series either from the manual import dialog or queue dialog. The season number or the episode number is not detected if the series is not detected. I know it is partly because without knowing which series sonarr can't tell if the series has such a season or episode. What I would like is once we select the series name either sonarr scans the files again against the series to detect the episode and season. Or it at least parses the episode numbers for the files so that we can just select manually the series name and season before importing. At the moment have to set each episode individually  that is okay most of the time. But I recently had to import a whole show with around 250 episodes.

**Comment by markus101** [comment] 2019-05-02 04:39
Dupe of https://github.com/Sonarr/Sonarr/issues/1893

**Closed by markus101** 2019-05-02 04:39 UTC
