### ISSUE TITLE
[REQUEST] Notification Trigger on Folder Change

### ISSUE THREAD

**Issue by devanteweary** [Sonarr/Sonarr#6900] opened 2024-06-25 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

Just like there are triggers for "On Grab", "On Import", "On Upgrade", etc., I am requesting adding on for "On Folder Change".

### Describe alternatives you've considered

There are no alternatives.

### Anything else?

I also posted this request in the Radarr github, so please forgive the mockup showing Radarr!

---

Came across this idea when trying to use the Autoscan app.  

I specifically wanted this app to detect root folder changes and send them to Plex in realtime.

I separate shows into `/Live Action` and `/Animated` and long story short, always have to manually change the root folder of shows from Live Action to Animated.

Unfortunately, none of the Sonarr triggers send on root folder change, thus this request!  
And now that I think about it, it'd probably be better if it's just any folder change, not just root folder.  
As to cover any changes in the show's folder's name as well.

Here's a mockup:

![image](https://github.com/Radarr/Radarr/assets/29805497/ace26176-4b62-4d76-811c-e78e46c7eaaa)

Thank you!

**Comment by markus101** [comment] 2024-06-25 13:10
This is a duplicate of #4541, please search before opening issues.

**Closed** 2024-06-25 13:10 UTC
Labels: needs-triage

**Comment by devanteweary** [comment] 2024-06-25 15:09
> This is a duplicate of #4541, please search before opening issues.

Oh whoops. I swear I searched. Sorry about that.
I searched for root folder trigger so that may be why.

And dang, a request from 2021, how'd you even remember that???

Also.. 2021... not looking good for this request haha...

Alrighty sorry again!
