### ISSUE TITLE
Manual search string on Interactive Search

### ISSUE THREAD

**Issue by fengapappit** [Sonarr/Sonarr#3822] opened 2020-06-18 20:46 UTC
**Describe the problem**
Sometimes, series get indexed in Sonarr under season numbers that are not "right".
For example, from the last few weeks, I've had 2 cases that became a hassle because of it :

- Sabrina (don't judge), which shows as officially having 3 seasons, but was released actually under 2. You won't be able to find anything under Sabrina S03 because what is considered S03 by Sonarr is actually Season 2 part 2.

- Several animes, which are only one long string of episodes, without being split into seasons, that therefore don't match anything under NAME S01. Elfen Lied and Ergo Proxy come to mind for example.

**Describe any solutions you think might work**
I see a clean solution and a dirty one.

The clean : adding a manual input field on the "Interactive Search" popup, that would replace whatever keywords/search criteria are sent to the indexers when filled. A cleaner solution could be to add another search popup/button for manual search, so you can avoid sending useless requests to indexers if you know there won't be any match.

The dirty : dropping season numbers from the search string when no results are found. Sabrina S03 would become Sabrina, which is not optimal but would make it far easier to download a new season and having it matched in Sonarr.

**Comment by markus101** [comment] 2020-06-18 20:48
1. Dupe of https://github.com/Sonarr/Sonarr/issues/1128
2. Not something we plan to do

**Closed by markus101** 2020-06-18 20:48 UTC
