### ISSUE TITLE
Launch video in plex browser player from sonarr library view

### ISSUE THREAD

**Issue by preginald** [Sonarr/Sonarr#609] opened 2015-06-08 09:29 UTC
I have a suggestion for sonarr. I have a plex media service setup on my pc and I watch tv shows or movies in my chromium browser via the plex web interface. I have added my plex server settings to sonarr's configuration setting to update plex database when a video has completed download.

It would be great to play a tv show by clicking it in a sonarr interface and it open a new tab and launch the video in plex browser media player.

Thoughts?

**Comment by markus101** [comment] 2015-06-09 16:13
Duplicate of: https://github.com/Sonarr/Sonarr/issues/304

**Comment by kayone** [comment] 2015-08-29 18:17
I'm opening this instead of #304 since it's the more likely path we will take,

**Comment by dudumaroja** [comment] 2017-10-20 17:36
i hope the solution will not be plex feature.

**Comment by markus101** [comment] 2019-04-27 17:22
We have no immediate plans for this integration, but I've tagged it to look at in the future.

**Closed by markus101** 2019-04-27 17:22 UTC
Labels: enhancement, one-day-maybe

**Comment by DejayRezme** [comment] 2021-12-17 07:03
I was looking for a feature like "Launch External Player #304" to launch a video player if everything is just running on your local machine or local network.
Couldn't this be done with an URL Protocol similar to a magnet link? On installation of sonarr you could register the url protocol so it gets handled by your video player of choice. Then you'd only need a button in the web browser to play a specific episode.
It could work with a home server too but you'd need to register the URL protocol on the local machine of course.
