### ISSUE TITLE
Multiple or fallback metadata languages

### ISSUE THREAD

**Issue by FredHaa** [Sonarr/Sonarr#5052] opened 2022-06-08 12:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Non-english shows often don't have an english translation for its metadata on TVDB. This means that even if a show has a title and description in my native language, it is shown as TBA which affects the UI, the file renaming and the .nfo files.

### Describe the solution you'd like

Preferably, I would be able to choose multiple languages (e.g. Danish and English) and if a shows original language is either of those then it would pull metadata from that language. If not it would fallback to one of the two (English as default).

This should not affect the actual downloading of files as that is handled fine by language profiles.

### Describe alternatives you've considered

A simpler solution would be just to have a fallback language. E.g. if I set it to Danish then most of my content would be displayed correctly in English. The episodes I have which don't have English metadata would then fallback to using Danish descriptions, and if they don't exist then it would simply display TBA as it currently does.

### Anything else?

[This](https://thetvdb.com/series/301356-show) is an example of a show which has rich metadata in Danish but where episodes are listed as TBA because of missing English translations.

**Comment by bakerboy448** [comment] 2022-06-08 12:10
Duplicate of #269

**Comment by FredHaa** [comment] 2022-06-08 12:13
Whoops, I didn't look that far back when searching for existing issues

**Closed** 2022-06-08 14:28 UTC
Labels: needs-triage
