### ISSUE TITLE
Send only 1 notification when downloading a season

### ISSUE THREAD

**Issue by notDavid** [Sonarr/Sonarr#4273] opened 2021-01-21 20:22 UTC
**Describe the problem**
When i download a season (or 2...) my phone gets spammed with like 40 notifications for the next 5+ minutes (with like 10 seconds in between every single one.)

**Describe any solutions you think might work**
Send only a single notification per torrent/season instead of a single notification for every file/episode.

**Additional context**
I'm using Telegram notifications, but if i remember correct Pushover had the same issue so i'm assuming it applies to all type of notifications...

**Comment by 6cUbi57z** [comment] 2021-03-22 00:17
Duplicate of #363, #1585 and related to #1396

...however, I agree that one notification for a season pack would be useful.

**Comment by IvanStanul** [comment] 2022-04-14 00:16
Since #363 was closed, really hope this idea won't get shut down. 
Downloading is one thing, but when manually importing older series with lots of episodes it's even worse - tens or hundreds of notifications are sent out same second. Single notification would be much better (or at least option to disable them altogether for manual import).

**Comment by Phil57** [comment] 2022-07-03 06:46
That is a pain point when syncing with trakt and episodes are not marked as collected because of rate limiting.

**Comment by jack-mil** [comment] 2023-07-15 00:48
I have also found this annoying when picking out old season packs and starting a download for a whole series (older releases)

Discord notifications and spammed.

I am not sure what information is available that could prevent the notification event from sending multiple. I hope this wouldn't require a lot of backend API changes?

**Comment by demonspork** [comment] 2024-01-16 16:21
I just got ratelimited by PushBullet for downloading a single TV Show and it trying to send the "Episode Downloaded" for every single item in rapid succession.

**Comment by albert118** [comment] 2024-03-07 10:12
+1 for this, would defs be convenient to not be blasted when large seasons import (10 - 100 notifications is insane). An option in the notification triggers to notify on season grab complete would be perfect

**Comment by markus101** [comment] 2024-10-19 15:13
Grabbed events are sent for search episode grabbed.

https://github.com/Sonarr/Sonarr/pull/6937 adds support for a single grab event when all files in a release are imported.

**Closed by markus101** 2024-10-19 15:13 UTC
Labels: enhancement, connection
