### ISSUE TITLE
Password field disabled on Plex Media Server under Connect for Ubuntu

### ISSUE THREAD

**Issue by varun899** [Sonarr/Sonarr#2564] opened 2018-05-14 02:09 UTC
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Ubuntu 18.04 LTS

**.net Framework (Windows) or mono (macOS/Linux) Version:** mono

**Link to Log Files (debug or trace):** N/A since this looks like a UI bug

**Browser (for UI bugs):** Firefox

### Additional Information

![image](https://user-images.githubusercontent.com/11722153/39975143-d5a88e6c-56fa-11e8-8f59-a117471c0161.png)

**Comment by YipYup** [comment] 2018-05-14 02:59
What's broken? The picture doesn't really show anything other than a page with the form that hasn't been filled in.

**Comment by varun899** [comment] 2018-05-14 03:12
I am not able to type anything in the password field, its disabled only for plex media server. All other fields are fine. Thanks.

**Comment by markus101** [comment] 2018-05-14 17:28
Working fine for me in FF 59 and FF 60. Perhaps it's a browser plugin blocking it. Try a private browsing session/another browser.

I do see this warning when connected over an insecure connection:

![image](https://user-images.githubusercontent.com/413544/40013088-706972ac-5761-11e8-9913-56d52985a966.png)

**Comment by markus101** [comment] 2018-05-16 23:25
Closing as we're not able to reproduce.

**Closed by markus101** 2018-05-16 23:25 UTC

**Comment by varun899** [comment] 2018-05-18 00:19
I am still able to reproduce on firefox on linux. However, you are right this seems browser related. I used Vivaldi and it seems to work fine there. Thanks for looking.
