### ISSUE TITLE
Indexer Priority

### ISSUE THREAD

**Issue by TwilightIT** [Sonarr/Sonarr#2712] opened 2018-08-23 06:52 UTC
Priority for Indexers.

Could we possibly have a way to Priorities Indexers? so if the same release was found on 2 indexers but one had 5 seeds the other 20, but the indexer with 5 seeds was set as a higher priority as long as it met the seeding requirements it choose this one first.

I suggest this because even though i'm apart of a large amount of private indexers and for the most part it's not an issue as they cover the majority of releases but there is always the case where some mainly older releases they are not always on these indexers for that I have stuff like KAT and RARGB these tend to have the older releases but if a Private Indexer has the same Release i'd rather it grab from there this would stop fake seeds for the most part as it would only fall to these indexers if it had to and results it higher quality downloads overall as i'd much rather it grab from IP Torrents or Torrentday for Example than Pirate Bay if it has the choice as even though they tend to have lower seeds they are much more HQ and reliable.

**Comment by markus101** [comment] 2018-08-23 15:49
Dupe of https://github.com/Sonarr/Sonarr/issues/320

**Closed by markus101** 2018-08-23 15:49 UTC

**Comment by Qazerowl** [comment] 2019-09-29 05:03
This issue is a dupe, but the issue you linked to has been open for 6 years and not received an official response. And it's locked so it can't be discussed there.
