### ISSUE TITLE
MySQL Support in 2022?

### ISSUE THREAD

**Issue by jaycollett** [Sonarr/Sonarr#4735] opened 2021-11-03 15:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Given the surge in popularity of containerizing this application, especially with systems like Kubernetes, is there any willingness to move the data layer over to MySQL? I've heard some past developers on the project say they didn't want to open up a can of works but honestly, supporting SQLite and MySQL is a pretty easy line to draw and hold. In fact, the only issue with SQLite (other than performance) is that it does not play well with modern containerization setups that leverage remote file systems.

### Describe the solution you'd like

I'd like to see sonarr support MySQL as an option on install, some sort of env variable or config file that must be altered for advanced users who would like to take advantage of mysql.

### Describe alternatives you've considered

N/A

### Anything else?

This is a wonderful project and worth the investment to help keep it relevant in the future as containerization becomes the norm.

**Comment by bakerboy448** [comment] 2021-11-03 15:24
Duplicate of numerous others.

Markus/Taloth can reopen if their opinion has changed.

**Closed by bakerboy448** 2021-11-03 15:24 UTC
Labels: needs-triage
