### ISSUE TITLE
Support for automatic expiry, retention / deletion of media

### ISSUE THREAD

**Issue by magicdude4eva** [Sonarr/Sonarr#5593] opened 2023-04-29 09:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There is hardly a point to keep daily episodes around. As such I would like to suggest a "retention feature" which can be configured on a per-series-level.

### Describe the solution you'd like

On a Series level I should be able to configure:
-  "Keep the last XX episodes" OR "Keep epsiodes added in the past XX days"
-  "Only delete watched media (Y/N)"

Plex has such functionality and goes a bit further as it allows also to check the watched status. 
![image](https://user-images.githubusercontent.com/1632781/235294662-4bb21652-539f-4ad2-86b9-c86f99351f56.png)

### Describe alternatives you've considered

I have written my own scripts, connecting to the Sonarr API, but would then need to manually configure series. I have also logged a feature request with Overseerr (https://github.com/sct/overseerr/issues/3386#issuecomment-1528723705)

**Comment by stevietv** [comment] 2023-04-29 10:16
Sonarr has no concept of watched so this would not be possible. Why not use the functionality in plex?

**Comment by thezoggy** [comment] 2023-04-29 14:21
There is a script that already exists that handles this. 

https://gitlab.com/spoatacus/sonarr-episode-trimmer/-/tree/master

**Comment by markus101** [comment] 2023-04-29 14:35
This is a dupe of #314 and one of the few open results of you search for “delete”.

**Closed by markus101** 2023-04-29 14:35 UTC
Labels: needs-triage

**Comment by magicdude4eva** [comment] 2023-04-29 16:50
A bit pointless opening a feature-request and then being referred to #314 which was closed without comment. Would then be better to just say "No, we will never do any auto-archiving / retention".

Anyone else stumbling on this thread, there is at least a working docker/python solution which after some fixes also works with Sonarr v4 - https://github.com/jonfairbanks/sonarr-episode-trimmer

**Comment by stevietv** [comment] 2023-04-29 16:59
> #314 which was closed without comment.

this issue is still open right now - its only closed for commenting.
