### ISSUE TITLE
[Feature Request] Custom Search

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#2722] opened 2018-09-06 17:24 UTC
**Describe the problem**
For some tv shows in particular documentary's and sometimes others, the default search term dont find any results.

**Describe any solutions you think might work**
I think adding custom searches will help, for example, name s01e01 changed to name episode-name.
Thanks

**Comment by markus101** [comment] 2018-09-06 17:26
Dupe of https://github.com/Sonarr/Sonarr/issues/1128

**Closed by markus101** 2018-09-06 17:26 UTC
