### ISSUE TITLE
Exclude season number from search strings for single-season series

### ISSUE THREAD

**Issue by kSotin** [Sonarr/Sonarr#3896] opened 2020-08-05 12:26 UTC
**Describe the problem**

There are a large number of series that come with one single season. And releases of these series are often named without a season number, e.g., _Twenty.​Your.​Life.​On.​2020.​WEB-​DL.​4K.​H265.​AAC_ instead of _Twenty.​Your.​Life.​On.​2020.​S01.WEB-​DL.​4K.​H265.​AAC_, resulting in Sonarr getting nothing in search. 

**Describe any solutions you think might work**

Completely excluding season number from all searches is not a good idea. A possible workaround would be to add a toggle for users to specify that a series is one-season or not when the series is being added. 

**Additional context**

Here's an example of searches affected. 

Search in Sonarr's format, we've got nothing. 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/57791410/89411332-d1c9a080-d757-11ea-9f7a-eb98113e9a71.png">

But actually there is something. (Season number excluded) 
<img width="821" alt="image" src="https://user-images.githubusercontent.com/57791410/89411287-c1192a80-d757-11ea-91c7-80ce10772e34.png">

**Comment by markus101** [comment] 2020-08-05 14:42
Dupe of https://github.com/Sonarr/Sonarr/issues/3705

Using use season folder is not something we’d use for searching.

Those are release names we do not support (like full series releases that span multiple seasons).

**Closed by markus101** 2020-08-05 14:42 UTC
