### ISSUE TITLE
non-English metadata

### ISSUE THREAD

**Issue by monkiibiz** [Sonarr/Sonarr#2776] opened 2018-10-18 14:30 UTC
**Describe the problem**
When creating a profile with a language other than English, metadata (show information, episode titles and descriptions, etc.) are added in English

**Describe any solutions you think might work**
Get the metadata corresponding to the language set in the profile for the show similar to how Radarr handles different languages.

**Additional context**
Show information:
![image](https://user-images.githubusercontent.com/4595037/47161571-9778e000-d2f2-11e8-9a69-b3c6c64a5955.png)

Language set in profile attached to show:
![image](https://user-images.githubusercontent.com/4595037/47161616-afe8fa80-d2f2-11e8-99c7-ae54dba00d67.png)

Show information from thetvdb.com in Danish
![image](https://user-images.githubusercontent.com/4595037/47161790-09512980-d2f3-11e8-8f84-f5f8b9a1fd96.png)

**Comment by markus101** [comment] 2018-10-18 14:33
This is mentioned in the FAQ.

Dupe of https://github.com/Sonarr/Sonarr/issues/269

**Closed by markus101** 2018-10-18 14:33 UTC

**Comment by monkiibiz** [comment] 2018-10-18 14:51
interesting - I even searched open issues and the FAQ before opening this; sorry I missed it. 

Maybe I’m dense, but what is Skyhook?

**Comment by Taloth** [comment] 2018-10-18 22:04
Skyhook is a proxy that sits between Sonarr and tvdb. It does cleanup, caching and handles some important stuff like converting the tvdb local airtime to UTC airtime using network info.
