### ISSUE TITLE
Handling Stalled Downloads

### ISSUE THREAD

**Issue by XDark187** [Sonarr/Sonarr#7382] opened 2024-11-12 22:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be very helpful if Sonarr can handle stalled downloads, this issue has been requested since 2015 till now by many people on reddit/github/discord.
I know there are many variables to consider when implementing this but a simple checkbox can fix the main issue.

### Describe the solution you'd like

Add a checkbox in the settings to automatically check if any download has been stale for X amount of time. If so, Sonarr should automatically remove the download, blacklist it, and starts searching again.
The amount of time should be defined by the user under this checkbox.

### Describe alternatives you've considered

There are already multiple containers and scripts achieving this but running an entire container just to handle stalled downloads is a bit annoying, since they take up memory and cpu, or you'll have to manually check your download client for stalled downloads.
This is a great solution made by @ManiMatter 
https://github.com/ManiMatter/decluttarr

**Comment by markus101** [comment] 2024-11-12 22:29
>  I have searched the existing open and closed issues

You actually need to search.... Duplicate of #958

This is not a matter of a simple checkbox.

**Closed by markus101** 2024-11-12 22:29 UTC
Labels: needs-triage
