### ISSUE TITLE
Allow to add custom torrent in Interactive Search

### ISSUE THREAD

**Issue by Gaudi111** [Sonarr/Sonarr#4483] opened 2021-05-09 15:51 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes the configured providers do not find a torrent for a specific release.

**Describe the solution you'd like**
In the Interactive Search screen, I would like to have the possibility to add a manual magnet link/.torrent link/upload torrent file.
This way without having to configure extra providers, we could have the possibility of Sonarr adding a torrent for a specific episode/season and having it processed accordingly.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5664943/117578525-29b97d00-b0c5-11eb-9af8-33b6f014c34a.png)

**Comment by bakerboy448** [comment] 2021-05-09 16:47
Duplicate of #2845
Duplicate of #3258

no plans to add this functionality; add it to your client in sonarr's category and it'll track and pick it up if it can

**Closed by bakerboy448** 2021-05-09 16:47 UTC
