### ISSUE TITLE
constantly downloading wrong episodes if not listed in thexem

### ISSUE THREAD

**Issue by Gerk** [Sonarr/Sonarr#1859] opened 2017-04-17 16:05 UTC
I've reported this one directly once or twice, but it keeps cropping back up (I don't think it was ever addressed).  If a show that requires mapping via thexem does't have mappings Sonarr seems to revert to Season 0 and ends up downloading bad/incorrect episodes over and over again until the mappings are in place.

Example:

<img width="987" alt="screen shot 2017-04-17 at 12 04 58 pm" src="https://cloud.githubusercontent.com/assets/172505/25094645/26b0cbea-2366-11e7-923f-a4b56d753a6a.png">

**Comment by markus101** [comment] 2017-04-19 13:52
Dupe of: https://github.com/Sonarr/Sonarr/issues/1627

**Closed by markus101** 2017-04-19 13:52 UTC
