### ISSUE TITLE
Can sonarr add features like radarr " flag freeleech"

### ISSUE THREAD

**Issue by plsharevme** [Sonarr/Sonarr#4197] opened 2020-12-27 07:39 UTC
it quite important feature couse torrent download most on private tracker with decent speed .(most important some rare tv-show)

without this feature we cannot control our private tracker site keep ratio healty.

thanks.

**Comment by markus101** [comment] 2020-12-27 08:27
Please use the templates when filing issues. This is a dupe of https://github.com/Sonarr/Sonarr/issues/2782

**Closed by markus101** 2020-12-27 08:27 UTC
