### ISSUE TITLE
Fixing Sonarr restart on *nix platforms

### ISSUE THREAD

**Issue by ismell** [Sonarr/Sonarr#971] opened 2015-11-30 17:57 UTC
https://forums.sonarr.tv/t/fixing-sonarr-restart-on-nix-platforms/8328

From my understanding when Sonarr is running on a *nix platform restarting from the UI works like so:

Click restart on the UI.
SpinService stops sleeping.
SpinService spawns a new process with /restart flag.
Spawned process kills the original instance.
This has unintended consequences when using a process manager (upstart, smf, etc).
Because the original processes is killed, the process manager assumes that the process crashed and tries to restart it. It also closes the original stderr and stdout file descriptors. So if the process manager was logging stdout and stderr it will fail to log the newly restarted process.

I'm proposing that for *nix platforms that we replace steps 3 and 4 with the execv system calls. Mono provides it as Mono.Unix.Native.Syscall.execv().

This will cause the new process to replace the current process, which will keep the same PID allowing the process manager to keep tracking the same process, and it will also keep the std\* file descriptors open allowing logging to continue.

**Comment by feld** [comment] 2015-12-31 14:40
This would be greatly appreciated

**Comment by jackwilsdon** [comment] 2016-05-03 22:04
+1 this issue is still present.

**Comment by ismell** [comment] 2016-05-03 22:29
Another possible way of solving this is pass in a flag like /managed and change step 2 to just exit the process and let the process manager worry about restarting it.

**Comment by jackwilsdon** [comment] 2016-05-03 22:32
That is an alternative, although how does the process manager then differentiate between restart and shutdown? You could use the exit codes though that might end up with us [abusing their meanings](http://tldp.org/LDP/abs/html/exitcodes.html).

**Comment by ismell** [comment] 2016-05-04 13:59
I think upstart and smf, and maybe others will restart the process regardless of exit code if the service was not marked as stopped. So returning 0 would be fine.

**Comment by jackwilsdon** [comment] 2016-05-04 21:53
I don't think you quite understood my point.

Sonarr can either be shut down or restarted via the interface. With what you're suggesting, the shut down option would just restart Sonarr making it kind of pointless, as the restart option does the exact same thing.

**Comment by awprgrmmr** [comment] 2017-08-23 04:34
Is there any progress on this?

**Comment by feld** [comment] 2017-08-24 17:33
I would be plenty happy if on *nix platforms Sonarr did not even present an option to restart the process in the web interface.

**Comment by awprgrmmr** [comment] 2017-08-24 17:37
It's not the restart from the web GUI that it is important. It is how Sonarr handles restarting in general. When Sonarr auto updates, it's important that it restarts correctly and I would prefer if systemd could still track it's status.

**Comment by markus101** [comment] 2017-08-24 18:51
> When Sonarr auto updates, it's important that it restarts correctly and I would prefer if systemd could still track it's status.

When Sonarr updates (on non-Windows platforms) it stops Sonarr at the very end of the process and waits a few seconds for it to restart (this is where systemd should be starting it), if it's not restarted Sonarr starts it itself.

Restarting from the UI spawns a new instance immediately, because there isn't another wrapper (like the updater) when restarting itself. Potentially we could do something similar for restarting that would execute another application which would wait a few seconds and see if Sonarr was restarted and if not start itself.

**Comment by awprgrmmr** [comment] 2017-08-24 19:00
That would definitely solve the issue with service managers.

**Comment by Taloth** [comment] 2017-08-26 05:59
@awprgrmmr It's possible to configure systemd to react to different signals and exit codes, so Sonarr could most certainly have a working Shutdown/Restart command. However, atm we don't control the systemd unit file... it's not part of the package.
That's something we wanted to address in Sonarr v3 by providing more complete packages for specific platforms/distros. So it's in our mind, it's just something we can't realistically 'completely fix' right now.

@markus101 That's not viable, some users don't have the right systemd prop set (KillMode=process), the default is the entire cgroup, which means your helper app will be killed by systemd as soon as Sonarr gets terminated. This is why KillMode=process is relatively important for the updater to work.
It is however possible to detect we're managed by systemd, and act accordingly.

The OPs suggestion (execv to preserve the pid) is something that needs to be investigated, it just hasn't been a priority at all. I'm also not sure if preserving pid is ok, coz it's confusing, but if a third-party contributor wants to have a crack at it then I'd love to know the results.

**Comment by awprgrmmr** [comment] 2017-08-26 19:28
There are definitely multiple ways for it to be done. In my experience, most applications do it the way @markus101 suggested and provide a systemd on installation. What you are suggesting is exactly what NZBHydra does who has a working Restart via GUI that is tracked via systemd still.

Either way, providing the correct systemd file is crucial which is viable considering that right now, we already are providing a suggested systemd file.

**Comment by Nothing4You** [comment] 2020-11-15 14:11
I suspect it's also related to this that sonarr kills all running instances on the same user, not just the instance that should be restarting?
I'm running 2 instances on the same user with different data dirs (and different application dirs to avoid conflicts), yet every time one instance restarts both get killed.

**Comment by bakerboy448** [comment] 2020-11-18 01:09
Duplicate of #424

**Closed by bakerboy448** 2020-11-18 01:09 UTC
Labels: platform: linux, v3
