### ISSUE TITLE
Add IMDb to the api Series Lookup

### ISSUE THREAD

**Issue by marksie1988** [Sonarr/Sonarr#3688] opened 2020-04-19 07:48 UTC
**Describe the problem**
I would like to be able to use the IMDb I'd to search for series. Similar to how this is already achieved by Radarr

**Describe any solutions you think might work**
Looking at the file it should be fairly simple to add a check for IMDb. 

https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Api/Movies/MovieLookupModule.cs

**Additional context**
It would also be great to split it our so the URL is similar to Radarr e.g. 

series/lookup/IMDb
series/lookup/tvdb

**Comment by markus101** [comment] 2020-04-19 07:50
Dupe of https://github.com/Sonarr/Sonarr/issues/1829

**Closed by markus101** 2020-04-19 07:50 UTC
