### ISSUE TITLE
Better handling of multi-episode file upgrades

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#4864] opened 2022-01-20 22:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Right now, if a multi-episode file is imported, Sonarr will not replace this file with one that only has one of the episodes. This makes sense because such an upgrade could result in one of the previously imported episodes suddenly going missing.

However, this also has a drawback. It is entirely possible that an initial release has multiple episodes, but either due to a quality or preferred word upgrade, better versions of the episodes come out with the episodes split out per file. This has recently happened with Looney Tunes Cartoons.

Sonarr will not even grab these releases, so a user will have no way of knowing that a better version of the episodes was released. Had they not imported the multiple-episode file or manually deleted it, or even grabbed the same release, just split apart, Sonarr would properly grab and import the upgrades. This does not seem ideal because the multi-episode file essentially stops the automation unless an upgrade exists that also has the same episodes per file.

### Describe the solution you'd like

Sonarr should grab upgrades, even if they are not multi-episode. It can block the automatic import like it does now, so the user can decide what to do, see if upgrades exist for all episodes within the files, or delete the grab. But this way, users will be aware than upgrade *exists*, which is not the case right now.

### Describe alternatives you've considered

The user would have to either delete the multi-episode file and keep it missing until single episode files are released, or they will need to manually monitor for upgrades to these particular episodes. Both are not ideal. For example, with the Looney Tunes example I gave earlier, I only happened to notice that the releases I want were out when a future season was released. They would have been grabbed had I imported single episode files initially.

### Anything else?

N/A

**Comment by markus101** [comment] 2022-01-20 23:20
Dupe of https://github.com/Sonarr/Sonarr/issues/734 there are no short term plans for supporting this behaviour.

**Closed by markus101** 2022-01-20 23:20 UTC
Labels: needs-triage
