### ISSUE TITLE
Sonarr Search not finding matches where they are nearly correct

### ISSUE THREAD

**Issue by PsychoData** [Sonarr/Sonarr#4374] opened 2021-03-11 18:15 UTC
**Is your feature request related to a problem? Please describe.**
When search isn't matching something, but you can see it on the site you are trying to search. Usually due to small discrepancies for things like "Hell's Kitchen" vs "Hells Kitchen" vs "Hells Kitchen US" etc 

**Describe the solution you'd like**
It would be useful to be able to upload a torrent or give it a Magnet link as an option for Manual Search - Perhaps call it Manual Source? It could be another tab or link that shows up here if you aren't getting Search results. 
![image](https://user-images.githubusercontent.com/3719116/110827464-16746780-8264-11eb-9de1-36dc4cf83a3a.png)

**Describe alternatives you've considered**
There are two main alternatives I have seen
- Manually pull your download into your download client, and then do a manual import of the external Media into Sonarr 
- I believe if you request a [Scene Mapping](https://wiki.servarr.com/Sonarr_FAQ#why_cant_sonarr_import_episode_files_for_series_x_why_cant_sonarr_find_releases_for_series_x) it may get fixed for everyone using the Sonarr service, but this is a request process, and hopefully someone fills it. Hopefully
- Allow the ability to add or Override the Series Title or Search Terms for an item (With appropriate warnings "If you configure this wrong.... well yeah it might cause problems") 

**Additional context**
I was searching for Hell's Kitchen, but finding nothing. It seems that Sonarr was pushing searches for "Hells Kitchen US" and "Gordon Ramsay Hells Kitchen", but the listings were under "Hell's Kitchen". The TVDB also calls it "Hell's Kitchen (US)"

For a quick fix of this show, and possibly others, perhaps searching both with and without punctuation like Apostrophes/commas ?

**Comment by markus101** [comment] 2021-03-11 18:17
Dupe of https://github.com/Sonarr/Sonarr/issues/1225

**Closed by markus101** 2021-03-11 18:17 UTC

**Comment by PsychoData** [comment] 2021-03-16 05:08
Set what Category properly? Is there a reference for this that I am not seeing? 

Are you saying Sonarr will check the Download clients for downloads that it never initiated?

**Comment by bakerboy448** [comment] 2021-03-16 05:11
Category - the category within your download client that Sonarr will use

https://wiki.servarr.com/Sonarr_Settings#Torrent_Client_Settings

if it can parse and match it, and the episode is monitored yes

**Comment by PsychoData** [comment] 2021-03-16 05:18
So, for example, I have category set to "TV" 

I add "Good Eats" as monitored, but do not search it
I separately have a completed download in my download client already tagged "TV" with a name like "Good Eats S01" etc. just sitting there seeding

And when Sonarr checks the task (I am guessing "Downloaded Episodes Scan" or "Check For Finished Download") it should find that and pull it in? Assuming it figures out how to parse it and it's compatible, size and whatnot.
