### ISSUE TITLE
Moving files to another drive is slow

### ISSUE THREAD

**Issue by RainingTerror** [Sonarr/Sonarr#5923] opened 2023-08-14 20:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When a file has finished downloading to drive A and is moved by Sonarr to drive B, the speed and usage of both drives is low and fluctuates wildly.

### Expected Behavior

When a file has finished downloading to drive A and is moved by Sonarr to drive B, the speed and usage of both drives should be very high and consistent.

### Steps To Reproduce

1. Set the SABnzbd/qBittorrent download path to drive A
2. Set the Sonarr TV Show path to Drive B
3. Download a few episodes through Usenet or Torrent
4. Monitor drive speed/usage when the file finishes downloading and is moved from drive A to B, particularly on the second or third move in a row.

### Environment

```markdown
- OS: Windows 11 22H2
- Sonarr: 4.0.0.622
- Docker Install: No
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?

External HDD with write caching enabled:
[ExternalHDDCache.txt](https://github.com/Sonarr/Sonarr/files/12337903/ExternalHDDCache.txt)

External HDD with write caching disabled:
[ExternalHDDNoCache.txt](https://github.com/Sonarr/Sonarr/files/12337904/ExternalHDDNoCache.txt)

### Anything else?

The testing was performed on a fresh install of both Windows and Sonarr to rule out any config issues, and I was able to get a friend to reproduce it too.

I believe this may be related to write caching on Windows

Here is a screenshot of sonarr moving a file to an external HDD with write caching disabled
![Screenshot 2023-08-13 235937](https://github.com/Sonarr/Sonarr/assets/1512938/28699daf-ba31-47fe-92bf-c1d49442b0f7)

Here is a screenshot of sonarr moving the same file to the same external HDD with write caching enabled
![Screenshot 2023-08-14 000320](https://github.com/Sonarr/Sonarr/assets/1512938/65cc382b-93d1-4333-9c9d-a32b72236955)

Towards the end of these slow transfers, sometimes it will suddenly go to full speed until it finishes
![Screenshot 2023-08-14 000413](https://github.com/Sonarr/Sonarr/assets/1512938/fda2aefc-54a5-447c-8a56-5712c72c33a0)

Disabling write caching on internal drives had no effect however, they suffer from slow speeds regardless of it being enabled or not.

The drives are not the issue, using other programs to move or simply moving through windows explorer always results in the expected high speeds and usage. An exception is radarr, which also has the same issues as sonarr.

**Comment by TurboCheetah** [comment] 2023-08-14 22:34
:trollface:

**Comment by JohnTitor998** [comment] 2023-08-14 22:45
guyman curse is REAL!!

**Comment by adelefan** [comment] 2023-08-14 23:15
@JohnTitor998 dont sneed i was just letting u kno

**Comment by fryfrog** [comment] 2023-08-15 03:22
As a data point and work-a-round, how does it look if the *download client* does the move? That would look like torrent/usenet client's *incomplete* folder is on `A:\` while the *complete* folder is on `J:\`.

Also, you're a monster for using `A:\`! What are you going to do if you put a floppy drive in your computer!? ;)

**Comment by markus101** [comment] 2023-08-15 03:44
Any difference if you do a move vs a copy with explorer to the removable drive?

**Comment by RainingTerror** [comment] 2023-08-15 04:55
> As a data point and work-a-round, how does it look if the _download client_ does the move? That would look like torrent/usenet client's _incomplete_ folder is on `A:\` while the _complete_ folder is on `J:\`.

Using SABnzbd, it writes to the HDD at full speed

> Any difference if you do a move vs a copy with explorer to the removable drive?

They both perform the same

**Comment by markus101** [comment] 2023-08-15 07:14
Ultimately Sonarr uses `File.Move` (https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Disk/DiskProviderBase.cs#L276) from .net to move the files in this scenario, I've tried reproducing with and without write cache enabled with a nvme drive in an external USB dock and I'm not able to reproduce this issue in Sonarr.

Since we don't actually do the move and it's done by the framework there likely isn't much if anything we can do, especially if we're unable to reproduce.

**Comment by Ravencentric** [comment] 2023-08-15 12:16
I was able to reproduce this on *internal* disks, from an M.2 NVMe to a SATA HDD

Windows
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎15-‎03-‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0
```
Sonarr
```
Version
4.0.0.625
.NET
Yes (6.0.13)
```

1. I put a file on my NVMe
2. I manually imported it from Sonarr `Wanted -> Missing` and into a show that's on the HDD
3. Select Move or Copy as both show this same issue. Random speeds with Sonarr maxing out at roughly 100MB/s while constantly dipping to as low as 10MB/s. Same with disk usage.
![image](https://github.com/Sonarr/Sonarr/assets/78981416/4fab325a-79a4-4662-b06a-d386b5f934e3)
![image](https://github.com/Sonarr/Sonarr/assets/78981416/f05d0834-0fce-4edd-b176-7ab0bad62c89)
![sonarr_move](https://github.com/Sonarr/Sonarr/assets/78981416/c1d9fefc-f84c-4fc6-99fc-3f7fa2d23f96)

This is what it looks like when I move it manually in File Explorer
![file_explorer](https://github.com/Sonarr/Sonarr/assets/78981416/79b25146-694a-4796-a375-eadcd365dcfe)
![manual_move](https://github.com/Sonarr/Sonarr/assets/78981416/e62f73a4-c2dc-4af0-9d46-39231e4b6ada)

**Comment by fryfrog** [comment] 2023-08-15 23:03
Does Radarr behave the same way?

**Comment by markus101** [comment] 2023-08-19 06:04
To hopefully narrow down what might be happening I've created simple console app to copy or move a file from a source path to a destination path. [FileTransferTest.zip](https://github.com/Sonarr/Sonarr/files/12385213/FileTransferTest.zip)

Copy
```
FileTransferTest.exe --copy "source.mp4" "destination.mp4"
```

Move
```
FileTransferTest.exe "source.mp4" "destination.mp4"
```

The app does some minimal logging before/after transferring the file to give some information. Please test this out and let us know the results.

**Comment by RainingTerror** [comment] 2023-08-20 03:53
> The app does some minimal logging before/after transferring the file to give some information. Please test this out and let us know the results.

Thanks for this
While initially testing I was getting perfectly good speeds with both copy and move, then I realised I'm missing the Sab/Qbit download part (and so were my initial windows explorer tests).

If I do a Sab download+unpack on Drive A, then immediately move/copy the file to Drive B either through this program or explorer, I get the exact same slow/inconsistent speeds from the original post. 
Even taking Sab out of the equation, I can duplicate a file on Drive A, then move/copy it to Drive B and get the same poor results.

So in the end I guess it's just a Windows issue? I replicated it on my laptop too and had a bunch of people on discord do the same, all with matching results.
The mediocre speeds seem to last for roughly a minute after the unpack/duplication on Drive A, at which point the transfer to Drive B then goes to full speed as expected.

The only solution seems to be disabling write caching on the source drive (cripples my SSDs, not an option) or disabling it on the destination drive (only applies for externals).

Interestingly I saw somebody complaining about Teracopy's *lack* of write cache support, so I decided to try that too and it performs at full speed.

I also tried Robocopy, and with the /j flag `Copies using unbuffered I/O (recommended for large files).` it runs at full speed as well. Maybe it's possible to do something similar with .net too?

I'll be using the workaround [fryfrog](https://github.com/fryfrog) mentioned for now and letting Sab unpack directly onto the HDD, as this runs at max speed.

**Comment by markus101** [comment] 2023-08-20 17:53
Thanks for testing it out and providing more details. There is likely a way that we could avoid the caching, but it would end up being a lot more complex to achieve and isn't something we're going to commit to at this time.

It's possible that the script import could be used to achieve copying/moving without caching through Teracopy or Robocopy could be helpful.

**Closed by markus101** 2023-08-20 17:53 UTC
Labels: waiting-for-info, needs-triage
