### ISSUE TITLE
Ability to add quality and TVDB ID to TV series folder name

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#3490] opened 2020-01-05 05:16 UTC
**Describe the problem**
I would like the ability to add quality (e.g. 1080p, 720p) and the TVDB ID to the end of TV series folder names.

**Describe any solutions you think might work**
Something similar to how episode files can be named. In general, it would be nice to have more options of what can be added to series folder names, but quality and TVDB ID would specifically be the most useful.

**Comment by markus101** [comment] 2020-01-05 05:25
We do not have plans for quality as it's not a series level value, it exists for the episode files only.

TVDB ID is a dupe of https://github.com/Sonarr/Sonarr/issues/2659 (available in v3).

**Closed by markus101** 2020-01-05 05:25 UTC
