### ISSUE TITLE
Allow renaming without forcing season and episode number in file name, ERROR "Must contain season and episode numbers OR Original Title"

### ISSUE THREAD

**Issue by TriumphantD** [Sonarr/Sonarr#3338] opened 2019-10-14 17:20 UTC
When selecting renaming options, I would like the file to NOT include the Season number in the resulting filename. I like having my files being human readable and I find including the season number in the file name redundant, and it also causes issues with my scrapers.

Example of forced format: Bob's Burgers\Season 1\S01E01 - episode title.mkv. The file is already in a subfolder named season 1, so forcing S01 to appear in front of the file name is not necessary. Desired filename: Bob's Burgers\Season 1\01 - episode title.mkv

Currently, I am unable to do this. When I try to set the standard episode format as "E{episode:00} - {Episode Title}" I receive the error "Single Episode: Invalid Format Multi Episode: Invalid Format
Must contain season and episode numbers OR Original Title"

Can this option be added or is there a workaround?

Thank you.

**Comment by markus101** [comment] 2019-10-14 20:31
Dupe of https://github.com/Sonarr/Sonarr/issues/903

You may already be able to use `{season:0}/E{episode:00}` in which case that issue could be closed as well.

**Closed by markus101** 2019-10-14 20:31 UTC
