### ISSUE TITLE
Cannot add new TV show from firefox mobile

### ISSUE THREAD

**Issue by truenicoco** [Sonarr/Sonarr#2799] opened 2018-11-04 09:43 UTC
**Describe the bug**
Using firefox on android, there is no way to add a new TV show. The search feature seems to be working, but when trying to tap on the "add" or "search" icon, all the search results disappear. The issue does not occur when using Chromium.

**Logs**
Not much information there.

**System Information**

 - Sonarr Version: 2.0.0.5252
 - Operating System: Debian Buster
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.16.0.179

**UI Bugs:**
 - OS: Android (LineageOS)
 - Browser: Fennec F-Droid (=firefox)
 - Version: 63.0

**Comment by markus101** [comment] 2018-11-04 17:44
What do the trace logs on the server show?

**Comment by truenicoco** [comment] 2018-11-04 19:58
Nothing special. This looks like a CSS/JS issue to me. However, since this only concerns Firefox, maybe it is a bug on their side...

**Comment by markus101** [comment] 2018-11-06 16:56
Could you repost the logs? It looks like they have expired and I'd like to see what the server is seeing.

**Comment by markus101** [comment] 2018-11-11 00:12
This seems to be something with focus being lost on the input, if you click outside the search input, but above the results it seems to lose focus gracefully. You can also reproduce by clicking on a search result while the input is focused.

Can't reproduce in other browsers or against the v3 UI so I'm going to close this out.

**Closed by markus101** 2018-11-11 00:12 UTC

**Comment by EspadaV8** [comment] 2019-01-03 16:54
Is the v3 UI something that can be tested now? I am also having this issue with Firefox mobile and attempting to tap anywhere causes all the results to be removed.

**Comment by robeastwood** [comment] 2019-09-16 10:19
This is still an outstanding issue - it's been annoying me for some time. Any update on it?
Can a fix be pushed for the current UI?
