### ISSUE TITLE
Feature Request: Removing 0 seeder torrents

### ISSUE THREAD

**Issue by mccorkled** [Sonarr/Sonarr#2402] opened 2018-02-08 15:00 UTC
Is there a way to add the removing of torrents if they haven't done anything after X amount of hours or day? I am using some site that search many providers and they sometimes grab torrents with 0 seeders and then Transmission just sits there, and Sonarr waits for them to complete rather than going out and searching again for a different listing. 

Thanks

**Comment by markus101** [comment] 2018-02-08 15:01
Dupe of https://github.com/Sonarr/Sonarr/issues/958

**Closed by markus101** 2018-02-08 15:01 UTC
