### ISSUE TITLE
Color-Impaired mode is broken

### ISSUE THREAD

**Issue by TotallyNotInUse** [Sonarr/Sonarr#6264] opened 2023-12-20 02:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The colors with color-impaired mode enabled and disabled are the same.

### Expected Behavior

The colors should change so they are distinguishable to colorblind people.

### Steps To Reproduce

1. Look at colors
2. Enable color-impaired mode
3. Look at colors (they have not changed)

### Environment

```markdown
- OS: Windows Server 2022 (20348.2113)
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 120.0.1
- Database: Unknown
```

### What branch are you running?

Main

### Trace Logs?

https://logs.notifiarr.com/?cc72939881e243d2#8nguorAHggucjeqazqmcTA5b5qc63WrAoStaeaoJTrQ

**Comment by markus101** [comment] 2023-12-20 03:52
Possibly a dupe of https://github.com/Sonarr/Sonarr/issues/6129 but v4 has many changes.

**Closed by markus101** 2023-12-20 03:52 UTC
Labels: needs-triage
