### ISSUE TITLE
Get all titles from TVDB or add an option to add them manually as alternative

### ISSUE THREAD

**Issue by JoKerIsCraZy** [Sonarr/Sonarr#4584] opened 2021-07-18 09:26 UTC
**Is your feature request related to a problem? Please describe.**
Yes, I'm using Sonarr for my German TV Shows and some time ago I already noticed that Sonarr don't use the titles from the different languages from TVDB it only uses the alternative titles from the english one, means for example. "Everybody Hates Chris" has no alternative title, but the German title is "Alle hassen Chris" means when I'm searching for it it won't find anything.

**Describe the solution you'd like**
That Sonarr gets all Titles from every language and uses them as alternative titles

**Describe alternatives you've considered**
That you can add alternative titles when you edit an TV Show in Sonarr.

**Additional context**
![brave_M8qfrcm1Fa](https://user-images.githubusercontent.com/47474211/126062243-b01cf4da-dde4-4769-b0e4-a9b53201c744.png)
![brave_1ATkLm72PD](https://user-images.githubusercontent.com/47474211/126062228-966fad6a-f5b8-44dd-8106-63514aeab459.png)
![brave_uCZNrHYy9f](https://user-images.githubusercontent.com/47474211/126062231-a634994e-50c5-452c-afb2-f1d2ef7842a0.png)

**Comment by bakerboy448** [comment] 2021-07-18 11:19
Duplicate of https://github.com/Sonarr/Sonarr/issues/1234

no plans for this

**Closed by bakerboy448** 2021-07-18 11:19 UTC

**Comment by Taloth** [comment] 2021-07-18 11:22
Alternative titles can be requested here: https://forums.sonarr.tv/t/scene-naming-tvdb-naming-conflicts/137

Note that tvdb's alternative titles are not usable since they lack the necessary metadata about what kind of alternative it is (tvdb regularly has alternative titles that should only apply to a single season) and can conflict between series and languages.

**Comment by thezoggy** [comment] 2021-07-18 20:08
also things are subject to change with the whole new tvdb api...
