### ISSUE TITLE
Collapse episodes in the calendar when many are released at once.

### ISSUE THREAD

**Issue by Lattyware** [Sonarr/Sonarr#2739] opened 2018-09-17 14:19 UTC
**Describe the problem**
Currently, the calendar shows a separate item for every episode released on a day. Particularly with the rise of Netflix, some shows now release many episodes at the same time, which can lead to huge blocks that get a bit unwieldy.

**Describe any solutions you think might work**
It would be a nice cosmetic feature to collapse (that is, display a smaller element that represents a collection of episodes, rather than one element per episode) episodes when blocks are released at the same time. The lowest-hanging fruit would just be to detect an entire season being released at once and list it as the season, but potentially arbitrary chunks of episodes could be handled the same way.

This would involve a new interface on-click to show the list of episodes in the group. Alternatively, the element could just expand in the calendar when clicked to show every episode (as we see currently). Of course, if it is an entire season, it would be simple to go directly to the series page on that season and achieve a similar result.

**Additional context**
Here is an example where two shows had a season released on the same day, resulting in an excessively large calendar.

![image](https://user-images.githubusercontent.com/1239492/45628435-fd700e80-ba8b-11e8-97dc-0a521abefd10.png)

Obviously, this could be a configurable thing - potentially just an on/off switch, or a user-configurable number of episodes before they will be collapsed.

**Comment by markus101** [comment] 2018-09-17 15:17
Dupe of https://github.com/Sonarr/Sonarr/issues/2724

**Closed by markus101** 2018-09-17 15:17 UTC

**Comment by Lattyware** [comment] 2018-09-17 17:10
Apologies for the dupe, I did some searches, but managed to miss that one somehow.
