### ISSUE TITLE
Honor selected language for episode names

### ISSUE THREAD

**Issue by henningBunk** [Sonarr/Sonarr#3545] opened 2020-01-27 19:56 UTC
**Describe the problem**
I added a long running, german documentary series.
https://www.thetvdb.com/series/terra-x/allseasons/official
All the episodes have german titles but in english most (all?) of them just are named 'TBA'. After moving the files with sonarr it is very hard to find the correct episodes in the file structure since all episodes are named 'TBA' and not after the german episode title even though the series is set to German.

**Describe any solutions you think might work**
Honor the language selection for episode names.

**Comment by markus101** [comment] 2020-01-27 19:58
Dupe of https://github.com/Sonarr/Sonarr/issues/269 - Titles will need to be translated (unless the series is locked) on TheTVDB.

**Closed by markus101** 2020-01-27 19:58 UTC
