### ISSUE TITLE
Feature Request: add option to "remove all" inside Activity > Queue

### ISSUE THREAD

**Issue by jcchristian** [Sonarr/Sonarr#1650] opened 2017-01-31 13:51 UTC
It's quite frustrating when we have a bunch of items in our queue and we want to clear them all at once, nowadays that isn't possible and we have to delete every and each item manually, for 1~5 items that's easy, but for entire series/anime with tons of items on queue that's insane.

Feature Request: option to "remove all" inside Activity > Queue.

**Comment by markus101** [comment] 2017-01-31 17:17
Dupe of https://github.com/Sonarr/Sonarr/issues/792

The queue is built from your download client's queue/history, so you can always remove them from there.

**Closed by markus101** 2017-01-31 17:17 UTC
