### ISSUE TITLE
.NET 5 Support

### ISSUE THREAD

**Issue by hughesjs** [Sonarr/Sonarr#3901] opened 2020-08-06 00:03 UTC
.NET 5 is doing away with the separate core and framework. It will support Linux, Mac OS and Unix out of the box.

https://developer.okta.com/blog/2020/04/17/most-exciting-promise-dotnet-5

Given Mono has always been a bit of a pain and the .NET Core was never really targetted AFAIK, will the app be retargeting .NET 5 as soon as it is stable enough to allow for proper cross platform support?

**Comment by Qstick** [comment] 2020-08-06 02:17
This is pretty much a dupe of #948 and #1367. They have said NET 5 or 6 is in the future plans... .NET 5 is not planned to be LTS like 3.1 (and 6) and has dropped the planned Mono merging that was originally talked about.

**Comment by markus101** [comment] 2020-08-06 05:11
Yeah, close enough to #948 that we don't need a separate issue for it, something for v4.

**Closed by markus101** 2020-08-06 05:11 UTC
