### ISSUE TITLE
Ability to bulk manage Activity page enhancement

### ISSUE THREAD

**Issue by kontu** [Sonarr/Sonarr#1245] opened 2016-04-14 13:47 UTC
Being able to bulk manage the Activity page - on the Queue, History and Blacklist pages (beyond just "Clear all blacklist") would be great. I for some reason often have things getting stuck in the Queue and needing some manual love and intervention, and would benefit from being able to hit checkboxes next to all say, 5 items on the queue page (or 5 of 7), and telling all 5 to blacklist those releases and remove from the download manager.

**Comment by markus101** [comment] 2016-04-14 17:35
Dupe of https://github.com/Sonarr/Sonarr/issues/792

**Closed by markus101** 2016-04-14 17:35 UTC
