### ISSUE TITLE
Remove EpisodeGuide NFO tag from Kodi Metadata

### ISSUE THREAD

**Issue by Webbeh** [Sonarr/Sonarr#4448] opened 2021-04-18 07:46 UTC
**Is your feature request related to a problem? Please describe.**
When using Sonarr with the metadata plugin alongside KODI setup to only scrape informations locally, some KODI scrapes will fail seemingly randomly.

The issue comes from Sonarr adding the `<episodeguide><url>.../en.zip</url></episodeguide>` tag in the `tvshow.nfo`. KODI finds it, tries to read it, and fails miserably since you're asking it to only scrape info locally (so it does not follow any informations coming from that zip file, even though it downloads it).

A description of what happens is available here :
https://forum.kodi.tv/showthread.php?tid=200095

The issue described in that old topic still happens to this day in Kodi 19.

**Describe the solution you'd like**
Add a toggle in the KODI metadata plugin that would allow us to choose whether to add the `<episodeguide/>` tag or not.

Quite obviously, I want the `<episodeguide/>` tag to not be present in any NFO being created by Sonarr if the toggle switch is off.

**Describe alternatives you've considered**
For now, removing the `<episodeguide/>` tag from the NFO file BEFORE scraping with KODI does the trick quite well.

**Additional context**
Kodi v19, with only the Local NFO parser used (since Sonarr works quite well - not to mention way faster - at generating the NFOs)

**Comment by markus101** [comment] 2021-04-18 07:48
This sounds like a bug that Kodi needs to fix, the presence of that should not cause Kodi to try and download date remotely if configured not to.

**Comment by Webbeh** [comment] 2021-04-18 07:50
It quite obviously should be indeed.

But would that be a hard option to implement ?

**Comment by markus101** [comment] 2021-04-18 07:53
It's not that it's hard, it's that it's unnecessary and a bandaid. Unless there is a reason they won't fix it on their end (in which case we can discuss further), this is something that should be fixed on their end.

**Comment by Webbeh** [comment] 2021-04-18 07:57
Another reason to add that "bandaid" on this end is that different scrapers use different formats for episodeguide, and removing that tag entirely from the NFO will simply skip a seemingly very bug prone tag, that might not even be caused entirely by Kodi.

**Comment by Taloth** [comment] 2021-04-18 11:22
@markus101 Shouldn't we just nuke the whole thing anyway given it's a tvdb api v1 url?

**Comment by KarellenX** [comment] 2021-04-19 05:13
There is no activity on that bug at Kodi. No developer has shown an interest in investigating and fixing, so I expect that bug will be around for a while.

IMO, if an end-user is using nfo files to populate the library in Kodi, then there is no need for the <episodeguide> tag at all. It can be omitted from the tvshow.nfo file.... Especially for those users that also select Local Information Only as their scraper, which is a "double whammy" for the bug.

Sonarr's use of the v1 API has been a constant problem on our forum. Kodi does not use v1 API, it only uses v2 and above. But with v1-v3 API's being closed down in the coming months (should have already happened according to TVDB's original timeline) Sonarr will need to update the <episodeguide> format anyway or, as stated above, omit it as it is not needed when nfo files are in use.

The only problem caused by ommitting the tag is that nfo files are required for all episodes added to the library. But I would not expect that to be an issue for Sonarr users.

**Closed** 2021-04-20 07:21 UTC
Labels: suboptimal, up-for-grabs
