### ISSUE TITLE
Try to search without season when they're only one 

### ISSUE THREAD

**Issue by reprover** [Sonarr/Sonarr#3972] opened 2020-09-19 19:29 UTC
When I add some series and monitor it, sonarr will find the keyword 'TITLE S01 2020' for me. But sometimes there are only one seaon so nobody add the `season` keyword. It looks the title have no season like 'TITLE 2020', then sonarr will not able to find it. So could we have one more search option for not add season keyword when there're only one season here?

**Comment by markus101** [comment] 2020-09-20 00:58
Dupe of https://github.com/Sonarr/Sonarr/issues/3896

**Closed by markus101** 2020-09-20 00:58 UTC
