### ISSUE TITLE
Manual Import: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by datacenterdude** [Sonarr/Sonarr#5534] opened 2023-04-04 19:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Trying to manually import single episode in series.

Episode Title: _Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2_

Details
Cannot read properties of undefined (reading 'type')
  at Nz (http://172.16.10.130:8989/index.js?h=4yiu/fAiaaVffBwrBpPlMQ:1:512907)
  at Ch (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:157:136)
  at oi (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:180:153)
  at a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:269:342)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:346)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:277)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:137)
  at Lj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:243:162)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:114)
  at unstable_next (webpack://sonarr/node_modules/scheduler/cjs/scheduler.production.min.js:18:342)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:324)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:60)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:427)
  at Hb (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:292:100)
  at $c (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:73:351)
  at args.map(function (webpack://sonarr/node_modules/@sentry/browser/esm/helpers.js:74:22)
Version: 4.0.0.429

### Expected Behavior

When importing this series, every other episode worked as expected, but this one in particular error'ed, even across multiple downloaded versions of the file.

### Steps To Reproduce

Wanted > Manual Import > Select release

The error occurs when ticking the checkbox to select it for import.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.429
- Docker Install: yes (hotio/sonarr-v4)
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

2023-04-04 12:06:44.5|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=true: 200.OK (1 ms)
2023-04-04 12:06:49.8|Trace|Http|Req: 7374 [GET] /api/v3/manualimport?downloadId=1850&filterExistingFiles=false (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-04-04 12:06:49.8|Debug|Parser|Parsing string 'Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2'
2023-04-04 12:06:49.8|Trace|Parser|^(?<title>.+?\d{4})(?:\W+(?:(?:Part\W?|e)(?<episode>\d{1,2}(?!\d+)))+)
2023-04-04 12:06:49.8|Debug|Parser|Episode Parsed. Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914 - S01E02 
2023-04-04 12:06:49.8|Debug|Parser|Languages parsed: Unknown
2023-04-04 12:06:49.8|Debug|QualityParser|Trying to parse quality for Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2
2023-04-04 12:06:49.8|Debug|Parser|Quality parsed: Unknown v1
2023-04-04 12:06:49.8|Debug|Parser|Release Group parsed: 
2023-04-04 12:06:49.8|Debug|DiskScanService|Scanning '/data/usenet/nzbscratch/complete/Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2' for video files
2023-04-04 12:06:49.8|Trace|DiskScanService|1 files were found in /data/usenet/nzbscratch/complete/Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2
2023-04-04 12:06:49.8|Debug|DiskScanService|1 video files were found in /data/usenet/nzbscratch/complete/Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2
2023-04-04 12:06:49.8|Debug|Parser|Parsing string 'The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv'
2023-04-04 12:06:49.8|Trace|Parser|^(?<title>.+?\d{4})(?:\W+(?:(?:Part\W?|e)(?<episode>\d{1,2}(?!\d+)))+)
2023-04-04 12:06:49.8|Debug|Parser|Episode Parsed. The West - 09 - One Sky Above Us (1887-1914 - S01E02 
2023-04-04 12:06:49.8|Debug|Parser|Languages parsed: Unknown
2023-04-04 12:06:49.8|Debug|QualityParser|Trying to parse quality for The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv
2023-04-04 12:06:49.8|Debug|Parser|Quality parsed: HDTV-720p v1
2023-04-04 12:06:49.8|Debug|Parser|Release Group parsed: 
2023-04-04 12:06:49.8|Debug|Parser|Parsing string 'The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv'
2023-04-04 12:06:49.8|Trace|Parser|^(?<title>.+?\d{4})(?:\W+(?:(?:Part\W?|e)(?<episode>\d{1,2}(?!\d+)))+)
2023-04-04 12:06:49.8|Debug|Parser|Episode Parsed. The West - 09 - One Sky Above Us (1887-1914 - S01E02 
2023-04-04 12:06:49.8|Debug|Parser|Languages parsed: Unknown
2023-04-04 12:06:49.8|Debug|QualityParser|Trying to parse quality for The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv
2023-04-04 12:06:49.8|Debug|Parser|Quality parsed: HDTV-720p v1
2023-04-04 12:06:49.8|Debug|Parser|Release Group parsed: 
2023-04-04 12:06:49.8|Debug|Parser|Parsing string 'The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv'
2023-04-04 12:06:49.8|Trace|Parser|^(?<title>.+?\d{4})(?:\W+(?:(?:Part\W?|e)(?<episode>\d{1,2}(?!\d+)))+)
2023-04-04 12:06:49.8|Debug|Parser|Episode Parsed. The West - 09 - One Sky Above Us (1887-1914 - S01E02 
2023-04-04 12:06:49.8|Debug|Parser|Languages parsed: Unknown
2023-04-04 12:06:49.8|Debug|QualityParser|Trying to parse quality for The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv
2023-04-04 12:06:49.8|Debug|Parser|Quality parsed: HDTV-720p v1
2023-04-04 12:06:49.8|Debug|Parser|Release Group parsed: 
2023-04-04 12:06:49.8|Debug|QualityParser|Trying to parse quality for /data/usenet/nzbscratch/complete/Stephen Ives - The West (1996) - 09 - One Sky Above Us (1887-1914) Part 2/The West - 09 - One Sky Above Us (1887-1914) Part 2.mkv
2023-04-04 12:06:49.8|Trace|Http|Res: 7374 [GET] /api/v3/manualimport?downloadId=1850&filterExistingFiles=false: 200.OK (13 ms)
2023-04-04 12:06:49.8|Debug|Api|[GET] /api/v3/manualimport?downloadId=1850&filterExistingFiles=false: 200.OK (13 ms)
2023-04-04 12:06:56.0|Trace|Http|Req: 7375 [GET] /api/v3/health (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-04-04 12:06:56.0|Trace|Http|Res: 7375 [GET] /api/v3/health: 200.OK (0 ms)
2023-04-04 12:06:56.0|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2023-04-04 12:06:56.0|Trace|Http|Req: 7376 [GET] /api/v3/diskspace (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-04-04 12:06:56.0|Trace|Http|Req: 7377 [GET] /api/v3/system/status (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-04-04 12:06:56.0|Trace|Http|Res: 7377 [GET] /api/v3/system/status: 200.OK (0 ms)
2023-04-04 12:06:56.0|Debug|Api|[GET] /api/v3/system/status: 200.OK (0 ms)
2023-04-04 12:06:56.0|Trace|Http|Res: 7376 [GET] /api/v3/diskspace: 200.OK (15 ms)
2023-04-04 12:06:56.0|Debug|Api|[GET] /api/v3/diskspace: 200.OK (15 ms)
2023-04-04 12:06:56.7|Trace|Http|Req: 7378 [GET] /api/v3/log/file (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-04-04 12:06:56.7|Trace|Http|Res: 7378 [GET] /api/v3/log/file: 200.OK (0 ms)
2023-04-04 12:06:56.7|Debug|Api|[GET] /api/v3/log/file: 200.OK (0 ms)
2023-04-04 12:06:59.9|Trace|Http|Req: 7379 [GET] / (from 192.168.1.1 Uptime-Kuma/1.21.2)
2023-04-04 12:06:59.9|Trace|Http|Res: 7379 [GET] /: 200.OK (0 ms)
2023-04-04 12:07:00.0|Trace|Http|Req: 7380 [GET] /logfile/sonarr.trace.txt (from 172.16.10.183 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)

**Comment by markus101** [comment] 2023-04-04 19:12
Please search closed issues and make sure you're on the latest release as this was already fixed after another GHI was opened previously.

Dupe of https://github.com/Sonarr/Sonarr/issues/5532

**Closed by markus101** 2023-04-04 19:12 UTC
Labels: needs-triage
