### ISSUE TITLE
Missing Series naming convention that goes "Series Title, The"

### ISSUE THREAD

**Issue by lbinderup** [Sonarr/Sonarr#1099] opened 2016-01-28 12:58 UTC
It's a nice option to get a series folder that is sorted the same way that the series are sorted in the Sonarr interface. For instance: "Flash, The (2014)"

**Comment by markus101** [comment] 2016-01-28 17:23
Dupe of. https://github.com/Sonarr/Sonarr/issues/371

**Closed by markus101** 2016-01-28 17:23 UTC
