### ISSUE TITLE
Migration to .NET Core / .NET 5.0

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [Sonarr/Sonarr#4576] opened 2021-07-11 10:40 UTC
The issue is not with Sonarr as such, but with the fact that it relies on Mono. Mono is currently unsupported on Synology DSM 7, so Sonarr is not working. There wouldn't need to be a dependency if Sonarr is migrated to .NET 5.0. What is the hold-up with migrating away from the old .NET Framework please?

**Comment by markus101** [comment] 2021-07-11 16:49
Dupe of https://github.com/Sonarr/Sonarr/issues/948

**Closed by markus101** 2021-07-11 16:49 UTC
