### ISSUE TITLE
v3 + v4: qBittorrent adds throw bogus errors on existing torrents

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5400] opened 2023-01-31 00:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

[v4.0.0.362] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 186
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteEpisode remoteEpisode, String hash, String filename, Byte[] fileContent) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 137
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, String torrentUrl) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 190
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 117
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\DownloadService.cs:line 74
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 77

### Expected Behavior

"File already in queue" "file to be processed" "file in wrong category"

### Steps To Reproduce

add the same torrent twice.

### Environment

```markdown
- OS: nix
- Sonarr: v4-4.0.0.362
- Docker Install: y
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

https://github.com/Sonarr/Sonarr/blob/48b4cc5f3ffa0cb8eea6748db9091267216cef4f/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs#L181

**Comment by thezoggy** [comment] 2023-01-31 00:49
what version of qbit?

**Comment by KyleSanderson** [comment] 2023-01-31 01:01
4.4.5

**Comment by Qstick** [comment] 2023-01-31 01:27
The issue here is that qbit doesn't throw a great error for these. I was thinking there was already an issue, but that may be on Radarr GH

**Comment by bakerboy448** [comment] 2023-01-31 01:49
Duplicate of https://github.com/Sonarr/Sonarr/issues/5336

Nothing can be done as qbit returns a useless response that is a generic failure

**Comment by markus101** [comment] 2023-01-31 01:52
This is something qBit will need to solve.

**Comment by bakerboy448** [comment] 2023-01-31 01:53
For posterity - qbit GHI was opened a few weeks back.  Maybe it'll get traction one day.

https://github.com/qbittorrent/qBittorrent/issues/18361

**Closed by markus101** 2023-01-31 01:52 UTC
Labels: needs-triage
