### ISSUE TITLE
Sonarr wrongly cleans-up symbols when passing searches to jackett torznab

### ISSUE THREAD

**Issue by mirolm** [Sonarr/Sonarr#3520] opened 2020-01-15 12:17 UTC
**Describe the bug**

I added a newly started anime named "Darwin's Game" It adds alright in sonarr, but when i search for episodes nothing is found from jackett. I looked in sonarr debug logs and it seems that sonarr strips the apostrophe and "Darwin's" becomes "Darwins" when it is passed to jackett. From that on jacket finds no episodes, because in the torrent name it is the same as the anime name with the apostrophe.

Instead of cleaning up symbols i think sonarr should url-encode the search term and pass it as it is to jackett.

**Screenshots**

N/A

**Logs**

https://pastebin.com/gaT7SqdA

**System Information**

 - Sonarr Version: 3.0.3.688
 - Operating System: Debian Buster x64
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.6.0.161

**UI Bugs:**
 - OS: Windows 10 1909
 - Browser: Chrome 79
 - Version: 3.0.3.688

**Additional context**

N/A

**Comment by markus101** [comment] 2020-01-15 16:31
Dupe of https://github.com/Sonarr/Sonarr/issues/1225

**Closed by markus101** 2020-01-15 16:31 UTC
