### ISSUE TITLE
Search failed because its object reference not set to an instance of an object

### ISSUE THREAD

**Issue by zlammz** [Sonarr/Sonarr#4544] opened 2021-06-17 18:17 UTC
**Describe the bug**
When searching for a season pack for season 3 of Fairy Tail, after a while the error "Search failed because its object reference not set to an instance of an object. Try refreshing the series info and verify the necessary information is present before searching again" appears in the search result window. After refreshing the show, and reviewing the necessary information, it happens again.

**To Reproduce**
Do an interactive search for season 3 of Fairy Tail with the "Season pack" filter selected.

**Expected behavior**
Show all the season 3 packs.

**Screenshots**
https://i.imgur.com/HQttvPj.png

**Platform Information (please complete the following information):**

    OS: Ubuntu 18.04
    Docker: No
    .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 6.12.0.122
    Browser and Version (Only needed for UI issues):
    Sonarr Version: 3.0.6.1196
    Sonarr Branch: main

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!
https://pastebin.com/NuxJQXwL

**Comment by markus101** [comment] 2021-06-17 18:19
Dupe of https://github.com/Sonarr/Sonarr/issues/4414

We'll get this to master soon™

**Closed by markus101** 2021-06-17 18:19 UTC
