### ISSUE TITLE
qBittorrent connection error do not automatically disappear.

### ISSUE THREAD

**Issue by nextgenthemes** [Sonarr/Sonarr#3263] opened 2019-08-15 05:58 UTC
**Describe the bug**
qBittorrent connection error does not automatically disappear after its started.
I have Sonarr in autostart and always running, but I start qBittorrent only sometimes later. This loads to a status error on Sonar even when qBitorrent is up and even when torrents are fed to it.
On the status page when I click the `test/check all clients` or what its called. (just did it so I have to do this from memory). It does NOT make the error go away, I have to to to the qBittorrent client setup modal and click `test` on that dialog do make the error go away.

It seems everything is working fine its just that the error does not disappear automatically.

**Screenshots**
I can post some next time this happens if needed.

**System Information**

 - Sonarr Version: `3.0.2.582`
 - Operating System: `Open SUSE Tumbleweed`
 - .net Framework (Windows) or mono (macOS/Linux) Version:
```
mono --version
Mono JIT compiler version 5.20.1.19 (tarball Wed Jul 17 14:05:12 UTC 2019)
```

**UI Bugs:**
 - OS: `Open SUSE Tumbleweed`
 - Browser:  Firefox
 - Version: `68.0.1 (64-Bit)`

**Comment by markus101** [comment] 2019-08-15 18:32
I'm not able to reproduce this behaviour, as long as the test passes (Sonarr can connect to the download client) the error is cleared immediately for me. I found a couple small display issues for this, but not seeing an issue with test all not working as it should.

If you run into this again, please post the logs and we can take a look, but I've made a couple fixes and I'm closing this for now.

**Closed by markus101** 2019-08-15 18:32 UTC
