### ISSUE TITLE
pls add multiple language support

### ISSUE THREAD

**Issue by angelsky11** [Sonarr/Sonarr#3631] opened 2020-03-19 07:20 UTC
frist, thank you for the great job you have done, i really like this app, but your app is for english user only, for me it's not a problem, but then i recommend it to my english poor friends, it's hard to make them understand how things work
i checked your code, seems like ui is hardcoded in english, so could you guys please add multiple language support, put all the ui strings in one file, so we users can help to translate it to our mother language

thanks again

**Comment by markus101** [comment] 2020-03-19 15:13
Dupe of https://github.com/Sonarr/Sonarr/issues/749

**Closed by markus101** 2020-03-19 15:13 UTC
