### ISSUE TITLE
Use age of torrent/nzb in search for new episodes. Improve episode search?

### ISSUE THREAD

**Issue by SuperSonicFlea** [Sonarr/Sonarr#3859] opened 2020-07-09 19:10 UTC
Using the age in the search for new episodes would reduce the issues around shows like american dad where Episodes are being wrongly downloaded.

I know this is a miss match between theXEM and tvdb and the uploaders naming.

But I have found I can correct the incorrect versions by manual search and matching the air date with the Age of the nzb/torrent. 

Example:
Today is 9 July 2019, 
Airdate is  6 July 2019.
Difference is 3 days so in search episodes Age greater then 3 days should be excluded. Could add a day or 2 for early release or hour difference.

**Comment by markus101** [comment] 2020-07-09 19:11
Dupe of https://github.com/Sonarr/Sonarr/issues/969

**Closed by markus101** 2020-07-09 19:11 UTC

**Comment by SuperSonicFlea** [comment] 2020-07-09 19:14
Sorry about that, I searched for the wrong terms before logging.
