### ISSUE TITLE
add a 'discover' section like radarr

### ISSUE THREAD

**Issue by mattlevant** [Sonarr/Sonarr#5867] opened 2023-08-02 11:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no problem just a feature suggestion 

### Describe the solution you'd like

radarr has a discover section where it suggests movies based on your collection, can this be added to sonarr so it suggests new tv shows we may like 

or maybe even a if you liked this you may like this section from within each shows page based on its category/theme or the actors/actresses that star in the show

### Describe alternatives you've considered

n

**Comment by markus101** [comment] 2023-08-02 14:39
Duplicate of https://github.com/Sonarr/Sonarr/issues/4645

**Closed by markus101** 2023-08-02 14:39 UTC
Labels: needs-triage
