### ISSUE TITLE
Add option to use an indexer only for manual searches, but not for rss or automatic searches

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#1143] opened 2016-02-11 20:46 UTC
For trackers that have harder ratio requirements, bandwidth costs, or are RARed (or other reasons) I have trackers I don't want to use automatically, but if something is missing and I am going to manually select, I would like the option to be able to include the more rarely used trackers.

**Comment by markus101** [comment] 2016-02-11 20:48
Dupe of https://github.com/Sonarr/Sonarr/issues/253

**Closed by markus101** 2016-02-11 20:48 UTC
