### ISSUE TITLE
[feature request] View file copy status and percentage

### ISSUE THREAD

**Issue by jdukleth** [Sonarr/Sonarr#3559] opened 2020-02-02 02:25 UTC
There is no indication of how Sonarr copy files progress is going after a download finishes. You have to go manually check the filesize on the partial file.

It would be amazing to have a screen that shows which files are currently being copied from the downloads folder to the destination. With percentage and speed if possible.

This is not a request to troubleshoot but rather a feature request that I think would be invaluable.

**Comment by markus101** [comment] 2020-02-02 04:23
Dupe of https://github.com/Sonarr/Sonarr/issues/3524 which is covered by https://github.com/Sonarr/Sonarr/issues/282

**Closed by markus101** 2020-02-02 04:23 UTC
