### ISSUE TITLE
Subtitles with country attribute is being removed

### ISSUE THREAD

**Issue by alessandrojp** [Sonarr/Sonarr#2639] opened 2018-06-26 14:05 UTC
Hi,

For subtitles that contain the country attribute like `pt-BR` (Portuguese Brazilian) it is being removed when the Sonarr renames the file.

Before:
```
The.Walking.Dead.S01E01.XXXXXXXX.mkv
The.Walking.Dead.S01E01.XXXXXXXX.pt-BR.srt
```
After:
```
The.Walking.Dead.S01E01.mkv
The.Walking.Dead.S01E01.srt
```

It should be renamed to `The.Walking.Dead.S01E01.pt-BR.srt`
For cases that don't contain the country attribute, it works fine.

```
Sonarr
Version 2.0.0.5163
Mono Version 5.10.1.47
```

**Comment by markus101** [comment] 2018-06-26 20:01
Sonarr doesn't support/parse IETF language tags, it supports ISO 639-1 (2 letter) or ISO 639-2T (3 letter) language codes, which would be `pt` or `por` for Portuguese.

We haven't seen IETF language codes used for subtitle language naming, is there a particular reason you've done it that way?

We're considering adding it, but currently that'd result in it being rename to `po` and potentially `por` if we opt to use the 3 letter code instead.

**Comment by alessandrojp** [comment] 2018-06-27 15:52
Sorry for the delay.
I'm using this agent to get the subtitles to use in the Plex and it renames to `pt-BR`
https://github.com/pannal/Sub-Zero.bundle

I have checked here the 3 letter code and the Plex recognized it as Portuguese without any problem.
To be honest, as long the Plex can recognize it as Portuguese language, it is fine to me.

I hope you guys can add this.

**Comment by bakerboy448** [comment] 2020-11-18 01:49
largely a duplicate of #2570

**Closed by bakerboy448** 2020-11-18 01:49 UTC
Labels: suboptimal
