### ISSUE TITLE
[proposal] new series airing this month/week

### ISSUE THREAD

**Issue by FreesoulHV** [Sonarr/Sonarr#1249] opened 2016-04-16 06:57 UTC
Hi,

Sonarr is so awesome that since I am not monitoring torrents for series anymore I miss the new shows airing !
A link or suggestion in the series page to list all the new airing series that could be add to my series would be great :)

**Comment by thezoggy** [comment] 2016-04-16 10:32
this could be tossed into a 'trending' / 'recommendation' thing.. im sure theres already a github issue for that

**Comment by markus101** [comment] 2016-04-16 21:48
Yeah, a dupe of https://github.com/Sonarr/Sonarr/issues/354

**Closed by markus101** 2016-04-16 21:48 UTC
