### ISSUE TITLE
The Proxy again: EPIC FAIL: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Stinky78** [Sonarr/Sonarr#1641] opened 2017-01-26 09:32 UTC
17-1-25 03:21:47.7|Fatal|GlobalExceptionHandlers|EPIC FAIL: Object reference not set to an instance of an object

[v2.0.0.4472] System.NullReferenceException: Object reference not set to an instance of an object
  at Org.Mentalis.Proxy.Client.Dispose () [0x00031] in <d0a0ae0781c94569a389bb7a78536855>:0 
  at Org.Mentalis.Proxy.Client.OnRemoteReceive (System.IAsyncResult ar) [0x00043] in <d0a0ae0781c94569a389bb7a78536855>:0 
  at System.Net.Sockets.SocketAsyncResult+<Complete>c__AnonStorey0.<>m__0 (System.Object _) [0x00000] in /private/tmp/source-mono-4.6.0/bock
build-mono-4.6.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:150 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00019] in /private/tmp/source-mon
o-4.6.0/bockbuild-mono-4.6.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/thread
pool.cs:1277 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in /private/tmp/source-mono-4.6.0/bockbuild-mono-4.6.0-branch/profiles/mono-
mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:854 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /private/tmp/source-mono-4.6.0/bockbuild-mono-4.6.0-branch
/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1209 

Then it died! I have disabled the proxy and now it runs stable again

**Comment by markus101** [comment] 2017-02-27 06:34
@lloydsparkes another issue with the proxy, I'm sure it's quickly becoming your favourite thing. Are you able to take a look?

**Comment by lloydsparkes** [comment] 2017-02-27 13:39
Hmmm this looks interesting. Sure I'll take a look. Give me a few days

**Comment by lloydsparkes** [comment] 2017-03-05 12:24
@Stinky78 I've been taking a look, and I cannot see a cause for this issue. I'll keep looking

What Proxy are you using? (Public Proxy service / VPN) Or Software & Version, so i can attempt to reproduce it. 

Also what version of Sonarr did it occur in?

**Comment by Stinky78** [comment] 2017-03-06 11:09
hi there and thanks for looking at this problem...

to be honest, i don't know what version it was exactly at that time, but it was the most recent one available.

Regarding the SOCKS5 proxy, its a private one from PIA where i have to log in with my account. 

I know its thin, but does this help somehow? If i can do some tests for you, please let me know.

**Comment by lloydsparkes** [comment] 2017-03-12 11:37
Ok thanks. I'll try and reproduce it, but I am struggling to find the underlying issue. 

My only thought is a race condition, but i'll keep playing around

**Comment by lloydsparkes** [comment] 2017-04-15 15:02
Sorry its taken me so long to get around to this. I cannot reproduce the problem.

But I've updated the dependency to hopefully stop this issue happening. 

https://github.com/lloydsparkes/SocksWebProxy/commit/12df1a42e0e58917891d2a9d2fd92c5b62812d67

I'll create a PR in due course to update the version in Sonnar (need to reset some git bits first)

**Comment by lloydsparkes** [comment] 2017-04-15 15:52
Ok PR finally created. Let me know if there are any issues

**Comment by Stinky78** [comment] 2017-04-27 09:32
After activating proxy again, it ran for some hours, then:

17-4-27 07:42:23.9|Fatal|GlobalExceptionHandlers|EPIC FAIL.

[v2.0.0.4689] System.NullReferenceException: Object reference not set to an instance of an object
  at Org.Mentalis.Proxy.Client.Dispose () [0x00031] in <d0a0ae0781c94569a389bb7a78536855>:0
  at Org.Mentalis.Proxy.Client.OnRemoteReceive (System.IAsyncResult ar) [0x00043] in <d0a0ae0781c94569a389bb7a78536855>:0
  at System.Net.Sockets.SocketAsyncResult+<Complete>c__AnonStorey0.<>m__0 (System.Object _) [0x00000] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00019] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0

and Sonarr died again :(

**Comment by Stinky78** [comment] 2017-04-27 09:33
oh my Sonarr Version 2.0.0.4689 and Mono Version 4.8.1

**Comment by lloydsparkes** [comment] 2017-04-27 09:35
The fix has not been merged yet. Once it has been, hopefully it will go away

**Closed** 2017-04-29 15:11 UTC
