### ISSUE TITLE
Clickable paths and files

### ISSUE THREAD

**Issue by Milincho** [Sonarr/Sonarr#5745] opened 2023-06-16 15:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Clickable paths that open that folder:

![image](https://github.com/Sonarr/Sonarr/assets/60118859/4895c2f5-aa08-47de-b582-0dc4ae35850b)

### Describe the solution you'd like

Clicking on the path label opens the file explorer in that path.

### Describe alternatives you've considered

No.

**Comment by markus101** [comment] 2023-06-16 16:47
Duplicate of https://github.com/Sonarr/Sonarr/issues/4696

This is not possible without a browser extension.

**Closed by markus101** 2023-06-16 16:47 UTC
Labels: needs-triage
