### ISSUE TITLE
Audio track information

### ISSUE THREAD

**Issue by brezzz1** [Sonarr/Sonarr#6993] opened 2024-07-22 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I click into an episode file and hover over the track information in sonarr, there is information displayed regarding codec, language of the default audio track, etc but there is nowhere or way of searching the library for this information or using it in filters

### Describe the solution you'd like

It would be nice to be able to use this information within sonarr, for example display all x265 files or show all files that don't have English as their default language, etc

### Describe alternatives you've considered

The only way at present is by checking every file one by one

**Comment by augustuen** [comment] 2024-07-22 17:33
Filters don't apply to episode *files* at all, so this won't be implemented.

**Comment by thezoggy** [comment] 2024-07-22 17:56
sounds like user is asking for dupe of https://github.com/Sonarr/Sonarr/issues/5709

**Comment by markus101** [comment] 2024-07-22 18:51
This is only available when looking at series, no plans to overhaul things to be available for filtering at a higher level.

**Closed by markus101** 2024-07-22 18:51 UTC
Labels: needs-triage
