### ISSUE TITLE
Ability to manually call Connection from a series/season folder

### ISSUE THREAD

**Issue by Drapersniper** [Sonarr/Sonarr#5531] opened 2023-04-03 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes I just need to trigger a partial scan on plex for a given show/season/movie so having this ability built into the arr managers would be great.

### Describe the solution you'd like

A button within a Show/season to dispatch an event to the specified/all connections

### Describe alternatives you've considered

Manually calling the Plex/Jellyfin API

**Comment by thezoggy** [comment] 2023-04-03 19:49
generically just firing off an update command for connection would be nice (as this also applies to kodi). in sb land we had this "update library" that did just this

**Comment by markus101** [comment] 2023-04-03 19:52
This is a dupe of https://github.com/Sonarr/Sonarr/issues/595 which was closed because there wasn't much interest as you can see by the comments over the 6+ years it was open (and 0 :+1:s). At this time there are no plans to implement this functionality.

**Closed by markus101** 2023-04-03 19:52 UTC
Labels: needs-triage

**Comment by markus101** [comment] 2023-04-03 21:17
Possibly because it's now locked, but it was open for 6 years before it was closed.
