### ISSUE TITLE
FR: Update series/season/episode before downloading after release date

### ISSUE THREAD

**Issue by SoWhy** [Sonarr/Sonarr#1391] opened 2016-07-23 19:14 UTC
Could you please configure Sonarr, so it updates a show's info (whole series, season or single episode) before it attempts to download a new episode after its release? Oftentimes episode names are wrong or "TBA" in theTVDB and Sonarr will use that name when renaming the episode after download, even if there is new information published in theTVDB before the release of the episode. For example, all episodes of BoJack Horseman's third season where called "TBA" when Sonarr downloaded them but a forced update revealed that they actually had proper names.

TIA

SoWhy

**Comment by markus101** [comment] 2016-07-24 01:49
Dupe of: https://github.com/Sonarr/Sonarr/issues/1006

**Closed by markus101** 2016-07-24 01:49 UTC

**Comment by SoWhy** [comment] 2016-07-24 20:34
I disagree that this is a duplicate of #1006. The idea is similar but my request is to perform a refresh regardless of whether the title is "TBA" or not, just because the title might have changed.

**Comment by markus101** [comment] 2016-07-24 20:47
That would be needlessly expensive. Every time Sonarr would import a download it would need to refresh the series information from various servers which takes time and isn't free for the server hosts (even with caching). We're considering doing it for TBA episodes, no plans to do it every single time though. Files can be renamed after the fact and being able to know when files don't match the expected format (format or episode title change for example) is something else we're considering: https://github.com/Sonarr/Sonarr/issues/1118
