### ISSUE TITLE
Apply restriction tag through Series Editor or implement Global Restrictions - Enhancement Request

### ISSUE THREAD

**Issue by Swainoo** [Sonarr/Sonarr#1664] opened 2017-02-05 22:02 UTC
In my mind this seems like a simple request.

The ability to apply a restriction tag to multiple shows through Series Editor.

Its a bit cumbersome to have to go into every series to add a certain tag, either allowing the above or simply adding the option to apply a tag globally when creating a tag restriction would be very useful.

I'm sure i'm not the only person who has encountered the need to suddenly apply a tag to multiple season, in my situation a new steaming device was brought into the mix that doesn't like the audio from a certain release group, so now I need to go into every series and apply said tag.

**Comment by markus101** [comment] 2017-02-07 19:19
Dupe of: https://github.com/Sonarr/Sonarr/issues/397

**Closed by markus101** 2017-02-07 19:19 UTC
