### ISSUE TITLE
Allow sonarr to check date before download

### ISSUE THREAD

**Issue by Hello-World-Traveler** [Sonarr/Sonarr#7367] opened 2024-11-06 00:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

A show that has just aired, however since some metadata providers list wrong seasons.

Age (when grabbed) 365 days
Published Date
06 Nov 2023 17:16:57

Show aired yesterday.

### Describe the solution you'd like

For sonarr to check the age of the file and if it's more then a week or two old, wait a few hours to a few days in-case of new file. This might stop sonarr from grabbing Old (or wrong season) files for shows that just aired.

### Describe alternatives you've considered

Manual deleting the files after download.

**Comment by markus101** [comment] 2024-11-06 00:54
If it was 365 days old when grabbed that is either a search or an RSS feed doing something very unexpected. With a search there is no waiting for another release.

Age of release in general is a duplicate of https://github.com/Sonarr/Sonarr/issues/5312

**Closed by markus101** 2024-11-06 00:54 UTC
Labels: needs-triage
