### ISSUE TITLE
Different categories for different series type

### ISSUE THREAD

**Issue by h3llrais3r** [Sonarr/Sonarr#4841] opened 2022-01-06 18:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No possibility to specify a different category (for download client) for standard series and anime.
Without this, I'm not able to switch from medusa to sonarr because I need a different handling depending on the series type.
Series and anime are treated differently after download, so solution is a custom category.

### Describe the solution you'd like

Option to configure a different category for standard series and anime.

### Describe alternatives you've considered

No alternatives.

### Anything else?

Second option for category for anime:
![image](https://user-images.githubusercontent.com/1945295/148434349-350a5561-fd26-4322-9681-abd77246b7c4.png)

Can be extended for all series types:
![image](https://user-images.githubusercontent.com/1945295/148434572-2b06340b-26d0-403b-a1b7-e7cfb4934030.png)

Optional for all series types, default to same location for every type to keep backwards compatibility.

**Comment by bakerboy448** [comment] 2022-01-06 18:47
Duplicate of https://github.com/Sonarr/Sonarr/issues/2587

Closing - assuming no plans still, Markus or Taloth can reopen if they wish.

**Closed** 2022-01-06 18:48 UTC
Labels: needs-triage

**Comment by h3llrais3r** [comment] 2022-01-06 18:49
😢
