### ISSUE TITLE
[Request] Add Indexers using Jackett API

### ISSUE THREAD

**Issue by zero77** [Sonarr/Sonarr#3530] opened 2020-01-19 21:05 UTC
**Describe the problem**
When using a number indexers in Jackett it can take a wile to add them all into Sonarr.

**Describe any solutions you think might work**
Use Jackett API to find the enabled indexers and import them into Sonarr.

**Additional context**
API Path: `/api/v2.0/indexers/`

![Screenshot from 2020-01-19 21 02 53](https://user-images.githubusercontent.com/16563034/72688435-1dd82f00-3aff-11ea-9bba-2ede9ddf355d.png)

**Comment by markus101** [comment] 2020-01-19 23:34
Dupe of https://github.com/Sonarr/Sonarr/issues/3170 we’ll discuss again, but not likely something we plan on doing

**Comment by Thundernerd** [comment] 2020-01-20 15:36
@zero77 
If you enable advanced settings then you can set the API Path for your torznab indexer to `/torznab/all/api` which allows Sonarr to send only one query to Jackett instead of multiple separate ones.

![image](https://user-images.githubusercontent.com/5531467/72738939-ee7afe00-3ba2-11ea-9795-cd8165cf33ef.png)

**Comment by Ether009** [comment] 2020-01-21 16:04
Using the all pseudo indexer in jackett is highly discouraged. Not only do you lose granular control decisions based on indexer, but you're also increasing the number of entries per update, meaning a much higher risk of missing releases. If you do use it, you have to reduce the refresh interval so as to reduce the amount of releases per indexer per update so as to not hit the limit, BUT you are then hitting the indexers themselves waay too often and you'll just simply end up banned. If you have more than one or two indexers, just don't use that... And if you have only one or two, well then you really don't gain anything anyway.

**Comment by markus101** [comment] 2020-01-27 20:10
We don't have plans to support importing from the Jackett API, but we'll look at allowing copying indexers (similar to quality profiles) so it's less copying/pasting of the same thing.

**Closed** 2020-01-27 20:11 UTC
