### ISSUE TITLE
Emby library scan not working

### ISSUE THREAD

**Issue by aahmyu** [Sonarr/Sonarr#2662] opened 2018-07-13 06:09 UTC
**Describe the bug**
Sonarr is not updating Emby library when adding a tv show. I asked about this on the Emby forum and @LukePulverenti said  that you are using the old notification api and you need to use the new one.

**System Information**
 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows 10

**Comment by Qstick** [comment] 2018-07-13 23:48
FYI Related https://github.com/MediaBrowser/Emby/issues/3079

**Comment by LukePulverenti** [comment] 2018-07-14 04:06
Yes, it currently will work for updating existing media, but not new media. The new API in #3079 is the way forward. Thanks.

**Comment by Quiksmage** [comment] 2018-09-05 20:43
+1 on this

**Comment by s3627014** [comment] 2018-10-14 14:08
Is there any workaround for this until its fixed?

**Comment by matejzero** [comment] 2018-11-13 06:33
@s3627014 I think the only workaround is to increase library scan schedule in Emby to scan more aggresively.

Fixing this should be relatively easy, but I'm not familiar enough with C# to fix thix:/

**Comment by LukePulverenti** [comment] 2018-11-13 06:36
What version of the server are you testing with?

**Comment by Corey-Evans** [comment] 2018-12-19 21:51
Any progress on this? 

Thanks!

**Comment by markus101** [comment] 2019-03-16 22:57
The fix has landed in v3.

**Closed by markus101** 2019-03-16 22:57 UTC
Labels: connection

**Comment by 1aTa** [comment] 2019-09-14 23:56
This still doesn't work for me on v3.

**Comment by IkeTaylor11** [comment] 2019-12-31 18:27
This issue still exists in Sonarr v3. Can this issue be reopened and fixed?

**Comment by markus101** [comment] 2019-12-31 18:53
Is it the same issue, or is it a new similar issue.

We're also going to need to know what the issue is, "not working" doesn't give us enough information.

**Comment by IkeTaylor11** [comment] 2019-12-31 18:56
the issue is the same as whats listed in the original bug. 

Describe the bug
Sonarr is not updating Emby library when adding a tv show. I asked about this on the Emby forum and @LukePulverenti said that you are using the old notification api and you need to use the new one.

I setup Sonarr to communicate with Emby, the Test button works, but sonarr never triggers a library update in Emby when new episodes are added.

**Comment by markus101** [comment] 2019-12-31 19:41
The fix was done in both by the same dev.

https://github.com/Sonarr/Sonarr/commit/ecebe73c333582a4651b66a2fa66369d8ffbc337
https://github.com/Radarr/Radarr/commit/3e96fe4a726f68cf21814ced63b3098663b7702a

Besides the differences for the actual implementations, they look the same to me.

Either a mapping on the Emby side or not using TVDB would be my guess, unless the Emby implementation is different for TV.

Best to open a thread on the forums to troubleshoot, we'll need debug logs at a minimum. Check logs on Emby's side as well.

**Comment by nayrnet** [comment] 2020-01-14 07:20
yeah its not mapping up anymore with Emby using the new API.. here's the log entry from emby's side:
```2020-01-14 00:17:11.529 Info HttpServer: HTTP POST http://192.168.4.15:8096/mediabrowser/Library/Media/Updated. UserAgent: Sonarr/3.0.3.688 (ubuntu 18.04)
2020-01-14 00:17:11.530 Debug LibraryMonitor: New file refresher created for /tv/adultSwim/American.Dad
2020-01-14 00:17:11.530 Info HttpServer: HTTP Response 204 to 192.168.4.5. Time: 1ms. http://192.168.4.15:8096/mediabrowser/Library/Media/Updated
```
the path on emby is: /mnt/media/television/adultSwim/American.Dad/
need a remote mapping path feature like the download clients have but for emby with this new API.

**Comment by LukePulverenti** [comment] 2020-02-19 17:12
@nayrnet did you use the optional network path feature in Emby Server when setting up the library? We could probably use that to do a backwards path mapping to try and determine the right location.

**Comment by nayrnet** [comment] 2020-02-19 19:18
no they were local paths in emby, Sonarr is in a docker and had different path structure OTB.. I modified my docker to have identical paths to emby and its now working as expected.. but mass editing the paths is only feasible in the new Sonarr.

**Comment by LukePulverenti** [comment] 2020-02-21 01:31
Ok great, thanks for the info.
