### ISSUE TITLE
Trending/new tv shows

### ISSUE THREAD

**Issue by ricardodevries** [Sonarr/Sonarr#5592] opened 2023-04-29 08:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No. This is a new feature request.

### Describe the solution you'd like

A new page, under or within the New page, showing (not added) shows that have not been added that will have a new season soon or are a completely new series or already an ongoing series. You should be able to filter on genre and maybe on air year or popularity, etc.

### Describe alternatives you've considered

None, I use tvmaze.com manually but that is time consuming.

**Comment by markus101** [comment] 2023-04-29 14:39
Dupe of https://github.com/Sonarr/Sonarr/issues/4640 but also some crossover with https://github.com/Sonarr/Sonarr/issues/5481

**Closed by markus101** 2023-04-29 14:39 UTC
Labels: needs-triage
