### ISSUE TITLE
Latest Season monitoring not monitoring unaired/recently aired episodes.

### ISSUE THREAD

**Issue by Cruv** [Sonarr/Sonarr#2533] opened 2018-04-27 04:44 UTC
### System Information/Logs

**Sonarr Version:**
2.0.0.5163
**Operating System:**
Docker
**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono version 5.10.1.20
**Link to Log Files (debug or trace):**
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1953851/sonarr.debug.txt)
[sonarr.debug.14.txt](https://github.com/Sonarr/Sonarr/files/1953845/sonarr.debug.14.txt)
[sonarr.debug.15.txt](https://github.com/Sonarr/Sonarr/files/1953846/sonarr.debug.15.txt)
[sonarr.debug.11.txt](https://github.com/Sonarr/Sonarr/files/1953847/sonarr.debug.11.txt)
[sonarr.debug.12.txt](https://github.com/Sonarr/Sonarr/files/1953848/sonarr.debug.12.txt)
[sonarr.debug.13.txt](https://github.com/Sonarr/Sonarr/files/1953849/sonarr.debug.13.txt)

### Additional Information
Calendar view https://i.imgur.com/d1VoTYR.png

Newly moved to Sonarr from Medusa. Added all the series using the Latest Season setting. Even went into the series editor and set all the series to 'All', waited for that to finish, and then set them to 'Latest Season'.

The episodes that were grabbed today were because sometime around 9pm I set them to 'Latest Season' again and it set today's aired episodes to monitored. As you can see though the other series that start at 10pm didn't get monitored.

### What problem are you looking to solve?
Auto monitor newly aired episodes either before they are as part of the latest season or after they air.

**Comment by markus101** [comment] 2018-04-28 01:05
What's the status of those episodes on the series details page (or what was if you made changes since then)?
If the series isn't monitored they will appear as unmonitored on the calendar, is the series monitored?

How many series do you have in Sonarr?
How many did you update from Season Pass?
Do they update if you select a smaller number of series?

I'm not seeing any issues with using Season Pass to monitor the latest season in my testing (only 46 seasons).

**Comment by Cruv** [comment] 2018-04-30 13:46
On the series detail page of any show that is continuing, it has the series as monitored, with the season monitored. The episodes are monitored up to the latest aired episodes as of the time I last used the series editor to change them to 'Latest Season'. So for example the last time I ran that operation was 4/26/2018 and the episodes that aired the next day are all un-monitored despite the fact they have all aired and should be part of the 'Latest Season' classification.

The number of series I have are as below.
Series: 464
Ended: 189
Continuing: 275

When I use Season Pass I try to only update 50 at a time, but maybe I should try less? Either way I have done this test on just 1 show as a control and it is also not updating the monitor status of episodes once they have aired.

**Comment by Cruv** [comment] 2018-05-01 13:44
So using the LinuxServer.io docker image with the devolop tag, it seems to have fixed the issue. I added a series using the Latest Season setting and it is now marking the correct episodes as monitored. I think when I added all my series to Sonarr I went too quickly and made something bug out. If a dev doesn't think this is a bug or reproducible we can close this.

**Comment by markus101** [comment] 2018-05-03 07:07
Tried again to repro and still working as expected. Glad to hear it's working for you as well. Closing this out.

**Closed by markus101** 2018-05-03 07:07 UTC

**Comment by secjoe88** [comment] 2019-03-12 06:44
I'd like to follow up on this, as I'm experiencing this issue as well. 

## Bug Report
### System Information
**Sonarr Version:**
2.0.0.5301
**Operating System:**
Debian 
**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono version 5.14.0.177

### What problem are you looking to solve?
I cannot use Season Pass to monitor "unaired" episodes of a selected series.

### Steps to Reproduce
1. Navigate to the Season Pass page and select a series (in this case, The Magicians (2015)). From the "Monitor Episodes" dropdown, select "Future". Click "Update Selected Series". <img width="1440" alt="Screen Shot 2019-03-11 at 11 03 24 PM" src="https://user-images.githubusercontent.com/2219156/54179031-d7cd2c00-4454-11e9-8b39-c57d1bfdb359.png">

2. Navigate to the overview page for the series (In this case, The Magicians (2015)): 
![screengrab_future](https://user-images.githubusercontent.com/2219156/54179209-5d50dc00-4455-11e9-98d6-c2714c3bc6eb.jpg) Note that "unaired" episodes in the current season are **not** listed as monitored

3. Navigate back to the Season Pass page and select the same series (In this case, The Magicians (2015)). This time, from the "Monitor Episodes" dropdown, select "Latest Season". Click "Update Selected Series". <img width="1440" alt="Screen Shot 2019-03-11 at 11 06 01 PM" src="https://user-images.githubusercontent.com/2219156/54179455-13b4c100-4456-11e9-8603-c8113bad6c6a.png">

2. Navigate back to the overview page for the series (In this case, The Magicians (2015)): ![screengran_latest](https://user-images.githubusercontent.com/2219156/54179598-773eee80-4456-11e9-9a61-53b5e6d3b724.jpg) Note that "aired" episodes in the current season are now monitored, but "unaired" episodes in the current season are _still_ listed as **not** monitored.

### Expected Behavior 
Selecting either "Latest Season" or "Future" from the "Monitored Episodes" dropdown on the Season Pass page should update "unaired" episodes for the selected series to the "Monitored" state.

**Comment by markus101** [comment] 2019-03-12 07:46
We've made changes in v3 which should improve this behaviour, which includes what would be breaking API changes so they will not be backported to v2. No plans to spend time on investigating this in v2,
