### ISSUE TITLE
Compatability with DSM 7.0 / Download Station 3.9.0+

### ISSUE THREAD

**Issue by Rajackar** [Sonarr/Sonarr#3943] opened 2020-09-08 14:52 UTC
**Describe the bug**
After upgrading the Synology NAS to the 7.0 preview version the new download station seems to break compatibility with Sonarr
When connecting to DS the error is " The requested method does not exist"

**System Information**

 - Sonarr Version: both latest 2 and 3 branches
 - Operating System: DSM 7.0

Looks like this is DSM / DS breaking things but more people might run in to this as the new version becomes more widespread as the preview was released today.

I'd be happy to supply more information.

**Comment by bakerboy448** [comment] 2020-09-08 14:54
Grab the Sonarr trace logs for the request to DownloadStation and DS 3.9.0+ Trace logs (if possible) as well.

Sounds like they changed something

**Comment by Rajackar** [comment] 2020-09-08 15:12
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5189176/sonarr.txt)

Here's the log. Looks to me like the error is in there. Let me know if you need more.
Thanks for looking in to this :)

**Comment by markus101** [comment] 2020-09-08 16:43
It shows the error, but they aren't debug or trace logs. Enable trace logs and upload those.

**Comment by Rajackar** [comment] 2020-09-15 17:29
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5226687/sonarr.trace.txt)

Yeah, I was messing with the SSL settings to see if that made a difference. I've now attached the trace log.

**Comment by Rajackar** [comment] 2020-09-28 07:33
Just checking it to see if all needed information is now supplied.
Can I help out with anything else?

**Comment by thezoggy** [comment] 2020-09-29 23:40
per your logs, looks like defaults were loaded ? (config dir changed?) and then diskstation ssl isnt working due to selfsigned cert which wont pass verification check, so in sonarr disable strict checking for local, settings > general > Certificate Validation

**Comment by Rajackar** [comment] 2020-09-30 13:24
Yes, I just spun up a new container just for testing.
Still getting the same errors after turning off the validation.
Included a new trace log.
[sonarr.txt](https://github.com/Sonarr/Sonarr/files/5305801/sonarr.txt)

**Comment by bakerboy448** [comment] 2020-09-30 13:31
It looks like the username and password were not cleansed in the API call see line 20-9-30 11:15:38.9|Trace|HttpClient|  @ team sonarr, should this not be censored?

But the pertinent information in the logs is this
20-9-30 11:15:38.9|Trace|HttpClient|Response content (38 bytes): {"error":{"code":103},"success":false}
20-9-30 11:15:38.9|Debug|DownloadStationInfoProxy|Trying to login
20-9-30 11:15:38.9|Error|DownloadStationInfoProxy|Failed to login. Reason: The requested method does not exist
20-9-30 11:15:38.9|Error|TorrentDownloadStation|Error testing Torrent Download Station
[v3.0.3.928] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist

**Comment by matrixn** [comment] 2020-10-12 01:29
maybe this will help someone here to find a fix. I am having same problem. The ideea is that, it works if you change the API url version to 3 instead of 2 like this:

https://xxx.synology.me:8001/webapi/entry.cgi?api=SYNO.API.Auth&version=2&method=login&account=xxxx&passwd=xxx&format=sid&session=DownloadStation

for the first url i get this json response {"error":{"code":103},"success":false}

but if i change version=2 with version=3 then i get this response:
{"data":{"did":"cCA8GcGP8etA6C9RbaTu5orAHzpugeSmQamyW6PiHN0kPRANo0tWvedjHzWIYBFtjB6UjsnMcd7nTItKmvyFcSOKNRqtsY7lAu8gxjDVBR7B66ndHDpZxbO35SWoYCM","sid":"zZvcUzPTPIR4A5ikTC_AaoMk6yOgThBB5RtztlBesbwu_lSUxvVQIOWVTXOjnzYqVcMH6xeOgXpzuXMv2ghUnY"},"success":true}

now, can someone tell me if we can chage the version from within sonarr?

**Comment by bakerboy448** [comment] 2020-10-14 12:45
@markus101  looks like based on the above json they just changed the API version?

**Comment by Rajackar** [comment] 2020-10-22 09:54
Any more information on this that I could provide?

**Comment by markus101** [comment] 2020-10-26 00:13
It's more complicated than that, some requests use `version=1`, this one uses `version=2`, someone with DSM 7 access will need to investigate further (and ensure backwards compatibility with DSM 6).

**Comment by behold81** [comment] 2020-12-09 16:01
> It's more complicated than that, some requests use `version=1`, this one uses `version=2`, someone with DSM 7 access will need to investigate further (and ensure backwards compatibility with DSM 6).

Surely the answer is to add a field to the setup of the downloaders for API Version. this can be pre filled by the presets and altered if needed?

**Comment by bakerboy448** [comment] 2020-12-09 17:55
You asking for information most non-technical users will have any idea what it is or where to find it....a support nightmare

**Comment by behold81** [comment] 2020-12-09 18:03
Then setup 2 synology templates. Dsm7.0+ and one all other DSM.

**Comment by markus101** [comment] 2020-12-09 18:15
Different endpoints use different versions, so a "field" wouldn't be possible (excluding the support pain it'd be).

> Then setup 2 synology templates. Dsm7.0+ and one all other DSM.

Two problems with this, people upgrading would have to delete and re-add, which would not be understood. People would have to choose the correct version, people will absolutely fail at doing this.


A field or multiple clients is almost certainly not the solution, we don't know what needs to be done to support DSM 7, but for other clients we're able to automatically deal with multiple versions. We'll have a better idea once someone gets it working with DSM 7 and we can compare what we need to do.

**Comment by behold81** [comment] 2020-12-09 19:13
Well I am happy to be a tester if needed. Not sure I can help code. But capable to run technical captures or extracts as needed.

**Comment by thezoggy** [comment] 2020-12-09 23:45
also to note DSM7 still isnt released yet, only in beta/preview stage

**Comment by behold81** [comment] 2020-12-10 15:18
It might be beta but more and mor will move to it as it’s very stable and night and day over 6.2

**Comment by thezoggy** [comment] 2020-12-11 01:52
well to note, sab and other apps dont work with dsm7 either.

**Comment by brissou** [comment] 2020-12-12 23:21
Hy folks ! I've installed sonarr on DSM7 with same missing method Error. 
I let you tell me how I can Help you to find the good way to fix it.

**Comment by LynxMukka** [comment] 2020-12-14 09:41
Just to say having installed Sonarr v3 with DSM 7.0/Download Station, I'm also having the same issue.

**Comment by bakerboy448** [comment] 2020-12-14 09:45
> Just to say having installed Sonarr v3 with DSM 7.0/Download Station, I'm also having the same issue.

A simple +1 on the original issue will suffice

We know it doesn’t work there is nothing productive to gain from saying me too it’s broke

**Comment by chipped** [comment] 2020-12-23 00:06
Just came here to say I have the same issue. Sonarr with DSM 7.0 Beta.

I know I could just +1 but you know what they say, the squeaky wheel gets fixed :)

**Comment by markus101** [comment] 2020-12-23 01:26
If you don’t have anything valuable to add, 👍 on the issue. People don’t need alerts for your “me too” post.

**Comment by xxbiohazrdxx** [comment] 2021-01-22 00:13
> It's more complicated than that, some requests use version=1, this one uses version=2, someone with DSM 7 access will need to investigate further (and ensure backwards compatibility with DSM 6).

I've attached the output of `GET /webapi/query.cgi?api=SYNO.API.Info`

Looks like `Syno.API.Auth.maxVersion` is bumped up to 7. I can confirm on a DSM 6 device that maxVersion is 6. So it appears that this value directly correlates to the major version of DSM.

Honestly, the weird thing here is that `SYNO.API.Auth` still has a minVersion of 1, so any auth requests should still succeed. Doesn't appear that they renamed the method, becase as @matrixn said, if you take the raw request and just change version from 2 to 3, it succeeds.

It may just be that simple as adding a check in the NzbDrone DownloadStation proxy to check for `Syno.API.Auth.maxVersion == 7` and go from there.

[Query-Syno.Api.Info.txt](https://github.com/Sonarr/Sonarr/files/5852774/Query-Syno.Api.Info.txt)

**Comment by xxbiohazrdxx** [comment] 2021-01-22 02:13
I can also confirm that auth with `version=3` does work on DSM6

**Comment by carlogarro** [comment] 2021-02-02 11:49
@xxbiohazrdxx can we make this change once sonarr is installed or it has to be done before?

**Comment by xxbiohazrdxx** [comment] 2021-02-02 20:34
No this is not a setting that can be changed in a config file, it’s in the code so would need to be compiled

**Comment by RobertoPeters** [comment] 2021-02-04 16:19
I will stay on DSM 7.0 and I really would like to see this in the preview (docker image). And in order for us to test DSM 7.0/Download Station in combination with sonarr (docker), we need this in the preview (V3).
Would it be an option to have it configurable and maybe as an environment setting (docker setting e.g.)?
I use Download Station already and just to install another one to use it with sonarr seems overkill and not really desired.

**Comment by RobertoPeters** [comment] 2021-02-04 16:35
@bakerboy448 ok, you don't agree. But what is the plan? What do you (as member of the team) suggest?

**Comment by bakerboy448** [comment] 2021-02-04 16:39
> If you don’t have anything valuable to add, 👍 on the issue. People don’t need alerts for your “me too” post.

saying to effect “this is needed” is not beneficial to the issue at hand. same for any further discussions that are not to the point at hand

this thread is slowly heading towards the no valuable discussion => locked train.

To your question, I defer to Markus’s earlier comment:
> We'll have a better idea once someone gets it working with DSM 7 and we can compare what we need to do.

**Comment by devSparkle** [comment] 2021-02-06 11:49
After looking into this a bit and comparing DSM 6.1 to DSM7 I can affirm that the `SYNO.API.Auth` is no longer available with any version below v3, although this is not yet reflected in the `minVersion` as mentioned above. It's worth noting that when V1 was deprecated, this variable was not update either.

Despite the (very poor) documentation by Synology, I've gathered that there have been no significant changes to the Auth API in question, other than incrementing the number with each DSM version (go figure). Changing this to v3 will remove compatibility from DSM 2, although it's worth noting that the last version of DSM 2 (v2.3-1167) was released in 2014; and is no longer supported. It appears there are no devices stuck in this version, as Synology seems to have provided software upgrades to its entire range at the time to at least DSM 4.1.

There should be no negative impact in committing the change suggested by @xxbiohazrdxx.

> We'll have a better idea once someone gets it working with DSM 7 and we can compare what we need to do.

While I am unsure of any other issues that may arise with other Synology APIs that Sonarr may use, it seems clear to me that the change suggested above will not have any sort of negative impact and will fix the immediate issue, which would in turn allow current DSM 7 users to attempt to use the updated version and report back any further problems.

Let me know if there is any other test you'd like me to make in order to address this, @markus101.

**Closed** 2021-02-07 13:05 UTC
Labels: download-client, enhancement

**Comment by carlogarro** [comment] 2021-02-09 10:56
How can we install sonarr:phantom-develop on Linux?
As far as I know, the default one is sonarr:phandom.

Thank you for your help.

**Comment by RobertoPeters** [comment] 2021-02-09 11:31
@carlogarro , I use docker preview release. And is working for me.

**Comment by carlogarro** [comment] 2021-02-09 11:38
Thanks, Roberto. Let's see if someone can help me without using docker. I had some problems in the past with docker and an external drive, and I prefer it that way.

**Comment by bakerboy448** [comment] 2021-02-09 12:01
@carlogarro phantom-develop is the latest v3 builds 

see the website for v3 downloads and instructions

**Comment by carlogarro** [comment] 2021-02-09 12:41
Hello @bakerboy448, I got to install phantom-develop.
It is working like a charm. Thanks for your excellent work!
