### ISSUE TITLE
file name settings per indexer

### ISSUE THREAD

**Issue by sjpotter** [Sonarr/Sonarr#4508] opened 2021-05-25 07:46 UTC
**Is your feature request related to a problem? Please describe.**

different indexers have files that come with different namings, which means a global setting doesn't work if one prefers to not always rename files and prefers to keep original filename if its "sane".

**Describe the solution you'd like**
the ability to set the file naming macro on a per indexer level instead of just at a global level.  It would be a checkmark "use global renaming rules" (default checked) and if not checked, we enable a section that mirrors the global setting.

**Describe alternatives you've considered**

I basically have to do a manual rename when I download badly named files by going into settings, changig them to what I want, and then going back to the tv series to do a rename and hope that I don't mess up and rename files I didn't mean to.

**Additional context**

**Comment by bakerboy448** [comment] 2021-05-25 08:24
Arguably a dupe of #926 and presumably same comments/rationale as there.

**Comment by sjpotter** [comment] 2021-05-25 09:04
I dont think its the same.  that's asking on a per series level vs what I'm asking is per source of files.

basically, many files that come from usenet are obfuscated.  They have to be renamed, otherwise they are mostly useless (even if one uses sonarr to create the kodi style nfo files, won't help, as it seems most programs don't parse said file.  users who mix sources either need a different naming rules for them (i.e. this request) or you are essentially telling them that they have to rename all files.  This would harm files sourced from torrents as it make them more annoying to reshare in future without effort to rename everything back.

**Comment by bakerboy448** [comment] 2021-05-25 09:15
Seeding back torrents is moot as hardlinks (or copies of your system is setup (or incorrectly setup) so as to not facilitate hardlinks) take care of that for continuing to seed 

it sounds like there is a very easy fix and will likely do exactly what you want: use original tile not original filename

https://wiki.servarr.com/Sonarr_Settings#Original

**Comment by sjpotter** [comment] 2021-05-25 13:44
I disagree, that this solution is a global fix.  As an example.  rarbg indexer mucks with the title, but not with the filenames, so I want it to stick to filenames, not title  i.e. this is exactly why a global solution doesn't work for me.

**Comment by markus101** [comment] 2021-05-25 14:54
We do not have plans to change naming based on the source.

**Closed by markus101** 2021-05-25 14:54 UTC

**Comment by sjpotter** [comment] 2021-05-25 15:46
so you reject the use case I describe?  or basically say, you dont really want users to ever use original filename and title and those are really just concessions that you don't want to support?  I've like to be told how to do the use case in a normal manner.  the only option I see is to rename everything away from original title / filename and that's not a great solution to me.

**Comment by bakerboy448** [comment] 2021-05-25 16:15
For usenet, both download clients have scripts that can be used to rename/deobfuscate files which may alternatively resolve your issue at the source.

SceneName has a specific special meaning and will not have the definition changed.

**Comment by sjpotter** [comment] 2021-05-25 16:41
example of where I should look for this?  I'd be ok with that.
