### ISSUE TITLE
Reset to Defaults - Qualities

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4046] opened 2020-10-29 01:49 UTC
**Describe the problem**
users can change qualities and not know the defaults if they break things.

**Describe any solutions you think might work**
Reset to Defaults button for Qualities
would require a new table to maintain the defaults?

**Additional context**
inspired by this post:
https://www.reddit.com/r/radarr/comments/jk0y9t/default_quality_definitions/

**Comment by markus101** [comment] 2020-10-29 01:56
Dupe of https://github.com/Sonarr/Sonarr/issues/3390

**Closed by markus101** 2020-10-29 01:56 UTC
