### ISSUE TITLE
Better workaround for TV shows with another language

### ISSUE THREAD

**Issue by Hollander1908** [Sonarr/Sonarr#4223] opened 2021-01-05 09:45 UTC
**Describe the problem**
For example: Dutch TV shows will have a English title on Sonarr. This will cause issues when Sonarr will look at the indexers for the episodes because the releases will have the Dutch title and it will give no results. I think this happens with a lot of Dutch, but also other languages than English, TV shows.

**Describe any solutions you think might work**
I checked TVDB's API and I saw it has translations. (With this example it has both eng and a nld title) I might be wrong but I think it's possible when a Language Profile in Sonarr is set to Dutch for example that it gets translation nld from the API. Then the show will have the Dutch title instead of the English one and Sonarr will find the episodes related to the TV show. If the Language Profile of the same show is set to English it will get translation eng and when it's set to French it will get the translation fre and so on. If there's only a eng translation, it will get that ofcourse. But I doubt that it won't have the original title. (In this case the Dutch one)

Also with this specific TV show it seems like its not getting the aliases, so that might be the problem while searching.
But I think this will be a better workaround. Because it will also have the right File/foldername.

**Additional context**
This is the response of the API and it shows you both the English translated title and the original Dutch one.
![Screenshot_12](https://user-images.githubusercontent.com/76997445/103630399-e053f800-4f41-11eb-8e2e-a0975af229f3.png)

And this will show you that it doesn't find the episodes, while the episodes are on the indexers. (I checked that myself)
This is because it searches for the English title because it doesn't know the original one.
![Screenshot_13](https://user-images.githubusercontent.com/76997445/103631062-d4b50100-4f42-11eb-92ad-15965c4f0a71.png)

**Comment by markus101** [comment] 2021-01-05 15:33
Dupe of https://github.com/Sonarr/Sonarr/issues/269

**Closed by markus101** 2021-01-05 15:33 UTC
