### ISSUE TITLE
Partial import of season pack for cross-seeded torrent can lead to import loop

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#5625] opened 2023-05-06 23:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

A season with 20 episodes is missing 5 random episodes (all 1080) and a season pack is available (also 1080) so grab the season pack. It imports the missing 5 random episodes as expected and throws errors for the other 15 about not being a quality upgrade which is also expected. The item never leaves the queue though...

Manually importing the entire season just throws errors about files already existing on disk (in the logs) and sits in queue

Manually changing the label in the download client removes it from queue since it otherwise wont leave the queue and seems to be the only option

Episodes it did import & rename (the 5 it filled in) still show as missing and the season requires a manual refresh to get it to pickup those episodes which now messes up history for it as well because they never where marked as imported and it just thinks they where placed on disk to be found. This also means no connects fire for the episodes because they where not technically imported

As you can see below "Also Imported", the existing ones where replaced and sent notifications but the original missing ones are all skipped because of this.

![image](https://user-images.githubusercontent.com/8321115/236650854-6878c672-c964-4429-8ae4-d1b33bcc509b.png)

Grabbed a screenshot where it shows destination already exists (because sonarr renamed and imported them) but never marked them as imported so it is just stuck..

![image](https://user-images.githubusercontent.com/8321115/236650993-d67c556f-674e-4921-8d11-a7c917880865.png)

### Expected Behavior

Mark an episode as imported when it is imported

### Steps To Reproduce

Explained in the "Current Behavior" section

### Environment

```markdown
- OS: Windows 10
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

They rotate out far to fast to catch when this happens

### Anything else?

I would test on v4 but unless this specific issue was fixed i dont see why v4 would act any differently.

**Comment by markus101** [comment] 2023-05-07 00:17
With season packs (or any multi-file release) the items aren’t removed from queue until after all episodes are imported.

In this instance the 5 episodes imported doesn’t satisfy all episodes in the season so it remains.

With season packs the queue shows all the episodes in the pack, regardless of some of those episodes being imported.

> Manually importing the entire season just throws errors about files already existing on disk (in the logs) and sits in queue

Without logs it’s impossible to say what lead to this result.

> Manually changing the label in the download client removes it from queue since it otherwise wont leave the queue and seems to be the only option

It’s one several options, you can also remove it from the download client or tell Sonarr to ignore it (remove via queue, but not remove from the client).

> Episodes it did import & rename (the 5 it filled in) still show as missing and the season requires a manual refresh to get it to pickup those episodes which now messes up history for it as well because they never where marked as imported and it just thinks they where placed on disk to be found. 


Of everything mentioned here, this is the only thing that might be an issue, if they were actually imported by Sonarr and somehow failed after importing. History events are added shortly after the file is imported and then notifications are sent (if configured).

As mentioned logs it’s impossible to say what happened, history is added as each file is imported, it doesn’t matter that some episodes weren’t imported.

**Comment by austinwbest** [comment] 2023-05-07 00:38
There is no history on the ones that where missing, they where not marked as imported. Changing the category and doing a refresh brings them all in as on disk instead of missing so it does import them and rename them.

I get why the other things happen so really I'm just discussing a possible fix for the ones that do not trigger the import finished code path

**Comment by markus101** [comment] 2023-05-07 02:41
If the file was imported to the folder by Sonarr, but there isn’t any history or linked episode file in the DB then something failed and I’d expect to see something in the logs about that.

Regardless of whether there is one file or 20 in a release each file is treated as it’s own import.

Trace logs roll by quickly, but debug or even info should have something.

**Comment by markus101** [comment] 2023-05-11 04:28
Interested in understanding the root cause of this issue, but without logs showing why the original import wasn't completed fully there isn't anything actionable. If you're able to get logs for this in the future we can re-open.

**Comment by bakerboy448** [comment] 2023-06-01 22:55
Debug logs with some details based on troubleshooting an import loop, hopefully enough to work through it a bit.

Context is:
- season pack grabbed `Archer.2009.S12.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX`
- x-seed finds and adds cross-seeded releases to sonarr's category
- not all episodes are an upgrade for on-disk
- Sonarr goes into a true infinite loop appearing to round-robin among the releases (given downloadId is changing based on the webhook payloads) never marking as imported.
![image](https://github.com/Sonarr/Sonarr/assets/55419169/6ff54530-812d-48be-a376-e48b14aaf271)

Problematic looping file is `Archer.2009.S12E04.Photo.Op.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX`

Obviously same release in the same category is an edge-case, but it'll be the same concept as OP.

ScreenVid of episode's history
https://cdn.discordapp.com/attachments/915419360938582067/1113955212344963072/firefox_HUm2uk41io.mp4
Snippets of (i) details
![image](https://github.com/Sonarr/Sonarr/assets/55419169/61121c09-9460-4f25-b62b-0a006c6dae4c)
![image](https://github.com/Sonarr/Sonarr/assets/55419169/18474b83-d778-45a6-bf11-82759a49d84b)


Logs

[new_5.txt](https://github.com/Sonarr/Sonarr/files/11630291/new_5.txt)
[new_6.txt](https://github.com/Sonarr/Sonarr/files/11630292/new_6.txt)
[new_4.txt](https://github.com/Sonarr/Sonarr/files/11630293/new_4.txt)

**Comment by austinwbest** [comment] 2023-06-01 23:18
Different scenario but same issue.

If the episodes where marked as imported one by one regardless of the packs overall outcome then the duplicate packs from cross seed wouldn't have triggered more imports since it would have known it already imported it (so it seems)

**Comment by markus101** [comment] 2023-06-02 00:16
> ScreenVid of episode's history

Post a screenshot, instead of requiring a video file to be downloaded.

> If the episodes where marked as imported one by one regardless of the packs overall outcome then the duplicate packs from cross seed wouldn't have triggered more imports since it would have known it already imported it (so it seems)

The files themselves are marked as imported, you can see that in history, but the download client is reporting two "different" files to Sonarr and Sonarr is trying to import them.

The problem is, currently Sonarr imports one, then it is told to import another, it checks that the last thing it imported wasn't from that download ID and imports it, then it gets back to the original file it imported and does the same thing and on and on.

Checking more than the last grabbed/last imported would likely be able to help here, but with two different "files" Sonarr is still likely going to import it twice because it's unaware they are the same thing without filtering on path alone which has it's own drawbacks for more common use-cases.

Having the cross-seeded releases in another category would prevent the chance that Sonarr imports it multiple times.

**Comment by bakerboy448** [comment] 2023-06-02 00:23
> Having the cross-seeded releases in another category would prevent the chance that Sonarr imports it multiple times.

yup already has the user fixing that which would largely fix that part of the cause.

Still of the video
![image](https://github.com/Sonarr/Sonarr/assets/55419169/28046f8e-24c4-441b-aedd-c5b8e5b3ec34)

**Comment by austinwbest** [comment] 2023-06-02 00:50
Thats true, so not the same as my original manual download import filling the gaps issue as mine where not even in history

**Closed** 2023-08-20 07:35 UTC
Labels: bug
