### ISSUE TITLE
Indexer stat tracker

### ISSUE THREAD

**Issue by Shredder5262** [Sonarr/Sonarr#3998] opened 2020-10-05 23:02 UTC
This is a Feature request, not an issue. 
I noticed a feature that the Mylar fork has that I found kind of nice. It has a running counter of what downloads are obtained per indexer. I think this would be useful to have in both Sonarr and Radarr to help end users determine what indexers are performing.

**Comment by markus101** [comment] 2020-10-05 23:03
Dupe of https://github.com/Sonarr/Sonarr/issues/323

**Closed by markus101** 2020-10-05 23:03 UTC

**Comment by Shredder5262** [comment] 2020-10-05 23:04
Didn't know this was mentioned already, thank you
