### ISSUE TITLE
Grab single episode releases for multi-episode files

### ISSUE THREAD

**Issue by rg9400** [Sonarr/Sonarr#6550] opened 2024-02-27 03:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is reopening the discussion for https://github.com/Sonarr/Sonarr/issues/4864 and https://github.com/Sonarr/Sonarr/issues/734. Since most networks have shifted to streaming services now, we are seeing a lot of older shows get re-released on new platforms. This often means that those streamers will split apart double-header episodes, but I've noticed Sonarr will completely miss those upgrades since it may have already imported a multi-episode file instead. There is no way for the user to know that a potential upgrade was completely missed, and thus a multi-episode file can actually act as a very hard block to Sonarr functionality.

### Describe the solution you'd like

I think Sonarr should grab individual episodes as upgrades for sure. When importing, it can require manual intervention from the user end to determine if they want to replace the multi-episode file, but this way, the release is not completely skipped. Ideally, Sonarr would also have some intelligence to determine if both (or however many) episodes mapped to the existing file have releases in the queue/pending manual import, then it should override that block and allow the upgrades through automatically. 

### Describe alternatives you've considered

The alternatives are to either not import multi-episode files, or to pay very close attention to each and every upgrade. That way, if you see a season being upgraded, you can verify if every episode was upgraded in that season, and if not, you can use the interactive search to upgrade the multi-episode file manually. However, this requires you to be aware that a file was missed. Since some of these shows have 20+ episodes, it is very easy to miss a particular episode, so you may never even know that an upgrade could be grabbed.

**Comment by markus101** [comment] 2024-02-27 03:22
Dupe of #734

No short term plans to put effort into this.

**Closed by markus101** 2024-02-27 03:22 UTC
Labels: needs-triage

**Comment by markus101** [comment] 2024-02-27 04:31
Thinking about this further, this has the same underlying requirements of https://github.com/Sonarr/Sonarr/issues/6378 and as long as it doesn't exclusively apply to season packs it'd work.
