### ISSUE TITLE
Sonarr deletes half the season while importing when there's no space left

### ISSUE THREAD

**Issue by ocr893sa** [Sonarr/Sonarr#3274] opened 2019-08-23 21:30 UTC
**Describe the bug**
Sonarr imported half the season and then proceeded to delete the rest when disk is full instead of waiting for more space.

**Logs**
https://pastebin.com/zHNB9bJx

**System Information**

 - Sonarr Version: [3.0.2.607]
 - Operating System: [Windows 8.1]
 - .net Framework (Windows)

**Additional context**
I run Sonarr and Radarr on my laptop and I don't have much space so I watch something and the delete it, but sometimes Sonarr gets more episodes that I'm able to watch. In this case Sonarr tried to import 22Gb of the season into my media hard drive that was at 10 free more or less, it imported 6 episodes and then threw a System.IO.IOException saying the disk is full and instead of waiting in the queue for more space Sonarr deleted the original season folder with the rest of the season with it

**Comment by markus101** [comment] 2019-08-23 21:38
Do you have Remove Completed Downloads enabled?

If so that is covered by https://github.com/Sonarr/Sonarr/issues/668

**Comment by ocr893sa** [comment] 2019-08-23 21:44
> Do you have Remove Completed Downloads enabled?

I do, should I disable it?

**Comment by markus101** [comment] 2019-08-23 21:50
Normally no, but it's the cause of the deletion, Sonarr initially didn't delete it because there were valid video files there, but the logic that determines if a download is complete only cares that one file is imported and tells your download client to delete the files because it's already completed.

At best Sonarr wouldn't have imported those files, but at worst they got deleted because it was done seeding.

Closing as this is already covered by the linked issue.

**Closed by markus101** 2019-08-23 21:50 UTC
