### ISSUE TITLE
Indexer improvement

### ISSUE THREAD

**Issue by edimusxero** [Sonarr/Sonarr#2996] opened 2019-03-14 13:40 UTC
Not really a bug but more of a suggestion.  From time to time Sonarr losses connection to indexers hosted on Jackett in which I have found the only way to fix it is to go through each individual indexer and click on test.  Resetting jackett and Sonarr does not solve it.  It would be super helpful to have a way to test ALL indexers without having to individually going through each one, I currently have 15 indexers so it gets a little tedious going through each one every time this happens.

**Comment by markus101** [comment] 2019-03-14 15:42
Please search before opening issues, including closed issues. This is a dupe of https://github.com/Sonarr/Sonarr/issues/2987 from just 3 days ago and ultimately a dupe of https://github.com/Sonarr/Sonarr/issues/2753

**Closed by markus101** 2019-03-14 15:42 UTC
