### ISSUE TITLE
Manual Import Failure

### ISSUE THREAD

**Issue by EternalDeiwos** [Sonarr/Sonarr#2929] opened 2019-02-01 08:32 UTC
**Describe the bug**
Doing a manual import of any anime fails (see logs). I've already eliminated permission related issues (ensured correct ownership and tested with `777` file permissions).

**System Information**

 - Sonarr Version: 2.0.0.5301
 - Operating System: Ubuntu Server 18.04.1 - 4.15.0-45-generic (via linuxserver/sonarr Docker Container)
 - mono Version: 5.18.0.240

**Logs**
```
[Trace] Http: Res: 2585 [GET] /api/manualimport?folder=%2Fdownloads%2F&sort_by=qualityWeight&order=desc: 200.OK (2714 ms)
[Debug] Api: [GET] /api/manualimport?folder=%2Fdownloads%2F&sort_by=qualityWeight&order=desc: 200.OK (2714 ms)
[Trace] Http: Req: 2586 [POST] /api/command
[Trace] CommandQueueManager: Publishing ManualImport
[Trace] CommandQueueManager: Checking if command is queued or started: ManualImport
[Trace] CommandQueueManager: Inserting new command: ManualImport
[Trace] CommandExecutor: ManualImportCommand -> ManualImportService
[Trace] Http: Res: 2586 [POST] /api/command: 201.Created (48 ms)
[Trace] CommandQueueManager: Marking command as started: ManualImport
[Debug] Api: [POST] /api/command: 201.Created (48 ms)
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Trace] ManualImportService: Manually importing 1 files using mode Move
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Trace] ManualImportService: Processing file 1 of 1
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Debug] Parser: Parsing string '[HorribleSubs] Some Anime - 04 [1080p].mkv'
[Trace] Parser: ^\[(?<subgroup>.+?)\][-_. ]?(?<title>.+?)(?:[. ]-[. ](?<absoluteepisode>\d{2,3}(\.\d{1,2})?(?!\d+|[-])))+(?:[-_. ]+(?<special>special|ova|ovd))?.*?(?<hash>\[\w{8}\])?(?:$|\.mkv)
[Debug] Parser: Episode Parsed. Some Anime - 004
[Debug] Parser: Language parsed: English
[Debug] QualityParser: Trying to parse quality for [HorribleSubs] Some Anime - 04 [1080p].mkv
[Debug] Parser: Quality parsed: HDTV-1080p v1
[Debug] Parser: Release Group parsed: HorribleSubs
[Debug] VideoFileInfoReader: Getting media info from /downloads/[HorribleSubs] Some Anime - 04 [1080p].mkv
[Trace] MediaInfo: Read file offset 0-311296 (311296 bytes)
[Trace] MediaInfo: Read file offset 392980494-393005922 (25428 bytes)
[Trace] MediaInfo: Read a total of 336724 bytes (0.1%)
[Debug] ParsingService: Using absolute episode number 4 for: Some Anime - TVDB: 1x04
[Debug] AggregateQuality: Using quality: HDTV-1080p v1
[Warn] ImportApprovedEpisodes: Couldn't import episode /downloads/[HorribleSubs] Some Anime - 04 [1080p].mkv

[v2.0.0.5301] System.ArgumentException: An empty file name is not valid.
  at System.IO.DirectoryInfo.CheckPath (System.String path) [0x00016] in <04750267503a43e5929c1d1ba19daf3e>:0
  at System.IO.DirectoryInfo..ctor (System.String path, System.Boolean simpleOriginalPath) [0x00006] in <04750267503a43e5929c1d1ba19daf3e>:0
  at System.IO.DirectoryInfo..ctor (System.String path) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0
  at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo..ctor(string)
  at NzbDrone.Common.Extensions.PathExtensions.IsParentPath (System.String parentPath, System.String childPath) [0x00060] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:92
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00000] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:60
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.GetOriginalFilePath (NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) [0x0006f] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:177
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x00263] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:105

[Trace] ManualImportService: Manually imported 1 files
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Trace] CommandQueueManager: Updating command status
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Trace] EventAggregator: Publishing CommandExecutedEvent
[Trace] EventAggregator: CommandExecutedEvent -> TaskManager
[Trace] EventAggregator: CommandExecutedEvent <- TaskManager
[Trace] EventAggregator: CommandExecutedEvent -> TaskModule
[Trace] EventAggregator: CommandExecutedEvent <- TaskModule
[Trace] CommandExecutor: ManualImportCommand <- ManualImportService [00:00:00.0390110]
```

**Additional context**
I can import other non-anime content without issue. I'm not sure if this is related to other import failure issues (like #2384) but from looking through their logs I don't think so.

I should also mention that this only started happening when I moved servers -- I took down the previous containers and put up new containers _after moving all of the existing configuration and databases across_. Again I'll stress that this is unlikely to be a file privileges issue; I made absolutely sure that the correct user and group IDs were used when restarting the containers.

**Comment by markus101** [comment] 2019-02-01 08:36
Are you using Manual Import from Activity Queue?

> /downloads/[HorribleSubs] Some Anime - 04 [1080p].mkv

Is this the exact file path (no other nested folders)?

**Comment by EternalDeiwos** [comment] 2019-02-01 08:43
That is the absolute path; should have mentioned that I'm running this in a docker container -- edited the OP to show that.

I agree that the fact that its anime is probably coincidental -- however in my experience so far only anime is affected. Maybe this is a bug specifically with anime processing? Or perhaps it's something about how anime files are typically named?

**Comment by markus101** [comment] 2019-02-01 17:16
At that point the format of the file name doesn't matter. Are the other files directly in the `/downloads` folder as well? Pretty sure the issue is there is only one folder from the root (a bug).

**Comment by EternalDeiwos** [comment] 2019-02-01 17:48
Which other files are you referring to? There are other things in `/downloads` such as other series.

I think you might be right about it being one folder from the root that's a problem. I moved the completed downloads into a temporary folder (`/downloads/tmp`) and they imported correctly.

**Comment by markus101** [comment] 2019-02-01 18:33
> Which other files are you referring to?

I meant the files that imported successfully.

> I moved the completed downloads into a temporary folder (`/downloads/tmp`) and they imported correctly. 

Okay great, I know what the issue is then.

**Comment by EternalDeiwos** [comment] 2019-02-02 06:34
Thanks @markus101. Looking forward to a patch release.

**Comment by markus101** [comment] 2019-02-03 21:10
The fix has been cherry picked to develop.

**Closed by markus101** 2019-02-03 21:10 UTC

**Comment by aheavin** [comment] 2019-03-16 19:01
@markus101 Did you submit a pull request? I am still experiencing this issue but couldn't tell if you had submitted a change yet.
