### ISSUE TITLE
Prev / Next Show Buttons

### ISSUE THREAD

**Issue by davidpearce** [Sonarr/Sonarr#1660] opened 2017-02-05 01:11 UTC
Could we please have a Prev / Next Show button when on a show page ( /series/xxxxxx ) so that we can quickly move to the next show in our library?

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment] 2017-02-05 02:58
Dupe of https://github.com/Sonarr/Sonarr/issues/827

**Closed by markus101** 2017-02-05 02:58 UTC
