### ISSUE TITLE
DownloadStation broken after DSM7 update

### ISSUE THREAD

**Issue by lowrisk75** [Sonarr/Sonarr#4214] opened 2021-01-02 17:09 UTC
After DSM7 Update, Synology DownloadStation stoped worked:

"Failed to get the list of torrents: Failed to login. Reason: The requested method does not exist
Unknown exception: Failed to login. Reason: The requested method does not exist"

if using 127.0.0.1 instead of the the NAS IP then
"Unknown exception: Unable to connect to Diskstation, please check your settings"

**Comment by bakerboy448** [comment] 2021-01-02 17:28
Duplicate of #3943

1) please use the search functionality prior to opening issues
2) if you’re using a 3rd party GH app, don’t... they ignore templates
2b) if you didn’t use a 3rd party GH app, don’t blow away the damn template

**Closed by bakerboy448** 2021-01-02 17:28 UTC
