### ISSUE TITLE
Limit indexers for a show

### ISSUE THREAD

**Issue by douglas24** [Sonarr/Sonarr#3265] opened 2019-08-16 04:36 UTC
**The request**
There is currently no way to limit what indexers sonarr will search for each show. I would like to be able to customize by show which indexer(s) sonarr searches (e.g. RARBG for most shows, but sometimes MVGroup or TPB for documentaries).

**Solution I think might work**
Add customization option when adding/editing a show to pick ALL or specific indexers currently added to sonarr.

**Comment by markus101** [comment] 2019-08-16 05:49
Dupe of https://github.com/Sonarr/Sonarr/issues/487

**Closed by markus101** 2019-08-16 05:49 UTC
