### ISSUE TITLE
Add First Episode Only

### ISSUE THREAD

**Issue by rjcogin** [Sonarr/Sonarr#3954] opened 2020-09-12 11:22 UTC
Hello, I would love to have the option to add only the first episode of a series.
This would be great with the new lists feature so doesn't download a whole season of a show that you might not like.

Thanks for your time

**Comment by markus101** [comment] 2020-09-12 14:40
Dupe of https://github.com/Sonarr/Sonarr/issues/3768

**Closed by markus101** 2020-09-12 14:40 UTC
