### ISSUE TITLE
Lostfilm indexer filters out ' sign in the name

### ISSUE THREAD

**Issue by kekal** [Sonarr/Sonarr#4503] opened 2021-05-23 00:05 UTC
* **Env:**
   * Version: 3.0.6.1196
   * Package Version: 3.0.6.1196-ls104 by linuxserver.io
   * Mono Version: 5.20.1.34
   * Jackett Version: v0.18.98

</br>
</br>

* **Test title:**
https://www.thetvdb.com/series/jupiters-legacy

* **Generated query:**
`http://ds718:9117/api/v2.0/indexers/lostfilm/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Jupiters%20Legacy&season=1&ep=1`

   * **Result:**
   ```<?xml version="1.0" encoding="UTF-8"?>
   <rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
     <channel>
       <atom:link href="http://ds718:9117/" rel="self" type="application/rss+xml" />
       <title>LostFilm.tv</title>
       <description>Unique portal about foreign series</description>
       <link>https://www.lostfilm.run/</link>
       <language>en-us</language>
       <category>search</category>
     </channel>
   </rss>
   ```

* **Correct query:**
`http://ds718:9117/api/v2.0/indexers/lostfilm/results/torznab/api?t=tvsearch&apikey=(removed)&offset=0&limit=100&q=Jupiter%27s%20Legacy`
   * **Result:**
   ```<?xml version="1.0" encoding="UTF-8"?>
   <rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
     <channel>
       <atom:link href="http://ds718:9117/" rel="self" type="application/rss+xml" />
       <title>LostFilm.tv</title>
       <description>Unique portal about foreign series</description>
       <link>https://www.lostfilm.run/</link>
       <language>en-us</language>
       <category>search</category>
       <item>
         <title>Jupiter's Legacy - S1E2 - Paper and Stone  - rus WEBDL (LostFilm)</title>
         <guid>http://n.tracktor.site/td.php?s=A8eWz0A7vtnXn6NNqse24ug%2Bmbbg4IzaRqCggkaaqekAE4CT5AmOEHcy%2BJeUKaApguK%2FYrkjGA7GR3PstegIxKPOX0VQmtd8qVdK8TskfTTyxW71iJ4DNc%2B%2B6CZTThB6</guid>
         <jackettindexer id="lostfilm">LostFilm.tv</jackettindexer>
         <comments>https://www.lostfilm.run/series/Jupiters_Legacy/season_1/episode_2/</comments>
         <pubDate>Wed, 05 May 2021 00:00:00 +0000</pubDate>
         <size>515112960</size>
         <description />
         <link>http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRZRzd6a1R4c3FmM2p0T1oyRzJKNFJsWGR5dHlCcmJWRC1aY0UzaERKSWJEaXpndUtGQmR6aE1TckkydXlwd29uVHB1YlhsOXlwdmdSdV9VUTdJY05VTDRBMlJmUloyU1lHdGltLU5xcEdaWjV5eEpJLU9zelBMZHB3eG84NnltZGdFS2JHclFRdjFUWm4ySXlYemtZam1iS1YtcFFIR0lHR0pOWkt2SGppU1hWT3JJdkVCbEJFTG1CS0N4ZWJxY2tsclhYWVVQMXJDWmVQQnRjQ2Q0bWtTbjJxeDlUT1BNUkVmeGlPR2ZJeWt1TEMxcHdzYTBrUE9fTnhVMFNWZlB4bmdkVHJBMURodncyM0RLaThjc2d2RUM2d0NqVVg4d2dCZnJWbk5BUW9sWURRdTNxZ2hLVlR5cmlyT3dJUGpFaUU&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+WEBDL+(LostFilm)</link>
         <category>5000</category>
         <enclosure url="http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRZRzd6a1R4c3FmM2p0T1oyRzJKNFJsWGR5dHlCcmJWRC1aY0UzaERKSWJEaXpndUtGQmR6aE1TckkydXlwd29uVHB1YlhsOXlwdmdSdV9VUTdJY05VTDRBMlJmUloyU1lHdGltLU5xcEdaWjV5eEpJLU9zelBMZHB3eG84NnltZGdFS2JHclFRdjFUWm4ySXlYemtZam1iS1YtcFFIR0lHR0pOWkt2SGppU1hWT3JJdkVCbEJFTG1CS0N4ZWJxY2tsclhYWVVQMXJDWmVQQnRjQ2Q0bWtTbjJxeDlUT1BNUkVmeGlPR2ZJeWt1TEMxcHdzYTBrUE9fTnhVMFNWZlB4bmdkVHJBMURodncyM0RLaThjc2d2RUM2d0NqVVg4d2dCZnJWbk5BUW9sWURRdTNxZ2hLVlR5cmlyT3dJUGpFaUU&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+WEBDL+(LostFilm)" length="515112960" type="application/x-bittorrent" />
         <torznab:attr name="category" value="5000" />
         <torznab:attr name="seeders" value="1" />
         <torznab:attr name="peers" value="2" />
         <torznab:attr name="minimumratio" value="1" />
         <torznab:attr name="minimumseedtime" value="172800" />
         <torznab:attr name="downloadvolumefactor" value="0" />
         <torznab:attr name="uploadvolumefactor" value="1" />
       </item>
       <item>
         <title>Jupiter's Legacy - S1E2 - Paper and Stone  - rus 1080p WEBDL (LostFilm)</title>
         <guid>http://n.tracktor.site/td.php?s=NVMV6YkRPShHumUdZ6jltqlQE4RRP3NEnDC4b48JHhJ3ethO4I5ErcDrXUmhX2KxwJM2WCyAhRKx6a9YpnxKf%2BTaTTVhMAciKO6g8qfHMeGY6RoshMxoD75Eq6TvLmum</guid>
         <jackettindexer id="lostfilm">LostFilm.tv</jackettindexer>
         <comments>https://www.lostfilm.run/series/Jupiters_Legacy/season_1/episode_2/</comments>
         <pubDate>Wed, 05 May 2021 00:00:00 +0000</pubDate>
         <size>1954210176</size>
         <description />
         <link>http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRhV3czN004Yk5YdGZXaFZCanRJdTNTakRNVXhUanFUeXA5YXpCSHNQa2tCa0R5SHFQQ1Myb2hFNjN6RkFGekNsTERWY3JDdFVjZWx3TWFVZHhrQnpKYVlZQjNING9WMnQwejZyOTNZTEZEc1BsY0tqN1k1N1hTTGtoVVhNS1ZZa20xYUdDRnZveDhtaWlVNHVKYk1FdjRTRUt6QmF1UEZUWHpQOURLdjZDakxZRVFEVXhQTmd3YXFndGV4NkdaMFk3WTgxSWZqRDVpcTlKTDB0VWYyN2RoU2NYWGNXZjBCYWtqNkc0My1aUFFybFhfREd1TUdhcFJEZV9JN2NTblBvMVVycUVsYzEwRmtrNjU1aUNDSlcwSnZmSFNyQ082eHFveE13T1BsckJ1Njl6YklYNUstNXJ0Q3VCOThqV2UwbUE&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+1080p+WEBDL+(LostFilm)</link>
         <category>5000</category>
         <enclosure url="http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRhV3czN004Yk5YdGZXaFZCanRJdTNTakRNVXhUanFUeXA5YXpCSHNQa2tCa0R5SHFQQ1Myb2hFNjN6RkFGekNsTERWY3JDdFVjZWx3TWFVZHhrQnpKYVlZQjNING9WMnQwejZyOTNZTEZEc1BsY0tqN1k1N1hTTGtoVVhNS1ZZa20xYUdDRnZveDhtaWlVNHVKYk1FdjRTRUt6QmF1UEZUWHpQOURLdjZDakxZRVFEVXhQTmd3YXFndGV4NkdaMFk3WTgxSWZqRDVpcTlKTDB0VWYyN2RoU2NYWGNXZjBCYWtqNkc0My1aUFFybFhfREd1TUdhcFJEZV9JN2NTblBvMVVycUVsYzEwRmtrNjU1aUNDSlcwSnZmSFNyQ082eHFveE13T1BsckJ1Njl6YklYNUstNXJ0Q3VCOThqV2UwbUE&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+1080p+WEBDL+(LostFilm)" length="1954210176" type="application/x-bittorrent" />
         <torznab:attr name="category" value="5000" />
         <torznab:attr name="seeders" value="1" />
         <torznab:attr name="peers" value="2" />
         <torznab:attr name="minimumratio" value="1" />
         <torznab:attr name="minimumseedtime" value="172800" />
         <torznab:attr name="downloadvolumefactor" value="0" />
         <torznab:attr name="uploadvolumefactor" value="1" />
       </item>
       <item>
         <title>Jupiter's Legacy - S1E2 - Paper and Stone  - rus 720p WEBDL (LostFilm)</title>
         <guid>http://n.tracktor.site/td.php?s=%2BD6EsUEKj5Err0V0R8WmvNsmqigC%2Brdu5HCq%2FYhpNHMU0hbKcnW%2FaKWEDfDLxdjPKR0mToKapUc2N1ofA5wxByNqMRZpTZcmx%2BTwveNiEImCeMOYVjFL%2BPMwqQwA1V8U</guid>
         <jackettindexer id="lostfilm">LostFilm.tv</jackettindexer>
         <comments>https://www.lostfilm.run/series/Jupiters_Legacy/season_1/episode_2/</comments>
         <pubDate>Wed, 05 May 2021 00:00:00 +0000</pubDate>
         <size>1105954048</size>
         <description />
         <link>http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRhTFp0WVhtRkVEMkMwQkI4ZE5PRDZDNGdiR1hlcUpsQXJTbUlEajJYSFNYUWZURlpLT28wOVpjY3ZBVl9DRHdxLXloR0RmcXRXczV5dGJFVzRUWVBrRHdkMnNDdzV2TGN5NERJWU1tc3RQNjdNRU11ek5lMWxQbUxGNmtBd0Z1ZUhlRmphNGhHbmh3cGNnOUtSSWg0S0M3WjBjUUQ3VWVWT0ZiNVZDM29pV09McEFPcnVyc3UtRXBsSG94Z2F3emlieTdkSWtWaEs5VDdsalREZkJjY3pzUmtlOWRUenROVGZvc3JyQkVXM2N2XzIwY2tfczB3dlZvdjY0ZjhNdS13bTc1Vk1yQUlmUjA4cDRKVG9mZTYtSWJXbGtLN2tfYTgxWGtlQW80aEhOb0dWbm4xNm5TQVJYLUlRTElDZGhxTFU&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+720p+WEBDL+(LostFilm)</link>
         <category>5000</category>
         <enclosure url="http://ds718:9117/dl/lostfilm/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&amp;path=Q2ZESjhPMGlfYlY0VVhCTnBJLVJVLUNCMGRhTFp0WVhtRkVEMkMwQkI4ZE5PRDZDNGdiR1hlcUpsQXJTbUlEajJYSFNYUWZURlpLT28wOVpjY3ZBVl9DRHdxLXloR0RmcXRXczV5dGJFVzRUWVBrRHdkMnNDdzV2TGN5NERJWU1tc3RQNjdNRU11ek5lMWxQbUxGNmtBd0Z1ZUhlRmphNGhHbmh3cGNnOUtSSWg0S0M3WjBjUUQ3VWVWT0ZiNVZDM29pV09McEFPcnVyc3UtRXBsSG94Z2F3emlieTdkSWtWaEs5VDdsalREZkJjY3pzUmtlOWRUenROVGZvc3JyQkVXM2N2XzIwY2tfczB3dlZvdjY0ZjhNdS13bTc1Vk1yQUlmUjA4cDRKVG9mZTYtSWJXbGtLN2tfYTgxWGtlQW80aEhOb0dWbm4xNm5TQVJYLUlRTElDZGhxTFU&amp;file=Jupiter%27s+Legacy+-+S1E2+-+Paper+and+Stone%C2%A0+-+rus+720p+WEBDL+(LostFilm)" length="1105954048" type="application/x-bittorrent" />
         <torznab:attr name="category" value="5000" />
         <torznab:attr name="seeders" value="1" />
         <torznab:attr name="peers" value="2" />
         <torznab:attr name="minimumratio" value="1" />
         <torznab:attr name="minimumseedtime" value="172800" />
         <torznab:attr name="downloadvolumefactor" value="0" />
         <torznab:attr name="uploadvolumefactor" value="1" />
       </item>
     </channel>
   </rss>
```

**Comment by bakerboy448** [comment] 2021-05-23 00:16
Duplicate of:
- #1225
-  #4374 
-  #3520
-  #3457
Please search prior to posting.

Generally speaking this is best resolved between the indexer & jackett

**Closed by bakerboy448** 2021-05-23 00:16 UTC

**Comment by kekal** [comment] 2021-05-23 00:32
@bakerboy448 
I searched twice for LostFilm, not for apostrophes, sorry.
The category in the query does not make any difference to the result in this case. It is enough to add an apostrophe, and Jackett will return 3 results. 
It looks like #1225 have no chances to be fixed...

Anyway, thanks.
