### ISSUE TITLE
Enhancement: Manual Season Search

### ISSUE THREAD

**Issue by Quiksmage** [Sonarr/Sonarr#1888] opened 2017-05-01 16:03 UTC
Hello,

I'm coming from a torrent perspective.
I'm currently using the **other** TV downloader. One thing that is keeping me from swapping to Sonarr is the download handling and how that effects shows that have already long since aired. 

As it currently stands, when I add an previously airing show, I manually go and grab the season/s that have already aired in my preferred format/quality/release/scenename/etc. It gets dropped in a postprocess directory which, the downloader, tries to match file names to shows. 

From my understanding this is the Drone Factory in Sonarr, correct? From what I've read on it, it seems to be a legacy function which everyone is being urged away from. 

So, in the case of adding a show where a whole season has aired, or say, i would like to grab a new quality of a specific release, I would like to suggest adding the ability to "manual search" at the season level so that we can add our particular full season directly into our torrent client, giving us the ability to pick the release from inside the interface.

I'm unsure if the way it's currently coded makes this difficult to add or not, but thanks for reading :).

**Comment by markus101** [comment] 2017-05-01 17:14
Dupe of https://github.com/Sonarr/Sonarr/issues/266

**Closed by markus101** 2017-05-01 17:14 UTC
