### ISSUE TITLE
Downloading and uploading file during renaming

### ISSUE THREAD

**Issue by agneevX** [Sonarr/Sonarr#3373] opened 2019-11-03 12:17 UTC
My media files are stored in Google Drive and they're mounted with `rclone`. 
Instead of creating folders and moving the files to them or _just_ renaming the files, Sonarr v3 is downloading media files from the server and uploading it simultaneously, causing hundreds of gigabytes of bandwidth transfer unnecessarily. 

**System Information**
 - Sonarr Version: 3.0.3.652
 - Operating System: Ubuntu 18.04
 - mono Version: 6.4.0.198

**Comment by markus101** [comment] 2019-11-03 16:03
Please include trace logs.

If they are different mounts this is expected to avoid issues with cross-mount moving of files. Similarly it’s expected when files are on certain mount types.

In both cases this is to deal with truncated files while running under mono.

**Comment by agneevX** [comment] 2019-11-03 17:31
@markus101 It's in the same mount, using FUSE.

**Comment by agneevX** [comment] 2019-11-03 17:57
For testing purposes, I installed Sonarr v3 on a Windows machine where Drive File Stream runs... I renamed a single file and Sonarr ended up trashing the file :(

**Comment by markus101** [comment] 2019-11-04 01:43
IIRC if the mount type is Network then that’ll happen, due to the known truncation issues, but I believe others have solved this in their setups (not sure how offhand).

On Windows this behaviour is different, debug logs would be the first place to see what happened.

**Comment by 3a07d0c540** [comment] 2019-11-11 15:46
Are you running through docker? Try downgrading mono to 5.2.

**Comment by agneevX** [comment] 2019-11-12 14:53
> Are you running through docker? Try downgrading mono to 5.2.

Nope. Ubuntu 18.04.

**Comment by 3a07d0c540** [comment] 2019-11-12 15:02
> 
> 
> > Are you running through docker? Try downgrading mono to 5.2.
> 
> Nope. Ubuntu 18.04.

Ok, uninstall mono v6.4 from your system and install v5.2. There's a bug or some unintended behavior in mono v6 that causes the behavior you see.

I ran into the same problem you're having and downgrading to 5.2 fixed it.

**Comment by markus101** [comment] 2019-11-12 16:28
Mono 5.20, not 5.2, those are very different versions and 5.2 has it's own issues.

**Comment by 3a07d0c540** [comment] 2019-11-12 16:46
> 
> 
> Mono 5.20, not 5.2, those are very different versions and 5.2 has it's own issues.

Fixed, thank you

**Comment by agneevX** [comment] 2019-11-12 16:49
> Ok, uninstall mono v6.4 from your system and install v5.20.
How do I do that?

**Comment by markus101** [comment] 2019-11-16 08:11
You'd need to remove the mono packages and then explicitly install mono 5.20, you'll probably need to remove Sonarr/other packages that rely on mono to do that, then install again after mono.

I don't have specific steps, but IIRC there was a post on the forums or google will have generic instructions I'm sure.

**Comment by markus101** [comment] 2019-11-30 19:34
This should be fixed via https://github.com/Sonarr/Sonarr/commit/95d64208d0b803502bd2f255661e1b093ab69120

**Closed by markus101** 2019-11-30 19:34 UTC

**Comment by agneevX** [comment] 2019-12-02 06:50
Does this mean that rename won’t cause the file to be completely downloaded and completely uploaded with the new file name in the cloud drive?

**Comment by agneevX** [comment] 2019-12-02 10:04
From Google Drive web UI I can see that the original file is trashed (presumably after Sonarr downloaded it) and then the renamed file is uploaded.

**Comment by markus101** [comment] 2019-12-04 16:11
That behaviour could come down to how move through mono is handled. Mono 6 changed things from mono 5 as well. Trace logs will show exactly what Sonarr tried to do. With the fix above you should not see `Attempting to move hardlinked backup` in the logs when transferring on the same volume or using a mergefs/rclone mount.
