### ISSUE TITLE
[Feature Request] Use NZB from manual search when Sonarr isn't able to parse the episode from release name.

### ISSUE THREAD

**Issue by Grimeton** [Sonarr/Sonarr#1826] opened 2017-04-08 14:23 UTC
Hi,

when Sonarr is not able to parse the episode from the release name it would be nice to be able to download the NZB anyway without having to go to the website. But the Download option is missing at the right side of the manual search results list:

![grafik](https://cloud.githubusercontent.com/assets/2773919/24829722/80bfc1ea-1c77-11e7-9fad-8d26ac54f003.png)

It would help a lot.

Btw: I wonder why it isn't able to parse the results... Maybe because of the missing/wrong season/episode tags?

According to Sonarr the shown episode should be S00E02.

Cu

**Comment by markus101** [comment] 2017-04-08 15:22
Dupe of https://github.com/Sonarr/Sonarr/issues/395

**Closed by markus101** 2017-04-08 15:22 UTC
