### ISSUE TITLE
Unmonitor season when last episode is unmonitored/deleted

### ISSUE THREAD

**Issue by fatSquirrel42** [Sonarr/Sonarr#5633] opened 2023-05-09 20:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

There is already an option to "Unmonitor Deleted Episodes". If you have activated the option and deleted all episodes of a season, you end up with a monitored season in which all episodes are unmonitored. As an extension, there could be another option to unmonitor the season itself if the last episode was deleted/unmonitored.

I myself primarily delete episodes via Jellyfin after watching the episode and not via the Sonarr interface.
The main purpose of the option would be to improve the automatic maintenance of the library.

What I don't know is if this could impact an existing season getting new episodes and needing to be monitored again.

### Describe alternatives you've considered

Add functionality to "Unmonitor Deleted Episodes" itself.

### Anything else?

The prerequisite would be that the option "Unmonitor Deleted Episodes" is activated.

Each time an episode is deleted, Sonarr would need to check if that was the last monitored episode of a season. If it was the last monitored episode, Sonarr would not only unmonitor the episode, but also the season itself.

**Comment by thezoggy** [comment] 2023-05-09 21:46
the problem is that a season concept of last episode isnt apparent. show may have # episodes in the season.. a few weeks go by another episode shows up.. due to season break/writers strike/etc.. months goes by before other episodes show up. rinse and repeat. sometimes YEARS can go by before a season is picked back up (new episodes added).

**Comment by bakerboy448** [comment] 2023-05-09 21:48
Agree with Zoggy - I can't see anyway to conclusively know a Season is ended....and there's too many valid examples where seasons have weeks/months/years between episodes.

**Comment by fatSquirrel42** [comment] 2023-05-09 23:00
I see what you mean.
Would it maybe be a good idea/possibility to re-monitor a season if Sonarr registers that a new episode has been added to a season? Similar to how new seasons are also automatically monitored?

Regarding the term "last episode". My idea was, that Sonar knows season x has 10 episodes in its database. And when the number of monitored episodes reaches 0, that that's the trigger.

But maybe I'm just completely on the wrong track with my idea/workflow. Do you rather just leave the season on monitored and only unmonitor the episodes?

**Comment by thezoggy** [comment] 2023-05-09 23:14
Sonarr is going to add new episode as monitor status even if you have the season unmonitored. So I'm not sure what you think your trying to solve with your ask.

If you want sonarr to not grab new stuff you would have the unmonitored the series

**Comment by bakerboy448** [comment] 2023-05-09 23:17
> My idea was, that Sonar knows season x has 10 episodes in its database. And when the number of monitored episodes reaches 0, that that's the trigger.

doesn't account for the common case when TVDb is delayed in being updated and would cause premature unmonitorings

**Comment by markus101** [comment] 2023-05-10 00:46
> Would it maybe be a good idea/possibility to re-monitor a season if Sonarr registers that a new episode has been added to a season?

This would require Sonarr to know why the season was unmonitored, that's not something it knows, nor something we're going to track.

> Sonarr is going to add new episode as monitor status even if you have the season unmonitored

New episodes follow the monitored status of the season.

> what's the problem being experienced that this feature request is trying to solve?

This, why do you need to unmonitor the season? If all the episodes within are unmonitored the result is effectively the same.

**Comment by markus101** [comment] 2023-05-11 04:26
Closing as this isn't something we're going to do.

**Closed by markus101** 2023-05-11 04:26 UTC
Labels: needs-triage
