### ISSUE TITLE
Error importing multi-episodes from qBitTorrent

### ISSUE THREAD

**Issue by ftruzzi** [Sonarr/Sonarr#4252] opened 2021-01-14 20:55 UTC
Hi!

**Describe the bug**
When importing a torrent with multiple episodes such as: 
```
Masterchef.Italia.S10E03-04.HDTV.720p.x264.AAC.ITA-corey91\
  - Masterchef.Italia.S10E03.HDTV.720p.x264.AAC.ITA-corey91.mkv
  - Masterchef.Italia.S10E04.HDTV.720p.x264.AAC.ITA-corey91.mkv
```

Only the first episode is imported, renamed with the name of the parent folder (`S10E03-04`). As a result of this, the import of the second episode fails due a file with the same name already existing.

**Screenshots**
![image](https://user-images.githubusercontent.com/461133/104647570-5d097380-56b2-11eb-8137-d00778ef90bb.png)

**Logs**
https://pastebin.com/R1EqiFDb

**System Information**

 - Sonarr Version: 3.0.4.1060
 - qBittorrent v4.3.2
 - Operating System: Linux (unRAID / Slackware)
 - mono (macOS/Linux) Version: 5.20.1.34

Thanks :)

**Comment by markus101** [comment] 2021-01-14 21:13
Dupe of https://github.com/Sonarr/Sonarr/issues/3056

**Closed by markus101** 2021-01-14 21:13 UTC
