### ISSUE TITLE
Unreachable drive causes multiple failures/hangs

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#6076] opened 2023-10-09 01:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

So when a drive is not able to be connected to, things just simply start breaking. I have multiple mounts and one of them is an sshfs mount... For whatever reason windows is not able to connect to the sshfs mount and if that happens the app does not handle it well at all.

Updates stop working
Check health stops working
Disk Space in the UI hangs forever
Message cleanup stops working

These i have noticed but im not sure what else is tied to those threads that could also stop working. This happens in all of them and i have grabbed some screenshots from radarr and sonarr. It seems 8 days ago the sshfs mount stopped being reachable for whatever windows reason.

If i restart sonarr and some of the tasks make it in before health they will run & if fast enough will complete but after health check gets stuck that is it for some things

Radarr
![image](https://github.com/Sonarr/Sonarr/assets/8321115/01e928eb-4982-4cc8-9924-5a7aaf25c99e)
![image](https://github.com/Sonarr/Sonarr/assets/8321115/999abe3f-4f04-4131-9d70-10bf826fa995)
![image](https://github.com/Sonarr/Sonarr/assets/8321115/996045e3-d511-49e9-a3bd-5825ea1fa001)

Sonarr
![image](https://github.com/Sonarr/Sonarr/assets/8321115/aaf86d01-f345-45f5-8201-3f49978f790b)

### Expected Behavior

Timeout the drive connection when it cant pull the data instead of hanging indefinitely. Maybe show it as a red icon in the disk space, make it a health error, etc but allow the app to keep functioning.

### Steps To Reproduce

I guess create an sshfs mount and wait for it to stop working (this is windows so i cant say what causes it to stop, it just randomly does).. It usually throws an I/O thread operation error when trying to open it manually and requires a reboot to fix. However if one doesn't look at their apps all the time it is hard to catch it

### Environment

```markdown
- OS: Windows 11
- Sonarr: 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: SQLite
```

### What branch are you running?

Main

### Trace Logs?

I can do a restart and get them but it doesn't show anything about the drives that i have found. It sends the request for 

```
Http|Req: 9 [GET] /api/v3/diskspace (from ::1 Mozilla....
```

However there is never a Http|Res coming back from it as it hangs indefinitely in the UI

### Anything else?

I get this is some stupid windows sshfs connection issue but after talking to Q he thought it should be handled a little more gracefully as well but didn't have a solution so i am adding this here for thoughts and discussion as needed.

**Comment by austinwbest** [comment] 2023-10-09 01:23
As a side note... I wont reboot the machine as that will fix it (until windows freaks out again), incase something else is needed or wants to be tested while it is in this broken sshfs state

**Comment by markus101** [comment] 2023-10-09 02:42
Probably the most valuable piece would be around which health check is hanging, which should trace logs should have.

**Comment by austinwbest** [comment] 2023-10-09 03:18
OK, I can kill it, clear the logs, start it. How long do you want to allow it to run before grabbing trace?

**Comment by markus101** [comment] 2023-10-09 03:21
A couple minutes should be good.

**Comment by austinwbest** [comment] 2023-10-09 03:31
Here is the first 5 mins after that last startup. This was an end task from process manager and restart.
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12842488/sonarr.trace.txt)

And it is currently still hung from the restart a couple hours ago
![image](https://github.com/Sonarr/Sonarr/assets/8321115/41f846a6-b101-4a6b-8548-50b1be557e23)

![image](https://github.com/Sonarr/Sonarr/assets/8321115/ffae64a7-a3d2-4834-9daa-5beca9e8dd77)

**Comment by markus101** [comment] 2023-10-10 04:01
Unfortunately it doesn't look like we log anything related to which health check is being executed, but I've added some additional logging in v4.

**Comment by austinwbest** [comment] 2023-10-10 19:41
ok, i'll wait for it to make it into Radarr and keep an eye on it to mess up there so i can report back what is failing so you know as well. Im not on v4 atm but since the health checks are nearly identical if we know why it happens in one that should help with the others as well. I rebooted the machine and everything is working again (for now) so hopefully the update gets in before windows does whatever it is doing and breaks.

**Comment by austinwbest** [comment] 2023-12-05 23:16
Finally is happening again. This is the search all in the trace after about 3 mins from a restart & it just hangs. It never recovers from the mount check and now i have like 600 things sitting in queue because it wont process anything for the last few week or so.

Maybe put processing the queue on a thread where something cant completely block it like this (as an after thought)

Keep in mind this is from radarr because i dont run sonarr v4 but it is also stuck for the same amount of time on application update & health check.

So it seems health, app updates, process downloads are all blocking

![image](https://github.com/Sonarr/Sonarr/assets/8321115/072fd199-dfde-4cdb-99b7-4ba248d54032)

**Comment by markus101** [comment] 2023-12-12 00:41
> So it seems health, app updates, process downloads are all blocking

Health is not blocking.
App updating is blocking if it's the next task to run and when health is failing to complete it'll eventually be the next to run and block everything.
Processing downloads itself is not blocking, the actual import portion of it is, but only to other tasks that require disk access.

A bandage here would be to split checking for updates from installing updates, but it's a bandage because there would still be a hung thread and Sonarr would be operating at -1 threads.

Preventing the thread from hanging when checking health would allow the task queue to execute, at least to some degree, but will likely get hung up trying to import, unless the issue only lies with getting the mounts that the health check is doing.

Not sure what the best solution here is at the moment, but thanks for the information.

**Comment by austinwbest** [comment] 2023-12-12 02:52
@mynameisbogdan did a test exe for me to try and get a little deeper, he might be able to share as well just for more information

**Comment by markus101** [comment] 2024-07-25 00:21
I've been unable to reproduce this issue and given that this isn't affecting the vast majority of users I'm going to close this. If the underlying issue is narrowed down or someone has a fix, I'll take another look.

**Closed by markus101** 2024-07-25 00:21 UTC
Labels: one-day-maybe, waiting-for-info

**Comment by markus101** [comment] 2024-07-25 01:12
That would explain the disk space check hanging, but unless there is something special with trying to get the root disk / folder it wouldn't break the health check.

Caching would probably help here, but may only prolong the issue.

**Comment by markus101** [comment] 2024-07-25 05:10
[This PR](https://github.com/Sonarr/Sonarr/pull/7006) adds caching and cuts down on the number of requests made to disk to one per root folder instead of one per series.

**Comment by miguelpduarte** [comment] 2026-06-17 14:13
Just in case someone finds this later, I had this happen due a "dead" systemd automount unit that no longer existed but caused the filesystem "query" to hang indefinitely. Stopping the `.automount` unit made it disappear properly and the services were able to go back to working normally.

This gets me thinking if there is a possibility of adding a timeout to the filesystem checks so that a slow filesystem that happens to be queried by Sonarr "proactively" (in my case this was an external HDD) doesn't hang the whole service.

(for the record this was on `Version 4.0.17.2952` of Sonarr, but happened also with Radarr)
