### ISSUE TITLE
when search string include "." , Should it be replaced with spaces not remove directly?

### ISSUE THREAD

**Issue by Uzibird** [Sonarr/Sonarr#4872] opened 2022-01-25 14:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the search string is "DrWhite"

### Expected Behavior

the search string should be "Dr.White" or "Dr White"

### Steps To Reproduce

1. add tvdb:414356
2. run... 

### Environment

```markdown
- OS: Ubuntu 18.04.6 LTS
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Microsoft Edge 97.0.1072.69
```

### What branch are you running?

Main

### Trace Logs?

2022-01-25 22:12:47.1|Trace|Http|Req: 438 [POST] /api/v3/command (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-01-25 22:12:47.1|Trace|CommandQueueManager|Publishing SeasonSearch
2022-01-25 22:12:47.1|Trace|CommandQueueManager|Checking if command is queued or started: SeasonSearch
2022-01-25 22:12:47.1|Trace|CommandQueueManager|Inserting new command: SeasonSearch
2022-01-25 22:12:47.1|Trace|CommandExecutor|SeasonSearchCommand -> SeasonSearchService
2022-01-25 22:12:47.1|Trace|CommandQueueManager|Marking command as started: SeasonSearch
2022-01-25 22:12:47.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:47.1|Trace|Http|Res: 438 [POST] /api/v3/command: 201.Created (28 ms)
2022-01-25 22:12:47.1|Debug|Api|[POST] /api/v3/command: 201.Created (28 ms)
2022-01-25 22:12:47.1|Debug|IndexerFactory|Temporarily ignoring indexer U2 till 1/26/2022 12:10:35 AM due to recent failures.
2022-01-25 22:12:47.1|Info|NzbSearchService|Searching indexers for [Dr.White : S01]. 6 active indexers
2022-01-25 22:12:47.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:47.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:47.1|Debug|Torznab|Downloading Feed http://host/api/v2.0/indexers/lemonhd/results/torznab/api?t=tvsearch&cat=5000,5070,5080,8000,103583,145460,157000,2000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|HttpClient|Req: [GET] http://host/api/v2.0/indexers/lemonhd/results/torznab/api?t=tvsearch&cat=5000,5070,5080,8000,103583,145460,157000,2000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-25 22:12:47.1|Debug|NewznabRequestGenerator|Indexer capabilities lacking season & ep query parameters, no Standard series search possible.
2022-01-25 22:12:47.1|Debug|Torznab|Downloading Feed http://host/api/v2.0/indexers/acgsou/results/torznab/api?t=tvsearch&cat=5070,100002,100007,100008,100009,100016&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|HttpClient|Req: [GET] http://host/api/v2.0/indexers/acgsou/results/torznab/api?t=tvsearch&cat=5070,100002,100007,100008,100009,100016&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-25 22:12:47.1|Debug|Torznab|Downloading Feed http://host/api/v2.0/indexers/acgrip/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|HttpClient|Req: [GET] http://host/api/v2.0/indexers/acgrip/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-25 22:12:47.1|Debug|Torznab|Downloading Feed http://host/api/v2.0/indexers/eztv/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|HttpClient|Req: [GET] http://host/api/v2.0/indexers/eztv/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-25 22:12:47.1|Debug|Torznab|Downloading Feed http://192.168.0.111:29117/api/v2.0/indexers/pterclub/results/torznab/api?t=tvsearch&cat=5000,100404,100405,100411,100413&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|HttpClient|Req: [GET] http://192.168.0.111:29117/api/v2.0/indexers/pterclub/results/torznab/api?t=tvsearch&cat=5000,100404,100405,100411,100413&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1
2022-01-25 22:12:47.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-25 22:12:48.8|Trace|HttpClient|Res: [GET] http://192.168.0.111:29117/api/v2.0/indexers/pterclub/results/torznab/api?t=tvsearch&cat=5000,100404,100405,100411,100413&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1: 200.OK (1687 ms)
2022-01-25 22:12:49.2|Trace|HttpClient|Res: [GET] http://host/api/v2.0/indexers/eztv/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1: 200.OK (2068 ms)
2022-01-25 22:12:50.3|Trace|HttpClient|Res: [GET] http://host/api/v2.0/indexers/lemonhd/results/torznab/api?t=tvsearch&cat=5000,5070,5080,8000,103583,145460,157000,2000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1: 200.OK (3146 ms)
2022-01-25 22:12:50.6|Trace|HttpClient|Res: [GET] http://host/api/v2.0/indexers/acgrip/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1: 200.OK (3466 ms)
2022-01-25 22:12:54.7|Trace|HttpClient|Res: [GET] http://host/api/v2.0/indexers/acgsou/results/torznab/api?t=tvsearch&cat=5070,100002,100007,100008,100009,100016&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1: 200.OK (7559 ms)
2022-01-25 22:12:54.7|Debug|NzbSearchService|Total of 0 reports were found for [Dr.White : S01] from 6 indexers
2022-01-25 22:12:54.7|Debug|NzbSearchService|Setting last search time to: 1/25/2022 2:12:54 PM
2022-01-25 22:12:54.7|Info|DownloadDecisionMaker|No results found
2022-01-25 22:12:54.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Info|SeasonSearchService|Season search completed. 0 reports downloaded.
2022-01-25 22:12:54.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Trace|CommandQueueManager|Updating command status
2022-01-25 22:12:54.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-01-25 22:12:54.7|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-01-25 22:12:54.7|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-01-25 22:12:54.7|Trace|CommandExecutor|SeasonSearchCommand <- SeasonSearchService [00:00:07.6061440]
2022-01-25 22:12:54.7|Trace|Http|Req: 439 [GET] /api/v3/command (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-01-25 22:12:54.7|Trace|CommandQueueManager|Getting all commands
2022-01-25 22:12:54.7|Trace|Http|Res: 439 [GET] /api/v3/command: 200.OK (4 ms)
2022-01-25 22:12:54.7|Debug|Api|[GET] /api/v3/command: 200.OK (4 ms)
2022-01-25 22:12:57.3|Trace|Http|Req: 440 [GET] /logfile/sonarr.trace.txt (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-01-25 22:12:57.3|Trace|Http|Res: 440 [GET] /logfile/sonarr.trace.txt: 200.OK (0 ms)

### Anything else?

I have added a tvshow that named "Dr.White", tvdb:414356

the search api is:     http://host/api/v2.0/indexers/pterclub/results/torznab/api?t=tvsearch&cat=5000,100404,100405,100411,100413&extended=1&apikey=(removed)&offset=0&limit=100&q=DrWhite&season=1

![image](https://user-images.githubusercontent.com/40909658/150988857-a6623954-e765-44fe-a053-b15ab300d39d.png)

it can't be found result when sonarr search string is "DrWhite", it should be "Dr White" or "Dr.White".

![image](https://user-images.githubusercontent.com/40909658/150994504-36945e71-a40a-4f7d-93b7-0f9c26e496eb.png)

![image](https://user-images.githubusercontent.com/40909658/150994554-08703273-f49f-4779-8bc8-c76363a4b811.png)

**Comment by Uzibird** [comment] 2022-01-25 14:31
![image](https://user-images.githubusercontent.com/40909658/150996021-2b380d23-e966-489a-931c-8414b9ceaae2.png)

![image](https://user-images.githubusercontent.com/40909658/150995910-8f47200f-5a57-45e9-a1ef-bff452954602.png)

![image](https://user-images.githubusercontent.com/40909658/150995967-c2605971-041a-4fd6-ad3e-9e41ffbc2a31.png)

**Comment by bakerboy448** [comment] 2022-01-25 14:33
Not a bug - your indexers do not follow normal standards nor does jackett indicate they should use raw search and send the query as `Dr White`

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

Duplicate of https://github.com/Sonarr/Sonarr/issues/1225#issuecomment-981153943

**Closed by bakerboy448** 2022-01-25 14:33 UTC
Labels: needs-triage
