### ISSUE TITLE
Better filtering options for "cutoff unmet" section

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#4181] opened 2020-12-21 01:07 UTC
**Describe the problem**
When I look at the 'cutoff unmet' section, there are dozens of episodes that haven't met the cutoff. The issue is most of them are currently airing shows which have a cutoff of "bluray" which won't be available for several months at best. Some shows however, don't have such a high cutoff (webdl) and haven't met that cutoff, which should already be available.

**Describe any solutions you think might work**
Add options to filter the 'cutoff unmet' sections by series type, tags, custom, etc - just like the main 'series' section.

**Comment by bakerboy448** [comment] 2020-12-21 01:09
Duplicate of #3657

Please use the search function next time

**Closed by bakerboy448** 2020-12-21 01:09 UTC
