### ISSUE TITLE
Different Metadata providers available, options per series

### ISSUE THREAD

**Issue by Tschiyo** [Sonarr/Sonarr#7430] opened 2024-11-28 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently TVDB is hindering the existence of "One Piece Fishman Island Remake" specifically, while other metadata providers (like Kitsu, Anilist, IMDB) for example have metadata for this. 
Its not possible to have Sonarr search for this show while it would be possible with a different metadata provider. Other shows have different sortings depending on the databases as well, here I've had issues between requestrr (which uses TMDB) not recognizing the show was fully available because of different sortings.

### Describe the solution you'd like

Add a possibility in the "Metadata Source" to add/edit metadata providers, have TVDB as default and have a option "per series" to have metadata provided by a different source (like TMDB, IMDB, AniList...)

### Describe alternatives you've considered

I can really only go and manually add the download, move files as sonarr doesnt recognize the show or have an option to "manually add" an episode. For the requestrr issue I've had to mark it as available manually as well.

**Comment by stevietv** [comment] 2024-11-28 08:00
Duplicate of #7383, https://github.com/Sonarr/Sonarr/issues/7023, https://github.com/Sonarr/Sonarr/issues/6499, https://github.com/Sonarr/Sonarr/issues/4136 , https://github.com/Sonarr/Sonarr/issues/3937, https://github.com/Sonarr/Sonarr/issues/321, and https://github.com/Sonarr/Sonarr/issues/255

Please do search the open and closed issued before raising a new one.

**Closed by stevietv** 2024-11-28 08:00 UTC
Labels: needs-triage

**Comment by Tschiyo** [comment] 2024-11-28 08:07
all of those refer to using different tvdb based ordering (dvd), which may resolve the requestrr issue I faced, but not the "doesnt exists in tvdb" issue regarding one piece remake.

**Comment by stevietv** [comment] 2024-11-28 08:14
They cover alternate metadata orders.

These cover alternate metadata sources: Dupe of https://github.com/Sonarr/Sonarr/issues/1324 https://github.com/Sonarr/Sonarr/issues/4395 https://github.com/Sonarr/Sonarr/issues/5903 and others
