### ISSUE TITLE
Add preferred words like Radarr

### ISSUE THREAD

**Issue by jooncheez** [Sonarr/Sonarr#1673] opened 2017-02-12 13:29 UTC
Radarr now implemented preferred words that you can add to a profile through tags. Could this be implemented in Sonarr too? I use it for x265 files, which it is perfect for, since they are not always available for every episode/show. 

Another option would be an x265 quality ofcourse. 

Here is the link to the Radarr issue:
https://github.com/Radarr/Radarr/issues/227

**Comment by markus101** [comment] 2017-02-12 17:05
Please search before requesting as there is already an issue for this.

Dupe of https://github.com/Sonarr/Sonarr/issues/385

**Closed by markus101** 2017-02-12 17:05 UTC
