### ISSUE TITLE
Add Unrar feature

### ISSUE THREAD

**Issue by anakaine** [Sonarr/Sonarr#1748] opened 2017-03-09 21:36 UTC
Help complete the automation cycle, add an unrar feature. With more releases than not still coming from scene, where multiple rar files are used to pack videos, it seems unreasonable to have an automation solution that cannot unrar automatically. 

Previous solutions have suggested using a torrent client to do this, however when people are using seedboxes or remote computers, this adds an unnecessary overhead both in terms of processor and space usage on the remote host, and bandwidth between the local host and seedbox. As an additional example, many of the most comprehensive automation guides available today recommend using btsync / resilio sync to pass off a completed torrent on a seedbox to the destination where Sonarr resides, and having the torrent client unpack a directory of rars will trigger twice the bandwidth as all rar files, and the resulting unpacked video file will be transferred.

Products with same / similar intent have it::
Sick+Rage/RageTv/Gear 
Couchpotato
Headphones

Sonarr is certainly more stable, user friendly, and faster than the Sick* scripts (speaking from years experience), but the missing unpack feature breaks the automated experience.

**Comment by markus101** [comment] 2017-03-09 21:38
Please search before posting new issues, this is a dupe of https://github.com/Sonarr/Sonarr/issues/784

**Closed by markus101** 2017-03-09 21:38 UTC
