### ISSUE TITLE
[Request] Search all cut-off unmet

### ISSUE THREAD

**Issue by PintjesBier** [Sonarr/Sonarr#2997] opened 2019-03-14 14:02 UTC
As the titles suggests: I have around 1699 records of unmet cut-off's.

For example: I have 1699 records of unmet cut-off's, I would have to search 114 pages, wait for it to finish searching after each page and I can't click on another screen for once because the pages would be messed up if it found a couple records and the page get's refreshed... 

Thanks in advance!

EDIT: from discussing this in the discord I think it is actually a feature in V3; if so, sorry for the useless thread!

**Comment by markus101** [comment] 2019-03-14 15:40
Dupe of https://github.com/Sonarr/Sonarr/issues/576

**Closed by markus101** 2019-03-14 15:40 UTC
