### ISSUE TITLE
Put.io as download client

### ISSUE THREAD

**Issue by doma2345** [Sonarr/Sonarr#4216] opened 2021-01-03 14:51 UTC
**Describe the problem**
Add put.io as a download client

**Describe any solutions you think might work**
Push torrent downloads to put.io using their api and then use there api to report back completed downloads.

**Additional context**
http://api.put.io/

**Comment by bakerboy448** [comment] 2021-01-03 14:52
Duplicate of #1972

please use the search function

**Closed by bakerboy448** 2021-01-03 14:52 UTC
