### ISSUE TITLE
480p web-dl get wrongly parsed as 720p hdtv

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#869] opened 2015-10-18 14:57 UTC
480p web-dl get wrongly parsed as 720p hdtv:
![sonarr132](http://zoggy.net/sonarr132.png)

**Comment by thezoggy** [comment] 2015-10-18 15:00
most likely due to obfuscation, thus it cant figure out the quality and falls back to extension (mkv). talked about this months ago.. figure ill toss this up here so this can be addressed.. as this issue becomes a nuisance to deal with when you have a sonarr instance with a lot of shows.. only do SD. thus you randomly have hdtv releases scattered across your shows.. thus you have to hunt to find them (painful in sonarr.. could take a page out of sb and add episode status management, so you can search for all ep with x quality), then once you find the releases.. you have to change quality then rename. thus you end up renaming episodes that could be days/weeks old (depending on how often you look) thus wrecking your plex/kodi watched status in your library.

**Comment by markus101** [comment] 2015-10-18 17:37
Dupe of https://github.com/Sonarr/Sonarr/issues/603

**Closed by markus101** 2015-10-18 17:37 UTC
