### ISSUE TITLE
Cannot find show 24 (Even with TVDB ID)

### ISSUE THREAD

**Issue by Jakesparrow** [Sonarr/Sonarr#3469] opened 2019-12-20 23:46 UTC
**Describe the bug**
You can type it in, or use the tvdb:76290   and it makes no difference. Nothing finds it.

**Screenshots**
![image](https://user-images.githubusercontent.com/17485169/71298935-8b563b80-2358-11ea-8281-ad19fb2fb05e.png)

**Logs**
N/A

**System Information**

 - Sonarr Version: 3.0.3.668
 - Operating System: Windows 10
 - IDK, but when I tried to install 4.8 it said I have 4.8 or higher.

**UI Bugs:**
 - OS: Windows
 - Browser: Chrome (Tried Edge also)
 - Version: 
**Additional context**

**Comment by alexhk** [comment] 2019-12-21 01:31
I noticed the same with Stranger Things, but using Sonarr on Ubuntu.  Using the name I couldn't find it. Using the TVDB ID also won't find it. Others work as expected, for instance American Dad.

tvdb:73141 (American Dad - works)
tvdb: 305288 (doesn't find anything0

Version 3.0.3.668
Package Version 3.0.2
Mono Version 6.6.0.161
AppData directory /var/lib/sonarr
Startup directory /usr/lib/sonarr/bin
Mode Console
Ubuntu 18.04 Server

**Comment by markus101** [comment] 2019-12-21 05:10
It’s an ongoing problem with the TVDB’s API.

Dupe of https://github.com/Sonarr/Sonarr/issues/3415

**Closed by markus101** 2019-12-21 05:10 UTC
