### ISSUE TITLE
[indexer] Move "save" to "save & test" and add "save" to dropdown

### ISSUE THREAD

**Issue by smitetierlist** [Sonarr/Sonarr#854] opened 2015-10-18 01:10 UTC
Basically title.

When editing/adding an indexer rename the existing save button to "save & test" and add an option "save (without testing)" to the dropdown menu.

It really bothers me that I can't edit a indexer when my request limit is reached.

Also it was a weird UX while setting the indexers up - at least for me. My workflow was:

 - click <kbd>+ (add indexer)</kbd>
 - fill form
 - click <kbd>test</kbd>
 - click <kbd>save</kbd>

Which just runs the test twice.

**Comment by thezoggy** [comment] 2015-10-18 04:25
sometimes you want to test and not close the modal..  like if your trying to check username/pw or site url. not just to 'test' to clear the backoff counter.. which i bet is ultimately why your going there.. that is what needs to be addressed.. not so much mis-using the test button.

**Comment by markus101** [comment] 2015-10-18 20:18
The problem is the people that try to add any crappy indexer thinking its newznab and then complain when it doesn't work. Adding a way to get around the problem of people wanting to do the wrong thing doesn't make sense. The use case you specify could be addressed by relaxing the errors that cause the test to fail, but it is also a problem with people relying on free indexers, paid indexers have such a high API limit, that reaching the limit is unlikely.

**Comment by markus101** [comment] 2015-12-27 09:19
GHI created to better handle this scenario: https://github.com/Sonarr/Sonarr/issues/1028

**Closed by markus101** 2015-12-27 09:19 UTC
