### ISSUE TITLE
DownloadStationTaskProxyV2 issues | Downloads cannot be added to Download Station

### ISSUE THREAD

**Issue by Prime-Omega** [Sonarr/Sonarr#4562] opened 2021-06-30 21:01 UTC
**Description**

Potentially related to [#4388](https://github.com/Sonarr/Sonarr/issues/4388). I upgraded my Synology from DSM 6 to DSM 7. Unfortunately that automatically caused my Download station to upgrade from version 3.8.16-3563 to 3.9.0-4600. Everything works up until the point where Sonarr has to forward the torrent to Download station. Also weirdly enough, Radarr is not affected by this and is still able to relay torrents to download station.

**To Reproduce**
1. Go to a show & look for an episode
2. Sonarr returns a bunch of torrents
3. Download a torrent
4. Sonarr returns Reason: 120 - Unknown error

**Platform Information**

Syno version > DSM 7.0-41890
DS version > 3.9.0-4600
Docker version > 20.10.3-1233
Sonarr version > dev 3.0.6.1272

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6743988/sonarr.trace.txt)

### **EDIT: You can manually fix this by adding a destination folder in Sonarr under settings > download clients > download station config.**

**Comment by bakerboy448** [comment] 2021-06-30 21:06
Diagnosed here https://github.com/Radarr/Radarr/pull/6294#issuecomment-871640833

@twentynine78 will review and work on it when he can.

**Comment by markus101** [comment] 2021-06-30 21:12
Based on that thread it sounds like Sonarr and Radarr are configured differently, which would explain "Radarr is not affected by this" can you confirm?

**Comment by Prime-Omega** [comment] 2021-06-30 21:30
Running Radarr in the same environment as mentioned above by the way, nightly ver 4.0.0.5120.

**Comment by To0wnn** [comment] 2021-07-02 07:47
I have the exact same issue. Radarr is working but Sonarr is not. Reinstalled DS and Sonarr but the same result somehow..

**Comment by To0wnn** [comment] 2021-07-02 10:16
Difference between Radarr uses DownloadStationTaskProxy and Sonarr DownloadStationTaskProxy**V2** do not know is this is the issue or how you can switchback

**Comment by bakerboy448** [comment] 2021-07-02 12:37
So now you're saying the fix that was merged for DS now breaks DS on only Sonarr yet the same fix that is merged into Radarr Nightly works fine

that makes no sense at all.

**Comment by To0wnn** [comment] 2021-07-02 12:51
Maybe i do not understand then indeed. With version nightly-3.0.5.1146 of sonarr it is working. I use it in a docker. DS i use torrents

**Comment by bakerboy448** [comment] 2021-07-02 13:02
3.0.5 is out of date. 

the fix for newer versions of DS breaking was already merged into Nightly of both apps.  This issue is relating to the release not being added due to newer DS versions changing how the path is needed and that being accidentally missed on the PR

additionally a reminder regarding nightly builds:
> This is the bleeding edge. It is released as soon as code is committed and passes all automated tests. This build may have not been used by us or other users yet. There is no guarantee that it will even run in some cases. **This branch is only recommended for advanced users. Issues and self investigation are expected in this branch.**

**Comment by To0wnn** [comment] 2021-07-02 13:18
So what do you suggest me to do now then? Lasted DSM 7.0 , latest DS 3.9.0-4900 and latest Sonarr stable version is not working now.

**Comment by bakerboy448** [comment] 2021-07-02 13:21
> So what do you suggest me to do now then? Lasted DSM 7.0 , latest DS 3.9.0-4900 and latest Sonarr stable version is not working now.

That's 100% expected.  The fix for new versions of DS is only in nightly...so naturally stable would not work.

So you wait for a new main to be released;  jump on nightly; Or switch to a download client that doesn't suck.  This is also why it is never a good idea to immediately jump on the latest versions of new OSes and Download Client software, especially for Synology.

For further discussions given this is unproductive for the github issue at hand:
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by To0wnn** [comment] 2021-07-02 13:35
Haha ok i will keep the latest DSM with the latest sucking download client with an outdated sonar till it is fixed

**Comment by twentynine78** [comment] 2021-07-02 14:41
The error in the Sonarr log is due to the fact that the destination folder was not specified in the download client parameter. In the Radarr log there is no error because the download client has a destination folder set.

The new API does not handle the default destination folder, and requires a destination folder to be specified.

I am working on a solution to get the default destination folder with the new API if a destination folder is not defined in the client settings.

Translated with www.DeepL.com/Translator (free version)

**Comment by Prime-Omega** [comment] 2021-07-02 21:13
> The error in the Sonarr log is due to the fact that the destination folder was not specified in the download client parameter. In the Radarr log there is no error because the download client has a destination folder set.
> 
> The new API does not handle the default destination folder, and requires a destination folder to be specified.
> 
> I am working on a solution to get the default destination folder with the new API if a destination folder is not defined in the client settings.

Just specified a destination folder in the client (was indeed empty/default before) and it is working again, cheers!

**Comment by twentynine78** [comment] 2021-07-03 08:23
I don't want to make the destination field mandatory because that would introduce a regression and break certain configurations.

I found a way to get the default destination folder from the new Downloadstation API.
The commit is published f4c5922d62ec2256943e55835f8caa29e773899b, I will continue testing before creating a PR.

**Comment by ddmunhoz** [comment] 2021-07-04 02:46
Great news @twentynine78 ! I was just having the same issue and was about to push a fix similar to yours, I agree on not making it mandatory.

**Closed** 2021-08-01 20:20 UTC
Labels: download-client
