### ISSUE TITLE
Improve upgrading of existing downloads

### ISSUE THREAD

**Issue by stuntguy3000** [Sonarr/Sonarr#1954] opened 2017-06-01 12:27 UTC
I've found pretty commonly that when a new show is released, it will start downloading the 720p version as per my profile. Once a 1080p version is released it will then download that _and not cancel the download_ of the 720p version (assuming the 720p version is still downloading).

**Comment by markus101** [comment] 2017-06-01 13:40
Dupe of https://github.com/Sonarr/Sonarr/issues/370

**Closed by markus101** 2017-06-01 13:40 UTC
