### ISSUE TITLE
Sonarr not using title with & in it?

### ISSUE THREAD

**Issue by NCLI** [Sonarr/Sonarr#3134] opened 2019-05-23 19:11 UTC
Sonarr won't download episodes from a series named Carole & Tuesday. For some reason, it only looks for "Carole and Tuesday", which no one releases it as. It knows both titles, so why aren't they both used for searching? Heck, the one it's not using is the primary title.

What is the bug here? Is it because Sonarr doesn't like using titles with ampersand in them?

**Comment by markus101** [comment] 2019-05-23 19:19
Most shows released don't use `&` they use `and`. Dupe of https://github.com/Sonarr/Sonarr/issues/1225 though.

**Closed by markus101** 2019-05-23 19:19 UTC

**Comment by NinjaBanjo** [comment] 2019-06-12 01:43
Sorry for the brash response, but I feel like that's what was received above. (and the dup ticket appears to encapsulate multiple seemingly unrelated bugs (or very slightly related, in that they have to do with name normalization)

In this case, tvdb has the show with the name including the "&" "Carole & Tuesday" and to trackers uploads have used the same naming convention

I find it slightly off-putting that a piece of software (Even opensource) would shrug off a very clearly common scenario (look at the number of comments on #1225) with "most shows don't use &" and calling it a day.

Any chance we can have a discussion about potential solutions?
