### ISSUE TITLE
qBittorrent finished torrents are not removed.

### ISSUE THREAD

**Issue by PiscisSwimeatus** [Sonarr/Sonarr#2449] opened 2018-03-08 09:54 UTC
## Bug Report

Sonarr does not remove finished torrents.
Fails with /command/deletePerm: 400.BadRequest

It works on version 2.0.0.5134
But both versions after that it does not.

### System Information/Logs
Version 2.0.0.5152
Mono Version 4.6.2
Ubuntu 17.10
qBittorrent 4.0.4

18-3-8 10:45:39.8|Warn|HttpClient|HTTP Error - Res: [POST] http://123.123.123.123:8999/command/deletePerm: 400.BadRequest
18-3-8 10:45:39.8|Error|DownloadEventHub|Couldn't remove item from client Crashing.US.S02E08.1080p.WEB.H264-DEFLATE[rarbg]

[v2.0.0.5152] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://123.123.123.123:8999/command/deletePerm]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00129] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:98 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00017] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:225 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00068] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:241 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent (System.String hash, System.Boolean removeData, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x0004b] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:118 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem (System.String hash, System.Boolean deleteData) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:167 
  at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x00038] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadEventHub.cs:68 

18-3-8 10:45:39.8|Debug|DownloadEventHub|[The.Young.and.the.Restless.2018.03.06.1080p.CBS.WEBRip.AAC2.0.x264-SOAP[rarbg]] Removing download from qBittorrent history
18-3-8 10:45:39.8|Warn|HttpClient|HTTP Error - Res: [POST] http://123.123.123.123:8999/command/deletePerm: 400.BadRequest
18-3-8 10:45:39.8|Error|DownloadEventHub|Couldn't remove item from client The.Young.and.the.Restless.2018.03.06.1080p.CBS.WEBRip.AAC2.0.x264-SOAP[rarbg]

[v2.0.0.5152] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://123.123.123.123:8999/command/deletePerm]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00129] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:98 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00017] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:225 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00068] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:241 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent (System.String hash, System.Boolean removeData, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x0004b] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:118 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem (System.String hash, System.Boolean deleteData) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:167 
  at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x00038] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadEventHub.cs:68 

18-3-8 10:45:39.9|Debug|DownloadEventHub|[Bliss.S01E04.1080p.HDTV.x264-MTB[rarbg]] Removing download from qBittorrent history
18-3-8 10:45:39.9|Warn|HttpClient|HTTP Error - Res: [POST] http://123.123.123.123:8999/command/deletePerm: 400.BadRequest
18-3-8 10:45:39.9|Error|DownloadEventHub|Couldn't remove item from client Bliss.S01E04.1080p.HDTV.x264-MTB[rarbg]

[v2.0.0.5152] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://123.123.123.123:8999/command/deletePerm]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00129] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:98 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00017] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:225 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00068] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:241 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent (System.String hash, System.Boolean removeData, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x0004b] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:118 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem (System.String hash, System.Boolean deleteData) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:167 
  at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x00038] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadEventHub.cs:68 

![image](https://user-images.githubusercontent.com/4976642/37144590-d5e3e496-22be-11e8-8d42-4365c4ad3f13.png)

![image](https://user-images.githubusercontent.com/4976642/37144662-004c6f1e-22bf-11e8-97f7-587404aa708c.png)

**Comment by markus101** [comment] 2018-03-08 13:49
Dupe of https://github.com/Sonarr/Sonarr/issues/2438

**Closed by markus101** 2018-03-08 13:49 UTC
