### ISSUE TITLE
Race condition during episode import / quality check

### ISSUE THREAD

**Issue by lps-rocks** [Sonarr/Sonarr#5475] opened 2023-03-08 21:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

All releases are for the same show and episode.

Release A and Release B are pushed via the https://sonarr.tv/docs/api/#/ReleasePush/post_api_v3_release_push endpoint. Release B is pushed first, Release A is pushed second, both are accepted.

Release X = 1080p Web-DL already imported to Sonarr
Release A = 4K Web-DL w/Custom formats score of 4100
Release B = 4K Web-DL w/Custom formats score of 3800

1. Release A and B are both added to the download client within seconds or minutes of each other. 
2. Both Release A and B download at the same time. 
3. Release A finishes downloading and gets Queued for import because it trumps Release X while Release B is still downloading. 
4. Release B finishes downloading but Release A hasn't finished importing (file is being copied). 
5. Sonarr sees finished release B, checks to see if it should be imported but uses the OLD data from existing Release X instead of Release A, and queues release B to be imported not knowing that release A trumps release B. 
6. This causes release B to overwrites release A in Sonarr since it's already in the queue.

### Expected Behavior

All releases are for the same show and episode.

Release A and Release B are pushed via the https://sonarr.tv/docs/api/#/ReleasePush/post_api_v3_release_push endpoint. Release B is pushed first, Release A is pushed second, both are accepted.

Release X = 1080p Web-DL already imported to Sonarr
Release A = 4K Web-DL w/Custom formats score of 4100
Release B = 4K Web-DL w/Custom formats score of 3800

1. Release A and B are both added to the download client within seconds or minutes of each other. 
2. Both Release A and B download at the same time. 
3. Release A finishes downloading and gets Queued for import because it trumps Release X while Release B is still downloading. 
4. Release B finishes downloading but Release A hasn't finished importing (file is being copied). 
5. Sonarr sees finished release B, checks to see if it should be imported but should be checking for in-progress imports for this episode, if there are other active imports for the episode do not queue the release to be imported, wait for the next cycle checking for finished downloads.

### Steps To Reproduce

See Above behavior. 

### Environment

```markdown
- OS: Docker container linuxserver/sonarr
- Sonarr: 4.0.0.396
- Docker Install: 20.10.18
- Using Reverse Proxy: No
- Browser: FireFox 110.0.1
```

### What branch are you running?

Develop

### Trace Logs?

Acquiring. Will attach later.

**Comment by lps-rocks** [comment] 2023-03-08 22:44
> missing tidbit of info per discord "autobrr is pushing the releases to sonarr"

Added. Although relatively irrelevant since it looks like the releases pushed via https://sonarr.tv/docs/api/#/ReleasePush/post_api_v3_release_push are treated as RSS downloads.

**Comment by markus101** [comment] 2023-03-13 06:16
Sonarr only imports one file at a time, if something is importing nothing else will be processed and more downloads complete they won't be imported until after items already being processed are imported. Definitely need at a minimum debug logs, preferably trace logs to start.

**Comment by lps-rocks** [comment] 2023-03-13 07:08
> Sonarr only imports one file at a time, if something is importing nothing else will be processed and more downloads complete they won't be imported until after items already being processed are imported. Definitely need at a minimum debug logs, preferably trace logs to start.

Please reach out to @fryfrog about this. He seems to understand exactly what I’m describing. Race conditions are not easy to follow, so I understand why I keep getting “this can’t be possible responses”. 

Let me reiterate what’s happening. I understand Sonarr only imports one file at a time, but that import is consumed from a queue of imports. 

The race condition exists between the time the currently importing release has began importing and ended importing because the quality and file information for an episode is not updated till the file copy has completed.

Release A as described above, is in the process of being imported, it’s actively being copied. While release A is being copied, release B is checked for import eligibility based on the data from existing release X and is then queued for import asynchronously. Now it’s behind release A in the queue. 

Because the import eligibility check is done before the release is QUEUED FOR IMPORT and is done without checking for any IN PROGRESS imports, it uses the old data from release X and thus, the race condition. 

Is that more clear?

**Comment by fryfrog** [comment] 2023-03-13 07:12
Trace logs of it happening will be very useful for understanding it. A screenshot of an episode's history where this happened would also be useful.

**Comment by markus101** [comment] 2023-03-13 08:05
I understand what you said the first time, mansplaining race conditions and using more words doesn’t clarify anything.

> Because the import eligibility check is done before the release is QUEUED FOR IMPORT and is done without checking for any IN PROGRESS imports, it uses the old data from release X and thus, the race condition.

Please point to where you see this occurring.

**Comment by markus101** [comment] 2023-03-14 01:10
Unless Sonarr is not responsible for starting the import process because a script is telling Sonarr to run it's `` command then Sonarr's import process will not run in parallel (nor will any other background tasks). In the case of Completed Download Handling being responsible for importing Sonarr will:

1. Get completed downloads from the client
2. Mark each completed download as ready to import, if not already being processed
3. Queue the task to process the imports
4. Import the downloads and the files within 1 at a time
5. Mark them as imported
6. Wait for more downloads

This is what is logged when Sonarr tries to queue imports while already running the import task:

```
2023-03-13 17:48:35.1|Trace|CommandQueueManager|Checking if command is queued or started: ProcessMonitoredDownloads
2023-03-13 17:48:35.2|Trace|CommandQueueManager|Command is already in progress: ProcessMonitoredDownloads
```

as opposed to the following when the task is not already running/queued:

```
2023-03-13 17:41:37.5|Trace|CommandQueueManager|Checking if command is queued or started: ProcessMonitoredDownloads
2023-03-13 17:41:37.5|Trace|CommandQueueManager|Inserting new command: ProcessMonitoredDownloads
```

It looks like the only case where Sonarr would run imports simultaneously is if told to import via the `DownloadedEpisodesScanCommand`, but given that's not used in the case of Sonarr monitoring for completed downloads I don't believe that's the issue here, though we'll fix it all the same.

Since I've been unable to reproduce this issue and there isn't logs to provide more information to go on I'm closing this issue, if there ends up being something in logs later on we can take a look then.

**Closed by markus101** 2023-03-14 01:10 UTC
Labels: waiting-for-info, needs-triage

**Comment by lps-rocks** [comment] 2023-03-14 01:15
Here's the screenshot of the problem in action...

![0843be20-35c0-4b13-afcb-8d2d329b584a](https://user-images.githubusercontent.com/10893911/224867180-369c05b8-65e8-421f-a570-58b49d8a566e.jpg)

**Comment by fryfrog** [comment] 2023-03-14 02:39
To be clear, you're submitting the `.torrent` for approval and then letting sonarr do its normal importing, right? You're not downloading outside of sonarr and then pushing the result in?

Can you show screenshots of hovering the `i` on both cloud icons and both import lines?

**Comment by lps-rocks** [comment] 2023-03-14 02:50
> To be clear, you're submitting the `.torrent` for approval and then letting sonarr do its normal importing, right? You're not downloading outside of sonarr and then pushing the result in?

I'm not sure how autobrr pushes it with the rest of the metadata via the [/api/v3/release/push](https://sonarr.tv/docs/api/#/ReleasePush/post_api_v3_release_push) API endpoint. Let me double check. 

> Can you show screenshots of hovering the `i` on both cloud icons and both import lines?

Release B grabbed
![b3cce31f-eff1-42ff-8f81-770226195acb](https://user-images.githubusercontent.com/10893911/224879545-a8bc923c-f138-4c72-a6fa-2ddcb238aacc.jpg)

Release A grabbed
![534af83b-9fbd-4fb7-b68a-b7575dec5176](https://user-images.githubusercontent.com/10893911/224879548-c5cdf154-add0-4bb3-bc94-999f01dd6cb1.jpg)

Release A imported
![88572cdb-43b0-4741-8779-4ee97e17ef0c](https://user-images.githubusercontent.com/10893911/224879542-1b80f7fd-37d1-408e-9ac3-0b61ac9a86c2.jpg)

Release B imported
![50cb8b0c-6863-4443-9794-273948a287a9](https://user-images.githubusercontent.com/10893911/224879547-61f1744a-a7c7-4218-96df-74dc2aa68c23.jpg)

**Comment by fryfrog** [comment] 2023-03-14 03:02
Its fine, autobrr only submits `.torrents` for approval, you'd be doing something else home grown to be pushing actual imports. Looking at your screenshots now. :)

**Comment by lps-rocks** [comment] 2023-03-14 03:07
Okay, so *no* autobrr is *not* grabbing a .torrent file - It is simply passing the download metadata to sonarr and letting it choose. 

Here's a full trace log of a push of an accepted release. https://gist.github.com/lps-rocks/9f3446c7c8abe6d5c100e7b7e9bce8c6

**Comment by markus101** [comment] 2023-03-14 07:30
Turns out imports weren't considering Custom Formats at all, so it didn't matter if it finished 1s later or an hour later it would be imported and a lower CF score could replace a higher CF score. Normally it's not likely an issue because multiple releases aren't going to be grabbed in the same RSS sync and by the time the next RSS sync rolls around the first grab is probably going to be way ahead in downloading, but pushing releases caused things to be grabbed multiple times and imported close together.

This is a prime example why logs are crucial for bug reports, instead of theorizing what happened we'd be able to see a lot more and not go on a wild goose chase because someone pointed fingers at the wrong thing. The screenshots of the grabs/imports weren't very useful due to the lack of accurate timestamps, though they could have been if they'd been provided when the GHI was opened as they _may_ have had times instead of all having the same date from days ago.

**Comment by lps-rocks** [comment] 2023-03-14 11:09
Thanks @markus101 and @fryfrog for nailing this down. One more day and I probably would have had the logs but appreciate you looking into it without the logs. Can't wait to test out the fix!
