### ISSUE TITLE
Download is in base download directory instead of subfolder

### ISSUE THREAD

**Issue by kristianvmd** [Sonarr/Sonarr#6280] opened 2023-12-31 06:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've been using sonarr for several years now, and it has been rare for me not to be able to import before, but recently I've been getting some frequent import errors after a certain version update, so to make it easier to explain, I've listed the ways to reproduce the import errors

### Expected Behavior

none

### Steps To Reproduce

1. Add indexer MioBT to prowlarr.
2. Add anime ```Rurouni Kenshin (2023)```
3. Manually search for seasons
4.Sort by size, select 10.6 GiB size search result --```[猎户手抄部] 浪客剑心 －明治剑客浪漫谭－ Rurouni Kenshin（2023）[01-24] [WebRip] [1080p] [简日内嵌] [2023年7月番]```
, you need to specify the episode name and season.
5.Import error: Download warning: ```Unable to Import. Path matches client base download directory, it's possible 'Keep top-level folder' is disabled for this Path matches client base download directory, it's possible 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT set to 'Original' or 'Create Subfolder'?```

My qbittorrent settings are as follows:
![qbittorrent](https://github.com/Sonarr/Sonarr/assets/142248225/a1c911b8-b17c-45ec-898c-93f514faefdb)

### Environment

```markdown
- OS: unraid
- Sonarr: 4.0.0.746
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[2.04.txt](https://github.com/Sonarr/Sonarr/files/13800414/2.04.txt)

**Comment by markus101** [comment] 2023-12-31 07:27
Please post the trace logs that include this error, the logs you posted are unrelated.

**Comment by kristianvmd** [comment] 2023-12-31 07:32
> Please post the trace logs that include this error, the logs you posted are unrelated and are not trace.

![image](https://github.com/Sonarr/Sonarr/assets/142248225/b2c1979a-0a75-4f46-b02d-ed198bfdc0de)

**Comment by kristianvmd** [comment] 2023-12-31 07:32
> Please post the trace logs that include this error, the logs you posted are unrelated and are not trace.

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/13800507/sonarr.debug.txt)

**Comment by markus101** [comment] 2023-12-31 07:33
Closer, but those are debug, not trace and don't contain that error,

**Comment by kristianvmd** [comment] 2023-12-31 07:52
> Closer, but those are debug, not trace and don't contain that error,

Sorry, now I've re-searched and waited for the error to appear, then downloaded all the logs

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/13800530/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13800531/sonarr.trace.txt)

**Comment by markus101** [comment] 2023-12-31 17:51
I'm not able to reproduce this issue.

That release correctly is using a subfolder in my testing. Unfortunately the while the second debug logs you provided do show the release the trace logs are from several minutes later and don't include the response from qbit to check some of the information there.

To get the correct logs it's probably easiest to clear the existing logs, restart Sonarr and post everything (debug and trace) from the the folder after a few minutes.

**Comment by kristianvmd** [comment] 2023-12-31 17:54
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/13801851/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13801852/sonarr.trace.txt)


I've re-prepared another log this afternoon, can I trouble you to see if it meets the requirements, if not I'll go and prepare a new one now

**Comment by kristianvmd** [comment] 2024-01-02 06:28
> I'm not able to reproduce this issue.
> 
> That release correctly is using a subfolder in my testing. Unfortunately the while the second debug logs you provided do show the release the trace logs are from several minutes later and don't include the response from qbit to check some of the information there.
> 
> To get the correct logs it's probably easiest to clear the existing logs, restart Sonarr and post everything (debug and trace) from the the folder after a few minutes.

I followed the steps below to regenerate the log:
1. Clean up the logs
2. re-downloaded this step of the anime
3. wait 10 minutes for the download to complete and then download the logs

But there are several copies of the log, I submitted the download at 13:57 and the download completed at 14:10 while the import failed.


I downloaded the logs for these points in time, please bother to let me know if there is something wrong with my steps. I've re-executed it once and I'm pretty sure it's an import failure


[2.00pm.trace.8.txt](https://github.com/Sonarr/Sonarr/files/13807596/2.00pm.trace.8.txt)
[2.05pm.trace.7.txt](https://github.com/Sonarr/Sonarr/files/13807597/2.05pm.trace.7.txt)
[2.08pm.trace.3.txt](https://github.com/Sonarr/Sonarr/files/13807599/2.08pm.trace.3.txt)
[2.17pm.trace.2.txt](https://github.com/Sonarr/Sonarr/files/13807600/2.17pm.trace.2.txt)
[2.18pm.trace.1.txt](https://github.com/Sonarr/Sonarr/files/13807593/2.18pm.trace.1.txt)

**Comment by markus101** [comment] 2024-01-02 19:19
You don't need to redownload the anime, just leave the one failing to import in your download client so Sonarr can process it.

When it's in there and failing

1. Clear logs
2. Restart Sonarr
3. Wait a few minutes
4. Post _all_ trace logs

We need to see the response from qbit for this item, the logs you've posted above don't include that. Make sure your logs don't include any searches (like these do) otherwise there will be a ton of useless information to filter through.

**Comment by kristianvmd** [comment] 2024-01-03 12:29
> You don't need to redownload the anime, just leave the one failing to import in your download client so Sonarr can process it.
> 
> When it's in there and failing
> 
> 1. Clear logs
> 2. Restart Sonarr
> 3. Wait a few minutes
> 4. Post _all_ trace logs
> 
> We need to see the response from qbit for this item, the logs you've posted above don't include that. Make sure your logs don't include any searches (like these do) otherwise there will be a ton of useless information to filter through.

I've been waiting for half an hour, there are a lot of logs generated automatically, if it's not convenient, you can tell me the keywords or other identifiers and I'll filter that part of the log for you

[sonarr.trace.13.txt](https://github.com/Sonarr/Sonarr/files/13818889/sonarr.trace.13.txt)
[sonarr.trace.12.txt](https://github.com/Sonarr/Sonarr/files/13818891/sonarr.trace.12.txt)
[sonarr.trace.11.txt](https://github.com/Sonarr/Sonarr/files/13818894/sonarr.trace.11.txt)
[sonarr.trace.10.txt](https://github.com/Sonarr/Sonarr/files/13818896/sonarr.trace.10.txt)
[sonarr.trace.9.txt](https://github.com/Sonarr/Sonarr/files/13818897/sonarr.trace.9.txt)
[sonarr.trace.8.txt](https://github.com/Sonarr/Sonarr/files/13818899/sonarr.trace.8.txt)
[sonarr.trace.7.txt](https://github.com/Sonarr/Sonarr/files/13818900/sonarr.trace.7.txt)
[sonarr.trace.6.txt](https://github.com/Sonarr/Sonarr/files/13818901/sonarr.trace.6.txt)

**Comment by markus101** [comment] 2024-01-03 19:25
When Sonarr queries qbit torrent it'll log something like:

```
2024-01-03 00:00:00.0|Trace|HttpClient|Req: [GET] http://host:8080/api/v2/torrents/info?category=tv
```

followed by the response from qbit, which is what I wanted to look at, I have been able to find it in one of the previous logs that I missed before, so I think we're good on that end.

Looking at that item in your logs, Sonarr's processing of it is correct as Qbit is reporting the download is in the root of the downloads and not in a subfolder. I've verified against a similar qbit version locally (I say similar because 2.8.19 is the API version for both, but not exactly sure which versions have that API version) and Sonarr adds the torrent and handles it on the other end without issue.

The only setting I see different is I'm using an incomplete folder with qbit (`Keep incomplete torrents in:`).

In the current develop version of Sonarr you can tell Sonarr to specify the torrent content layout when adding torrents, under qbit's settings. When set to `Default` it will let qbit decide, which is the default setting, make sure that setting hasn't been changed in Sonarr's settings since it looks like you're using a develop version of Sonarr.

**Comment by kristianvmd** [comment] 2024-01-04 14:56
Mainly I've been using sonarr for almost 2 years now and never encountered this glitch until recently when it started happening more frequently, so I suspect it's a bug, I just don't know how to troubleshoot it...

And I've tried it on my friend's side who downloaded different episodes than I did (the settings are the same) but also got this error in large numbers，It's mostly anime episodes that get this import error, could the site be the cause?
![9](https://github.com/Sonarr/Sonarr/assets/142248225/545e7e52-76f3-4e11-80b7-9d3b0ef63ef6)


The qbittorrent settings in my sonarr:
![1](https://github.com/Sonarr/Sonarr/assets/142248225/f4b74c5c-b7a1-476d-b7d8-b4367cca5d8d)
![2](https://github.com/Sonarr/Sonarr/assets/142248225/5eed0736-e0cf-4d09-b877-dccc4d785bb8)

Remote Path Mappings Settings in my sonarr：
![3](https://github.com/Sonarr/Sonarr/assets/142248225/dd618546-3c46-4503-b11f-2c56a25e0a2b)

Mount folder path settings for sonarr in my docker:
![5](https://github.com/Sonarr/Sonarr/assets/142248225/d5a4ffa6-2890-4a3f-bea7-9e7c46f30848)

**Comment by markus101** [comment] 2024-01-05 01:13
> That Default setting never changed in Sonarr's settings

That setting is very recent, only in the v4 develop builds at this time. Does changing that setting in Sonarr to `Create Subfolder` resolve the issue?

> Were you unable to reproduce the failure by following the steps I sent you? Kind of strange...

Correct, I was unable to reproduce the issue.

> It's mostly anime episodes that get this import error, could the site be the cause?

If the site consistently releases multi-file episodes without subfolder it's could be, but the torrent you reported issues with does have a subfolder for all the files, your qbit just seems to handle that differently.

Which version of qbit are you running?

**Comment by kristianvmd** [comment] 2024-01-05 01:25
qBittorrent v4.5.2 Web UI (64-bit)

**Comment by kristianvmd** [comment] 2024-01-05 03:38
I set it up as follows and re-downloaded it and it still reports the same error
![1](https://github.com/Sonarr/Sonarr/assets/142248225/0bd555de-0def-4c32-b7d8-56f2dc614c8d)
![2](https://github.com/Sonarr/Sonarr/assets/142248225/fc1014a4-e95f-4bcb-a9c3-7674ed00e400)
![3](https://github.com/Sonarr/Sonarr/assets/142248225/b9e43882-1a62-4651-bf17-d6db4a281fb9)


My version of qbittorrent
![5](https://github.com/Sonarr/Sonarr/assets/142248225/ae0e6afc-c4f1-4f98-b963-2cb516a9f346)

**Comment by kristianvmd** [comment] 2024-01-06 05:23
> > That Default setting never changed in Sonarr's settings
> 
> 
> 
> That setting is very recent, only in the v4 develop builds at this time. Does changing that setting in Sonarr to `Create Subfolder` resolve the issue?
> 
> 
> 
> > Were you unable to reproduce the failure by following the steps I sent you? Kind of strange...
> 
> 
> 
> Correct, I was unable to reproduce the issue.
> 
> 
> 
> > It's mostly anime episodes that get this import error, could the site be the cause?
> 
> 
> 
> If the site consistently releases multi-file episodes without subfolder it's could be, but the torrent you reported issues with does have a subfolder for all the files, your qbit just seems to handle that differently.
> 
> 
> 
> Which version of qbit are you running?

Can you tell me your qbittorrent version? I will use your version to test it.

**Comment by markus101** [comment] 2024-01-07 17:55
I'm using qbit 4.5.2 and was debugging with a build right from` develop`, with all the changes from `4.0.0.746`.

I'm closing this issue as we've been unable to reproduce and there have been no other related reports here or in our support channels. If you'd like to troubleshoot further it's probably best to join Discord and discuss it there, but all the support channels are below.

Support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Closed by markus101** 2024-01-07 17:55 UTC
Labels: waiting-for-info, needs-triage

**Comment by kristianvmd** [comment] 2024-01-12 07:40
> I'm using qbit 4.5.2 and was debugging with a build right from` develop`, with all the changes from `4.0.0.746`.
> 
> I'm closing this issue as we've been unable to reproduce and there have been no other related reports here or in our support channels. If you'd like to troubleshoot further it's probably best to join Discord and discuss it there, but all the support channels are below.
> 
> Support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I encountered the same import failure,, here is the reproduction method and logs：

1.Search for this anime: Heavenly Delusion, using this site https://acg.rip/
2.Select this search result: https://acg.rip/t/295305, size 22.3 GiB
3.The same import failure occurs once the download is complete

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13916024/sonarr.trace.txt)

**Comment by 3isenHeiM** [comment] 2024-04-02 21:52
Hi I have the same issue (Sonarr version 4.0.3.1413 and qBittorrent v4.5.2) :

<img width="860" alt="Screenshot  2024-04-02 à 23 34 20" src="https://github.com/Sonarr/Sonarr/assets/26417172/49116514-af16-43da-aa99-8fc45f3a7a30">

From [this comment above](https://github.com/Sonarr/Sonarr/issues/6280#issuecomment-1875856534) I managed to isolate the following logs :

```log
2024-04-02 23:33:57.1|Trace|HttpClient|Req: [GET] http://qbittorrent.home:8090/api/v2/torrents/info?category=tv-sonarr
2024-04-02 23:33:57.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-04-02 23:33:57.2|Trace|HttpClient|Res: HTTP/1.1 [GET] http://qbittorrent.home:8090/api/v2/torrents/info?category=tv-sonarr: 200.OK (24152 bytes) (15 ms)
2024-04-02 23:33:57.2|Trace|HttpClient|Response content (24152 bytes): <JSON OBJECT>
```

The JSON blob is a list of object, each one being a file in error, with the following structure:
```json
    {
        "added_on": 1712001512,
        "amount_left": 0,
        "auto_tmm": false,
        "availability": -1,
        "category": "tv-sonarr",
        "completed": 21458640597,
        "completion_on": 1712008649,
        "content_path": "/mnt/Downloads/tv-sonarr",
        "dl_limit": 0,
        "dlspeed": 0,
        "download_path": "",
        "downloaded": 21467639603,
        "downloaded_session": 0,
        "eta": 8640000,
        "f_l_piece_prio": false,
        "force_start": false,
        "hash": "8f131c3189f5ca8f2dea09a6a437fbb3dd2c0d25",
        "infohash_v1": "8f131c3189f5ca8f2dea09a6a437fbb3dd2c0d25",
        "infohash_v2": "",
        "last_activity": 1712023617,
        "magnet_uri": "magnet:?xt=urn:btih:8f131c3189f5ca8f2dea09a6a437fbb3dd2c0d25&dn=Yellowstone.S03.MULTi.1080p.WEB.DDP5.1.H265-TFA&tr=http%3a%2f%2ftracker.loadpeers.org%3a8080%(removed)%2fannounce",
        "max_ratio": -1,
        "max_seeding_time": -1,
        "name": "Yellowstone.S03.MULTi.1080p.WEB.DDP5.1.H265-TFA",
        "num_complete": 5,
        "num_incomplete": 6,
        "num_leechs": 0,
        "num_seeds": 0,
        "priority": 0,
        "progress": 1,
        "ratio": 0.00029048414801637285,
        "ratio_limit": -2,
        "save_path": "/mnt/Downloads/tv-sonarr",
        "seeding_time": 36366,
        "seeding_time_limit": -2,
        "seen_complete": 1712008649,
        "seq_dl": false,
        "size": 21458640597,
        "state": "queuedUP",
        "super_seeding": false,
        "tags": "",
        "time_active": 41548,
        "total_size": 21458640597,
        "tracker": "",
        "trackers_count": 1,
        "up_limit": 0,
        "uploaded": 6236009,
        "uploaded_session": 0,
        "upspeed": 0
    },
```

I don't know if that can help...
