### ISSUE TITLE
Sonarr find nothing at tvdb anymore

### ISSUE THREAD

**Issue by DunklerPhoenix** [Sonarr/Sonarr#3506] opened 2020-01-10 10:54 UTC
**Describe the bug**
Sonarr can't find many series on tvdb anymore. I also tried to add 9-1-1 with name or id and also nothing.  I stopped Sonarr for three days, so I can't exactly say since when it happens.

**Screenshots**
![sonarr](https://user-images.githubusercontent.com/1261305/72147561-1302f900-339f-11ea-8de3-68cf61be4945.png)
![sonarr2](https://user-images.githubusercontent.com/1261305/72147716-742acc80-339f-11ea-85c1-c25d34666b0d.png)

**Logs**
Link to debug or trace log files.
[sonarr.0.txt](https://github.com/Sonarr/Sonarr/files/4045215/sonarr.0.txt)

**System Information**

 - Sonarr Version: 3.0.3.687
 - Operating System: Ubuntu 18.04.3 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**Comment by t3knical** [comment] 2020-01-10 11:06
Series Breaking Bad (tvdbid 81189), Supernatural (tvdbid 78901), True Detective (tvdbid 270633), Whose Line Is It Anyway? (US) (tvdbid 76808), Marvel's Agents of S.H.I.E.L.D. (tvdbid 263365), Archer (2009) (tvdbid 110381), Arrow (tvdbid 257655), Better Call Saul (tvdbid 273181), Billions (tvdbid 279536), Blindspot (tvdbid 295647), DC's Legends of Tomorrow (tvdbid 295760), Doom Patrol (tvdbid 355622), Impossible Engineering (tvdbid 294492), Lucifer (tvdbid 295685), Mr. Robot (tvdbid 289590), Outlander (tvdbid 270408), Peaky Blinders (tvdbid 270915), Silicon Valley (tvdbid 277165), Stranger Things (tvdbid 305288), Supergirl (tvdbid 295759), The Boys (tvdbid 355567), The Flash (2014) (tvdbid 279121), The Good Doctor (tvdbid 328634), The Magicians (2015) (tvdbid 299139), The Orville (tvdbid 328487), The Walking Dead (tvdbid 153021), Titans (2018) (tvdbid 341663), Vikings (tvdbid 260449), Westworld (tvdbid 296762), Family Guy (tvdbid 75978), One Piece (tvdbid 81797), One-Punch Man (tvdbid 293088), Sword Art Online (tvdbid 259640), The Seven Deadly Sins (tvdbid 284131), This Is Us (tvdbid 311714), American Horror Story (tvdbid 250487), The Mandalorian (tvdbid 361753), Watchmen (tvdbid 360733), The Witcher (tvdbid 362696), Ozark (tvdbid 329089), The Expanse (tvdbid 280619), His Dark Materials (tvdbid 360295), Star Trek: Picard (tvdbid 364093), Star Trek: Discovery (tvdbid 328711), The Outsider (2020) (tvdbid 365480), The Last Kingdom (tvdbid 298566) were removed from TheTVDB, 

it's not all for me but yeah slowly and slowly i keep loosing shows, today was the biggest chunk which i posted above usually it was just 1-3 every other day or so.

**Comment by vinanrra** [comment] 2020-01-10 12:14
Same error here:

`Series Young Sheldon (tvdbid 328724), Shameless (US) (tvdbid 161511), Godfather of Harlem (tvdbid 365186), Star Trek: Picard (tvdbid 364093), The Boys (tvdbid 355567), The Mandalorian (tvdbid 361753), Mr. Robot (tvdbid 289590), Black Clover (tvdbid 331753), One Piece (tvdbid 81797), Sorcerous Stabber Orphen (tvdbid 372939), The Promised Neverland (tvdbid 348002), The Rising of the Shield Hero (tvdbid 353712), Assassins Pride (tvdbid 357431), Vinland Saga (tvdbid 359274), Sword Art Online (tvdbid 259640), My Hero Academia (tvdbid 305074), Dr. Stone (tvdbid 355774), The Seven Deadly Sins (tvdbid 284131), Fire Force (tvdbid 355480), Arifureta - From Commonplace to World's Strongest (tvdbid 357019), Cautious Hero: The Hero Is Overpowered but Overly Cautious (tvdbid 369048), Cells at Work! (tvdbid 346931), Re:ZERO -Starting Life in Another World- (tvdbid 305089), House of the Dragon (tvdbid 371572), The Outsider (2020) (tvdbid 365480), Hunters (2020) (tvdbid 372081), Sex Education (tvdbid 356317), Vikings (tvdbid 260449), Lovecraft Country (tvdbid 357864), The Walking Dead (tvdbid 153021), Dracula (2020) (tvdbid 361160), Taboo (2017) (tvdbid 292157), 9-1-1: Lone Star (tvdbid 364080), FBI: Most Wanted (tvdbid 364088), Briarpatch (tvdbid 359608), Tommy (tvdbid 364089), The Plot Against America (tvdbid 367559), Brave New World (2019) (tvdbid 359606), Awkwafina is Nora From Queens (tvdbid 356417), Council of Dads (tvdbid 363853), Locke & Key (tvdbid 361594), Outmatched (tvdbid 359349), Little Fires Everywhere (tvdbid 363194), COBRA (2020) (tvdbid 372696), White House Farm (tvdbid 373989), Tokyo Vice (tvdbid 366624) were removed from TheTVDB`

**Comment by Matt84uk** [comment] 2020-01-10 12:42
Same here, I lost a handful of shows towards the end of last year, but today I've lost well over a hundred. Manually checking on thetvdb finds them, but a refresh on Sonarr states it's deleted. Sample trace for The Flash:



> 20-1-10 12:30:13.9|Trace|EventAggregator|Publishing SceneMappingsUpdatedEvent
20-1-10 12:30:13.9|Trace|EventAggregator|SeriesRefreshStartingEvent <- SceneMappingService
20-1-10 12:30:13.9|Info|RefreshSeriesService|Updating The Flash (2014)
20-1-10 12:30:13.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-1-10 12:30:13.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-1-10 12:30:13.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-1-10 12:30:13.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-1-10 12:30:13.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-1-10 12:30:13.9|Trace|HttpClient|Req: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/279121
20-1-10 12:30:13.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-1-10 12:30:14.0|Trace|HttpClient|Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/shows/en/279121: 404.NotFound
{"message":"NotFound","description":"thetvdb.com does not have a series with the tvdbid 279121, it may have been removed."} (163 ms)
20-1-10 12:30:14.0|Error|RefreshSeriesService|Series 'The Flash (2014)' (tvdbid 279121) was not found, it may have been removed from TheTVDB.
20-1-10 12:30:14.0|Trace|EventAggregator|Publishing SeriesRefreshCompleteEvent
20-1-10 12:30:14.0|Trace|CommandQueueManager|Updating command status
20-1-10 12:30:14.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-1-10 12:30:14.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-1-10 12:30:14.1|Trace|EventAggregator|Publishing CommandExecutedEvent
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
20-1-10 12:30:14.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
20-1-10 12:30:14.1|Trace|CommandExecutor|RefreshSeriesCommand <- RefreshSeriesService [00:00:03.2250000]

**Comment by Fossil01** [comment] 2020-01-10 13:18
Looks like their API has issues: https://forums.thetvdb.com/viewtopic.php?f=17&t=61698&sid=1608dbe66a7cec6f48d83ae6b03086e6

**Comment by Thundernerd** [comment] 2020-01-10 14:38
Here's a link to the [Known Issues Log & Status](https://forums.thetvdb.com/viewtopic.php?f=122&t=60239) of the TVDB.

They are currently researching the issues it seems.

> - Ongoing 504 errors causing site delays and "Whoops" error messages — Researching

**Comment by markus101** [comment] 2020-01-10 15:33
Yes they co to use to have issues. Dupe of https://github.com/Sonarr/Sonarr/issues/3415

**Closed by markus101** 2020-01-10 15:33 UTC

**Comment by Routhinator** [comment] 2020-01-10 16:35
@markus101 This problem renders Sonarr unusable. Is there no way to configure it to use IMDB or something else that isn't horribly broken? This has been getting worse for months now.

**Comment by Fossil01** [comment] 2020-01-10 16:49
TVMaze and The Movie DB are pretty good. But I still think TVDB has a larger dataset.

**Comment by Co0ljay** [comment] 2020-01-10 17:05
Same issue on WIndows 10

Sonarr 2.0.0.5337 - Jul 2 2019
