### ISSUE TITLE
Refresh Series task crashes Sonarr with mono v4.6.x

### ISSUE THREAD

**Issue by j4m35** [Sonarr/Sonarr#1529] opened 2016-10-31 07:16 UTC
Hi,

I am running Sonarr on a Gentoo system.

When I upgraded the mono package to v4.6.x, Sonarr will crash when the Refresh Series task is executed.

Upon downgrading the mono package to v4.4.x, Sonarr will be able to complete the Refresh Series task without crashing.

Please let me know how I can help with this issue, e.g. what verbosity of logs should be set and what log files should I post.

Best regards,
James

**Comment by markus101** [comment] 2016-10-31 08:24
Sounds like it may be the same issue as: https://forums.sonarr.tv/t/sonarr-on-linux-now-crashing-after-a-few-secs/12254/

**Comment by j4m35** [comment] 2016-11-01 01:20
You are absolutely right. It is the same. I used the trace logs and saw the same error with libgdiplus.so.0.

Installing the "libgdiplus" package resolves the issue; however installing that package requires a lot of other packages which I do not need on my headless system.

Would appreciate if you could see why the lack of libgdiplus.so.0 causes the crash.  In the meantime I would prefer to stick with mono v4.4.x even though it has minor issues of connecting to indexers / clients.

**Comment by athei** [comment] 2016-11-01 20:07
I can confirm that this issue is present on Freebsd, too. I could not test whether it's resolved by installing libgdiplus because the port does not built at the moment: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213973

**Comment by athei** [comment] 2016-11-05 10:25
Compiled libgdiplus myself. I confirm that it is working when libgdiplus is installed in freebsd.

**Comment by Mask66** [comment] 2016-11-05 19:39
I'd like to confirm this too (for FreeBSD 11) and ask if the dependency can be removed/worked around, since it's a lot of X11 overhead for a headless system.

**Comment by markus101** [comment] 2016-11-05 19:57
`libgdiplus` has been used for some time now (over a year I believe) and this problem only surfaced in mono 4.6 on some systems. We do plan to remove our reliance on it, but it's not something that will be addressed in the near term. Using a version of mono before 4.6 will workaround the issue.

**Comment by Taloth** [comment] 2016-11-05 20:02
We don't strictly require gdiplus, if it's absent Sonarr used to work fine, we just don't resize images in that case.
It's only since mono 4.6 that it started crashing. We _might_ be able to implement a workaround for that.

**Comment by markus101** [comment] 2016-11-06 05:51
2.0.0.4385 is now out in develop (https://github.com/Sonarr/Sonarr/wiki/Release-Branches), which has a fix for this. It hasn't been tested with mono 4.6 yet, but if someone can confirm whether it works or not we'll get this out to master ASAP.

**Comment by Mask66** [comment] 2016-11-06 09:21
2.0.0.4385 looks good, just ran "refresh series" without installed libgdiplus and no crash.
This is on FreeBSD 11.0-STABLE r308338 with mono 4.6.1 (Stable 4.6.1.5/ef43c15.

**Comment by Taloth** [comment] 2016-11-06 12:43
Awesome, tnx for confirming, Mask66.

Closed via https://github.com/Sonarr/Sonarr/commit/b093be3f4e16ebd2dcbb286f57aca4ec74be0b6f

**Closed by Taloth** 2016-11-06 12:43 UTC
