### ISSUE TITLE
Upgrade without deleting. 

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [Sonarr/Sonarr#3459] opened 2019-12-16 21:04 UTC
## Feature Request: Upgrade without deleting. 

Transcoding 4k is rather expensive compared to keeping a 1080p on storage. Looking for a way to keep the i.e 1080p. A simple workaround could be to add a "move" operation so the file is moved out of the Sonarr monitored folder, and therefore doesn't break necessary logic in terms of folders and their content. 

Adding a custom hook for "on delete" doesn't work as sonarr doesn't wait for script. (V3)

**Comment by markus101** [comment] 2019-12-16 22:31
Dupe of https://github.com/Sonarr/Sonarr/issues/312
https://github.com/Sonarr/Sonarr/issues/791 could also be useful since On Delete is after import.

**Closed by markus101** 2019-12-16 22:31 UTC
