### ISSUE TITLE
Ability to allow sonarr to set the save location of a torrent

### ISSUE THREAD

**Issue by RedTedRedemption** [Sonarr/Sonarr#3674] opened 2020-04-11 21:30 UTC
**Describe the problem**
While Sonarr does a great job of moving finished torrent files to their final locations on the disk once the download has completed, I have to manually go into my torrent client to move the location of the torrented files to their final location to prevent having duplicate files on the system. While I am aware that sonarr does support hardlinking files, I would rather have my torrents pointing directly to their final locations, making organization easier and functioning as a backup system of sorts that can automatically rebuild if data is lost.

**Describe any solutions you think might work**
If supported by the APIs, I would suggest allowing sonarr to set the download location for torrents to the location it would normally copy to on completion, or move the files using the torrent client when it detects that the download is complete.

**Comment by markus101** [comment] 2020-04-11 21:33
Dupe of https://github.com/Sonarr/Sonarr/issues/3654

We don't have plans to support this functionality, but it could be achieved with custom scripts and disabling of Completed Download Handling. Upgrading quality will be an issue with this configuration though.

**Closed by markus101** 2020-04-11 21:33 UTC
