### ISSUE TITLE
Health Check for rename feature

### ISSUE THREAD

**Issue by g4m3r7ag** [Sonarr/Sonarr#3535] opened 2020-01-21 21:52 UTC
Some sort of health check that does a dry-run of the rename functionality on a series and outputs Series Name - X number of episodes incorrectly named to indicate something may have changed in the available data. This would run against all series whenever it is triggered.

**Comment by markus101** [comment] 2020-01-21 21:53
Dupe of https://github.com/Sonarr/Sonarr/issues/1118

**Closed by markus101** 2020-01-21 21:53 UTC
