### ISSUE TITLE
When Manually Importing Multiple Items, Only Notify Plex when All Items Completed

### ISSUE THREAD

**Issue by raynotroy** [Sonarr/Sonarr#1948] opened 2017-05-27 02:24 UTC
I've noticed that the import process is significantly faster if I disable Plex notifications, but I want to leave it on by default for individual episodes downloading from that day.  Either Sonnar should only notify Plex when all items are imported so it only scans my library once or the manual import screen should allow me to select the notifications manually.

Ideally on the Manually Import screen at the bottom there would be a second drop down that allows me to notify plex as well as "do nothing".

**Comment by markus101** [comment] 2017-05-27 04:54
> Sonnar should only notify Plex when all items are imported so it only scans my library once

Sonarr tells Plex to scan the single series (if partial scanning is enabled and you're using a plex version from the past year or so), though importing multiple episodes in a single series will try to update for every episode, but we have an issue for that: https://github.com/Sonarr/Sonarr/issues/363

As well as a dupe of excluding notifications

**Closed** 2017-05-27 04:55 UTC
