### ISSUE TITLE
Download torrents directly to correct directory

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#1141] opened 2016-02-11 20:06 UTC
Option to download torrents directly to correct series/season directory. This would remove the need for either soft or hard copying, which makes deletion and space recovery much easier.

Also, if imports fail, manual imports would only need to process a smaller list of files (right now if you try to do a manual import against the sonarr download directory, it takes several minutes to render, and the UI does not work correctly due to div sizes (separate issue will be created))

A few caveats : 
Probably not compatible with renaming (since that would screw up the seeding). UI would need to validate you don't choose both options.

Need to detect seasons vs episodes for determining correct folder (if confused, dump into series root folder, still better than duplicates all over)

**Comment by markus101** [comment] 2016-02-12 02:48
Dupe of https://github.com/Sonarr/Sonarr/issues/738

**Closed by markus101** 2016-02-12 02:48 UTC
