### ISSUE TITLE
Add “on delete” trigger to Connections

### ISSUE THREAD

**Issue by flying-sausages** [Sonarr/Sonarr#3730] opened 2020-05-04 00:41 UTC
**Describe the problem**
My overarching problem is that I'd like to keep only n amount of episodes on the disk (both sonarr and download client). TO be more precise, I only want the last episodes of shows like The Daily show. From what I've seen, this was a requested feature for quite some time (#314 and all its duplicates) however no progress has been made on this for at least 7 years from what I can tell.

Currently I have to manually delete the files first in the sonarr directory (either through plex, manually or from sonarr itself) and then manually in the torrent client, which can be quite time consuming.

**Describe any solutions you think might work**
What I have been told only now is that Plex can handle this deletion behaviour on its own through the advanced settings. When the episode is deleted by Plex, Sonarr will pick this up and--if it is set to do so--unmonitor these episodes.
These events are visible in the history.
![image](https://user-images.githubusercontent.com/23618693/80929843-bc328c80-8d9e-11ea-80c2-fdf04a0ac741.png)

What I propose is to add an "on delete" to the "Connection settings".
![image](https://user-images.githubusercontent.com/23618693/80929853-dd937880-8d9e-11ea-9691-baf57aa858df.png)
This way, anyone could make their own script to tell their download client to delete the episodes as well, seeing as the hash is passed to the scripts/webhooks. 

Another option would be to build this option straight into sonarr by adding an advanced option to "Delete torrent data from client when episode is removed and unmonitored." Either this could be for all shows, or a toggle for specific shows.

Honestly, even the option to "Remove data from torrent client" either by adding another column with checkboxes to this menu or just one single checkbox for all the ones that are being processed would already help speed my use case up. And I am fairly sure this would apply to a lot of people who are keeping up to date with any daily shows.
![image](https://user-images.githubusercontent.com/23618693/80929965-a5d90080-8d9f-11ea-9528-a9df963db414.png)

Please help us automatically delete episodes in one way or another :(

**Comment by flying-sausages** [comment] 2020-05-04 01:02
I cross-posted this to the forum so please close whichever is in the wrong place https://forums.sonarr.tv/t/add-on-delete-trigger-to-connections/25675

**Comment by markus101** [comment] 2020-05-04 01:29
Dupe of https://github.com/Sonarr/Sonarr/issues/2410

**Closed by markus101** 2020-05-04 01:29 UTC
