### ISSUE TITLE
Global disable button for connection(notification client)

### ISSUE THREAD

**Issue by PedroBuffon** [Sonarr/Sonarr#7287] opened 2024-10-09 17:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

So, as of now the only way to disable a notification for a certain connection is to either delete it completely(which will delete saved info such as api keys) or uncheck every single notification trigger.

### Describe the solution you'd like

Add a global checkbox on the client to disable it without needing to uncheck or deleting the connection.

### Describe alternatives you've considered

Same like Indexer setting that you can disable it by unchecking the Enable RSS checkbox.

**Comment by markus101** [comment] 2024-10-09 17:21
Duplicate of #7188. No plans to add.

**Closed by markus101** 2024-10-09 17:21 UTC
Labels: needs-triage
