### ISSUE TITLE
Prefer certain filenames when looking for releases

### ISSUE THREAD

**Issue by serialoverflow** [Sonarr/Sonarr#1655] opened 2017-02-02 19:17 UTC
Hey,

i know there is a "Must contain" option when looking for posts on an indexer but is there something less absolute, like a "Should contain" option?
I want to prefer files that contain certain words, for example "Obfuscated" or a specific release group.

Is there a way to do that yet?

**Comment by markus101** [comment] 2017-02-02 19:54
Dupe of https://github.com/Sonarr/Sonarr/issues/385

**Closed by markus101** 2017-02-02 19:54 UTC
