### ISSUE TITLE
Group activity queue by download item

### ISSUE THREAD

**Issue by ipbeegle** [Sonarr/Sonarr#7201] opened 2024-09-12 04:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When downloading many season packs, the activity queue page can fill up very quickly.

### Describe the solution you'd like

Add an option to group items in the activity queue by download item. Ideally, under some sort of accordion. I'm not sure exactly how this would work with other non-grouped items. Perhaps separate tables for the grouped items and then one for loose items? Pagination would also be an issue. I could see there being an option added to the queue API which would do the grouping itself, rather than being done on the frontend.

### Describe alternatives you've considered

One alternative would be to limit the number of simultaneous downloads, but that is not always possible. Take anime packs for instance, which can contain upwards of 100+ items.

**Comment by markus101** [comment] 2024-09-12 04:38
Duplicate of #6537

**Closed by markus101** 2024-09-12 04:38 UTC
Labels: needs-triage
