### ISSUE TITLE
Support MULTi / language option the way Radarr does

### ISSUE THREAD

**Issue by sevospl** [Sonarr/Sonarr#4741] opened 2021-11-08 16:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Yes, the problem is when you want to build a library in your local language, yet do it in a practical way.

### Describe the solution you'd like

In Radarr when you configure an indexer you can specify which languages
typically occur in a MULTi release, e. g. Original and Polish.

Then you can configure a profile (e.g. HD - 720/1080p) to prefer "Polish" as "Language for Releases".

This is a fantastic way of handling such a case scenario where a user prefers their content to be in their language.
A release can either have only Polish audio or Polish + Original (this is where "MULTi" comes in handy).

This feature request is probably going to be super easy to implement
as it would take only copying the existing code from Radarr and it probably would work just fine.

### Describe alternatives you've considered

No better alternative. This is the Way of Mandalore...

### Anything else?

![image](https://user-images.githubusercontent.com/15851064/140778164-5df43825-2eb3-43c0-ad47-45871782bf9f.png)

![image](https://user-images.githubusercontent.com/15851064/140778187-cee8252f-0375-4814-bed2-eb54a4656119.png)

**Comment by bakerboy448** [comment] 2021-11-08 16:19
> > Is there an existing issue for this?

>  I have searched the existing issues

Why lie and open a duplicate?

duplicate of https://github.com/Sonarr/Sonarr/issues/2854

**Closed by bakerboy448** 2021-11-08 16:19 UTC
Labels: needs-triage

**Comment by sevospl** [comment] 2021-11-08 16:37
> > > Is there an existing issue for this?
> 
> > I have searched the existing issues
> 
> Why lie and open a duplicate?
> 
> duplicate of #2854

Why accuse me of doing something I'm not? I searched for "multi" or "language" and didn't see this particular issue.

**Comment by bakerboy448** [comment] 2021-11-08 16:38
> searched for "multi" or "language" and didn't see this particular issue.

https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+is%3Aopen+multi

It's there clear as day, so not sure why you didn't see it

**Comment by sevospl** [comment] 2021-11-08 16:54
> > searched for "multi" or "language" and didn't see this particular issue.
> 
> https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+is%3Aopen+multi
> 
> It's there clear as day, so not sure why you didn't see it

Me neither, but please don't be quick to accuse people of something like that.

You can close the issue and I'll engage myself in the other issue. Thanks for the headsup.
