### ISSUE TITLE
Parse newznab:attr - language field

### ISSUE THREAD

**Issue by PeterRudolpf78910** [Sonarr/Sonarr#6004] opened 2023-09-05 10:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

[newznab naming scheme](https://inhies.github.io/Newznab-API/attributes/#attribute-example)

Sonarr is not getting all languages of a show or just set's the language english. Here is an example API call to an indexer:
![image](https://user-images.githubusercontent.com/143845956/265126821-413acd39-26bb-4852-b697-0de2f3202fa6.png)

It is related to this issue #4593

### Describe the solution you'd like

An option to parse the newznab:attr language field, or a mechanism to parse this field instead of or in addition to simply parsing the name.

### Describe alternatives you've considered

Alternatively, you can use something like NZBHydra to add the language to the title so sonarr is parsing it.

Here is the issue I created over there: [NZBHydra2 Issue #888](https://github.com/theotherp/nzbhydra2/issues/888)

### Anything else?

If you need some additional info I can provide or logs I can add it here.

**Comment by markus101** [comment] 2023-09-05 15:05
Duplicate of https://github.com/Sonarr/Sonarr/issues/5654

**Closed by markus101** 2023-09-05 15:05 UTC
Labels: needs-triage

**Comment by PeterRudolpf78910** [comment] 2023-09-07 21:57
Okay then move my thing to a bug report. The parser you implemented in #5654 is searching for multiple newznab language attributes. On my indexer site it ist sometime that they put multiple languages in one attribute. Could you parse that as well? I know it's probably an indexer issue and not the right way. But can you just grep all languages out of that field? 

You are doing that with the "TryGetMultipleNewznabAttributes" function, implemented here:
https://github.com/Sonarr/Sonarr/commit/9c5a07f62a6e32832c10c80813cd3b98c5859989#

**Comment by Qstick** [comment] 2023-09-08 02:47
Which indexer is this?

**Comment by markus101** [comment] 2023-09-08 03:48
Looks like nzbgeek from the screenshot.

Based on my discussion with QStick, we can probably update it to support comma separated values, similar to how `subs` are presented, but `English - Japanese` would still fail because it's incorrectly presented.

**Comment by PeterRudolpf78910** [comment] 2023-09-08 05:57
You can probably get away with Regex `\w+` or? That would get all words out of the field regardless of the perimeter. 
And yes it's nzbgeek

**Comment by markus101** [comment] 2023-09-10 20:49
No, the expectation is that it follows the documented specifications.
