### ISSUE TITLE
Automated Deletion

### ISSUE THREAD

**Issue by CoderKiwi** [Sonarr/Sonarr#2811] opened 2018-11-11 04:31 UTC
**The Problem**
I have a limited amount of disk space on my server. I also watch a lot of daily TV shows. My entire system is entirely automated, except for the deletion of episodes after a certain time period.

**Potential Solutions**
Plex does have a feature which deletes media:
* After a time period (7 days, 30, etc)
* When over a certain number of episodes (e.g. max 5 episodes kept)

But this seems clunky to me and it doesn't always work. In my mind, Sonarr manages my media. It moves it around, it renames it, and it can delete it too (albeit manually). I think Sonarr should, under the settings for each show that sets the profile, etc. have a deletion profile/policy so that I can limit the number of say, Tonight Show with Jimmy Fallon episodes I have. I don't need episodes older than a week there! It would be great to have a way to set a number of days that episodes expire, or set a max number of episodes for a tv show to exist; similar to Plex, but more configurable and reliable.

**Comment by markus101** [comment] 2018-11-11 04:32
Dupe of https://github.com/Sonarr/Sonarr/issues/314

**Closed by markus101** 2018-11-11 04:32 UTC

**Comment by aspearman** [comment] 2018-11-11 05:44
Ah, sorry. I had searched to see if it already existed but didn’t find that. 

It’s 5 years old and locked. Any updates on whether it’ll be implemented?
