### ISSUE TITLE
TVDB Metadata for other languages

### ISSUE THREAD

**Issue by romainalca** [Sonarr/Sonarr#5765] opened 2023-06-29 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, metadata files are generated by Sonarr via TVDB API in EN language. Would it be possible to have an option to specify the language code in the Metadata menu in order to generate the nfo files with the relative content ?

### Describe the solution you'd like

Add a drop-down list containing language codes to specify a choice for the search.
If the information does not exist in this language, we take the default values ​​(most of the time in EN).

### Describe alternatives you've considered

For the moment, there is no alternative from Sonarr. We have to use an middleware beetween Sonarr and the player to build the metadata in a specific language.

**Comment by markus101** [comment] 2023-06-29 14:13
Duplicate of #269

**Closed** 2023-06-29 14:13 UTC
Labels: needs-triage

**Comment by romainalca** [comment] 2023-06-29 14:16
Duplicate but seems to be frozen for 6 years
