### ISSUE TITLE
Show title apostrophes being stripped from Jackett search URLs

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#3457] opened 2019-12-15 13:10 UTC
**Sonarr version (exact version)**: 3.0.3.664
**Mono version (if Sonarr is not running on Windows)**: 5.20.1.34
**OS**: Synology/Linux
**Description of issue**: 

Episodes for *Kirstie's Handmade Christmas* aren't being found by Sonarr on the TVChaosUK site via Jackett. Originally I thought it was a category thing, because a manual search in Jackett returned no category, but that's fixed in the latest version and still no joy. 

The search sent from Sonarr to Jackett is: 

`http://192.168.1.30:9117/torznab/all/api?t=tvsearch&cat=5000,5060,5080,5040,5030&extended=1&apikey=blahblahblah&offset=0&limit=100&q=Kirsties%20Handmade%20Christmas&season=7&ep=15
`

but it returns **no results** from TVCUK. Yet if I go into Jackett and manually search, I get results. The exact torrent name on TVCUK is "Kirstie's Handmade Christmas - S07E15 (13 December 2019) 540p mp4 Subs". If I modify the URL passed to Jacket to pass in the apostrophe, I get results back in the feed:

`http://192.168.1.30:9117/torznab/all/api?t=tvsearch&cat=5000,5060,5080,5040,5030&extended=1&apikey=blahblahblah&offset=0&limit=100&q=Kirstie%27s%20Handmade%20Christmas&season=7&ep=15`

(note the additional %27 in 'Kirsties')

Here's a snippet of what gets returned - i.e., the show as expected.

`<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://192.168.1.30:9117/" rel="self" type="application/rss+xml" />
    <title>AggregateSearch</title>
    <description>This feed includes all configured trackers</description>
    <link>http://127.0.0.1/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://192.168.1.30:9117/logos/all.png</url>
      <title>AggregateSearch</title>
      <link>http://127.0.0.1/</link>
      <description>AggregateSearch</description>
    </image>
    <item>
      <title>Kirstie's Handmade Christmas - S07E15 (13 December 2019) 540p mp4 Subs</title>
      <guid>https://tvchaosuk.com/torrents/14798</guid>
      <jackettindexer id="tvchaosuk">TVChaosUK</jackettindexer>
      <comments>https://tvchaosuk.com/torrents/14798</comments>
      <pubDate>Sat, 14 Dec 2019 12:59:46 +0000</pubDate>
      <size>612798272</size>
      <grabs>77</grabs>`

So I think the problem is that Sonarr is erroneously stripping the apostrophe from the show title, instead of http-encoding it as part of the Jacket URL request.

**Comment by markus101** [comment] 2019-12-15 15:37
Dupe of searches

**Closed by markus101** 2019-12-15 15:37 UTC
