### ISSUE TITLE
Series Mass Editor: sort by Language Profile

### ISSUE THREAD

**Issue by zandadoum** [Sonarr/Sonarr#4035] opened 2020-10-26 10:36 UTC
Version
3.0.4.982

Series-> Mass Editor

It's possible to sort by all columns except by the Language Profile column

I'd like this to be implemented.

thank you.

**Comment by markus101** [comment] 2020-10-26 14:43
Please search before opening new issues, this is a dupe of https://github.com/Sonarr/Sonarr/issues/3854

**Closed by markus101** 2020-10-26 14:43 UTC
