### ISSUE TITLE
Import Fails: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by phiresky** [Sonarr/Sonarr#2640] opened 2018-06-29 22:11 UTC
**Describe the bug**
Sonarr is not importing any series anymore. Even manual import does not work. I think it worked before in this version, but not sure.

**Logs**

```
Couldn't evaluate decision on .../....mkv: Object reference not set to an instance of an object.


System.NullReferenceException: Object reference not set to an instance of an object.
  at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.MatchesFolderSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x0009c] in <b002067148074a36acd1bfc7ade34009>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec (NzbDrone.Core.MediaFiles.EpisodeImport.IImportDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00000] in <b002067148074a36acd1bfc7ade34009>:0 
```
**System Information**

 - Sonarr Version: 2.0.0.5225
 - Operating System: Arch Linux Arm
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono JIT compiler version 5.12.0

Is there any other info that would help?

**Comment by markus101** [comment] 2018-06-29 22:13
Upgrade to the latest version of Sonarr (2.0.0.5228).

If you're still having issues open a thread on the forums for support.

**Comment by ngotchac** [comment] 2018-07-04 09:08
Hey, I have a related issue, might have been introduced fixing this one:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.FullSeasonSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\FullSeasonSpecification.cs:19 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec (NzbDrone.Core.MediaFiles.EpisodeImport.IImportDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportDecisionMaker.cs:158 
```

**System Information**
(It's this Docker image: https://hub.docker.com/r/linuxserver/sonarr/)
- Sonarr Version: 2.0.0.5228
- Mono Version: 5.12.0.226

**Comment by phiresky** [comment] 2018-07-04 09:09
This issue still happens for me on 2.0.0.5228, though interestingly currently only for all downloads in single season of a single show.

**Comment by Taloth** [comment] 2018-07-04 17:37
@phiresky Please reproduce it after turning on Trace log level in Settings->General.
Then either upload the trace log FILE somewhere and provide a link, or upload the relevant part of the trace log file (including extra lines for context) and provide a link.

**Comment by phiresky** [comment] 2018-07-04 17:54
Here you go, relevant trace log for one of the episodes:

```
18-7-4 19:47:50.1|Trace|HttpClient|Req: [POST] http://localhost:6789/jsonrpc: history()
18-7-4 19:47:50.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
18-7-4 19:47:50.2|Trace|HttpClient|Res: [POST] http://localhost:6789/jsonrpc: 200.OK (25 ms)
18-7-4 19:47:50.2|Trace|HttpClient|Response content (80281 bytes): {
"version" : "1.1",
"id" : "eb07f473",
"result" : [
{
"ID" : 3019,
"Name" : "Mad.Men.S06E12.1080p.BluRay.x264-rovers",
"RemainingFileCount" : 0,
"RetryData" : false,
"HistoryTime" : 1530300863,
"Status" : "SUCCESS/UNPACK",
"Log" : [],
"NZBID" : 3019,
"NZBName" : "Mad.Men.S06E12.1080p.BluRay.x264-rovers",
"NZBNicename" : "Mad.Men.S06E12.1080p.BluRay.x264-rovers",
"Kind" : "NZB",
"URL" : "",
"NZBFilename" : "Mad.Men.S06E12.1080p.BluRay.x264-rovers.nzb",
"DestDir" : "\/mnt\/merged\/nfs\/vid\/usenet\/nzbget\/dst\/Series\/Mad.Men.S06E12.1080p.BluRay.x264-rovers",
"FinalDir" : "",
"Category" : "Series",
"ParStatus" : "NONE",
"ExParStatus" : "NONE",
"UnpackStatus" : "SUCCESS",
"MoveStatus" : "SUCCESS",
"ScriptStatus" : "NONE",
"DeleteStatus" : "NONE",
"MarkStatus" : "NONE",
"UrlStatus" : "NONE",
"FileSizeLo" : 4020430891,
"FileSizeHi" : 0,
"FileSizeMB" : 3834,
"FileCount" : 76,
"MinPostTime" : 1395390873,
"MaxPostTime" : 1395391059,
"TotalArticles" : 5127,
"SuccessArticles" : 4648,
"FailedArticles" : 0,
"Health" : 1000,
"CriticalHealth" : 896,
"DupeKey" : "",
"DupeScore" : 0,
"DupeMode" : "ALL",
"Deleted" : false,
"DownloadedSizeLo" : 3648445294,
"DownloadedSizeHi" : 0,
"DownloadedSizeMB" : 3479,
"DownloadTimeSec" : 223,
"PostTotalTimeSec" : 283,
"ParTimeSec" : 0,
"RepairTimeSec" : 0,
"UnpackTimeSec" : 277,
"MessageCount" : 327,
"ExtraParBlocks" : 0,
"Parameters" : [
{
"Name" : "drone",
"Value" : "5ec628c1c5a04683ba85f13c59a4aed8"
},
{
"Name" : "*Unpack:",
"Value" : "yes"
}],
"ScriptStatuses" : [
],
"ServerStats" : [
{
"ServerID" : 2,
"SuccessArticles" : 4648,
"FailedArticles" : 0
}]
},
[...]

18-7-4 19:47:50.9|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
18-7-4 19:47:51.0|Debug|Parser|Parsing string 'Mad.Men.S06E12.1080p.BluRay.x264-rovers'
18-7-4 19:47:51.0|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
18-7-4 19:47:51.0|Debug|Parser|Episode Parsed. Mad Men - S06E12 
18-7-4 19:47:51.0|Debug|Parser|Language parsed: English
18-7-4 19:47:51.0|Debug|QualityParser|Trying to parse quality for Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.0|Debug|Parser|Quality parsed: Bluray-1080p v1
18-7-4 19:47:51.0|Debug|Parser|Release Group parsed: rovers
18-7-4 19:47:51.0|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
18-7-4 19:47:51.0|Debug|Parser|Parsing string 'Mad.Men.S06E12.1080p.BluRay.x264-rovers'
18-7-4 19:47:51.0|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
18-7-4 19:47:51.0|Debug|Parser|Episode Parsed. Mad Men - S06E12 
18-7-4 19:47:51.0|Debug|Parser|Language parsed: English
18-7-4 19:47:51.0|Debug|QualityParser|Trying to parse quality for Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.0|Debug|Parser|Quality parsed: Bluray-1080p v1
18-7-4 19:47:51.0|Debug|Parser|Release Group parsed: rovers
18-7-4 19:47:51.1|Debug|Parser|Parsing string 'Mad.Men.S06E12.1080p.BluRay.x264-rovers'
18-7-4 19:47:51.1|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
18-7-4 19:47:51.1|Debug|Parser|Episode Parsed. Mad Men - S06E12 
18-7-4 19:47:51.1|Debug|Parser|Language parsed: English
18-7-4 19:47:51.1|Debug|QualityParser|Trying to parse quality for Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-7-4 19:47:51.1|Debug|Parser|Release Group parsed: rovers
18-7-4 19:47:51.1|Debug|DiskScanService|Scanning '/mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers' for video files
18-7-4 19:47:51.1|Trace|DiskScanService|1 files were found in /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.1|Debug|DiskScanService|1 video files were found in /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.1|Debug|ImportDecisionMaker|Analyzing 1/1 files.
18-7-4 19:47:51.1|Debug|Parser|Parsing string 'Mad.Men.S06E12.1080p.BluRay.x264-rovers'
18-7-4 19:47:51.1|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
18-7-4 19:47:51.1|Debug|Parser|Episode Parsed. Mad Men - S06E12 
18-7-4 19:47:51.1|Debug|Parser|Language parsed: English
18-7-4 19:47:51.1|Debug|QualityParser|Trying to parse quality for Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.1|Debug|Parser|Quality parsed: Bluray-1080p v1
18-7-4 19:47:51.1|Debug|Parser|Release Group parsed: rovers
18-7-4 19:47:51.1|Debug|VideoFileInfoReader|Getting media info from /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers/BXcUfX4OHXg8Tx7Uw/MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv
18-7-4 19:47:51.1|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
18-7-4 19:47:51.1|Trace|MediaInfo|Read file offset 3516798606-3516813069 (14463 bytes)
18-7-4 19:47:51.1|Trace|MediaInfo|Read a total of 47231 bytes (0.0%)
18-7-4 19:47:51.1|Debug|DetectSample|Runtime is over 90 seconds
18-7-4 19:47:51.1|Debug|Parser|Rejected Hashed Release Title: MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv
18-7-4 19:47:51.1|Debug|Parser|Attempting to parse episode info using directory and file names. BXcUfX4OHXg8Tx7Uw
18-7-4 19:47:51.1|Debug|Parser|Parsing string 'BXcUfX4OHXg8Tx7Uw MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv'
18-7-4 19:47:51.2|Debug|Parser|Unable to parse BXcUfX4OHXg8Tx7Uw MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv
18-7-4 19:47:51.2|Debug|Parser|Attempting to parse episode info using directory name. BXcUfX4OHXg8Tx7Uw
18-7-4 19:47:51.2|Debug|Parser|Parsing string 'BXcUfX4OHXg8Tx7Uw.mkv'
18-7-4 19:47:51.2|Debug|Parser|Unable to parse BXcUfX4OHXg8Tx7Uw.mkv
18-7-4 19:47:51.2|Debug|VideoFileInfoReader|Getting media info from /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers/BXcUfX4OHXg8Tx7Uw/MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv
18-7-4 19:47:51.2|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
18-7-4 19:47:51.2|Trace|MediaInfo|Read file offset 3516798606-3516813069 (14463 bytes)
18-7-4 19:47:51.2|Trace|MediaInfo|Read a total of 47231 bytes (0.0%)
18-7-4 19:47:51.2|Debug|AggregateQuality|Using quality: Bluray-1080p v1
18-7-4 19:47:51.2|Debug|EpisodeTitleSpecification|Episode aired more than 1 day ago
18-7-4 19:47:51.2|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
18-7-4 19:47:51.2|Debug|SameFileSpecification|No existing episode file, skipping
18-7-4 19:47:51.2|Debug|Parser|Parsing string 'Mad.Men.S06E12.1080p.BluRay.x264-rovers'
18-7-4 19:47:51.2|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)
18-7-4 19:47:51.2|Debug|Parser|Episode Parsed. Mad Men - S06E12 
18-7-4 19:47:51.2|Debug|Parser|Language parsed: English
18-7-4 19:47:51.2|Debug|QualityParser|Trying to parse quality for Mad.Men.S06E12.1080p.BluRay.x264-rovers
18-7-4 19:47:51.2|Debug|Parser|Quality parsed: Bluray-1080p v1
18-7-4 19:47:51.2|Debug|Parser|Release Group parsed: rovers
18-7-4 19:47:51.2|Error|ImportDecisionMaker|Couldn't evaluate decision on /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers/BXcUfX4OHXg8Tx7Uw/MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv

[v2.0.0.5228] System.NullReferenceException: Object reference not set to an instance of an object.
  at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.MatchesFolderSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x0009c] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec (NzbDrone.Core.MediaFiles.EpisodeImport.IImportDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00000] in <f8c4a2c9e6194b509efc6018724d76df>:0 

18-7-4 19:47:51.2|Error|ImportDecisionMaker|Couldn't evaluate decision on /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers/BXcUfX4OHXg8Tx7Uw/MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv

[v2.0.0.5228] System.NullReferenceException: Object reference not set to an instance of an object.
  at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.FullSeasonSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00006] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec (NzbDrone.Core.MediaFiles.EpisodeImport.IImportDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00000] in <f8c4a2c9e6194b509efc6018724d76df>:0 

18-7-4 19:47:51.3|Debug|VideoFileInfoReader|Getting media info from /mnt/merged/nfs/vid/usenet/nzbget/dst/Series/Mad.Men.S06E12.1080p.BluRay.x264-rovers/BXcUfX4OHXg8Tx7Uw/MyfU4bOFDH7Kd3fUKACeVfwbkgdT1VjEd.mkv
18-7-4 19:47:51.3|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
18-7-4 19:47:51.3|Trace|MediaInfo|Read file offset 3516798606-3516813069 (14463 bytes)
18-7-4 19:47:51.3|Trace|MediaInfo|Read a total of 47231 bytes (0.0%)
18-7-4 19:47:51.3|Debug|DetectSample|Runtime is over 90 seconds
18-7-4 19:47:51.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
18-7-4 19:47:51.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] MatchesFolderSpecification: Object reference not set to an instance of an object., [Permanent] FullSeasonSpecification: Object reference not set to an instance of an object.
```

**Comment by Taloth** [comment] 2018-07-04 19:53
The issue is caused by the combination of nested directory + obfuscated filename.

I'll get it fixed on the develop branch, but it'll be a while till that gets released on master. 

I believe that, as workaround, you can force the import via Manual/Force Import in Activity. Or otherwise simply rename the file.

**Closed** 2018-07-04 19:55 UTC
Labels: bug
