### ISSUE TITLE
Episode inconsistency between TVDB and IMDB

### ISSUE THREAD

**Issue by thisisbenwoo** [Sonarr/Sonarr#4663] opened 2021-09-27 04:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm looking at a show called Forbidden History (2013-  )
On TVDB, it shows there are 5 seasons, with a 6th pending, but 
On IMDB, it shows there are 6 seasons. 

From what I can tell, the show actually follows the IMDB season naming.
Is there a way of using the IMDB info instead?

Thank you.

### Expected Behavior

The Episode numbers and names need to be consistent with what IMDB is showing, not what TVDB is showing

### Steps To Reproduce

Compare **https://thetvdb.com/series/forbidden-history** and **(https://www.imdb.com/title/tt4192786/)**

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1265
- Docker Install: Yes
- Using Reverse Proxy: Yes (via HAProxy on Pfsense)
- Browser: All
```

### What branch are you running?

Main

### Anything else?

-

**Comment by bakerboy448** [comment] 2021-09-27 05:40
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

This is covered on the FAQ
- https://wiki.servarr.com/sonarr/faq#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc
- https://wiki.servarr.com/sonarr/faq#why-cant-sonarr-import-episode-files-for-series-x-why-cant-sonarr-find-releases-for-series-x

No plans to add IMDB support nor do they have a free, open API.

Duplicate of / Related to
- https://github.com/Sonarr/Sonarr/issues/2621
- https://github.com/Sonarr/Sonarr/issues/3688
- https://github.com/Sonarr/Sonarr/issues/3676
- https://github.com/Sonarr/Sonarr/issues/1829
- https://github.com/Sonarr/Sonarr/issues/3622
- https://github.com/Sonarr/Sonarr/issues/3661

**Closed by bakerboy448** 2021-09-27 05:40 UTC
Labels: needs-triage
