### ISSUE TITLE
Changes in Media Undetected if Replacement File has Same Filename

### ISSUE THREAD

**Issue by dioxin187** [Sonarr/Sonarr#4550] opened 2021-06-22 20:38 UTC
I've noticed that Sonarr does not detect changes to episodes if the replacement files have the exact same filename as the previous file.

Example: If I replace a standard definition episode of a series with a high definition version and ask Sonarr to update, it will still show that episode as standard definition with the old file size.

I suppose there is a way where timestamps/hashes could be used instead of filenames to detect changes, which I believe would resolve the issue.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Sonarr Version: 3.0.6.1265

**Comment by markus101** [comment] 2021-06-22 21:07
Dupe of https://github.com/Sonarr/Sonarr/issues/3366

**Closed by markus101** 2021-06-22 21:07 UTC
