### ISSUE TITLE
Improve Messaging Around Notifications in Jellyfin

### ISSUE THREAD

**Issue by rwjack** [Sonarr/Sonarr#7042] opened 2024-07-31 15:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I suppose nobody would like to keep refreshing their Jellyfin library manually every time new media has been added (or wait for the automatic Jellyfin library refresh task).

And according to https://github.com/Sonarr/Sonarr/issues/5828, the Jellyfin notifications API has been broken for quite some time, as shown in Sonarr logs:

```
...
[Warn] HttpClient: HTTP Error - Res: HTTP/2.0 [POST] https://jellyfin.localdomain.tld:443/Notifications/Admin: 404.NotFound (0 bytes) 
...
```

### Describe the solution you'd like

This leaves us desperate for a new connection to Jellyfin, separate from Emby, which would have the same ability of refreshing the Jellyfin library on media changes, if possible at all due to Jellyfin Notifications API changes.

### Describe alternatives you've considered

If not possible, removing Jellyfin from the existing "Emby/Jellyfin" connection would be an option, just to clear the confusion.

**Comment by markus101** [comment] 2024-07-31 15:16
This is a duplicate of https://github.com/Sonarr/Sonarr/issues/5828

You don't need to manually update anything, just turn off `Send Notifications` in your connection. Given this is the only difference between Emby and Jellyfin I don't think a separate connection is warranted, just don't enable the one setting that doesn't work for Jellyfin.

**Comment by rwjack** [comment] 2024-07-31 15:24
It was my understanding that "Notifications" are used to actually communicate with Jellyfin, in order to tell it when to "Update the Library". If that's not the case, then my particular issue is solved. 

Although I am curious as to what do "Notifications" actually do? And mainly, if Emby/Jellyfin have diverged with their notifications API, wouldn't it make sense to separate the two in Sonarr/Radarr?

**Comment by markus101** [comment] 2024-07-31 15:53
I don't know how you came to that conclusion given `Send Notifications` and `Updating Library` are separate options, neither is enabled by default and can be enabled independently, especially since you saw #5828 where this was discussed.

![image](https://github.com/user-attachments/assets/cd8ef963-897b-446d-89db-7e6eaf60c15c)

We'll update the help text to reflect that `Send Notifications` is not supported for Jellyfin as well as update the warning that is logged in this case.

If Jellyfin had different notifications then it would make sense, but otherwise the it's a lot of duplication when you can just not check a checkbox.

If you have more questions or potential feature request please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) to discuss before opening another duplicate issue or making a request for something that already exists.

**Comment by rwjack** [comment] 2024-07-31 16:02
> We'll update the help text to reflect that Send Notifications is not supported for Jellyfin as well as update the warning that is logged in this case.

Cool, thank you! I'm thinking something like a little tooltip `Keep this unchecked if using Jellyfin` would do the job, or whatever you'd think is best.

> If Jellyfin had different notifications then it would make sense, but otherwise the it's a lot of duplication when you can just not check a checkbox.

And yes, that definitely makes sense, especially when the user is properly notified that the checkbox would effectively do nothing.

**Closed** 2024-08-01 05:16 UTC
Labels: suboptimal, connection
