### ISSUE TITLE
Unable to communicate with Deluge. Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by xcorp** [Sonarr/Sonarr#2682] opened 2018-07-26 20:38 UTC
Hi, I'm getting the following error
Unable to communicate with Deluge. Object reference not set to an instance of an object
But my Deluge instance is working fine, and sometimes I'm able to send downloads from Sonarr to it, but Sonarr never picks up that they are finished

Any help would be much appreciated, and I'm happy to help with what I can.

**Sonarr Version:**
2.0.0.5228

**Operating System:**
Ubuntu 16.04.5

**.net Framework (Windows) or mono (macOS/Linux) Version:**
4.2.3 (4.2.3.4-0xamarin2)

**Link to Log Files (debug or trace):**
https://pastebin.com/6i4kDhMD

**Comment by markus101** [comment] 2018-07-26 21:46
Dupe of https://github.com/Sonarr/Sonarr/issues/2566

**Closed by markus101** 2018-07-26 21:46 UTC
