### ISSUE TITLE
Please add support for Custom Formats to Sonarr, like Radarr do.

### ISSUE THREAD

**Issue by batuhankrmn** [Sonarr/Sonarr#4552] opened 2021-06-23 15:42 UTC
Since most of us using Radarr too, we're already got used to radarr's custom formats and they are ultimate customizing system to be honest. You can literally do filter almost anything that you need. Sonarr definitely needs the Custom Formats because preferred words are not even close to Custom Formats. Radarr gives use literally tons of custom format indepency and Sonarr lacks of these.

That would be awesome If we get Custom Format support. This feature asked many times in forums and github and I saw one comment dev team says "Custom Formats" is too complex, we dont wanna see millions of issue thread on github but hear this, there is already awesome guide made by TRaSH, so configuring Custom Formats wont give users that much trouble.

I am not sure about alternatives, custom formats already offers best of it but If we cant get custom formats like feature, so maybe preferred words feature can be improved and enchanced.

**Comment by bakerboy448** [comment] 2021-06-23 15:45
Duplicate of #3463

**Closed by bakerboy448** 2021-06-23 15:45 UTC

**Comment by batuhankrmn** [comment] 2021-06-23 16:14
> Duplicate of #3463


Why are you so strict about this? I know this thread has been opened before, but this thread is locked. Other users are also unable to express their opinions on this matter. You instantly close the thread. It's unfortunate that Radarr and Sonarr are so close to each other, yet the support team behaves so differently.

**Comment by markus101** [comment] 2021-06-23 16:31
At this time we do not have plans to support Custom Formats, we don't keep issues for features we don't plan to implement open. The previous issue was linked because the answer is the same.

> I saw one comment dev team says "Custom Formats" is too complex

The original "Custom Formats" as shown in the linked issue was absolutely too complex for most users, it never should have been implemented the way it was. The refreshed custom formats is better, but there is still (to me at least) an awkward relationship between custom formats and quality profiles.

> You can literally do filter almost anything that you need. Sonarr definitely needs the Custom Formats because preferred words are not even close to Custom Formats.

What can you filter in Radarr that you can't in Sonarr?
Not even close how?

> Radarr gives use literally tons of custom format indepency and Sonarr lacks of these.
I'm not sure what you mean here, it seems like it's just rehashing your comments that CF is better than PW, but providing no information as to why that's the case for you.

> maybe preferred words feature can be improved and enchanced.

Maybe, but we need to understand what you/others think is missing/needs to be improved upon. Right now there isn't anything actionable here, so our position remains the same, we don't have plans to implement Custom Formats. Right now there isn't anything to discuss here.

**Comment by batuhankrmn** [comment] 2021-06-23 17:02
> What can you filter in Radarr that you can't in Sonarr?
> Not even close how?

![image](https://user-images.githubusercontent.com/57859656/123136349-81d0f680-d45b-11eb-9999-90392a03653d.png)

You can't get these scoring system with preferred word scoring. There is not even a freeleech flag option.

![image](https://user-images.githubusercontent.com/57859656/123136696-e3916080-d45b-11eb-8010-c0dbc4249b45.png)

Also there is no cutoff option for preferred word scores, I always get multiple downloads for new aired episodes because sonarr cant know when it stops looking for preferred word score. For instance: 

![image](https://user-images.githubusercontent.com/57859656/123137097-4e429c00-d45c-11eb-8b51-a02e1522504f.png)

For instance, I got x264 release as soon as episodes come out but Sonarr did download x265 release too because there is +100 preferred word score for "x265", so it's useless at this point If I already got x264.

![image](https://user-images.githubusercontent.com/57859656/123138238-77aff780-d45d-11eb-9e27-2b8602f32864.png)

Preferred word scoring can't handle almost half of these above.

> The refreshed custom formats is better, but there is still (to me at least) an awkward relationship between custom formats and quality profiles.

It's quite amazing when you figured out. I got no problem with custom formats, I'm actually fan of it. It gives Radarr huge power of automating things.

**Comment by bakerboy448** [comment] 2021-06-23 17:07
> You can't get these scoring system with preferred word scoring. There is not even a freeleech flag option.

Only missing freeleech as an option for scoring.

>Also there is no cutoff option for preferred word scores, I always get multiple downloads for new aired episodes because sonarr cant know when it stops looking for preferred word score.

https://github.com/Sonarr/Sonarr/issues/4302

> For instance, I got x264 release as soon as episodes come out but Sonarr did download x265 release too because there is +100 preferred word score for "x265", so it's useless at this point If I already got x264.

You told sonarr you prefer x265; working as designed.  Sounds like you don't care if it is x265 or x264 if you are fine with either or.

I'm thinking Discord may be better for further discussion.

**Comment by davidnewhall** [comment] 2021-06-26 06:04
How about import/export. Ya know, so folks can share.

**Comment by bakerboy448** [comment] 2021-06-26 07:38
@davidnewhall https://github.com/Sonarr/Sonarr/issues/3952  up for grabs

**Comment by davidnewhall** [comment] 2021-06-26 20:58
Thanks for the link! +1'd. I'd take a swing at it, but I've never written a single line of C#, so I'm probably not the right guy. <3

**Comment by TRaSH-** [comment] 2021-06-26 22:10
> but there is still (to me at least) an awkward relationship between custom formats and quality profiles.

The main benefit of this is that you could add certain Custom Formats/Release profile/word to a Quality Profile and use that Quality Profile for certain certain shows that are Standard or Anime,
Now if you need to mess with tags what is kind of messy being that a release profile without a tag would be global, where giving a show a certain Quality Profile is much easier.

> What can you filter in Radarr that you can't in Sonarr?

If it comes to Custom Formats you're able to match certain words but only if a certain word, source, resolution etc matches or if not a certain word, source, resolution etc matches or even a combination of it.

probably still possible with a over complicated regex over multiple releases
For example:
If I prefer DoVi for Remuxes but not for the streaming services that are WEB-DL because they don't have the fallback to HDR for non DoVi setups.

Now you need to use something like this
`/\b(dv|dovi|dolby[ .]vision)\b.*(?=[ ._-]web[ ._-]?(dl|rip)\b)/i`
and
`/(?=[ ._-]web[ ._-]?(dl|rip)\b).*\b(dv|dovi|dolby[ .]vision)\b/i`

Where you can use with custom formats 
![image](https://user-images.githubusercontent.com/6155095/123526882-067d7800-d6db-11eb-840b-06d830fa78f1.png)

probably others can come up with a few other examples but i couldn't think of one that fast or important enough for me being i often come with a work around for it.

Note on my reply before people think i'm bashing

For my use case release profile works in Sonarr ,
But i'm missing 2 things i really would like to see some improvements on.
1. Import/Export
2. The option to match the release profile to a Quality Profile
