### ISSUE TITLE
Notification spam on season pack download

### ISSUE THREAD

**Issue by Jakst** [Sonarr/Sonarr#1585] opened 2016-12-14 09:31 UTC
When a season pack is downloaded, each episode is sent to notification extensions separately. Using PushBullet, I receive these approx. 1 second apart, leading to a horrible noise if I choose to have sound or vibration on for PushBullet. I can also easily have 40+ notifications from Sonarr when waking up in the morning.

I would like to suggest that all downloads get collated into one single notification telling the user that the season pack has finished downloading.

**Comment by baz1860** [comment] 2016-12-14 10:06
The issue is valid, *but* to play devils advocate, how do we then account for the season pack that has a single episode that won't extract (I've had this before) - your suggestion means I don't get a notification of the 23 episodes that did import because one would fail, this failing the season pack, but with a 23/24 (or whatever) success rate.

I don't use pushbullet, but can you not mute sonarr notifications overnight while leaving them on for anything else you do need?

**Comment by Jakst** [comment] 2016-12-14 12:32
Maybe the notification could include a warning when at least one file fails to import. Alternatively Sonarr could send one notification when the process completes and another one for episodes that do not complete successfully.

I cannot mute Sonarr separately in PushBullet, but I really don't want to either. It is incredibly helpful to have notifications telling me whatever new episodes were fetched during the night when I wake up, but they regularly get drowned out by noise from season packs.

Also notifications on desktop are even more annoying when they start going off, because they hide the right side of the screen and have to be closed one by one. This is of course the fault of the PushBullet chrome implementation, but nonetheless something that could be remedied from the Sonarr end. PushBullet should simply not be sent bursts of messages, because it is not built to handle them well.

**Comment by markus101** [comment] 2016-12-14 17:57
Dupe of https://github.com/Sonarr/Sonarr/issues/363

**Closed by markus101** 2016-12-14 17:57 UTC
