### ISSUE TITLE
Alerts on Issues

### ISSUE THREAD

**Issue by Rhysers** [Sonarr/Sonarr#2142] opened 2017-08-20 22:15 UTC
Would it be possible to add to option to send alerts through any of the already existing clients (e.g. slack) when there is an issue. My indexer (Jackett) crashed and I didn't know it. If it could have sent me a notification that all indexers were down that would have been awesome.

**Comment by markus101** [comment] 2017-08-20 22:21
Dupe of https://github.com/Sonarr/Sonarr/issues/1798

**Closed by markus101** 2017-08-20 22:21 UTC
