### ISSUE TITLE
[REQ] Minimum Availability

### ISSUE THREAD

**Issue by budgetfermium** [Sonarr/Sonarr#4108] opened 2020-11-21 11:41 UTC
**Describe the problem**
Fake releases purporting to be episodes that have not aired yet are downloaded by Sonarr.

**Describe any solutions you think might work**
Adding a "Minimum Availability" button to prevent downloading titles before their release would fix this issue. 

**Additional context**
Radarr implemented this feature in commit 140a22034082178510621f9d51d08e12649dd3ca.

**Comment by bakerboy448** [comment] 2020-11-21 12:46
Duplicate of #969

**Closed by bakerboy448** 2020-11-21 12:46 UTC
