### ISSUE TITLE
Added the function of selecting the language of video information

### ISSUE THREAD

**Issue by moxiaoweng** [Sonarr/Sonarr#7316] opened 2024-10-24 03:06 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Why can't I choose the language of the movie information in the settings like Radarr does?
![image](https://github.com/user-attachments/assets/4e0ddc5f-d417-4a01-a22f-576eb8a395de)

### Describe the solution you'd like

Add support for other languages. The movie name does not correspond to the name of the scraper data source, resulting in the scraper being unable to search for the corresponding resource normally. I hope to switch to TMDB's metadata source, TVDB will not be able to load the poster
![image](https://github.com/user-attachments/assets/3ec0ffdf-d432-4b90-a05e-4532b0b35961)

### Describe alternatives you've considered

There is no alternative solution for now. I think sonarr should also be able to do the same things as radarr.

**Comment by augustuen** [comment] 2024-10-24 03:10
Simply because TVDB's API only shared the English metadata up until fairly recently. Work is being done on adding metadata in other languages, but it requires a lot of work.

**Comment by markus101** [comment] 2024-10-24 05:50
Why did you open another issue instead of looking at the existing issue?

Duplicate of https://github.com/Sonarr/Sonarr/issues/269

**Closed** 2024-10-24 05:50 UTC
Labels: needs-triage
