### ISSUE TITLE
qBitTorrent stuck at 100%.

### ISSUE THREAD

**Issue by sbeaudoin** [Sonarr/Sonarr#2585] opened 2018-05-24 00:07 UTC
**Description**
Episode download requested by sonarr to my qbitTorrent client successfully.  Download is executing in qBittorrent.  Once qBittorrent finished download, even after 10 minutes and executing manually the "Check for finished download" task, sonard indicates a 100% completion, but do not process the file.

**Logs**
There seems to be an incompatibility in the API command sent to the qBittorrent client :

```
18-5-23 19:41:53.3|Warn|HttpClient|HTTP Error - Res: [POST] http://vm-apps:8686/command/resume: 400.BadRequest
18-5-23 19:41:53.4|Warn|QBittorrent|Failed to set inital state for 4136dee32b15344b1943c2ccac0e2c1a9168c6e7.
```
**System Information**

 - Sonarr Version: 2.0.0.5163
 - Operating System: Windows 10 Hyper-V machine under Windows Server Essentials 2016 as a service.

**Supplement**
This is a new install with no known success.  But the communication between sonarr and qBittorrent is ok since a download request as been successfully requested and executed.

**Comment by markus101** [comment] 2018-05-24 00:08
Dupe of https://github.com/Sonarr/Sonarr/issues/2565

**Closed by markus101** 2018-05-24 00:08 UTC
