### ISSUE TITLE
Consistent Crashing

### ISSUE THREAD

**Issue by RustyBower** [Sonarr/Sonarr#4888] opened 2022-02-06 04:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the last few days, my sonarr installation is crashing repeatedly. The initial crash seems to happen a short while after startup, seemingly during the directory scan, where the webui will just hang and eventually timeout/fail. Eventually it'll trace and restart, but fail soon after.

### Expected Behavior

Not having this fail.

### Environment

```markdown
- OS: Centos/Docker
- Sonarr: Multiple Versions, but currently 3.0.6.1457 from LinuxServer docker
- Docker Install: Y
- Using Reverse Proxy: Y, but also directly
- Browser: Brave
```

### What branch are you running?

Develop

### Trace Logs?
```
2022-02-05 15:25:15.6|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-02-05 15:25:15.6|Trace|Http|Res: 37 [GET] /api/v3/config/host: 200.OK (26 ms)
2022-02-05 15:25:15.6|Debug|Api|[GET] /api/v3/config/host: 200.OK (26 ms)
2022-02-05 15:25:15.8|Trace|HttpClient|Res: [GET] https://services.sonarr.tv/v1/update/main/changes?version=3.0.6.1342&os=linux&runtimeVer=5.20.1.34&active=false: 200.OK (184 ms)
2022-02-05 15:25:15.8|Trace|Http|Res: 36 [GET] /api/v3/update: 200.OK (230 ms)
2022-02-05 15:25:15.8|Debug|Api|[GET] /api/v3/update: 200.OK (230 ms)
2022-02-05 15:25:16.1|Trace|Http|Req: 38 [GET] /api/v3/system/backup (from 172.16.0.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-02-05 15:25:16.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:16.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:16.1|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:16.1|Trace|Http|Res: 38 [GET] /api/v3/system/backup: 200.OK (6 ms)
2022-02-05 15:25:16.1|Debug|Api|[GET] /api/v3/system/backup: 200.OK (6 ms)
2022-02-05 15:25:24.9|Trace|Scheduler|Pending Tasks: 0
2022-02-05 15:25:46.4|Trace|Http|Req: 39 [POST] /api/v3/system/backup/restore/589315776 (from 172.16.0.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-02-05 15:25:46.5|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:46.5|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:46.5|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:46.5|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-02-05 15:25:46.5|Debug|ArchiveService|Extracting archive [/config/Backups/scheduled/sonarr_backup_v3.0.6.1342_2022.02.03_19.41.37.zip] to [/tmp/sonarr_backup_restore]
2022-02-05 15:25:46.5|Debug|ArchiveService|Validating Archive /config/Backups/scheduled/sonarr_backup_v3.0.6.1342_2022.02.03_19.41.37.zip
2022-02-05 15:25:54.9|Trace|Scheduler|Pending Tasks: 1
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Inserting new command: RefreshMonitoredDownloads
2022-02-05 15:25:54.9|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand -> DownloadMonitoringService
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Marking command as started: RefreshMonitoredDownloads
2022-02-05 15:25:54.9|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
2022-02-05 15:25:54.9|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
2022-02-05 15:25:54.9|Trace|EventAggregator|Publishing QueueUpdatedEvent
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusModule
2022-02-05 15:25:54.9|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusModule
2022-02-05 15:25:54.9|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Publishing ProcessMonitoredDownloads
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Checking if command is queued or started: ProcessMonitoredDownloads
2022-02-05 15:25:54.9|Trace|CommandQueueManager|Inserting new command: ProcessMonitoredDownloads
2022-02-05 15:25:55.0|Trace|CommandQueueManager|Updating command status
2022-02-05 15:25:55.0|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand -> DownloadProcessingService
2022-02-05 15:25:55.0|Trace|CommandQueueManager|Marking command as started: ProcessMonitoredDownloads
2022-02-05 15:25:55.0|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-02-05 15:25:55.0|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.RefreshMonitoredDownloadsCommand
2022-02-05 15:25:55.0|Trace|EventAggregator|Publishing DownloadsProcessedEvent
2022-02-05 15:25:55.0|Trace|EventAggregator|DownloadsProcessedEvent -> DownloadMonitoringService
2022-02-05 15:25:55.0|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
2022-02-05 15:25:55.0|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
2022-02-05 15:25:55.0|Trace|EventAggregator|Publishing QueueUpdatedEvent
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusModule
2022-02-05 15:25:55.0|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusModule
2022-02-05 15:25:55.0|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2022-02-05 15:25:55.0|Trace|EventAggregator|DownloadsProcessedEvent <- DownloadMonitoringService
2022-02-05 15:25:55.0|Trace|CommandQueueManager|Updating command status
2022-02-05 15:25:55.0|Trace|EventAggregator|DownloadsProcessedEvent ~> NotificationService
2022-02-05 15:25:55.0|Trace|EventAggregator|DownloadsProcessedEvent <~ NotificationService
2022-02-05 15:25:55.0|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-02-05 15:25:55.0|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-02-05 15:25:55.0|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand <- DownloadProcessingService [00:00:00.0221380]
2022-02-05 15:25:55.0|Trace|Http|Req: 40 [GET] /api/v3/command (from 172.16.0.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-02-05 15:25:55.0|Trace|CommandQueueManager|Getting all commands
2022-02-05 15:25:55.1|Trace|Http|Res: 40 [GET] /api/v3/command: 200.OK (23 ms)
2022-02-05 15:25:55.1|Debug|Api|[GET] /api/v3/command: 200.OK (23 ms)
2022-02-05 15:25:55.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-02-05 15:25:55.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-02-05 15:25:55.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-02-05 15:25:55.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-02-05 15:25:55.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-02-05 15:25:55.1|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand <- DownloadMonitoringService [00:00:00.0330120]
2022-02-05 15:25:55.1|Trace|Http|Req: 41 [GET] /api/v3/command (from 172.16.0.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-02-05 15:25:55.1|Trace|CommandQueueManager|Getting all commands
2022-02-05 15:25:55.1|Trace|Http|Res: 41 [GET] /api/v3/command: 200.OK (2 ms)
2022-02-05 15:25:55.1|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
2022-02-05 15:26:00.0|Trace|Http|Req: 42 [GET] /api/v3/queue?apikey=(removed) (from 172.16.10.8 axios/0.21.4)
2022-02-05 15:26:00.0|Trace|Http|Res: 42 [GET] /api/v3/queue?apikey=(removed) 200.OK (9 ms)
2022-02-05 15:26:00.0|Debug|Api|[GET] /api/v3/queue?apikey=(removed) 200.OK (9 ms)
2022-02-05 15:26:03.1|Debug|ArchiveService|Extraction complete.
2022-02-05 15:26:03.1|Trace|DiskProviderBase|Deleting file: /config/config.xml
2022-02-05 15:26:03.9|Trace|Http|Res: 39 [POST] /api/v3/system/backup/restore/589315776: 200.OK (17482 ms)
2022-02-05 15:26:03.9|Debug|Api|[POST] /api/v3/system/backup/restore/589315776: 200.OK (17482 ms)
2022-02-05 15:26:04.0|Trace|Http|Req: 43 [POST] /api/v3/system/restart (from 172.16.0.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36)
2022-02-05 15:26:04.0|Info|LifecycleService|Restart requested.
2022-02-05 15:26:04.0|Trace|Http|Res: 43 [POST] /api/v3/system/restart: 200.OK (9 ms)
2022-02-05 15:26:04.0|Debug|Api|[POST] /api/v3/system/restart: 200.OK (9 ms)
2022-02-05 15:26:04.0|Trace|EventAggregator|Publishing ApplicationShutdownRequested
2022-02-05 15:26:04.0|Trace|EventAggregator|ApplicationShutdownRequested -> NzbDroneServiceFactory
```

### Anything else?

N/A

**Comment by bakerboy448** [comment] 2022-02-06 05:09
There's no crash in your logs?

But it looks like you triggered a restart via the UI which is a known issue.

**Comment by bakerboy448** [comment] 2022-02-06 05:09
Duplicate of https://github.com/Sonarr/Sonarr/issues/424#issuecomment-104800945

**Closed** 2022-02-06 05:09 UTC
Labels: needs-triage

**Comment by RustyBower** [comment] 2022-02-06 19:22
Poking around a bit more, not it won't even start up.

```2022-02-06 13:18:36.3|Debug|ProcMountProvider|Failed to retrieve mounts from /proc/mounts

[v3.0.6.1457] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs:3211
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs:56
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMount.cs:21
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:127
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:43

2022-02-06 13:18:36.3|Debug|ProcMountProvider|Failed to retrieve mounts from /proc/mounts

[v3.0.6.1457] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs:3211
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs:56
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMount.cs:21
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:127
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:43

2022-02-06 13:18:36.3|Debug|ProcMountProvider|Failed to retrieve mounts from /proc/mounts

[v3.0.6.1457] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs:3211
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs:56
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMount.cs:21
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:127
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:43

2022-02-06 13:18:36.3|Debug|ProcMountProvider|Failed to retrieve mounts from /proc/mounts

[v3.0.6.1457] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs:3211
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs:56
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMount.cs:21
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:127
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:43

2022-02-06 13:18:36.3|Debug|ProcMountProvider|Failed to retrieve mounts from /proc/mounts

[v3.0.6.1457] System.EntryPointNotFoundException: Mono_Posix_Syscall_getfsfile assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_getfsfile(string,Mono.Unix.Native.Syscall/_Fstab&)
  at Mono.Unix.Native.Syscall.getfsfile (System.String mount_point) [0x00010] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs:3211
  at Mono.Unix.UnixDriveInfo..ctor (System.String mountPoint) [0x00014] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs:56
  at NzbDrone.Mono.Disk.ProcMount..ctor (System.IO.DriveType driveType, System.String name, System.String mount, System.String type, NzbDrone.Common.Disk.MountOptions mountOptions) [0x0002b] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMount.cs:21
  at NzbDrone.Mono.Disk.ProcMountProvider.ParseLine (System.String line) [0x000a3] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:127
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <b4947f9d8e3644dfaa46480ad2f64100>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/(removed)/aports/testing/mono/src/mono-6.12.0.122/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at NzbDrone.Mono.Disk.ProcMountProvider.GetMounts () [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\ProcMountProvider.cs:43```
