### ISSUE TITLE
Support for downloading a 1080 and 4k version of shows

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#4155] opened 2020-12-11 14:37 UTC
**Describe the problem**
4k shows cannot be easily transcoded. Therefore there is a desire to have both a 4k and a 1080 version available of some shows

**Describe any solutions you think might work**
Allow 2 copies of a show?
2 quality profiles per show?
option to leave upgrades in place

**Comment by bakerboy448** [comment] 2020-12-11 14:38
Duplicate of #312

**Closed by bakerboy448** 2020-12-11 14:38 UTC
