### ISSUE TITLE
Ability to bulk change series and season on manual import

### ISSUE THREAD

**Issue by mr-bo-jangles** [Sonarr/Sonarr#2658] opened 2018-07-11 22:22 UTC
**Describe the problem**
Manually importing very large seasons such as season 2 of Hunter x Hunter with 78 episodes requires me to manually select "Hunter X Hunter" and "Season 2" 156 times. It would be very much appreciated if the option to change all of the selected series and season values for an import at once. This drops the number of required selections to ~2 for any size of import

**Describe any solutions you think might work**
Add an additional row, with the ability to bulk change the selected episodes series or season value on change

**Additional context**
It would be magical if Sonarr could then take the provided values as "hints" and try to update the episode match for you (on a button to avoid clobbering the server and existing matches if it gets it wrong)

**Comment by markus101** [comment] 2018-07-11 22:22
Dupe of https://github.com/Sonarr/Sonarr/issues/1643

**Closed by markus101** 2018-07-11 22:22 UTC
