### ISSUE TITLE
TV Series not showing all seasons and episodes

### ISSUE THREAD

**Issue by EloToJaa** [Sonarr/Sonarr#5341] opened 2023-01-03 15:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The TV Series called Sons of Anarchy ([TheTVDB](https://thetvdb.com/series/sons-of-anarchy)) is not showing all of the seasons and episodes. Missing seasons 1-5 and episodes from season 6.

### Expected Behavior

Expected to show all the seasons and episodes like shown on [TheTVDB](https://thetvdb.com/series/sons-of-anarchy).

### Steps To Reproduce

1. Add the Sons of Anarchy TV Series

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: Sonarr 3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Not UI related
```

### What branch are you running?

Main

### Trace Logs?

[Trace Logs](https://hastebin.com/omodogehav.apache)

### Anything else?

![image](https://user-images.githubusercontent.com/22549550/210390938-6467fd59-9f84-4e96-a369-8e4e16286a15.png)

Part of /series enpoint response
```json
[
  {
    "title": "Sons of Anarchy",
    "alternateTitles": [],
    "sortTitle": "sons of anarchy",
    "status": "ended",
    "ended": true,
    "overview": "Sons of Anarchy is an adrenalized drama with darkly comedic undertones that explores a notorious outlaw motorcycle club’s (MC) desire to protect its livelihood while ensuring that their simple, sheltered town of Charming, California remains exactly that, charming. The MC must confront threats from drug dealers, corporate developers, and overzealous law officers. Behind the MC’s familial lifestyle and legally thriving automotive shop is a ruthless and illegal arms business driven by the seduction of money, power, and blood.",
    "network": "FX",
    "airTime": "22:00",
    "images": [
      {
        "coverType": "banner",
        "url": "/MediaCover/124/banner.jpg?lastWrite=638083560554607780",
        "remoteUrl": "https://artworks.thetvdb.com/banners/graphical/82696-g12.jpg"
      },
      {
        "coverType": "poster",
        "url": "/MediaCover/124/poster.jpg?lastWrite=638083560557087804",
        "remoteUrl": "https://artworks.thetvdb.com/banners/posters/82696-11.jpg"
      },
      {
        "coverType": "fanart",
        "url": "/MediaCover/124/fanart.jpg?lastWrite=638083560560287834",
        "remoteUrl": "https://artworks.thetvdb.com/banners/fanart/original/82696-70.jpg"
      }
    ],
    "seasons": [
      {
        "seasonNumber": 0,
        "monitored": false,
        "statistics": {
          "episodeFileCount": 0,
          "episodeCount": 0,
          "totalEpisodeCount": 12,
          "sizeOnDisk": 0,
          "releaseGroups": [],
          "percentOfEpisodes": 0.0
        }
      },
      {
        "seasonNumber": 6,
        "monitored": false,
        "statistics": {
          "episodeFileCount": 0,
          "episodeCount": 0,
          "totalEpisodeCount": 4,
          "sizeOnDisk": 0,
          "releaseGroups": [],
          "percentOfEpisodes": 0.0
        }
      },
      {
        "seasonNumber": 7,
        "monitored": false,
        "statistics": {
          "episodeFileCount": 0,
          "episodeCount": 0,
          "totalEpisodeCount": 13,
          "sizeOnDisk": 0,
          "releaseGroups": [],
          "percentOfEpisodes": 0.0
        }
      }
    ],
    "year": 2013,
    "path": "/torrents/Seriale/Sons of Anarchy (2013) [imdb-tt1124373]",
    "qualityProfileId": 4,
    "languageProfileId": 1,
    "seasonFolder": true,
    "monitored": false,
    "useSceneNumbering": false,
    "runtime": 42,
    "tvdbId": 82696,
    "tvRageId": 18174,
    "tvMazeId": 76,
    "firstAired": "2013-11-12T00:00:00Z",
    "seriesType": "standard",
    "cleanTitle": "sonsanarchy",
    "imdbId": "tt1124373",
    "titleSlug": "sons-of-anarchy",
    "rootFolderPath": "/torrents/Seriale/",
    "certification": "TV-MA",
    "genres": [
      "Crime",
      "Drama",
      "Thriller"
    ],
    "tags": [],
    "added": "2023-01-03T15:20:55.119292Z",
    "ratings": {
      "votes": 7958,
      "value": 8.9
    },
    "statistics": {
      "seasonCount": 2,
      "episodeFileCount": 0,
      "episodeCount": 0,
      "totalEpisodeCount": 29,
      "sizeOnDisk": 0,
      "releaseGroups": [],
      "percentOfEpisodes": 0.0
    },
    "id": 124
  }
]
```

**Comment by markus101** [comment] 2023-01-03 16:04
Dupe of https://github.com/Sonarr/Sonarr/issues/5339

**Closed** 2023-01-03 16:04 UTC
Labels: needs-triage
