### ISSUE TITLE
Feature Request: Bulk operations in unrecognised manual imports

### ISSUE THREAD

**Issue by faminebadger** [Sonarr/Sonarr#1991] opened 2017-06-22 18:34 UTC
Sometimes - typically having downloaded an older series of an anime - I end up needing to do a manual import when Sonarr doesn't recognise the file names.  This is fine - you can't match everything all the time.

But when there are dozens of files to import, it's really annoying to have to manually click on the three selections for every single file.

e.g. for a 20 episode import that isn't recognised, I have to do the following 20 times:
- Click to bring up series list
- Scroll down to find series
- Click to select series
- Click to bring up season list
- Click to open drop-down
- Click to select season
- Click to bring up episode list
- Scroll down to find episode
- Click to tick episode
- Click select

That's an awful lot of mouse work, and really frustrating.  So I have some suggestions for ease of life improvements that could be made around this functionality:
- Allow selection of series just once, and apply it to all files being imported
- Try to detect season & episode numbers even if series isn't recognised (as far as I can tell, it ignores good SxxEyy in a name if the series wasn't detected)
-- Could only do this after series is manually set, if preferred, to avoid picking invalid seasons for a series
- Allow to set season for multiple files being imported at once

I'm sure there are some other ideas around this too - but the basic intent is to try and make this manual import form much friendlier to use.

Thanks

**Comment by markus101** [comment] 2017-06-23 14:14
Dupe of https://github.com/Sonarr/Sonarr/issues/1643 (will be in v3).

**Closed by markus101** 2017-06-23 14:14 UTC
