### ISSUE TITLE
Allow folders to be ignored for Media Management unmapped folders

### ISSUE THREAD

**Issue by katbyte** [Sonarr/Sonarr#5479] opened 2023-03-10 17:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In my media folders there are some series i don't want to track in sonarr for various reasons:
- As Sonarr uses TVDB it doesn't always align with TMDB which i use with emby/jellyfin and thus some series that sonarr/tvdb treat as one, are (correctly imho) 2 in my library & emby instance. so 1 is tracked 1 is just.. sitting there
- sometimes i have multiple versions of a show: DS9 480p, DS9 upscaled, TNG 480, TNG HD etc, 

and it would be nice if they could just be ignored to keep the noise down

### Describe the solution you'd like

if a folder contains a file called `.ignore` simply ignore it. this is how emby/jellyfin does it and it is both easy to do as a user, as well implement.

### Describe alternatives you've considered

move these folders somewhere else: that would mean having yet another folder to keep track of and add to plex/emby/etv sync and this would not be organized. It also means when people browse the folders they would not be aware of them.

**Comment by katbyte** [comment] 2023-03-10 18:35
i am not trying to add these to sonarr, just have them not show up in the media management "add" area. Hence why i am looking for a way to have sonarr just ignore these folders.

adding them to "extras" will mess up file organization that is working for us atm and would clutter emby/jellyfin/other tools with 1000s of files that make no sense as they are not extras. Right now the .ignore file works great as it's easy to add and can contain the reason why its ignored.

not to mention that wouldn't address shows like [This Is England](https://en.wikipedia.org/wiki/This_Is_England_(film_series)) where it is three separate series, thus is three separate folders, but the tvdb insists its 1 and thus sonarr doesn't know how to handle it. Moving these to extras would break these series, as would combining them as they shouldn't be combined. 

Not asking for it to know/be able to deal with these or support TMDB just a way to ignore these folders in media management. Updated title to be more specific.,

**Comment by bakerboy448** [comment] 2023-03-10 18:41
> The other thing that you could do is move those folders to another location and add that as an additional location in Plex. That way Sonarr doesn't see them, but Plex will.
>  As far as ignoring them in Sonarr, this isn't something we plan to do at this time.

_Originally posted by markus101 in https://github.com/Sonarr/Sonarr/issues/4927#issuecomment-1059504630_

Duplicate of #4927

**Comment by markus101** [comment] 2023-03-11 00:23
Something like this is necessary when rescanning the folder imports new series, but given after the initial import, you don’t need to use import to add new series this isn’t something we have plans to do as mentioned in https://github.com/Sonarr/Sonarr/issues/4927

**Closed by markus101** 2023-03-11 00:23 UTC
Labels: needs-triage

**Comment by katbyte** [comment] 2023-03-12 01:47
I do not import shows via sonarr add for a number of reasons, i add them via the library import for tracking & downloading so it is something that comes up frequently.

**Comment by bakerboy448** [comment] 2023-03-12 04:33
Library import doesn't add any tracking?

also see https://github.com/Sonarr/Sonarr/issues/4927#issuecomment-1059450236  As the OP on 4927 sounds like they had a similar process order to you

**Comment by katbyte** [comment] 2023-03-12 22:05
The workflow i have is more similar to the one you suggested actually. Manual Import with monitoring all episodes with desired quality profile, works great for triggering a download of new eps or HD releases for SD content.

 The problem is with shows that are in TVDB incorrectly or where i have multiple versions of the same show that continue to show up in import. Hence it would be nice to have a way to just ignore these folders in the manual import.

**Comment by bakerboy448** [comment] 2023-03-12 22:30
Manual Import has no folders to exclude - it looks in the exact directory you point it at.

> Hence it would be nice to have a way to just ignore these folders in the manual import.

this sounds like you're using library import and calling it manual import.

wanted => manual import is the only manual import that exists

**Comment by katbyte** [comment] 2023-03-15 00:22
sorry yes that would be what i mean then. i go media management -> root folder -> import
