### ISSUE TITLE
Disk space not reporting for ZFS volumes

### ISSUE THREAD

**Issue by emptied** [Sonarr/Sonarr#1139] opened 2016-02-10 21:05 UTC
I assume this is part of whatever ignores remote FS space, but I am running Sonarr on a zfs system and it sees / (ext4) but not my media mount (zfs).

**Comment by markus101** [comment] 2016-02-10 21:07
Dupe of: https://github.com/Sonarr/Sonarr/issues/423 Though I believe @Taloth has already merged some fixes for this (in develop).

**Closed by markus101** 2016-02-10 21:07 UTC
