### ISSUE TITLE
Language setting is being ignored in many places

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#3175] opened 2019-06-16 23:45 UTC
**Describe the bug**
While Sonarr allows the user to set the desired language for every series, this is being ignored in the naming system. It only seems to be used during NZB/Torrent search. Sonarr is missing the following functionalities (or they are not working properly):
- Series and episode titles are only shown in English, even if the language of the series is set to something different.
- If no English episode title is set on TheTVDB, Sonarr uses "TBA" as episode title, even if the correct title is set in the desired language. 
- If no English Series title is set on TheTVDB, Sonarr cannot find the series at all. Not even with the TVDB-ID.

Sonarr should respect the user's chosen language, i.e. load the metadata in the desired language and use that to name the series folders and episode files correctly. Also, Sonarr give access to all series, not only the ones that have an English series title set.

**System Information**
 - Sonarr Version: 2.0.0.5322

**Comment by markus101** [comment] 2019-06-16 23:49
There is no language setting for a series, that’s part of the profile.

Please search before posting this is a dupe of https://github.com/Sonarr/Sonarr/issues/269

**Closed by markus101** 2019-06-16 23:49 UTC

**Comment by hr1232** [comment] 2019-06-16 23:56
As the other one is closed and comments are forbidden there, the only way to comment on this issue still being there is by opening a new thread. Why was #269 completely blocked without comment or reason?

**Comment by markus101** [comment] 2019-06-17 00:15
Nothing constructive had been posted on that issue, the entire thread didn’t need to get an alert when someone wanted to +1 it. There are other ways to subscribe to issues and show interest.

Asking when something is going to be done isn’t useful either. We’ll post an update when it makes sense to do so. Opening another issue to ask the status of another issue is the same amount of noise to us, when there is progress there will be an update.
