### ISSUE TITLE
TBA episode names not updating; not importing downloads

### ISSUE THREAD

**Issue by jray06** [Sonarr/Sonarr#3102] opened 2019-05-06 13:48 UTC
Game of Thrones is popular right now, and has made this bug apparent. 

GoT does not release episode names prior to airing. As a result, Sonarr lists them as TBA.

After air, Sonarr will grab the unnamed episode and send to downloader (SAB), however it will not import the downloaded file until it has processed a name for the TBA episode from TVDB. 

TVDB does not allow general users to update titles on shows that have been locked by moderators.... that’s just a general gripe. In any event, I end up with a downloaded episode that isn’t imported because someone hasn’t input the name. 

After TVDB names it, Sonarr is not automatically updating the TBA name. Manual triggering of “Refresh Series” does nothing. Restarting the Sonarr service via the GUI button will trigger an update, at which point Sonarr imports the completed download. 

Can we get this set up so that TBA episodes get imported before TVDB’s name is updated? It’s annoying as hell to tell my wife I’ve already downloaded the episode but she can’t watch it because some yahoo moderator at TVDB hasn’t input an episode title yet.

Thanks for all your work. Otherwise absolutely love the program.

**Comment by markus101** [comment] 2019-05-06 14:16
Dupe of the already closed https://github.com/Sonarr/Sonarr/issues/3086 this change is not being brought to v2.

**Closed by markus101** 2019-05-06 14:16 UTC
