### ISSUE TITLE
Nyaa.se Closed

### ISSUE THREAD

**Issue by ToastyStoemp** [Sonarr/Sonarr#1890] opened 2017-05-02 18:55 UTC
Due to recent changes in the EU law system, the owner of Nyaa.se has decided to close down the site.
most people will probably switch to [shanaproject](https://www.shanaproject.com/)
I don't know what your personal opinion is on these changes.
Thought I'd let you know.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by Catarrius** [comment] 2017-05-02 19:29
Shana Project is just a mirror of TokyoTosho, not a replacement for Nyaa. Also, there are rumors Nyaa will resurface by the end of the week. No need to rush into anything yet. The real key is which tracker the main fansub groups decide to migrate to.

**Comment by xelra** [comment] 2017-05-02 21:16
Maybe we can use https://www.tokyotosho.info/rss.php?filter=1 at least for RSS in the meantime.

**Comment by zSoulweaver** [comment] 2017-05-03 03:37
Where have you heard it will resurface? Everywhere I've seen the owner has just gone silent.

**Comment by ShafferZee** [comment] 2017-05-03 22:14
It's confirmed dead by both HorribleSubs and CommieSubs.

**Comment by Catarrius** [comment] 2017-05-03 22:36
Yeah, we've heard from Nyaa himself now that it's definitely gone. Still waiting to see where most fansub groups resurface.

**Comment by ShafferZee** [comment] 2017-05-03 22:55
I believe some group in minor relation to HorribleSubs will are trying to create a full replacement for nyaa. I don't believe they have a db backup or anything; but just a startup from scratch.

**Comment by zSoulweaver** [comment] 2017-05-03 23:23
4chin has a site with a backup that is about 4 months old. Waiting on some guy who apparently has a dump of the entire website since it went down, but he could just be lying as per usual.

**Comment by ShafferZee** [comment] 2017-05-04 10:45
https://animetosho.org/test/

Of course the nyaa tracker is down but hope DHT should carry you guys through if you are looking for a quick fix.

**Comment by raildex1** [comment] 2017-05-04 11:14
Anidex is a good alternative - https://anidex.info/rss/

Needs some fixing to work with sonarr.

**Comment by Siegfrost** [comment] 2017-05-04 12:35
HorribleSubs also created their own RSS Feed - http://horriblesubs.info/rss.php?res=1080
However it doesn't have a size field in them. 

Would it be possible to make it work with Sonarr in the future?

**Comment by raildex1** [comment] 2017-05-04 13:21
^Just use the zero size option when direct adding the RSS feed it'll work.

**Comment by Siegfrost** [comment] 2017-05-04 13:39
Thanks for that, now I feel dumb!

**Comment by Cerbis** [comment] 2017-05-04 15:09
Can someone explain how to add horriblesubs or any other site as indexer as replacement for nyaa?

**Comment by Siegfrost** [comment] 2017-05-04 15:57
^ You can go to the indexer option and add the bottom right one 'Torrent RSS Feed'.

Put the rss url there and toggle 'allow zero size' to 'yes'

**Comment by xelra** [comment] 2017-05-04 16:39
The admin from animetosho has an almost complete torznab api, but afaik he didn't finish it. If you guys wanna ask nicely, you should contact him.

Any torznab api is instantly compatible with Sonarr and supports all features.

**Comment by Taloth** [comment] 2017-05-04 16:42
> Any torznab api is instantly compatible with Sonarr and supports all features.

There are 'levels' of support. Just saying. It's possible to have a torznab api with no search capability, but fully paging 'rss'-like feed.

**Comment by Salamander3** [comment] 2017-05-05 03:11
@ToastyStoemp What recent change in EU last system? Do you have any link/source?

**Comment by ToastyStoemp** [comment] 2017-05-05 06:22
Nothing is really official,
There is a maybe official statement here: https://torrents.me/site/nyaa/
Court case information:
https://www.theregister.co.uk/2017/04/26/ecj_kodi_addons/

Long story short, a dutch site was selling pre-configured media servers that was basically pulling movies from torrents rss feeds etc. 
The European higher court has decided that media servers with addons for piracy content are also considered illegal.

**Comment by tatu007** [comment] 2017-05-05 06:31
Anidex is a good alternative - https://anidex.info/rss/

**Comment by ToastyStoemp** [comment] 2017-05-05 06:49
Personally I think we shouldn't really discuss alternative sites in this thread. Nyaa can never be replaced in my heart.
We just need to come up with a solution sonarr can deal with the issue ay hands. 
Option 1, is to discontinue the current anime tracker support. And leave it up to the people them selves to add rss feeds, torznab api's etc. 
Adding search for rss would be amazing to help this cause. 
Option 2. Is to gather the pitchforks, start a movement, march against the eu system.

If the devs have a preferred anime tracker, let them add their favorite tracker as primary option. 
Or let there be a vote.

**Comment by Cerbis** [comment] 2017-05-05 06:51
> The European higher court has decided that media servers with addons for piracy content are also considered illegal.

Not sure if i'm right afaik it's related to media servers with preinstalled addons for piracy, which were sold over amazon and other shops. These ain't considered to be legal (anymore).

**Comment by Taloth** [comment] 2017-05-05 07:36
@ToastyStoemp 

> Nyaa can never be replaced in my heart.

Touching... lol.
I usually don't like ppl comparing indexers on our sites/forums, but it's preferable to ppl opening up 10 threads about nyaa going down. So we allow discussing indexers and alternativer rss-feeds for a time so stuff remains centralized a bit, till the chaos dies down.
I think for KAT I eventually created a single topic on reddit listing some options. There were a lot of brain-dead users panicking coz kat was their only source and their world literally ended.

Also, I don't think we need to be discussing those EU verdicts. It's irrelevant.

> Adding search for rss would be amazing to help this cause.

rss can't search... that's what torznab is for.

> If the devs have a preferred anime tracker

No. We don't 'endorse' specific sites. We only say to which degree a site integrates with Sonarr.

**Comment by Warlockx** [comment] 2017-05-10 12:22
https://nyaa.pantsu.cat is a option too... they have a feed and filters like nyaa...

**Comment by M0UL** [comment] 2017-05-10 16:23
https://nyaa.pantsu.cat  is useless without search,  those are only the old releases. nothing new after first of may.

**Comment by Warlockx** [comment] 2017-05-10 16:30
it does have search but no new releases... im not the owner of the site so idk how it will develop forward but might be a solution... worth keeping a eye on.

**Comment by zSoulweaver** [comment] 2017-05-11 00:06
They are moving ownership to a new person with more opsec. They have a tracker in works too, just a matter of time, uploading is enabled now IIRC too.

**Comment by ToastyStoemp** [comment] 2017-05-11 00:29
Any source on that?

**Comment by zSoulweaver** [comment] 2017-05-11 22:59
Their IRC and 4chin.

**Comment by zjhendryx** [comment] 2017-05-12 13:05
The "new" version of the site would seems to be https://nyaa.si/

HorribleSubs are certinaly marking it as the new version.

**Comment by gamesbe** [comment] 2017-05-13 05:37
Sadly can't add nyaa.si to sonarr due to 

>Indexer feed is not supported: Failed to find a valid download url in the feed.

Would really love a fix :D

**Comment by Bryan792** [comment] 2017-05-13 05:40
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Indexers/RssParser.cs#L283

Ya I was getting an error around here. Something along the lines of:

`system.argumentexception uri didn't match expected pattern`

**Comment by CodeMonkey626** [comment] 2017-05-13 05:44
PR adding Nyaa.si support to Jackett:
https://github.com/Jackett/Jackett/pull/1365

**Comment by Taloth** [comment] 2017-05-13 08:56
@CodeMonkey626 Why add it to Jackett? Using website scraping...
Nyaa.si has an api, it's open source. They might even be interested in a torznab PR. Which would give it support for Sonarr and Sickrage, which Jackett should be easily able to proxy (for aggregation purposes). And is much lighter on the Nyaa.si servers since it doesn't involve html website scraping.

**Comment by CodeMonkey626** [comment] 2017-05-13 11:38
@Taloth mostly because I wasn't aware that they had an API. I will take a look later today.

**Comment by CodeMonkey626** [comment] 2017-05-13 13:18
@Taloth The only existing APIs for nyaa.si are limited to uploading:
* https://github.com/nyaadevs/nyaa/blob/master/nyaa/routes.py#L626
* https://github.com/nyaadevs/nyaa/blob/master/nyaa/api_handler.py

So it seems like scraping is the only valid option in the short term until additional APIs are provided.

**Comment by Taloth** [comment] 2017-05-13 13:33
the fact that the api isn't fully functional yet (it mimics the nyaa api), is a good thing. Coz that means someone could write a PR that does a basic torznab api.
Point being that in this stage of the project, they might be open to the idea.

**Comment by CodeMonkey626** [comment] 2017-05-13 14:27
@Taloth I spoke to some of the nyaa.si team on IRC and they sounded open to it I created a feature request here: https://github.com/nyaadevs/nyaa/issues/18

Python development is outside my wheelhouse however.

**Comment by Taloth** [comment] 2017-05-13 14:34
Tnx for talking to them on IRC, I actually was typing out an Issue myself. I also pinged the sonarr irc channel in the hopes of getting one interested python guy.

**Comment by JamesTheAwesomeDude** [comment] 2017-05-18 14:25
It looks like nyaa.si might be a suitable replacement for this

**Comment by ecspresso** [comment] 2017-06-03 09:59
Will https://nyaa.pantsu.cat/ be supported as well?

**Comment by xelra** [comment] 2017-06-03 17:34
@ecspresso That depends on the site admin. Sonarr automagically supports any api that adheres to the torznab specification.

Last I know, the dev of nyaa.pantsu.cat wants to do it "some time in the future".

**Comment by ZadesSC** [comment] 2017-06-03 22:14
@ecspresso Both Nyaa.si and Nyaa.cat.pantsu are supported through Jackett
https://github.com/Jackett/Jackett

**Comment by ewhal** [comment] 2017-06-13 11:43
We're currently slowly adding in a more torznab compatible api for pantsu.cat

**Comment by xelra** [comment] 2017-06-14 11:58
@ewhal That's very good news. I'm looking forward to using the torznab api very much.

I'm referencing the corresponding issue here https://github.com/NyaaPantsu/nyaa/issues/607

**Comment by ewhal** [comment] 2017-06-22 05:52
Update on this pantsu.cat now has full sonarr support.
You can access the feed at https://nyaa.pantsu.cat/feed/torznab

**Comment by Anvirol** [comment] 2017-07-06 10:53
@ewhal 
> Update on this pantsu.cat now has full sonarr support.
You can access the feed at https://nyaa.pantsu.cat/feed/torznab

Care to provide some instructions? I've tried to add that as Nyaa indexer, but I'm getting error:
"Unable to connect to indexer, check the log for more details"

"17-7-6 13:49:43.0|Warn|HttpClient|HTTP Error - Res: [GET] https://nyaa.pantsu.cat/feed/torznab/?page=rss: 404.NotFound"


17-7-6 13:49:43.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

**Comment by weirdcrap** [comment] 2017-07-06 11:58
I'm posting from my mobile but the URL should be: https://nyaa.pantsu.cat

Then set API path to /feed/torznab

That should be all you need. You will have to turn on advanced settings to see the API path.

**Comment by Taloth** [comment] 2017-07-06 13:43
For those wondering how to use this:

![image](https://user-images.githubusercontent.com/6383890/27913894-d0043634-6261-11e7-821c-e4ba2e3506a3.png)

**Closed by Taloth** 2017-07-06 13:43 UTC

**Comment by Anvirol** [comment] 2017-07-06 14:35
@Taloth 
> For those wondering how to use this:

Still getting error..

`17-7-6 17:31:13.2|Warn|HttpClient|HTTP Error - Res: [GET] https://nyaa.pantsu.cat/feed/torznab?t=caps: 500.InternalServerError
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

17-7-6 17:31:13.2|Warn|Torznab|Unable to connect to indexer

[v2.0.0.4859] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://nyaa.pantsu.cat/feed/torznab?t=caps]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 106
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 193
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 62
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 22
   at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 26
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 315
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>


17-7-6 17:31:13.5|Warn|HttpClient|HTTP Error - Res: [GET] https://nyaa.pantsu.cat/feed/torznab?t=caps: 500.InternalServerError
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

17-7-6 17:31:13.5|Warn|Torznab|Unable to connect to indexer: HTTP request failed: [500:InternalServerError] [GET] at [https://nyaa.pantsu.cat/feed/torznab?t=caps]

[v2.0.0.4859] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://nyaa.pantsu.cat/feed/torznab?t=caps]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 106
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 193
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 62
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Core.Indexers.Torznab.Torznab.TestCapabilities() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:line 102
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>


17-7-6 17:31:13.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
 -- Unable to connect to indexer, check the log for more details
`

![image](https://user-images.githubusercontent.com/3955313/27915734-c6644f8e-626f-11e7-88dd-171a925e7c05.png)

**Comment by Taloth** [comment] 2017-07-06 14:45
Yeah, check the site:

![image](https://user-images.githubusercontent.com/6383890/27916785-6e23afcc-626a-11e7-820d-31b8e7601f58.png)

I'll retry once it's back up.

**Comment by Anvirol** [comment] 2017-07-06 15:59
@Taloth Thanks. It's now working properly.

**Comment by L0LL3R** [comment] 2018-05-05 22:00
https://animetorrents.me
