### ISSUE TITLE
False language being parsed from title 

### ISSUE THREAD

**Issue by Royalflash5220** [Sonarr/Sonarr#5340] opened 2023-01-03 15:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sorry in advance if im reporting this bug in a wrong way, its my first time. I dont even know if this is fixable, i just wanted to report it.

I was monitoring this show called "fargo" [IMDB](https://www.imdb.com/title/tt2802850/)

Episode 1 in season 2 is called "Waiting for Dutch" and Sonarr picked up "dutch" as the language for this episode, despite it being in german and "dutch" just being a name of someone in the tv show.

![Screenshot](https://user-images.githubusercontent.com/81267123/210379632-406ea950-cf3d-4f3e-b9be-eb6af566cdb4.png)

Its also happening for other releases of this episode being labeled as dutch, despite it being in english

### Expected Behavior

I expected the show to be correctly labeled as german

### Steps To Reproduce

Steps to reproduce with an german episode labled as dutch:
1. Add "Fargo" Season 2 to Sonarr 
2. Add "Drunkenslug" as an Indexer 
3. Do an interactive search for Season 2 Episode 1
4. Result:
![Screenshot 2023-01-03 160330](https://user-images.githubusercontent.com/81267123/210383548-2887874b-c102-4678-8dc7-e95d5fa0b22e.png)

### Environment

```markdown
- OS: Unraid 6.11.5
- Sonarr: 3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: NO
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

2023-01-03 16:09:37.2|Debug|Parser|Episode Parsed. Fargo - S02E01 
2023-01-03 16:09:37.2|Debug|Parser|Language parsed: Dutch
2023-01-03 16:09:37.2|Debug|QualityParser|Trying to parse quality for Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG
2023-01-03 16:09:37.2|Debug|Parser|Quality parsed: Bluray-1080p v2
2023-01-03 16:09:37.2|Debug|Parser|Release Group parsed: RSG
2023-01-03 16:09:37.2|Trace|PreferredWordService|Calculating preferred word score for 'Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG'
2023-01-03 16:09:37.2|Trace|PreferredWordService|Calculated preferred word score for 'Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG': 0 (0 match(es))
2023-01-03 16:09:37.2|Debug|AcceptableSizeSpecification|Beginning size check for: Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG
2023-01-03 16:09:37.2|Debug|AcceptableSizeSpecification|Possible double episode, doubling allowed size.
2023-01-03 16:09:37.2|Debug|AcceptableSizeSpecification|Item: Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG, meets size constraints
2023-01-03 16:09:37.2|Debug|AlreadyImportedSpecification|Performing already imported check on report
2023-01-03 16:09:37.2|Debug|AlreadyImportedSpecification|Skipping already imported check for episode without file
2023-01-03 16:09:37.2|Debug|LanguageSpecification|Checking if report meets language requirements. Dutch
2023-01-03 16:09:37.2|Debug|LanguageSpecification|Report Language: Dutch rejected because it is not wanted in profile German
2023-01-03 16:09:37.2|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2023-01-03 16:09:37.2|Debug|MaximumSizeSpecification|Maximum size is not set.
2023-01-03 16:09:37.2|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2023-01-03 16:09:37.2|Debug|MinimumAgeSpecification|Minimum age is not set.
2023-01-03 16:09:37.2|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. Bluray-1080p v2
2023-01-03 16:09:37.2|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG
2023-01-03 16:09:37.2|Debug|ReleaseRestrictionsSpecification|[Fargo.S02E01.Warten.auf.Dutch.German.DL.1080p.BluRay.x264.REPACK-RSG] No restrictions apply, allowing
2023-01-03 16:09:37.2|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2023-01-03 16:09:37.2|Debug|RetentionSpecification|Checking if report meets retention requirements. 462
2023-01-03 16:09:37.2|Debug|SceneMappingSpecification|No applicable scene mapping, skipping.
2023-01-03 16:09:37.2|Debug|SeriesSpecification|Checking if series matches searched series
2023-01-03 16:09:37.2|Debug|DelaySpecification|Ignoring delay for user invoked search
2023-01-03 16:09:37.2|Debug|HistorySpecification|Skipping history check during search
2023-01-03 16:09:37.2|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
2023-01-03 16:09:37.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Dutch is not allowed in profile German
2023-01-03 16:09:37.2|Trace|DownloadDecisionMaker|Processing release 27/96
2023-01-03 16:09:37.2|Debug|DownloadDecisionMaker|Processing release 'Fargo.S02E01.WEBRip.10Bit.1080p.DDP5.1.H265-d3g' from 'DrunkenSlug (Prowlarr)'
2023-01-03 16:09:37.2|Debug|Parser|Parsing string 'Fargo.S02E01.WEBRip.10Bit.1080p.DDP5.1.H265-d3g'
2023-01-03 16:09:37.2|Trace|Parser|^(?<title>.+?)(?:(?:[-_\W](?<![()\[!]))+S?(?<season>(?<!\d+)(?:\d{1,2})(?!\d+))(?:[ex]|\W[ex]){1,2}(?<episode>\d{2,3}(?!\d+))(?:(?:\-|[ex]|\W[ex]|_){1,2}(?<episode>\d{2,3}(?!\d+)))*)\W?(?!\\)

**Comment by markus101** [comment] 2023-01-03 15:41
Dupe of https://github.com/Sonarr/Sonarr/issues/861

**Closed by markus101** 2023-01-03 15:41 UTC
Labels: needs-triage
