### ISSUE TITLE
Sonarr is failing to import files because it expects an incorrect file extension (.mkv[eztv])

### ISSUE THREAD

**Issue by aidenmitchell** [Sonarr/Sonarr#4122] opened 2020-11-25 05:12 UTC
**Describe the bug**
Sonarr is failing to import files because it expects an incorrect file extension (.mkv[eztv])

**Logs**
https://pastebin.ubuntu.com/p/Wjv6nyk8tZ/

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: How can I find this?

**UI Bugs:**
N/A

**Additional context**
Error in UI:
```
young.sheldon.s04e03.1080p.web.h264-ggwp[eztv.re].mkv[eztv]
No files found are eligible for import in C:\Users\Administrator\Downloads\young.sheldon.s04e03.1080p.web.h264-ggwp[eztv.re].mkv[eztv]
```

**Comment by aidenmitchell** [comment] 2020-11-25 05:13
NOTE: Renaming the file in the Download Client fixes the issue.

**Comment by markus101** [comment] 2020-11-25 05:14
Dupe of https://github.com/Sonarr/Sonarr/issues/3968

**Closed by markus101** 2020-11-25 05:14 UTC

**Comment by aidenmitchell** [comment] 2020-11-25 05:16
@markus101 Is there a fix mentioned in #3968?

**Comment by bakerboy448** [comment] 2020-11-25 05:18
fixed on v3 and will only be fixed on v3 at this time.  @aidenmitchell

**Comment by micahmo** [comment] 2020-11-25 12:12
@aidenmitchell Workaround (if you don't want to go to v3) is to downgrade qBit to 4.2.5.
