### ISSUE TITLE
Having Series only search selected indexer

### ISSUE THREAD

**Issue by JayMan6014** [Sonarr/Sonarr#1097] opened 2016-01-28 04:02 UTC
I looked but I don't see this suggested.

Having the option to assign an indexer to a series.   The wife makes me download Dr. Phil which only shows up on Kickass so I have to leave that indexer enabled to get those shows. But I don't want other shows coming from Kickass so being able to say  Dr. Phil search only from kickass so I don't need to leave that indexer turned on for all series.

I hope this makes sense.

**Comment by markus101** [comment] 2016-01-28 17:24
Dupe of https://github.com/Sonarr/Sonarr/issues/487

**Closed by markus101** 2016-01-28 17:24 UTC
