### ISSUE TITLE
4.0.0.614 and later failing during migrations

### ISSUE THREAD

**Issue by ridizy** [Sonarr/Sonarr#5924] opened 2023-08-14 20:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I tried to upgrade from 4.0.0.600 to 4.0.0.625.  I was unable to access the UI and notice a fatal error in the log files regarding the database migration.  I kept trying other builds and the last version that I am able to run without the error is 4.0.0.613

### Expected Behavior

The upgrade should complete successfully and the UI should be accessable

### Steps To Reproduce

Upgrade from 4.0.0.600 to any version after 4.0.0.613

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.600 -> 4.0.0.614
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Develop

### Trace Logs?

https://hastebin.com/share/adogunehek.csharp

**Comment by stevietv** [comment] 2023-08-14 20:57
dupe of #5915

**Comment by stevietv** [comment] 2023-08-14 21:00
Your database has underlying corruption. This migration is causing it to become apparent now, but likely would have appeared at some point. You can find a guide to fixing corruption on our [wiki](https://wiki.servarr.com/en/sonarr/faq#i-am-getting-an-error-database-disk-image-is-malformed).

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for any additional questions about it.

**Comment by ridizy** [comment] 2023-08-14 21:04
Thank you.  I have tried backups and using the sqlite3 recover facility without success.  I'll give one of the support options a shot.

**Comment by Qstick** [comment] 2023-08-15 01:03
DBBrowser Export to SQL and Import as DB usually works to at least get back to a mostly functional salvaged DB. (mentioned in the wiki). Make sure you aren't accessing the DB over a network drive when working with it outside of Sonarr

**Closed by Qstick** 2023-08-15 01:03 UTC
Labels: needs-triage

**Comment by ridizy** [comment] 2023-08-15 02:08
Thank you @Qstick.  I followed the wiki precisely and tried the DB Browser method.  I ensured that all operations were done locally and not across the network.  I'm still getting the same result.

**Comment by Qstick** [comment] 2023-08-15 02:33
Come to discord
