### ISSUE TITLE
Preserve custom tags/suffixes when importing subtitles

### ISSUE THREAD

**Issue by jusher00** [Sonarr/Sonarr#2570] opened 2018-05-16 22:48 UTC
### What problem are you looking to solve?
I have a lot of movie folders containing a structure like this:

`movie-2018.de.forced.idx`
`movie-2018.de.forced.sub`
`movie-2018.de.idx`
`movie-2018.de.sub`
`movie-2018.en.forced.idx`
`movie-2018.en.forced.sub`
`movie-2018.en.idx`
`movie-2018.en.sub`
`movie-2018.mkv`

[Plex supports this naming scheme](https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/), however Sonarr fails to import this correctly unfortunately.

When I import this, the subtitles flagged as `forced` neither keep that forced flag, nor is the language parsed.

It would be great if Sonarr was able to keep that `forced` flag and recognize the language as well.

**Comment by markus101** [comment] 2020-04-20 15:20
This should also include things like unknown language codes (`tc` (Traditional Chinese) or `sc` (Simplified Chinese)) or `sdh` (Subtitles for the Deaf or Hard-of-Hearing) or a specific audio track (director, etc).

**Comment by bakerboy448** [comment] 2020-11-18 01:48
Duplicate of #2639

**Comment by wsegatto** [comment] 2021-06-28 04:32
Let me add an important comment – at least for me and all Brazilians. 

For subtitles that contain the country attribute like pt-BR (Brazilian Portuguese) it is being removed when Sonarr renames the file.

Before:

The.Walking.Dead.S01E01.XXXXXXXX.mkv
The.Walking.Dead.S01E01.XXXXXXXX.pt-BR.srt
After:

The.Walking.Dead.S01E01.mkv
The.Walking.Dead.S01E01.srt

It should be renamed to The.Walking.Dead.S01E01.pt-BR.srt

For cases that don't contain the country attribute, it works fine.

The one that sets our subtitles to "pt-BR" is Bazarr, so it makes sense that Sonarr should maintain - and not lose - this critical information, specially when maintaining multiple language subtitles.

**Comment by bakerboy448** [comment] 2021-06-28 04:37
https://typecraft.org/tc2wiki/Brazilian_Portuguese_(BP)

Probably should add support and get all ISO languages covered as a stop gap

https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Parser/IsoLanguages.cs

**Comment by wsegatto** [comment] 2021-08-23 14:26
Any updates?

**Comment by gdmachado** [comment] 2021-10-16 12:48
I'm using Bazarr to download Brazilian Portuguese subtitles, and I can add that downloaded `.srt` files will contain the `pt-BR` language code, which then gets removed by Sonarr when renaming is turned on, making the renaming feature unusable for that use-case.

**Closed** 2022-08-07 18:47 UTC
Labels: suboptimal
