### ISSUE TITLE
Feature Request: Insure no download of episode before finish air date/time

### ISSUE THREAD

**Issue by GregoryGHarding** [Sonarr/Sonarr#1705] opened 2017-02-22 04:58 UTC
i actually really surprised i haven't found this in the settings already CP has it for movies.

im having issues where Sonarr will download episodes the day before they air resulting in a fake video being processed, or more commonly.. the day of airing around the time of airing it will download the episode and it will be only half the file (cal it fake, or incomplete to push release first)

but id really like to see a feature where we can set (in minutes) how long after a show finishes airing that sonarr will begin searching or allowing download of that episode.

Thanks

**Comment by markus101** [comment] 2017-02-22 05:01
Dupe of: https://github.com/Sonarr/Sonarr/issues/969

No plans for limiting it to after a certain amount of time, though delay profiles may be of some use there (but after posting).

**Closed by markus101** 2017-02-22 05:01 UTC
