### ISSUE TITLE
missing season finale episode

### ISSUE THREAD

**Issue by MadayLyncoln** [Sonarr/Sonarr#7175] opened 2024-09-04 01:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm having a problem that during episode releases sonarr finds them on the net but the last episode isn't usually released as a standalone or separate episode, it's usually released as part of a pack with all the episodes from the season, so sonarr can't find the last episode and it's always missing, even if there's a full pack available to download. 

### Expected Behavior

I would like sonarr, when it finds a full pack in a season missing an episode, to download the full pack and apply it to that season, thus completing the missing episodes.

### Environment

```markdown
- OS:  Microsoft Windows 11 Pro
- Sonarr: 4.0.9.2244
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

N/A

**Comment by markus101** [comment] 2024-09-04 02:51
Duplicate of #6378

**Closed by markus101** 2024-09-04 02:51 UTC
Labels: needs-triage
