### ISSUE TITLE
Option to Search by episode title for documentaries.

### ISSUE THREAD

**Issue by shad90** [Sonarr/Sonarr#3823] opened 2020-06-19 09:15 UTC
**Describe the problem**
Sonarr send search queries to indexer formatted somewhat as {Show Title}{SxxExx}. This works for most of tv series. And i think it works best with NZB indexers. Torrents are wild lands. Not everyone following TVdB format. It works most of the times with torrents too. 

But, i am having problem searching for documentaries. Many channels have documentary series, and episodes can be searched using existing search method. Like for` BBC horizon `searching "`Horizon S00E00`" will most of the time get you torrent results. I have added series named "Discovery Channel Documentaries". I hope you can see the problem here. These are stand alone documentaries. 

Now I will give one particular example. I have added series named _"`Discovery  Channel Documentaries`"_ in Sonarr. Its 2020 season has documentary titled as _"`NASA & SpaceX: Journey to the Future`"_. 
Now Sonarr will search for `Discovery  Channel Documentaries S2020E02`. No indexer will return any result to that. Not even NZB indexers. I searched for` NASA & SpaceX: Journey to the Future` in Jackette and it returned multiple good results. Same for series titled as "_`BBC Documentaries`_", "_`HBO Documentaries`_" etc. etc.

**Describe any solutions you think might work**
As I said current search string scheme work good for normal TV shows but in special cases like i discussed above. There should be an option to search by _episode title_ **not** by show title.

**Additional context**
Other examples of same type of Series in TVDB added in Sonarr are "PBS Specials" , "DW Documentaries", "History Channel Documentaries".

**Comment by markus101** [comment] 2020-06-19 14:38
Please search before opening new issues, this is a dupe of https://github.com/Sonarr/Sonarr/issues/332

**Closed by markus101** 2020-06-19 14:38 UTC
