### ISSUE TITLE
Anime Series not being Imported (Due to title length)

### ISSUE THREAD

**Issue by warsix4** [Sonarr/Sonarr#3238] opened 2019-08-03 16:01 UTC
**Describe the bug**
Sonarr does not import/rename episodes from the series "**Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?**"
Manually importing does not provide any immediate indication for failure. Logs indicate that the title is too long.

The sub group [HorribleSubs] has gone with the name "**Okaa-san Online**" for the series which is obviously much shorter. Can I force Sonarr to use this alternate title somehow? 

**Logs**
```
19-8-3 10:50:51.3|Warn|ImportApprovedEpisodes|Couldn't import episode \\storage\Scratch\NZB\complete\[HorribleSubs] Okaa-san Online - 04 [720p].mkv\[HorribleSubs] Okaa-san Online - 04 [720p].mkv

[v2.0.0.5337] System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.EnsureEpisodeFolder(EpisodeFile episodeFile, Series series, Int32 seasonNumber, String filePath) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 154
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 77
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 76
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 105
```

 - Sonarr Version: 2.0.0.5337
 - Operating System: Windows Server 2016
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.5

**Comment by markus101** [comment] 2019-08-03 16:03
Dupe of https://github.com/Sonarr/Sonarr/issues/2699

**Closed by markus101** 2019-08-03 16:03 UTC
