### ISSUE TITLE
Alternative Titles for Anime 

### ISSUE THREAD

**Issue by SomeThingElseZ** [Sonarr/Sonarr#4937] opened 2022-03-09 11:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

when sonarr rename animes it uses the English title instead of the such as 
"Shinigami Bocchan to Kuro Maid"  ==> "The Duke of Death and His Maid"

its not a problem when i add 2 or 3 animes i can just change the name manually
but i have a large library (around 8tb of anime) so you can see how  that's inconvenient 

### Describe the solution you'd like

since sonarr search for animes using alternate title it could also get the Japanese title and preferably give an option when choosing Anime in Series Type to use the Japanese naming 

### Describe alternatives you've considered

changing it manually but that not convenient and kind of defeat the purpose of automating stuff with sonarr 

### Anything else?

This guy explains it better than me https://www.reddit.com/r/sonarr/comments/hv17y4/options_for_alternative_titles_for_anime/

**Comment by bakerboy448** [comment] 2022-03-09 12:36
Duplicate of https://github.com/Sonarr/Sonarr/issues/269

**Closed** 2022-03-09 12:37 UTC
