### ISSUE TITLE
Variables For Custom Formats

### ISSUE THREAD

**Issue by onisaibogu** [Sonarr/Sonarr#6852] opened 2024-06-02 09:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

More so annoyance than problem, I sometimes use custom filters when manually searching for a show to sort out unwanted results on a basis of either name or year, however I find myself only needing to use said filter once and resorting to either making a new filter or editing the old one with what would be the "same" information about another series (title and year for me).

### Describe the solution you'd like

Tokens similar to or identical to what are used for naming could simplify the custom filter list by quite a bit. As opposed to, say, having "show x", "show y", and "show z" appear in the list, it could be {Series Title} and you could be done with it for most series. I could see use cases for some of the other name tokens to some people, such as episode name or air date for some shows, as well as year for shows with multiple incarnations.

### Describe alternatives you've considered

I feel as though there are a few ways around this as you would primarily need the information that I suspect is stored when the show is added to the list and a way to use it as a replacement for a user added string on a custom manual search filter.

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/20854203/2e38ae40-dc4b-4e16-8bb0-0ceacd922772)
I mean this obviously isn't working out currently, but repurposing the file naming tokens maybe? I could see some issues for more particular ones such as episode title or name in a season search, but I could see it being solved by returning no results or having no value outside of manual episode searches.

**Comment by stevietv** [comment] 2024-06-02 09:34
I think instead of allowing a ton of variables here, perhaps a standard filter could be added to the search results box for matches to Series Title (or alias) - i.e. filter any out that don't match one of the titles

**Comment by markus101** [comment] 2024-06-02 15:30
The problem is there are releases that won't match an alias exactly, but are matches to the series and are parsed and linked correctly.

Really this comes down to rejecting a release that isn't a series match, which falls under https://github.com/Sonarr/Sonarr/issues/4132

Duplicate of #4132

**Closed** 2024-06-02 15:30 UTC
Labels: needs-triage
