### ISSUE TITLE
v4 Custom Formats: add support for indexer flags

### ISSUE THREAD

**Issue by kvothe-the-arcane** [Sonarr/Sonarr#5728] opened 2023-06-11 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently cannot prioritise freeleech.

Also some trackers have strict rules around release naming, which can mean that some info is stripped out (i.e. DV w/ HDR fallback only including "DV" in the release title; although the tracker I'm thinking of hasn't implemented these as flags yet, but apparently they are under development).

### Describe the solution you'd like

Add support for 'indexer flags' as a condition for custom formats (exactly as radarr has done for a while).

### Describe alternatives you've considered

N/A.

### Anything else?

I can see there have been previous and differing requests around indexer flags/freeleech etc., but these are all to do with v3 and the old way of doing things (i.e. preferred words, required/exclusions). However now that custom formats have been adopted in v4 (which is greatly appreciated, as this is much more powerful than preferred words) surely support for indexer flags under this feature would be ideal and relatively easy to implement, I would expect?

**Comment by markus101** [comment] 2023-06-11 15:23
Duplicate of #2782

**Closed by markus101** 2023-06-11 15:23 UTC
Labels: needs-triage
