### ISSUE TITLE
Indexer priority

### ISSUE THREAD

**Issue by soulvoid86** [Sonarr/Sonarr#3447] opened 2019-12-08 15:57 UTC
**Describe the problem**
I'd like to have a way to set indexer priority. I have certain indexers that I'd like to user over others, so that my activity is as secure as possible. But I do have some as back-ups, in the event that they have items available that my primary indexer doesn't.

**Describe any solutions you think might work**
Maybe something that lets you drag the indexer tiles around on the settings page, to sort their priority. Or a drop down in the indexer settings. Anything would work.

**Additional context**
Nope, thanks for the amazing system! :) Feel free to tell me I'm dumb if this exists.

**Comment by markus101** [comment] 2019-12-08 17:30
Dupe of https://github.com/Sonarr/Sonarr/issues/320

**Closed by markus101** 2019-12-08 17:30 UTC
