### ISSUE TITLE
Bind Address doesn't work with DNS name

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#622] opened 2015-06-17 00:29 UTC
Bind to a specific IP address and then attempt to connect via the hostname or any other DNS name and the connection doesn't go through.

This might be a limitation in httpsys and how OWIN is bound to the IP.

**Comment by Morten242** [comment] 2015-06-17 18:32
I bound sonarr to my local IP address given by router and was able to connect with my computer's hostname and some .redirectme.net address.

I may be just misreading the issue, but I can't reproduce.

**Comment by markus101** [comment] 2015-06-18 19:44
@Morten242 I'm not able to reproduce it myself (Windows Server 2012), restarting Sonarr to make sure the change takes effect.

This is what I tested:
- Private IP :white_check_mark: 
- DNS pointed at private IP :white_check_mark: 
- localhost :white_check_mark: 
- 127.0.0.01 🚫

How are you connecting?

**Comment by Morten242** [comment] 2015-06-18 19:48
On a whim I whipped out my laptop. At which point the DNS pointed at my private IP returned something along the lines of "invalid hostname".

**Comment by mwronski** [comment] 2015-06-24 23:28
Running on Linux not windows.  Connecting from other device (any OS) to the IP:8989 works fine. If I use the DNS name, I get a white screen with "Bad Request (Invalid host)"

**Comment by djmixman** [comment] 2015-08-30 20:46
Has there been any progress on this problem? I am having the same issue too.

**Comment by naq90** [comment] 2015-09-30 05:47
This just happened to me. Everything was working fine and out the blue I get the same error when trying to connect from outside my network. Has there been any progress?

**Comment by mikazuki** [comment] 2015-10-07 17:36
I'm on OSX and have the same issue.
As a workaround a setup an nginx server before the sonarr and proxy everything through the nginx and rewrite the HTTP Host header:
```nginx
server {
	location / {
		proxy_pass http://127.0.0.1:8989;
		proxy_set_header Host localhost:8989;
	}
}
```

**Comment by joeyaiello** [comment] 2015-10-13 08:32
Miiight be a different issue, but I'm not able to bind to a local IP on Windows. However, my weirdness is that I'm also trying to bind to port 80 when 192.168.1.102 is one of many IPs assigned to a single physical NIC (and the other local IPs assigned to that NIC are *also* bound to their own port 80). I think Sonarr might be trying to bind to port 80 on other IPs as well. Config is as follows:

```xml
<Config>
  <Port>80</Port>
  <UrlBase></UrlBase>
  <BindAddress>192.168.1.102</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>ee0d3839aa314470bce43886b583f169</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <LogLevel>Info</LogLevel>
  <Branch>master</Branch>
  <LaunchBrowser>True</LaunchBrowser>
  <SslCertHash></SslCertHash>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
</Config>
```

When I restart on the port change, I get an error message that reads:

```
Epic Fail!
PortInUseException: Port 80 is already in use, please ensure NzbDrone is not already running.
```

**Comment by MartinAyla** [comment] 2015-11-06 13:55
I have the same problem, can't connect from Safari on OS X, anything we can do, beside using an nginx proxy?

**Comment by spencerbutler** [comment] 2021-01-16 01:57
I have BindAddress set to an IP that resolves for every other docker container I am running. I can access sonarr via the IP, but not the host name. 

Did anyone ever resolve (heh..) this trivial issue?

**Comment by Morten242** [comment] 2022-11-29 17:30
@Qstick - The issue is still there.

**Comment by markus101** [comment] 2022-12-05 06:13
I've done some more digging into this and a Bind Address of a DNS name is not supported, the webserver we're using (Kestrel) allows the following:

- `localhost`
- IPv4
- IPv6
- `*`, `+` or anything else

The `*`, `+` or anything else means everything else, if you specify: `sonarr.mydomain.tld` the server will just bind it to everything same as if you chose `*` (which is what we use internally to listen to everything).

We'll be making some changes and closing this out to match what is allowed by the webserver.

**Closed** 2022-12-07 07:12 UTC
Labels: bug, priority:high
