### ISSUE TITLE
Issue with show titles that contain numbers

### ISSUE THREAD

**Issue by Nerdy314159265** [Sonarr/Sonarr#4463] opened 2021-04-24 17:08 UTC
**Describe the bug**

Some shows containing numbers will cause the search to fail to recognize matching results (Unknown Series) because it will detect the number in the title as the episode number. Automatic importing will also fail because, despite recognizing the series, it will become confused on the episode season/number.

Possibly anime-only issue caused by absolute episode number search/scanning.

**To Reproduce**
1. Add series: I've Been Killing Slimes for 300 Years and Maxed Out My Level
2. Search for an episode
3. Results will populate but be unrecognized
4. Attempt automatic import of test file named appropriately
5. Import fails, detecting proper series but unknown season/episode

**Expected behavior**

Properly titled files/releases should be detected as matching with correct series/episode

**Platform Information (please complete the following information):**
 - OS: FreeBSD 12.2
 - Docker: No
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 6.8
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Comment by markus101** [comment] 2021-04-24 17:10
Please search before opening issues this is a dupe of https://github.com/Sonarr/Sonarr/issues/4433

**Comment by bakerboy448** [comment] 2021-04-24 17:10
Closing; improper template (no logs)

also dupe and fixed in nightly (assuming its the "300" being picked up on

**Closed by markus101** 2021-04-24 17:10 UTC

**Comment by Nerdy314159265** [comment] 2021-04-24 17:11
> Please search before opening issues this is a dupe of #4433

I did.

However, I searched "numbers" and not "number" so didn't see that result. 

Apologies for the dupe.

**Comment by Nerdy314159265** [comment] 2021-04-24 17:13
> Closing; improper template (no logs)
> 
> also dupe and fixed in nightly (assuming its the "300" being picked up on

Man you guys are fast.

Again, apologies. I was about to go attempt to generate some clean logs.
