### ISSUE TITLE
Sonarr not deleting after importing 

### ISSUE THREAD

**Issue by Hhhonlyfan** [Sonarr/Sonarr#4233] opened 2021-01-08 16:08 UTC
Sonarr isn't deleting files after it imports to its destination.

**System Information**

Ubuntu 18.04
 Version
3.0.4.1059
Package Version
3.0.4 by Team Sonarr
Mono Version
6.12.0.107
AppData directory
/var/lib/sonarr
Startup directory
/usr/lib/sonarr/bin
Mode
Console
Uptime

 - Branch:

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by bakerboy448** [comment] 2021-01-08 16:20
Closing; no information provided, template not filled out.

And more than likely not a bug

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Closed by bakerboy448** 2021-01-08 16:20 UTC

**Comment by Hhhonlyfan** [comment] 2021-01-08 16:23
Didn't use template? I copied all the info I have for it.

When my ubuntu server guru has never seen this issue as well.

He uses Ubuntu as an developer and works with it daily yet he cannot see why sonarr doesn't delete even though permissions are correctly assigned.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by bakerboy448** [comment] 2021-01-08 16:25
Yes, the template.
https://github.com/Sonarr/Sonarr/issues/new?assignees=&labels=&template=bug_report.md

Third party apps tend to ignore it which is frustrating for all involved.

torrents that are still seeding will be copied or hardlinked (if possible)

usenet will be copy/delete or atomic moved (if possible)

**Comment by Hhhonlyfan** [comment] 2021-01-08 16:26
I'm using usenet and trying to fill this in properly.

Sent from ProtonMail mobile

-------- Original Message --------
