### ISSUE TITLE
Add "Discover" page like in Radarr

### ISSUE THREAD

**Issue by nausley** [Sonarr/Sonarr#4645] opened 2021-08-30 01:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I can't find a way to view Import Lists to review before adding to Sonarr like there is in the Radarr via "Discover" tab.

### Describe the solution you'd like

Add Discover feature tab like currently in Radarr.

### Describe alternatives you've considered

Tag shows added via Import lists, and provide a filter to see them.  This works but I'm trying to keep my library clean with only monitored shows.

### Anything else?

Nothing else.  Thank you for your time.

**Comment by bakerboy448** [comment] 2021-08-30 01:11
Duplicate of #
Duplicate of #
Duplicate of #

**Closed** 2021-08-30 13:43 UTC
Labels: enhancement
