### ISSUE TITLE
Suggest Rename of TBA episodes

### ISSUE THREAD

**Issue by stevietv** [Sonarr/Sonarr#4031] opened 2020-10-24 10:46 UTC
**Describe the problem**
Currently episodes with TBA in the title are delayed for importing for 24 hours, however if there is no title after that 24 hours then they are imported with TBA. With delays in syncs between TVDB , their API and Skyhook, it can quite commonly occur that a TBA show still has the TBA title 24 hours after downloading, especially in shows where the title is not yet known until airing.

**Describe any solutions you think might work**
Store records of titles that have been imported with TBA after the 24 hour delay and either 
1. rename them automatically when a title becomes available (may cause issues if file is being streamed at that point)
2. create a session, task or screen that can be run to rename them, similar perhaps to the cut-off unmet screen.

**Additional context**
N/A

**Comment by markus101** [comment] 2020-10-24 16:50
Dupe of https://github.com/Sonarr/Sonarr/issues/1118

**Closed by markus101** 2020-10-24 16:50 UTC
