### ISSUE TITLE
Ability to choose metadata source (Example; tmdb, or DVD Ordering from tvdb)

### ISSUE THREAD

**Issue by Nomelas** [Sonarr/Sonarr#4395] opened 2021-03-19 19:14 UTC
**Is your feature request related to a problem? Please describe.**
Yes, sometimes tvdb aired order is not ideal, example: https://www.thetvdb.com/series/dragon-ball-kai

**Describe the solution you'd like**
The ability to choose metadata source, per series and overall defaults.

**Describe alternatives you've considered**
None, other than using another app? Manual renames defeats the purpose of this app.

**Additional context**
With Plex's new _[BETA] New Plex TV Series Scanner_ (https://forums.plex.tv/t/beta-new-plex-tv-series-scanner/696242). You can choose what source to choose to get metadata from in a more fine-grained options. Now, instead of being limited to only aired order, you can choose others such as dvd order. This is extremely beneficial for shows like Dragon Ball Kai, where DVD order is vastly superior to the aired order. Unfortunately, this can't be used with Sonarr since we're specifically limited to the aired order in tvdb.

**Comment by bakerboy448** [comment] 2021-03-19 19:15
Dupe of #255

please use the search function next time

**Closed by bakerboy448** 2021-03-19 19:15 UTC
