### ISSUE TITLE
"Object reference not set to an instance of an object" when searching episode (sonnar-v3)

### ISSUE THREAD

**Issue by flashkiller999** [Sonarr/Sonarr#3386] opened 2019-11-09 11:20 UTC
**Describe the bug**
This only happens with a specific episode of a specific series.
When I try to search for a new episode (either manual or automatic), I get "No results found".
Upon activating Tracing, I found that he was able to find some releases that would be accepted.
But at the time of sonarr trying to hand me back these releases, there is an exception thrown:

`[v3.0.3.653] System.NullReferenceException: Object reference not set to an instance of an object
  at Sonarr.Api.V3.Indexers.ReleaseResourceMapper.ToResource (NzbDrone.Core.DecisionEngine.DownloadDecision model) [0x00039] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseResource.cs:84 
  at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecision (NzbDrone.Core.DecisionEngine.DownloadDecision decision, System.Int32 initialWeight) [0x00006] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:25 
  at Sonarr.Api.V3.Indexers.ReleaseModule.MapDecision (NzbDrone.Core.DecisionEngine.DownloadDecision decision, System.Int32 initialWeight) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:203 
  at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecisions (System.Collections.Generic.IEnumerable`1[T] decisions) [0x00016] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:15 
  at Sonarr.Api.V3.Indexers.ReleaseModule.GetEpisodeReleases (System.Int32 episodeId) [0x0001c] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:157 `

**Logs**
https://privatebin.net/?4186993e8864e098#7LvhmpRSiarQiK6wAYQmyGX1bwD446UrrS6B64TSUCJV

**System Information**

 - Sonarr Version: 3.0.3.653
 - Operating System: Ubuntu Server 18.04.03
 - mono (Linux) Version: 6.4.0.198

**Comment by markus101** [comment] 2019-11-09 16:18
Dupe of https://github.com/Sonarr/Sonarr/issues/3377

**Closed by markus101** 2019-11-09 16:18 UTC
