### ISSUE TITLE
Allow user to force download on Manual Search

### ISSUE THREAD

**Issue by jcchristian** [Sonarr/Sonarr#1732] opened 2017-03-04 01:57 UTC
I'm searching for some series specials and while I get correct results I can't download them because "Unknown Series", for example:

![image](https://cloud.githubusercontent.com/assets/4141392/23574982/8d8c1b64-0064-11e7-8bde-37d0dceb952b.png)
![image](https://cloud.githubusercontent.com/assets/4141392/23574986/9ac23cb4-0064-11e7-97a9-1a4ad4543dda.png)
![image](https://cloud.githubusercontent.com/assets/4141392/23575010/f001291a-0064-11e7-9b8e-a5ee2d73a61c.png)

I know those are the files I want, why can't I force download them as I'm doing a manual search already?

**Comment by markus101** [comment] 2017-03-04 01:58
Dupe of https://github.com/Sonarr/Sonarr/issues/395

**Closed by markus101** 2017-03-04 01:58 UTC
