### ISSUE TITLE
Non-Anime Show with Episodes over 999 not matched 

### ISSUE THREAD

**Issue by tobsen987** [Sonarr/Sonarr#3841] opened 2020-06-29 12:38 UTC
**Describe the bug**
The german series Tatort (https://www.thetvdb.com/series/tatort) gets released with absolute episode numbers. The Problem is, that thetvdb lists the seasons as the current year. So I Set the series to anime, which leads to manual search finding the releases, but they are not grabbed, because episodes are over 1000, and it seems like Sonarr caps out at Episode 999.

Releases are e.g. Tatort.E1135.Lasst.den.Mond.am.Himmel.stehen.GERMAN.1080p.WEBRip.x264-Group (Group varies!)

This Release should be S2020E21 but is detected as E113, S1980E06.

I was in the IRC Channel of TheXEM a while back, and they said its not a problem their service could fix. 

**System Information**
Version
3.0.3.896
Package Version
3.0.3.896-ls29 by linuxserver.io
Mono Version
5.20.1.34

**Comment by thezoggy** [comment] 2020-07-02 01:03
E#### is absolute numbering. which is mainly only used by anime, so this ends up being a dupe of
https://github.com/Sonarr/Sonarr/issues/1125

**Comment by tobsen987** [comment] 2020-07-09 13:05
The used regex is:
`20-7-9 15:00:37.6|Trace|Parser|^(?:\[(?<subgroup>.+?)\][-_. ]?)?(?<title>.+?)(?:(?:_|-|\s|\.)+(?:e|ep)(?<absoluteepisode>\d{2,3}(\.\d{1,2})?))+.*?(?<hash>\[\w{8}\])?(?:$|\.)`

Wouldn't it be sufficient to change <absoluteepisode>\d{2,3} to <absoluteepisode>\d{2,4} ?

**Comment by thezoggy** [comment] 2020-07-09 15:49
you have to look at the pecking order of the regex's.  I believe the issue with just doing 4 digits is that it would break other regex's like:
>                 //Episodes with a title, 4 digit season number, Single episodes (S2016E05, etc) & Multi-episode (S2016E05E06, S2016E05-06, S2016E05 E06, etc)
>                 //Episodes with a title, 4 digit season number, Single episodes (2016x05, etc) & Multi-episode (2016x05x06, 2016x05-06, 2016x05 x06, etc)

since the issue is when parsing is that you dont know if the show is a specific type to only apply certain regexes to it.  
and the amount of shows that have 4+ digits for absolute numbering is so tiny it wasnt worth the false positive/breakage for the huge amount of shows that do years in their numbering

**Comment by tobsen987** [comment] 2020-07-09 15:54
I don‘t think it would break those, as it expects an „E“ or „EP“ before the digits.

**Closed** 2020-07-26 17:51 UTC
Labels: parsing, suboptimal
