### ISSUE TITLE
Can't match download to show despite name being identical

### ISSUE THREAD

**Issue by Fma965** [Sonarr/Sonarr#2617] opened 2018-06-14 15:13 UTC
**Describe the bug**
Sonarr can't match the name with the download despite the name being identical

**Screenshots**
![unknown](https://user-images.githubusercontent.com/1707290/41421025-b61d88e8-6fed-11e8-944d-7adce34251c2.png)

**Logs**
There isn't any relevant log but i can get them if required.

**System Information**

 - Sonarr Version: 2.0.0.5163
 - Operating System: LinuxServer Docker on OpenMediaVault

**Additional context**

**Comment by markus101** [comment] 2018-06-14 17:07
`All New Traffic Cops` is an alias for the original show: https://www.thetvdb.com/series/traffic-cops which appears to have the same episodes that https://www.thetvdb.com/series/all-new-traffic-cops has (in the different seasons).

It looks like the new series is duplicate of sorts, since the original is updated and how TVDB wants it listed.

Removing the current series and adding the original is the best way to get it fixed up right now. If TheTVDB wants the new series instead of building on the old series the old series should be fixed up and we can remove the alias, but best to open a thread on their forums to figure out if that is the appropriate course of action.

**Closed by markus101** 2018-06-14 17:07 UTC

**Comment by Fma965** [comment] 2018-06-14 18:57
Perfect thanks :)
