### ISSUE TITLE
Sonarr is unable to remove torrents that have finished seeding when using rTorrent

### ISSUE THREAD

**Issue by blackwind** [Sonarr/Sonarr#2204] opened 2017-10-03 22:15 UTC
Someone posted on the forums about this last year and was told this is because:

> From what we've seen rTorrent doesn't provide a way for Sonarr to know that the torrent actually finished seeding and wasn't manually stopped for another reason. We opted to leave it unavailable than to guess and hope we don't nuke something that was paused/stopped for another reason.

I posted an issue at rakshasa/rtorrent#647 asking them to add an API, and I was told this can already be accomplished via ratio groups. Could you take another look at this, and, if necessary, report to them in the linked issue why ratio groups aren't a sufficient solution?

**Comment by pyroscope** [comment] 2017-10-07 10:32
It's not rocket science, someone who wants this has to debug / test the sketch below, then it can be added to the docs of THIS project as a prerequisite for using the feature.

```ini
view.add = finished
method.set = group.seeding.ratio.command, \
    "d.try_close= ; d.ignore_commands.set=1 ; view.set_visible=finished"
```
Then ``d.views.has=‹hash›,finished`` is the sought-after API call. And you can enumerate them via `d.multicall2`.

**Comment by CRCinAU** [comment] 2017-10-12 10:45
I'm a bit curious here.... Do you mean method.set or system.method.set?

For example, I move finished torrents to somewhere else via:
`system.method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir="`

**Comment by pyroscope** [comment] 2017-10-12 17:32
I don't use deprecated commands.

**Comment by CRCinAU** [comment] 2017-10-13 01:21
Ok - so as someone who started using sonaar yesterday, are you saying that with that config for rtorrent, then the current stable version of sonaar should just pick it up successfully for rtorrent? Or is there something else assumed that may not be present?

**Comment by markus101** [comment] 2017-11-02 14:45
Dupe of https://github.com/Sonarr/Sonarr/issues/657

**Closed by markus101** 2017-11-02 14:45 UTC

**Comment by Taloth** [comment] 2021-05-15 22:52
Implemented in https://github.com/Sonarr/Sonarr/commit/411be4d0116f0739bb9c71235312d0c5a26dd3a2
