### ISSUE TITLE
Use keywords for language detection through automatic search

### ISSUE THREAD

**Issue by ComteNiark** [Sonarr/Sonarr#4303] opened 2021-02-04 12:52 UTC
**Describe the problem**
Currently, releases that are subbed in a language are considered to be in english. This is problem for anime, since something like french subbed anime is considered by the audience to be the "french version" until a dub comes along, and even then, some people would still prefer to grab subbed releases, but Sonarr says "no, this is english, since the audio isn't in french". Since this is to do with the language detection rather than media type, adding favored words doesn't help: if my profile won't even grab french subtitled episodes (since they are seen as "english"), I can't tell it to favor subs or dubs.

**Describe any solutions you think might work**
Language detection should work on keywords/favored words, set up by the user, rather than the AFAIK harcoded filter we have right now. This helps with multi-language media, such as anime, or with multi-language release (MULTI releases are treated as english right now, which suffers from the same problem: a MULTI release is good for my french users, but if I set the show to my french language profile, it won't be grabbed). 
By having the same keyword in two language profiles, as you would with MULTI for example, that would mean this release is flagged as ok to download for both an english and foreign language profile, with further tuning available through favored words.
This would even allow us to make a MULTI profile, for media we don't want to download unless it's available in multiple languages, for different users that enjoy subbed/dubbed.
As for the sorting, I think it should work the same way as favored words, but come before that sort. Which means that it first sorts all the releases, finds the ones with the language that best matches the language keywords, and then does another sort, finding the one between these that best fits the favored words.
It would be even better if these keywords were different for anime and regular shows.

**Additional context**
I think Radarr already works this way?

**Comment by bakerboy448** [comment] 2021-02-04 12:57
Being able to define what Multi is by indexer is likely the path of least resistance (and matches radarr)

**Comment by ComteNiark** [comment] 2021-02-04 13:08
This doesn't solve the issue. Sometimes you want to grab only MULTI releases (for comparison between audio tracks, for example, or like said before, for different users with different taste). 
Changing "MULTI" to a set language tracker by tracker doesn't allow this, and also hinders other forms of download: if I ask for something to be downloaded in english (which would mean I'm ok with a MULTI release since hey, english is in there anyway), but the indexer with the best quality available has MULTI set up to be changed to french, then that better release would be ignored. Not great.

More user tuning is always good IMO.

**Comment by markus101** [comment] 2021-02-04 15:32
For the purposes of multi, this is a dupe of https://github.com/Sonarr/Sonarr/issues/2854

You can use preferred words now to prefer specific keywords.

**Closed by markus101** 2021-02-04 15:32 UTC

**Comment by ComteNiark** [comment] 2021-02-04 15:47
> For the purposes of multi, this is a dupe of #2854
> 
> You can use preferred words now to prefer specific keywords.

This other issue doesn't adress the language detection issue for anime (VOSTFR (frenchsub) is treated as english to give an example), which was my main concern. Being able to make multi-language profiles was just a side effect of my proposed solution.
With the current setup, even if I were to add "VOSTFR" as a preferred word, it would never be picked up when I set the language to french, because these releases are flagged as english, which excludes them from being grabbed in the first place.
One way to somewhat get around this is to add VOSTFR as a preferred word and then select english, but then it would apply to all english language releases, even the ones I actually want english subtitles for instead of french ones, and picking english to get french is far from user-friendly IMO.

This is a personal thing but I watch all of my anime eng-subbed, but most of my users can't read english. Best case scenario would be to find a multi-sub release, which I of course already have keywords set up for, but in cases where I'm downloading something for someone else, I should just be able to select french as a language and it'll download the VOSTFR version, and, with my suggestion, I would even be able to pick a MULTI language profile to make sure that I get both english AND french subs, or just don't download it, in case I'm downloading something for both my users and myself.

**Comment by bakerboy448** [comment] 2021-02-04 15:54
for VOSTFR see https://github.com/Sonarr/Sonarr/issues/3977

**Comment by markus101** [comment] 2021-02-04 15:57
> One way to somewhat get around this is to add VOSTFR as a preferred word and then select english, but then it would apply to all english language releases

You can use tags to avoid that. Prefer VOSTFR with a tag, tag everything you want to apply it to, alternatively your prefer VOSTFR for everything, then with a profile tagged for anime you give VOSTFR the inverse score, which should 0 it out.

**Comment by ComteNiark** [comment] 2021-02-04 16:12
> > One way to somewhat get around this is to add VOSTFR as a preferred word and then select english, but then it would apply to all english language releases
> 
> You can use tags to avoid that. Prefer VOSTFR with a tag, tag everything you want to apply it to, alternatively your prefer VOSTFR for everything, then with a profile tagged for anime you give VOSTFR the inverse score, which should 0 it out.

I guess that would work, yes, but it means having to add the tag to every show I need. Not as easy as having the language profile set-up, and I'd still have to set up the language as english to get french releases. So it works, but it's counter intuitive and not very user-friendly, I would say.

I have to ask though, in the thread bakerboy488 linked, you said this:
> >Readd VOSTFR in French language parsing.

>This is not going to happen.
Why? Because then we could simply add a -1 to "VOSTFR" and choose french language. This would grab french audio releases first, and then VOSTFR if none around found.
The other poster also went into the idea of a custom "French subs" language, which I guess is nearly what I'm asking for, except that I'd rather have arbitrary language profiles setup by the user, that way if some group decides to mark their releases differently or some other weird edge case, no problem, nothing is baked in, you can just add that to the list and have it be identified as that language.

Is the language profiles part of sonarr messy to modify? Because this is the only part that has very little customization in my experience. If it's just a matter of not wanting users to mess it up for themselves, maybe you could make it an option you have to toggle outside of the GUI so that only people who know what they're doing can touch the hardcoded language detection settings? Just throwing ideas at the wall here.

**Comment by bakerboy448** [comment] 2021-02-04 16:14
VOSTFR  Does not mean French Audio so there is no rational reason to assume it is French language 

iVOSTFR stands for Version Originale Sous-Titrée en FRançais, meaning that it is the original version of a film with subtitles in French superimposed onto the screen.

**Comment by ComteNiark** [comment] 2021-02-04 16:32
Yes, but when a user selects french language, they would rather get a french subtitled show than no show. Context and intent behind the action matters. When no french audio version exists, to the foreign audience, the french subtitled version is the de-facto french version until a year later when a company comes around and maybe dubs it. But then VOSTFR would need to be rated lower than TRUEFRENCH (audio), which gets us back to my suggestion of weighted keyword for language profiles.

Unless you want to include separate "subtitle profiles", but that's probably much harder to implement on a global scale with all the different naming conventions. Letting users manage their own language settings passes the bulk of that work onto the user and gives them more power in how they use sonarr, which I'd say is a good thing?

I'm no dev so I don't know how long something like this would take to implement, but from a user experience perspective, this is how I'd like it to work, instead of having to fiddle around with using a different language and a tag, which I need to remember to put on. Use basically the same interface as for preferred words, but for language profiles.

**Comment by ComteNiark** [comment] 2021-02-04 20:07
Sorry for double post, but another idea I had is to simply allow the current keyword system to apply only to a specific language profile, just how you can currently set a set of keywords to only apply to a specific indexer. This way, one can simply hack around the restrictions by making a "French" profile that really searches for english releases, but with the keyword VOSTFR. Best of both worlds.

**Comment by bakerboy448** [comment] 2021-02-04 20:15
Markus already said how to make that work with tags.

There's no action to be taken here nor action to be taken.

**Comment by ComteNiark** [comment] 2021-02-04 21:02
Yes, in the end this comes down to a UI/UX change, because you can make it work with tags, it would just be an improvement in usability to have it work through language profiles.
