### ISSUE TITLE
Select indexer per series

### ISSUE THREAD

**Issue by guytpetj** [Sonarr/Sonarr#557] opened 2015-05-23 15:49 UTC
Add option to select which indexer(s) you want to use for each series. Like a selection list where you can select/deselect the indexer in the Edit Series menu.

**Comment by markus101** [comment] 2015-05-24 04:40
Duplicate of: https://github.com/Sonarr/Sonarr/issues/487

**Closed by markus101** 2015-05-24 04:40 UTC
