### ISSUE TITLE
Stop writing "Check For Finished Download" task to database.

### ISSUE THREAD

**Issue by Dr0bac** [Sonarr/Sonarr#3718] opened 2020-04-29 00:11 UTC
**Describe the problem**
Raspberry pi is very popular device for using it as media center server. And naturally many people are installing sonarr and radarr on it. Raspberry pi system is installed on micro sd card, and micro sd cards have a short life span if something is writing to it frequently.

Does some tasks like "Check For Finished Download" are needed to be written to database file every minute?

writes to sonarr database in 10 minutes:

````
23:05:42.065747 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.066404 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.066544 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.066734 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.359191 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.359399 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.404086 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.404281 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.404348 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.467865 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:05:42.468053 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:07:12.384468 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.384939 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.385165 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.385420 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.688214 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.688525 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.692312 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.692778 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.693054 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.693365 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.708290 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.708581 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.723254 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.723559 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.735386 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.735806 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.742015 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.742220 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.752174 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:07:12.752371 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:08:42.733374 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:42.733843 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:42.734071 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:42.734333 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.041188 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.041501 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.092392 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.092604 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.125221 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:08:43.125415 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:10:13.054877 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.055084 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.361366 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.361850 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.413255 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.413454 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.413523 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.423698 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:10:13.423895 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:11:43.389645 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.390122 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.390427 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.390732 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.684761 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.684962 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.728957 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.729164 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.811696 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:11:43.811897 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:12:13.697951 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:13.698240 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:13.698358 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:13.698540 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:13.987159 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:13.987367 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:14.000660 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:14.000866 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:14.010520 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:14.010723 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:12:44.003926 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.004245 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.310003 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.310320 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.362038 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.362245 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.371411 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:12:44.371614 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal

23:14:14.332092 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.332597 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.332923 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.333258 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.632160 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.632486 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.683190 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.683493 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.683637 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.683873 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.684120 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.684289 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.684507 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.684765 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.707341 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
23:14:14.707648 mono(2620): W /mnt/plex_media/dietpi_userdata/sonarr/nzbdrone.db-wal
````

**Comment by markus101** [comment] 2020-04-29 00:13
Dupe of https://github.com/Sonarr/Sonarr/issues/2373

**Closed by markus101** 2020-04-29 00:13 UTC

**Comment by Dr0bac** [comment] 2020-04-29 00:25
@markus101 these issues are not similar, my issue is about preserving micro sd card life with minimizing writes to it. That issue is about constant disk access. Access can mean read and write.

**Comment by markus101** [comment] 2020-04-29 01:24
Sure, but the writing every minute is covered in there too, we don’t need a separate issue to track that part of it.
