### ISSUE TITLE
HDBits manual search broken

### ISSUE THREAD

**Issue by emilsvennesson** [Sonarr/Sonarr#1656] opened 2017-02-02 21:18 UTC
No episodes/season packs are getting listed when using the manual search for HDBits. It works just fine when snatching episodes automatically, but it'd be nice to be able to select release with the manual search.

**Comment by markus101** [comment] 2017-02-02 21:20
Dupe of https://github.com/Sonarr/Sonarr/issues/266

**Closed by markus101** 2017-02-02 21:20 UTC

**Comment by emilsvennesson** [comment] 2017-02-02 21:22
@markus101 I'm not sure this is a dupe. I actually meant the manual search for individual episodes as well.

**Comment by markus101** [comment] 2017-02-02 21:23
Season packs aren't intended to show up there, BTN season packs do due to their removal rules (but that would be removed when manual search for seasons is added).

**Comment by emilsvennesson** [comment] 2017-02-02 21:28
@markus101 Ah, that explains it. Thanks a lot and keep up the good work! :-)
