### ISSUE TITLE
Sonarr V3 deletes images and subtitles

### ISSUE THREAD

**Issue by antegs** [Sonarr/Sonarr#3846] opened 2020-07-02 07:22 UTC
**Describe the bug**
Running Sonarr in docker with preview tag.  When the automatic update for a series runs, it deletes (moves to recycle folder) all images and subtitle files for that series, then marks the files as not there in the UI.  It does not delete the video files.  Manually clicking "Refresh and Scan" finds the video files without problem.  The paths in the log file have been double checked and they are correct.  When this happens, it is usually one or two old series per DB update.  Then another day might be another series, and so on.  This started with an update around one or two months ago.  It affects all series including old ones for which I never had that problem before.

**Logs**
This is the debug log for a single series.
https://pastebin.com/Uc6jYu7T

**System Information**
 - Sonarr Version: 3.0.3.896
 - Operating System: docker
 - mono (macOS/Linux) Version: 5.20.1.34

**Comment by Taloth** [comment] 2020-07-02 18:35
What OS and underlying filesystem?

**Comment by antegs** [comment] 2020-07-03 07:18
The filesystem is ext4 on an Ubuntu 20.04 LTS.  Docker version 19.03.8.

**Comment by antegs** [comment] 2020-07-04 08:26
Happened again today so 2 days (4 task executions) since last occurrence.  This time a different series which had no new files and been fine for a very long time was seemingly arbitrarily chosen during the "Refresh Series" task and all its files except video were moved to the recycle bin.  All other series, including the one from 2 days ago, were fine.
partial debug log: https://pastebin.com/tiuEpvN7

When the "Refresh Series" task run again after 12 hours, the series was found again and all video files were added to Sonarr.
partial debug log: https://pastebin.com/3TfdaaRn

**Comment by Taloth** [comment] 2020-07-04 15:15
It really does sound like a disk issue. you should probably check dmesg and syslog.

**Comment by antegs** [comment] 2020-07-05 12:14
Good suggestion. Preliminary check shows no problems but I'll monitor it for a while to make sure that's not it.

**Comment by antegs** [comment] 2020-07-09 12:59
I think I have narrowed it down.  Reverting back to version 3.0.3.807 stops this bug from happening 100% of the times the "Refresh Series" task runs.  The next version 3.0.3.809 starts having the problem once again.  Just looking at the dates published, the non working version appears to be May 14, and it's most pertinent commit d3a2245. I think it is the changes on file DiskScanService.cs since it is directly related to this error.  

https://github.com/Sonarr/Sonarr/commit/d3a22459ac6876a6d7966e25ac0069fbd24d72cb#diff-a2cb1baf6f8ea1fcf6b01729c67a181d

Looking at the changes themselves, it does not look like anything is actually changed in the section which gives the error (old line 88, new line 93).  But I believe it is the substitution further up (old 79, new 74) that is the culprit.  Filesystems mounted as volumes on docker containers need a little more time to access external resources.  By removing the "_diskProvider.GetDirectories" call, the loop becomes faster (good) but the filesystem sometimes doesn't have enough time to get a proper response from the next "_diskProvider.FolderExists(series.Path)" call so it returns false.  Maybe adding a safeguard check inside the two "if (!seriesFolderExists)" blocks would work to prevent this from happening.

**Comment by Taloth** [comment] 2020-07-09 19:29
> Filesystems mounted as volumes on docker containers need a little more time to access external resources.

That should just lead to a delay in the IO, not invalid info. FolderExists is blocking.
It's not like 'hey I saw a FolderExists call, let's return false and then try work out a real response next time I might get that call'.

When sonarr starts up there is a significant amount of time before any of those disk scans happen, so the volume should be mounted just fine.

> access external resources

You said that the underlying fs was ext4. Is it a local disk or usb/external/network storage? What's the complete story here?

**Comment by antegs** [comment] 2020-07-10 01:57
Should have been more clear.  The media is mounted on the box as an smb share and provided to the sonarr docker instance through a volume.

It looks like FolderExists calls System.IO.Directory.Exists which according to the docs will return false in various cases.
From https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.exists?view=netcore-3.1
> The Exists method returns false if any error occurs while trying to determine if the specified file exists. This can occur in situations that raise exceptions such as passing a file name with invalid characters or too many characters, a failing or missing disk, or if the caller does not have permission to read the file.

I think the smb connection chokes on the number of fast requests and Directory.Exists returns false when that happens. Anyway, this is just a hypothesis.  Do you see anything else in that commit that might cause this problem to start happening?

**Comment by Taloth** [comment] 2020-07-10 08:41
> The media is mounted on the box as an smb share and provided to the sonarr docker instance through a volume.

So smb, not ext4 :) I asked that for a reason, coz the behavior of local disks is so totally different than network shares.

> I think the smb connection chokes on the number of fast requests and Directory.Exists returns false when that happens.

It'd choke in many other situations then, causing failing transfers, partial transfers etc.

There is a tiny sliver of time (microseconds) where DirectoryExists(seriesFolder) can fail, and the subsequent DirectoryExists(rootFolder) can succeed. But only if the mount itself is failing.

What are the actual mount points of the smb share?

**Comment by antegs** [comment] 2020-07-10 12:12
> It'd choke in many other situations then, causing failing transfers, partial transfers etc.

Good point, but it could be that the implementation of the System.IO.Directory.Exists specifically is less strict and gives up too easily, compared with transfers or other disk functions.  I traced it down to this call of Stat but the ramifications are not clear right away.  https://source.dot.net/#System.IO.FileSystem/Interop.Stat.Span.cs,40ed17d2f4ecd5e3

It's pretty standard stuff. smb share with media is mounted on ```/home/user/mnt``` then passed in to docker with something like ```-v /home/user/mnt:/library```.

**Comment by Taloth** [comment] 2020-07-10 15:53
>  but it could be that the implementation of the System.IO.Directory.Exists specifically is less strict and gives up too easily,

Respectfully, that's just conjecture.

smb shares are never 'standard' :). Are those the exact mounts on the host? Your logs indicate /usenet-library/tv so /usenet-library volume is exactly /home/((user))/mnt or something else?
The reason i'm asking this is because I need to know exactly what is a subdirectory of the samba share and how it appears in the container. Details are important here. Like is `tv` the share, or is usenet-library the share.
What mount options does the smb share have?

You should check higher up in those log files, to see if and when it accessed the mount prior to the failure.

PS: You're checking the wrong source code. That's dot net core, you're running mono 5.20

**Comment by antegs** [comment] 2020-07-12 04:49
I understand.  Well, seeing as nobody else is chiming in this must me a problem with my setup.  I'll stick to the working version for now so feel free to close this issue.  Thank you so much for your help.

**Comment by Dnkhatri** [comment] 2020-07-12 05:48
> I understand.  Well, seeing as nobody else is chiming in this must me a problem with my setup.  I'll stick to the working version for now so feel free to close this issue.  Thank you so much for your help.

As you are using Linux I would recommend moving to nfs instead of smb. I personally had a lot of problems over the years with smb Linux and Kodi. After moving to nfs solved it for me haven't had a problem in the few years since I moved to nfs.

**Comment by Taloth** [comment] 2020-07-12 19:34
> I'll stick to the working version for now so feel free to close this issue.

That's not fixing anything. I did ask a few questions that you should try to answer. If you don't have time right now that's fine, but using an old version is not a fix.

**Comment by markus101** [comment] 2020-08-06 23:07
Closing, but we can re-open if there is anything actionable later on.

**Comment by tasilo** [comment] 2020-08-14 10:53
Thank you for pointing me here, markus101. Missed this issue during my preliminary search.
And thanks to @antegs for already doing a lot of the heavy lifting.
As described in #3911 my setup is quite similar to yours.

So far (only tested for 12h) 3.0.3.807 indeed seems to be without this issue.
But I also agree with Taloth that we should further investigate to get this properly fixed.

I'll quote from my other post and provide some additional details regarding the mount.

> Running the most recent linuxserver/sonarr:preview docker (package version: 3.0.3.907-ls37, mono version: 5.20.1.34) on an Ubuntu 20.04 LTS host (latest patch level).
> 
> The media in question is a cifs mount on the docker host (served by a VM on the same physical machine and virtual network) and bind-mounted into the container. It is never not available when the container is running.

The cifs share is mounted via fstab using the following mount options:
`noserverino,vers=3.0,cache=none,_netdev,uid=1000,gid=1000
` 

The container bind mount _/TV_ points to a sub directory of the Samba share, e.g.: _/media/cifsmount/videos/tv_ where /media/cifsmount would be the actual mount point defined in the docker host's fstab.

I previously ran and logged a looped stat from within the container to see if the network mount ever becomes unavailable.
Was not able to turn anything up. But the method seems useless if we are talking about a few milliseconds.
A lot of other tools and clients are regularly reading/writing/syncing from/to this share and I have not had any similar issues.
Kernel buffer of client and host do not show anything suspicious.

I guess my next step would be to crank up Samba's server side log level to debug and see if I can co-relate anything interesting with when the issue occurs within the Sonarr container.
Any other ideas?


Regards,
tasilo

**Comment by BodingClockchian** [comment] 2020-10-05 12:17
Im having the same issue

Sonarr version: 3.0.3.938-ls48 by linuxserver.io
Mono version: 5.20.1.34
Ubuntu 18.04.5 LTS 
Docker version: 19.03.13
SMBv1 CIFS network mount

None of the other 'services' has this problem.

Log
`20-10-5 14:08:04.5|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /tv/Raised_by_Wolves_(2020)/Season 01/Raised by Wolves (2020) - S01E01 - Raised by Wolves WEBDL-1080p.nl.srt
20-10-5 14:08:04.6|Error|EventAggregator|SubtitleFileService failed while processing [EpisodeFileDeletedEvent]

[v3.0.3.938] System.IO.IOException: Win32 IO returned 997. Path: /tv/Raised_by_Wolves_(2020)/Season 01/Raised by Wolves (2020) - S01E01 - Raised by Wolves WEBDL-1080p.nl.srt
  at System.IO.File.GetAttributes (System.String path) [0x00018] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.RemoveReadOnly (System.String path) [0x00008] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:360 
  at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile (System.String path) [0x0005c] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:197 
  at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFile (System.String path, System.String subfolder) [0x00054] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:86 
  at NzbDrone.Core.Extras.Files.ExtraFileService`1[TExtraFile].Handle (NzbDrone.Core.MediaFiles.Events.EpisodeFileDeletedEvent message) [0x000a9] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Extras\Files\ExtraFileService.cs:125 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (TEvent event) [0x0011a] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:92 

20-10-5 14:08:04.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /tv/Raised_by_Wolves_(2020)/Season 01/Raised by Wolves (2020) - S01E01 - Raised by Wolves WEBDL-1080p.nfo
20-10-5 14:08:05.1|Info|DiskScanService|Completed scanning disk for The Walking Dead: World Beyond
20-10-5 14:08:05.5|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-10-5 14:08:05.5|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-10-5 14:08:05.6|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-10-5 14:08:05.6|Info|ExistingExtraFileService|Found 0 extra files
20-10-5 14:08:05.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /tv/Raised_by_Wolves_(2020)/Season 01/Raised by Wolves (2020) - S01E05 - Infected Memory WEBDL-1080p.nl.srt
20-10-5 14:08:05.8|Info|RefreshSeriesService|Updating Westworld
20-10-5 14:08:05.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /tv/Raised_by_Wolves_(2020)/Season 01/Raised by Wolves (2020) - S01E05 - Infected Memory WEBDL-1080p.nfo`

**Comment by h45rd** [comment] 2021-03-08 09:38
My similar setup has been giving me the same issues as well.
Lacked the time for real debugging last year and cowardly :) version pinned to v3.0.3.807 (thanks to @antegs for narrowing the issue down) after losing some files and identifying the offender.
Got some time on my hands now and would like to help debug this before v3 goes to release.

Some details about my setup:
- System: `Linux host (Kernel 5.4.0-66) -> dockerd (20.10.3) -> Sonarr container (linuxserver/sonarr:preview)`
- Storage: `Server (smb 4.9.5) -> Linux host (fstab cifs vfs mount) -> dockerd (bind mound) -> Sonarr container`
- Mount options: `noserverino,cache=none,_netdev`
- Mount flags with system defaults: `rw,relatime,vers=3.11,cache=none,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,_netdev`
- Docker mount: `--mount type=bind,source=/net/mount,target=/media`

This setup works flawlessly with Sonarr v3.0.3.807 (Mono 5.20.1.34) and below.
Any later version (did not re-verify for some months now; will do so with the latest develop tag shortly) shows the behavior described in this issue.

Storage server and disks run 24/7 and are always accessible from the docker host and within the Sonarr container.
Verified this by running a continuous, throttled write loop to the share for a couple of days (during which the Sonarr bug reared it's head twice) without a hitch.


My next approach would be to spin up two VMs and try to reproduce this issue with vanilla installations.
Or do you have any more specific advice on where to start debugging this?

**Comment by markus101** [comment] 2023-02-13 06:41
With the change to dotnet in v4, I'm going to close this, if this or something similar is reproducible in v4 it'd be best to open a new issue.

**Closed by markus101** 2023-02-13 06:41 UTC
Labels: bug, platform: linux
