### ISSUE TITLE
Auto Unrar/Unzip Rarred or zipped files

### ISSUE THREAD

**Issue by RikT** [Sonarr/Sonarr#2586] opened 2018-05-24 07:41 UTC
As I see it most torrent clients do not have this feature or require buggy 3rd party scripts which are hit or miss.

I think that adding this feature would greatly enhance the user experience

**Comment by markus101** [comment] 2018-05-24 13:32
Please search before posting issues.

Dupe of https://github.com/Sonarr/Sonarr/issues/784

**Closed by markus101** 2018-05-24 13:32 UTC
