### ISSUE TITLE
Separate log database configuration

### ISSUE THREAD

**Issue by Nicba1010** [Sonarr/Sonarr#6771] opened 2024-04-30 21:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The main issue I have is that I cannot set up the docker containers to use a postgres database purely from running docker compose up. I need to enter the postgres database container and add a new log database.

### Describe the solution you'd like

If possible I'd like to be able to specify separate logins and hosts for the log and main databases. With the new environment variable controlled config.xml this would greatly simplify deployment in case you don't want to shut off the log database.

### Describe alternatives you've considered

The alternative is creating a separate entrypoint script but I can't do this just from docker compose.

**Comment by thezoggy** [comment] 2024-04-30 21:35
dupe of https://github.com/Sonarr/Sonarr/issues/6743 ?

**Comment by sillock1** [comment] 2024-04-30 22:07
No, this issue is asking for separate connection strings rather than disabling the log database

**Comment by Nicba1010** [comment] 2024-04-30 22:15
Yeah I'd rather not have to disable the logging database 😅. I know in an ideal world I'd be able to create both databases on the same container with the postgres dockerfile but unfortunately not :(.

**Comment by markus101** [comment] 2024-04-30 23:13
You can, but it requires an additional script, https://dev.to/bgord/multiple-postgres-databases-in-a-single-docker-container-417l has some information.

No plans at this time to have separate connections for main and log databases.

**Closed by markus101** 2024-04-30 23:13 UTC
Labels: needs-triage

**Comment by thezak48** [comment] 2024-05-01 02:13
From the wiki

> Create the databases mentioned above using your favourite method - for example [pgAdmin](https://www.pgadmin.org/) or [Adminer](https://www.adminer.org/).

**Comment by Nicba1010** [comment] 2024-05-01 05:41
I realize I can use pgAdmin or adminer, or I can just 
```bash
docker exec -it postgres psql -U postgres -c "CREATE DATABASE log;"
```
even easier. I was trying to maximally avoid anything other than the compose file. Anyways ok. So I also guess a PR for that wouldn't be acceptable right @markus101?
