### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JaiMistry** [Sonarr/Sonarr#4441] opened 2021-04-13 21:03 UTC
**Describe the bug**
While trying to do an interactive search of the show Re:ZERO -Starting Life in Another World- for season 2 episode 14, I ran into this error: 
`Episode search failed: Object reference not set to an instance of an object. Try refreshing the series info and verify the necessary information is present before searching again`

**To Reproduce**
1. Add the show Re:ZERO -Starting Life in Another World-
2. Click on interactive search for Season 2 Episode 14
3. See error

**Expected behavior**
Should display search results for the selected episode.

**Screenshots**
![bugs](https://user-images.githubusercontent.com/33847544/114618850-b3109780-9c5e-11eb-9f34-6a838577e54e.jpg)

**Platform Information (please complete the following information):**
 - OS: OpenMediaVault v5.6.2-1 (Usul)
 - Docker: Yes
 - mono (macOS/Linux) (System -> Status): 5.20.1.34
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6306708/sonarr.trace.txt)

**Comment by bakerboy448** [comment] 2021-04-13 21:07
Dupe and Fixed in Nightly
Dupe of #4414

**Closed by bakerboy448** 2021-04-13 21:07 UTC
