### ISSUE TITLE
Can't add items to Download Client when searching manually.

### ISSUE THREAD

**Issue by tdeverx** [Sonarr/Sonarr#4457] opened 2021-04-22 15:19 UTC
**Describe the bug**
When adding an item to the download client via manual search, I'm given the error "Invalid Perimeter". This error doesn't occur when searching for episodes automatically, only when adding manually. I've went through the trace logs and pulled out what I believe is the error, I hope this helps.

**To Reproduce**
1. Manually search for something.
2. Use button to add item to download client.
3. Receive error.

**Expected behavior**
Add item to download client for download.

**Screenshots**
<img width="1080" alt="Screenshot 2021-04-22 at 16 12 26" src="https://user-images.githubusercontent.com/44447832/115739110-8ad31800-a385-11eb-994e-62f2c9e3cebe.png">

**Platform Information (please complete the following information):**
 - OS: Mac OS Big Sur / DSM 7.0-41222
 - Platform: Desktop / NAS
 - Device: MacBook Pro / Synology DS918+
 - Docker: Yes
 - Mono: 6.12.0.122
 - Browser: Safari
 - Sonarr Version: 3.0.6.1209
 - Sonarr Branch: develop

**Trace Logs**
I tried to narrow them down to the error, but I've attached the file below.

10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15)
21-4-22 16:01:11.7|Trace|HttpClient|Req: [GET] http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros)
21-4-22 16:01:11.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:12.0|Trace|HttpClient|Res: [GET] http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros): 200.OK (273 ms)
21-4-22 16:01:12.0|Debug|TorrentDownloadStation|Downloading torrent for episode 'The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros)' finished (9063 bytes from http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros))
21-4-22 16:01:12.0|Trace|HttpClient|Req: [GET] http://192.168.0.16:5000/webapi/entry.cgi?_sid=mP_wyzoTY2J0REV2zjzKxVDAjNL9O6U0Czk10_Of1OYy5zBHtbi34GZG2MROaO6cj-E6XueuwHG8axffgWKlBA&api=(removed)&version=2&method=getinfo
21-4-22 16:01:12.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:12.3|Trace|HttpClient|Res: [GET] http://192.168.0.16:5000/webapi/entry.cgi?_sid=mP_wyzoTY2J0REV2zjzKxVDAjNL9O6U0Czk10_Of1OYy5zBHtbi34GZG2MROaO6cj-E6XueuwHG8axffgWKlBA&api=(removed)&version=2&method=getinfo: 200.OK (237 ms)
21-4-22 16:01:12.3|Trace|HttpClient|Response content (237 bytes): {"data":{"codepage":"enu","model":"DS918+","ram":8192,"serial":"19C0PDN011315","temperature":40,"temperature_warn":false,"time":"Thu Apr 22 16:01:12 2021","uptime":78261,"version":"41222","version_string":"DSM 7.0-41222"},"success":true}
21-4-22 16:01:12.3|Debug|DSMInfoProxy|Trying to get serial number
21-4-22 16:01:12.3|Trace|HttpClient|Req: [POST] http://192.168.0.16:5000/webapi/DownloadStation/task.cgi: 
_sid=mP_wyzoTY2J0REV2zjzKxVDAjNL9O6U0Czk10_Of1OYy5zBHtbi34GZG2MROaO6cj-E6XueuwHG8axffgWKlBA
api=SYNO.DownloadStation.Task
version=2
method=create
destination=media/Downloads/Sonarr
file=The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent (9063 bytes)
21-4-22 16:01:12.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:12.3|Trace|HttpClient|Res: [POST] http://192.168.0.16:5000/webapi/DownloadStation/task.cgi: 200.OK (37 ms)
21-4-22 16:01:12.3|Trace|HttpClient|Response content (39 bytes): {"error":{"code":101},"success":false}

21-4-22 16:01:12.3|Debug|DownloadStationTaskProxy|Trying to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent
21-4-22 16:01:12.3|Error|DownloadStationTaskProxy|Failed to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent. Reason: Invalid parameter
21-4-22 16:01:12.3|Trace|SonarrErrorPipeline|Handling Exception
21-4-22 16:01:12.3|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/release

[v3.0.6.1209] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent. Reason: Invalid parameter
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000e8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:125 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:66 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.AddTaskFromData (System.Byte[] data, System.String filename, System.String downloadDirectory, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00038] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:36 
  at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String hash, System.String filename, System.Byte[] fileContent) [0x0001f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:177 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00230] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:190 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00148] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:117 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x0018f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:75 
  at Sonarr.Api.V3.Indexers.ReleaseModule.DownloadRelease (Sonarr.Api.V3.Indexers.ReleaseResource release) [0x001a7] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:129 
  at Sonarr.Api.V3.Indexers.ReleaseModule.<.ctor>b__10_2 (System.Object x) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:65 
  at Nancy.NancyModule+<>c__DisplayClass38_0`1[T].<Post>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyModule+<>c__DisplayClass40_0`1[T].<Post>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 

21-4-22 16:01:12.4|Trace|Http|Res: 69 [POST] /api/v3/release: 500.InternalServerError (657 ms)
21-4-22 16:01:12.4|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (657 ms)
21-4-22 16:01:18.7|Trace|Http|Req: 70 [POST] /api/v3/release (from 172.17.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15)
21-4-22 16:01:18.7|Trace|HttpClient|Req: [GET] http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros)
21-4-22 16:01:18.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:18.9|Trace|HttpClient|Res: [GET] http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros): 200.OK (185 ms)
21-4-22 16:01:18.9|Debug|TorrentDownloadStation|Downloading torrent for episode 'The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros)' finished (9063 bytes from http://192.168.0.16:10440/dl/torrentleech/?jackett_apikey=(removed)&path=Q2ZESjhEbDdyalB0MThSTGxGWVlSTEROMl9neTZZN254ajBNVlNYWWxURkQzTGc2ckhsX2tWTWh3bVpiby0yeHByZFZEZjIyeVRzalJlLXZOMmhpcFRfV2ZlY2tfVlQ1cXFXZGdxeDZONlFSYW9NdzRvcWQ1TDc4aF9DbWxoeTN6bGk1dk9sZHFmTW5xZXRRMmR1RU1nWGxWZl9zckdFYUw2VzhlM3FMYm4wUFZfQUdsOFBfRTB4MGlvZWtkQ1F4Z3BPLV9yZnBycFV5bjR5cEdudXE3aG1kNWktNzdDb3Z0NjFjb1ZnWVpCRkVobFRGUEU3eTUxWmxUTDl1VVU3em5TV0lGV2l1RzdvNXd5Y0ExUERoYlNocTdBZUlVWFVlZkhwdm5TWU5VdnpEN1d2RjNnTXNHcFlkVW5tNm9IRHFtMVRWLWc&file=The+Falcon+and+The+Winter+Soldier+(2021)+S01E05+(1080p+DSNP+WEB-DL+x265+HEVC+10bit+Atmos+DDP+5+1+Vyndros))
21-4-22 16:01:18.9|Trace|HttpClient|Req: [POST] http://192.168.0.16:5000/webapi/DownloadStation/task.cgi: 
_sid=mP_wyzoTY2J0REV2zjzKxVDAjNL9O6U0Czk10_Of1OYy5zBHtbi34GZG2MROaO6cj-E6XueuwHG8axffgWKlBA
api=SYNO.DownloadStation.Task
version=2
method=create
destination=media/Downloads/Sonarr
file=The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent (9063 bytes)
21-4-22 16:01:18.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:19.0|Trace|HttpClient|Res: [POST] http://192.168.0.16:5000/webapi/DownloadStation/task.cgi: 200.OK (33 ms)
21-4-22 16:01:19.0|Trace|HttpClient|Response content (39 bytes): {"error":{"code":101},"success":false}

21-4-22 16:01:19.0|Debug|DownloadStationTaskProxy|Trying to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent
21-4-22 16:01:19.0|Error|DownloadStationTaskProxy|Failed to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent. Reason: Invalid parameter
21-4-22 16:01:19.0|Trace|SonarrErrorPipeline|Handling Exception
21-4-22 16:01:19.0|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/release

[v3.0.6.1209] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to add task from data The Falcon and The Winter Soldier (2021) S01E05 (1080p DSNP WEB-DL x265 HEVC 10bit Atmos DDP 5 1 Vyndros).torrent. Reason: Invalid parameter
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000e8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:125 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:66 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.AddTaskFromData (System.Byte[] data, System.String filename, System.String downloadDirectory, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00038] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:36 
  at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String hash, System.String filename, System.Byte[] fileContent) [0x0001f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:177 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00230] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:190 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00148] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:117 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x0018f] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:75 
  at Sonarr.Api.V3.Indexers.ReleaseModule.DownloadRelease (Sonarr.Api.V3.Indexers.ReleaseResource release) [0x001a7] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:129 
  at Sonarr.Api.V3.Indexers.ReleaseModule.<.ctor>b__10_2 (System.Object x) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:65 
  at Nancy.NancyModule+<>c__DisplayClass38_0`1[T].<Post>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyModule+<>c__DisplayClass40_0`1[T].<Post>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 

21-4-22 16:01:19.0|Trace|Http|Res: 70 [POST] /api/v3/release: 500.InternalServerError (316 ms)
21-4-22 16:01:19.0|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (316 ms)
21-4-22 16:01:25.4|Trace|Http|Req: 71 [GET] /api/v3/config/host (from 172.17.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15)
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
21-4-22 16:01:25.4|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
21-4-22 16:01:25.4|Trace|Http|Res: 71 [GET] /api/v3/config/host: 200.OK (17 ms)
21-4-22 16:01:25.4|Debug|Api|[GET] /api/v3/config/host: 200.OK (17 ms)
21-4-22 16:01:28.7|Trace|Scheduler|Pending Tasks: 1

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6359391/sonarr.trace.txt)

**Comment by bakerboy448** [comment] 2021-04-22 15:19
Duplicate of #4388

please search prior to posting

**Closed by bakerboy448** 2021-04-22 15:19 UTC

**Comment by tdeverx** [comment] 2021-04-22 15:22
> please search prior to posting

I'm glad its already been reported but I did search prior to posting. I searched for the keyword "Invalid Perimeter" which gave me no response, glad it's already on the list.
