### ISSUE TITLE
Download in serials folder

### ISSUE THREAD

**Issue by Leliil** [Sonarr/Sonarr#4660] opened 2021-09-23 15:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

transmission download the file in default download folder

### Describe the solution you'd like

download series in serials folder (do not used transmission default folder)

### Describe alternatives you've considered

automatic moving the files

### Anything else?

here it is implemented, very convenient
https://github.com/werwolfby/monitorrent/

**Comment by markus101** [comment] 2021-09-23 15:37
We do not have plans to support this functionality.

Dupe of #1141

**Closed by markus101** 2021-09-23 15:37 UTC
Labels: needs-triage
