### ISSUE TITLE
Shows translated through thexem not grabbed from Dronefactory Folder

### ISSUE THREAD

**Issue by Gerk** [Sonarr/Sonarr#935] opened 2015-11-13 13:47 UTC
Like the subject says, if a show needs to be "translated" through thexem once it has been downloaded and is sitting in the dronefatory folder Sonarr doesn't pick it up.  They have to be manually renamed to match thetvdb's naming scheme in order for them to be found and moved appropriately.

Two examples of this are Pawn Stars and American Pickers.  This has been an issue for some time now (not sure exactly how long) but I just kept forgetting to file a bug report on it.

Also they are not marked as found/downloaded and still show up in missing, so you can end up with many copies of the same shows sitting in the download area.

**Comment by markus101** [comment] 2015-11-13 16:30
This sounds like they weren't imported because the mapping is unverified, which is intentional. You can use manual import to import them, but ultimately thexem.de needs to be updated.

**Comment by Gerk** [comment] 2015-11-14 03:10
Hmm ok, this is disappointing as they seem to take some time before they are confirmed and Sonarr keeps downloading copies of them over and over again.  Maybe if they are unconfirmed Sonarr shouldn't try to download them until they are?  Having 8 different copies of the same show sitting in the Drone Factory folder doesn't seem like an optimal way to handle things here.

**Comment by markus101** [comment] 2015-11-14 03:18
Well the first thing to do would be to stop using drone factory, let Completed Download Handling import things, which will properly track the items in the download client and not download duplicates.

Unverified is done this way intentionally so releases are grabbed, but aren't imported to avoid the potential of deleting an existing episode. thexem.de itself is user contributed, so someone has to maintain it, the biggest issue is most people try to configure it wrong and the mods need to spend time confirming its wrong then time fixing it, which is a pain, but nothing is really going to change there (TheTVDB has the same issues, which is why seasons and entire series get locked).

Closing this out because its expected behaviour.

**Closed by markus101** 2015-11-14 03:18 UTC
