### ISSUE TITLE
Prioritisation of failed download re-grabs

### ISSUE THREAD

**Issue by lloydie11** [Sonarr/Sonarr#5983] opened 2023-08-29 21:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When a download fails due to the indexer or download client not having all the pieces needed, the next nzb tried is listed at the bottom of the download queue (sabnzbd)

### Describe the solution you'd like

It would be nice to have an option that can be enabled to override (set) the priority in sonarr of future grabs for failed downloads, so they are attempted within a reasonable timescale of the last failed one.

When big queues are mounted for downloads, I often prioritise downloads for what I'm currently watching and having failed join the back of queue requires intervention.

### Describe alternatives you've considered

I've consider writing a bash script to monitor fails, and set priority based by name, but this adds an additional complication to something that would be handy to have handled natively in sonarr.

**Comment by markus101** [comment] 2023-08-29 21:21
Duplicate of https://github.com/Sonarr/Sonarr/issues/2076

**Closed by markus101** 2023-08-29 21:21 UTC
Labels: needs-triage

**Comment by rabidpug** [comment] 2023-09-28 22:29
I wouldn't consider this a duplicate of #2076 as that issue was specifically for moving failed downloads re-grabs to the top of the download queue, which according to that issue is not possible with the download clients' API's. This issue is about configuring the **priority** like how it can be configured based on age currently.
