### ISSUE TITLE
Possibility to change the season type (Aired Order - DVD Order - etc)

### ISSUE THREAD

**Issue by LucDeGit** [Sonarr/Sonarr#6935] opened 2024-07-06 19:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I notice when i manage the tv show "The Office (us)" for example there is new episode with the Amazon release (S9 have originally 23 episodes and now 27) so i cant correctly manage the new episode 👎 

### Describe the solution you'd like

The solution can be that when we manage a tv show there is a possibilty to change the season base on the TVDB (and i notice they have new season order (see the screen))

![image](https://github.com/Sonarr/Sonarr/assets/71153939/4b8cfd9e-ae0b-4bde-8fc7-77196f5ba0b1)

### Describe alternatives you've considered

I dont find any solution for that

**Comment by markus101** [comment] 2024-07-06 19:51
> I have searched the existing open and closed issues

You actually didn't even need to search, https://github.com/Sonarr/Sonarr/issues/255 is the 4th item when sorted by the default of `Recently Updated`.

Duplicate of #255

**Closed by markus101** 2024-07-06 19:51 UTC
Labels: needs-triage

**Comment by LucDeGit** [comment] 2024-07-06 20:54
Sorry, but in my case how i can fix the issue with The Office ? I dont really understand the #255 section :/

**Comment by bakerboy448** [comment] 2024-07-07 12:05
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

You don't as it's not implemented yet and likely won't be in the near term given the complexity and work required
