### ISSUE TITLE
Series Posters Not Downloading

### ISSUE THREAD

**Issue by Rojikku** [Sonarr/Sonarr#5376] opened 2023-01-15 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I add the Anime, it adds a poster, but the wrong poster. Examples:
![image](https://user-images.githubusercontent.com/1676068/212557178-269fdb4d-f3e8-4d66-8ed3-d8c4955b4d00.png)
![image](https://user-images.githubusercontent.com/1676068/212557185-ba3d295e-c57a-47d7-9b98-96a270cbdae6.png)

I am somewhat mystified.

### Expected Behavior

Preferably, the poster would at least somewhat relate to the Anime at hand.

### Steps To Reproduce

Hopefully it reproduces easily in the base version, if not I'll try to find another reason. But this appears like some sort of bug.

Initial theory was that this effected 2023 Anime, but adding "Daily Life of the Immortal King" produced the same results.
Problem children:
Daily Life of the Immortal King
Reborn to Master the Blade: From Hero-King to Extraordinary Squire
The Iceblade Sorcerer Shall Rule the World
The Reincarnation of the Strongest Exorcist in Another World
The Magical Revolution of the Reincarnated Princess and the Genius Young Lady
Spy Classroom

Interestingly, The Vexations of a Shut-In Vampire Princess loaded with what appears to be a correct image.
The other images shown relate to images for other Anime I have.

The add screen shows the correct image:
![image](https://user-images.githubusercontent.com/1676068/212557391-997d917e-7175-4bdd-ab08-6d44e67de5eb.png)
After I add it, if I select it, the image is something completely different:
![image](https://user-images.githubusercontent.com/1676068/212557410-49219952-21d5-457c-9bbc-d3348e0b6504.png)

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 4.0.0.352
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chromium Version 109.0.5414.74
```

### What branch are you running?

Develop

### Trace Logs?
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10420941/sonarr.trace.txt)

### Anything else?

Screenshots attached above. Using someone else's auto-generated docker images, which I believe are based on Develop.
Regardless, issue is mystifying.
Deploy config:
https://github.com/Rojikku/home-ops/blob/main/cluster/apps/media/sonarr/helm-release.yaml

**Comment by markus101** [comment] 2023-01-15 18:03
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

First thing to do would be refresh the series in Sonarr.

**Comment by Rojikku** [comment] 2023-01-15 18:10
@markus101 

Thanks for your feedback.

Believe it or not, I did, in fact, hit "Refresh and scan" before spending 10 minutes making an issue to help point out a probable issue.
I also deleted and re-added the series, and took screenshots, and even did the event under trace logs and attached them to be helpful.
It's detailed in my issue.

Exactly what support do you want me to request? I've been using the program for years. I won't claim to be the most skilled at using, but I at least know the basic functionality.

**Comment by markus101** [comment] 2023-01-15 18:33
And before I replied I checked that v4 was showing the correct image for the correct series. 

![F046837C-52F1-460B-A28F-0B1397F28656](https://user-images.githubusercontent.com/413544/212559817-af8b21ec-fb02-45d6-b516-b4c371af3740.jpeg)

The issue is far more likely to be something that is not a bug and this is not the place to troubleshoot that. The support channels (especially Discord) have many people that can help troubleshoot.

Additionally, your trace logs appear to be HTML, not actual logs.

**Comment by Rojikku** [comment] 2023-01-15 18:34
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10420906/sonarr.trace.txt)
I apologize, I assumed when I hit download it gave me a raw text file, so I didn't copy and paste the data out, and instead I hit ctrl + s to save it.

The fact that you cannot reproduce the issue is useful information, thank you.

**Comment by markus101** [comment] 2023-01-15 18:58
I can’t reproduce on Windows, but I saw the messages on Discord about it, so looks like there is something going on that prevents some images from loading (doesn’t explain how the wrong image was loaded in your one example though). I was premature in closing it, but thanks for following up, reopening so we can resolve it.

```
2023-01-15 19:37:26.1|Error|MediaCoverService|Couldn't download media cover for [412957][Reborn to Master the Blade: From Hero-King to Extraordinary Squire]

[v4.0.0.352] System.NotSupportedException: The 'file' scheme is not supported.
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 109
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 62
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 255
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Series series, MediaCover cover) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 163
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Series series) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 121
```

**Comment by Rojikku** [comment] 2023-01-15 19:07
Thank you for looking into this!
In my last test of a re-add, it had no image, as the other people did.

For consolidation purposes:

I thought at one point it was taking images from other series, which would be a cache issue, but it's actually a subtly entirely different image, which is as far as I can tell unexplained.
See the image I thought it was stealing, which is actually different:
![image](https://user-images.githubusercontent.com/1676068/212561708-b1cfea5f-5257-40b6-8c70-ee4651d64f3c.png)

My trace log is from one of the wrong image instances, but the log indicates it failed to download.

```
2023-01-15 12:38:53.9|Error|MediaCoverService|Couldn't download media cover for [415378][The Reincarnation of the Strongest Exorcist in Another World]
...
[v4.0.0.352] System.NotSupportedException: The 'file' scheme is not supported.
2023-01-15 12:38:53.9|Debug|ImportDecisionMaker|Analyzing 2/2 files.
2023-01-15 12:38:53.9|Debug|MediaCoverService|Resizing Banner-70 for [415378][The Reincarnation of the Strongest Exorcist in Another World]
```
If I am reading this correctly, it failed to download, but then is resizing what it somehow downloaded?
Regardless, if it downloads the cover successfully, that shouldn't happen.

Please let me know if you need any further information on anything, I will do my best.

**Closed** 2023-01-16 05:21 UTC
Labels: bug

**Comment by Rojikku** [comment] 2023-01-16 18:26
Updated to `4.0.0.356`, and all my incorrect/missing covers appear to have updated to have correct covers.
