### ISSUE TITLE
Add "Set Release Group" input box to "Organize & Rename" section.

### ISSUE THREAD

**Issue by Maxtoid** [Sonarr/Sonarr#4321] opened 2021-02-11 23:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently, very few release groups get processed correctly by Sonarr due to poor and inconsistent media naming practices by various release groups. This results in users having to manually rename files and refresh in Sonarr to get media to properly show the release group.

**Describe the solution you'd like**
A simple and elegant solution would be to add an input text box to the Organize & Rename screen allowing users to enter a text element that would be used as the Release Group for that Organize & Rename session, overriding whatever is currently set if there is one, or adding one if not, as seen in this mockup:
![ReleaseGroupRenaming](https://user-images.githubusercontent.com/68936574/107712061-bb684880-6c96-11eb-83f6-46e561d2632f.png)

**Describe alternatives you've considered**
I'm not sure if the release group data for each episode is stored in the database or not, which is why I am primarily suggesting a simple way to modify the release group via the Organize & Rename screen, but if the release group data for each episode is stored in the database, it would be even more ideal to add the release group as a part of "Manage Episodes" section, where you could view and modify the release group at the season or show level as seen in this mockup:
![ModifyEpisodesMockup](https://user-images.githubusercontent.com/68936574/107712445-6d077980-6c97-11eb-8826-8f08bfa9d265.png)

**Additional context**
Radarr already has this feature, presumably because handling the release group metadata for a single movie is less complex than handling it for every episode of every show in Sonarr - Even if that metadata is not currently a part of the managed metadata for episodes, having the ability to manually set a release group during the Organize & Rename process would greatly reduce the amount of time many of us are spending fixing release group naming after Sonarr imports media.

**Comment by markus101** [comment] 2021-02-11 23:38
Dupe of https://github.com/Sonarr/Sonarr/issues/3237

**Closed by markus101** 2021-02-11 23:38 UTC

**Comment by Maxtoid** [comment] 2021-02-11 23:41
> Dupe of #3237

Actually I think this qualifies as enough of a different suggestion. The issue referenced was asking for release groups to be added to the Manage Episodes section; which requires quite a bit of change if the release groups are not currently stored in the database.

This feature request is for a much easier option, to add an edit text-box to the Organize & Rename section, which the other issue doesn't mention at all. Wouldn't this be an easier and more viable solution to track as a separate feature enhancement?

**Comment by markus101** [comment] 2021-02-11 23:44
They are in the DB (if Sonarr was able to parse it from the name when the file was imported). Just like you can't change the quality or language in the rename modal we're not going to support changing the release group there.
