### ISSUE TITLE
Make Scheduled tasks interval configurable

### ISSUE THREAD

**Issue by TheOneValen** [Sonarr/Sonarr#5377] opened 2023-01-15 18:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some tasks run much too often. Some I might want to run more often. This is fine-tuning for power users.

### Describe the solution you'd like

The interval for the tasks commands are currently hardcoded. I would like to have the interval configurable. It does not necessarily be in the UI, editing the xml would be fine for me.

### Describe alternatives you've considered

Configuration via xml.

**Comment by markus101** [comment] 2023-01-15 18:35
You’re not describing a problem, your describing a solution, but as we’ve said before we don’t have plans to make these configurable.

Dupe of https://github.com/Sonarr/Sonarr/issues/4325

**Closed by markus101** 2023-01-15 18:35 UTC
Labels: needs-triage
