### ISSUE TITLE
Failed download handling gives up after a few tries

### ISSUE THREAD

**Issue by ludwigbacklund** [Sonarr/Sonarr#3435] opened 2019-11-30 19:00 UTC
**Describe the bug**
When I ask Sonarr to download, for example, a season of a show and it fails on some episodes it will retry them a few times and then just give up even though there are candidates left to try. This is not one-off behavior, it happens consistently.

I've googled around and found other people also having this problem but no one have found any answers as to why it is happening. Is it possible to configure it somehow to retry ALL candidates of a particular episode regardless of how many it has to go through? Or is this a bug?

**Logs/Screenshots**

Four debug logs, from oldest to newest:

https://paste.ubuntu.com/p/5dv5zfgMpG/
https://paste.ubuntu.com/p/jHbMj5ZX7f/
https://paste.ubuntu.com/p/4JGjwCSqNR/
https://paste.ubuntu.com/p/YCXRQXVXPJ/

I don't expect you to read through all of them but I would suggest searching for S09E19, that is one of the episodes that stopped downloading after a while.

[Here is a list of viable candidates for S09E19](https://i.imgur.com/zsBWZ9d.png) that were not tried when they should have been.

Things I found in the logs: 
1. All episodes that were viable candidates but were *not* downloaded were parsed during the search and resulted in "Release accepted" but were *not* sent to the download client.
2. More than one hour after the initial search, Sonarr was still trying to download S09E19 and finding viable candidates resulting in "Release accepted" but still not sending them to the download client (see line 6136 in the last log for example).

I've been trying to find more patterns in the logs but it's a lot of stuff.

**System Information**
 - Sonarr Version: 3.0.3.658 dockerized (also happened in v2)
 - Operating System: Ubuntu 18.04
 - mono (macOS/Linux) Version: 5.20.1.34

Thanks!

**Comment by markus101** [comment] 2019-11-30 19:33
Dupe of https://github.com/Sonarr/Sonarr/issues/2973

**Closed by markus101** 2019-11-30 19:33 UTC

**Comment by ludwigbacklund** [comment] 2019-11-30 22:10
@markus101 Alright cool, then I'll +1 that.
