### ISSUE TITLE
Feature request: Navigation arrows for usability

### ISSUE THREAD

**Issue by RoChess** [Sonarr/Sonarr#2526] opened 2018-04-23 16:52 UTC
Simple usability feature request:

Would it be possible to add big giant < and > arrows off on the sides of a show details page that allow you to quickly jump to the next show? For mobile usage swiping would work.

Reasoning:

Wanting to quickly verify things on all newly added series I noticed that a usability feature is missing, and that is the ability to quickly navigate to the next series.

I was forced to open a show, adjust settings, go back to main overview and click on next show. The problem was that half way down the list it would often jump back to the top of the series overview so there was a lot of scrolling involved and going "darn it, where did I leave off again?".

**Comment by markus101** [comment] 2018-04-23 17:13
Dupe of https://github.com/Sonarr/Sonarr/issues/827

**Closed by markus101** 2018-04-23 17:13 UTC
