### ISSUE TITLE
Sonarr remove "the" in queries to indexers

### ISSUE THREAD

**Issue by ivandelabeldad** [Sonarr/Sonarr#2644] opened 2018-07-02 15:52 UTC
**Describe the bug**

If you have some series starting with **the**, like *The handmaid's tale*, or *The expanse*, what is sent to indexers is "handmaids tale" and "expanse", which is not the real name.

If one indexer works better without "the", is really easy to sanitize the query if the title is the real one.

On the other hand, if one indexer works better with "the", is way more complicated to determine the original title of the show in order to make it works (handmaids tale have not even apostrophe).

I think that **Sonarr should send the complete and real title to indexers**, and let them sanitize like they want. If one indexer doesn't support apostrophes, let them remove them.

**System Information**

 - Sonarr Version: 2.0.0.5228

**Comment by markus101** [comment] 2018-07-02 16:31
Partial dupe of https://github.com/Sonarr/Sonarr/issues/1225

Letting the indexer sanitize them isn't viable, because they're not doing always doing that. The biggest difference is usually anime, where apostrophes are left in whereas they aren't for standard series on _most_ indexers.

**Closed by markus101** 2018-07-02 16:31 UTC

**Comment by ivandelabeldad** [comment] 2018-07-02 17:23
If indexers are not doing that is not problem of Sonarr, is problem of the indexer. I don't understand that one application should do things that it shouldn't because other external applications do things wrong.

I wrote one indexer on Jackett, and fix other one to make it Sonarr compliant, and in my case I face the problem that Sonarr is "making up" titles that doesn't match the reality, so I cannot really know the real one.

Remove apostrophes or remove "the" from titles before send it to indexer is out of Sonarr scope.

**Comment by markus101** [comment] 2018-07-02 17:34
Title based searching is meant to be fuzzy, if you want to know exactly what series is being searched for ID based searching should be implemented.

Translating from the title Sonarr sends to a specific series isn't going to work for anything Sonarr alters before sending or for aliases.
