### ISSUE TITLE
DiskScanService "loses" directory -> extra files deleted

### ISSUE THREAD

**Issue by tasilo** [Sonarr/Sonarr#3911] opened 2020-08-12 18:47 UTC
Hi,

First off: Thank you for this great piece of software :)

I have Been losing "extra files" (nfos, subs, jpgs, etc.) from my TV archive lately and managed to track back to Sonarr as the culprit.
Running the most recent linuxserver/sonarr:preview docker (package version: **3.0.3.907-ls37**, mono version: **5.20.1.34**) on an Ubuntu 20.04 LTS host (latest patch level).

The media in question is a cifs mount on the docker host (served by a VM on the same physical machine and virtual network) and bind-mounted into the container. It is never not available when the container is running.

From the debug logs it seems that during a scheduled rescan Sonarr assesses that certain directories have become unavailable, consequently runs the MediaFileTableCleanupService and deletes the files I am missing now.
Sonarr is set to import the following "extra files": sub,idx,srt,nfo. Interestingly enough when the OtherExtraFileService is run, it also deletes e.g. JPG files. Even though Sonarr was never configured to handle those.
Was not able to debug how Sonarr comes to the conclusion that the folders in question have become unavailable in the first place. The mount is stat-able the whole way through and the affected directories are always available, proven by the fact that Sonarr deletes files from them only milliseconds after it reports them to be unavailable:

```
11:11:42.5|Info|RefreshSeriesService|Updating Dracula (2020)
11:11:42.6|Info|RefreshEpisodeService|Starting episode info refresh for: [361160][Dracula (2020)]
11:11:42.6|Debug|EpisodeAddedService|No new episodes, skipping search
11:11:42.6|Info|RefreshEpisodeService|Finished episode refresh for series: [361160][Dracula (2020)].
11:11:42.6|Debug|RefreshSeriesService|Finished series refresh for Dracula (2020)
11:11:42.6|Debug|XemService|Scene numbering is not available for Dracula (2020) [361160]
11:11:42.7|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
11:11:42.7|Info|DiskScanService|Scanning Dracula (2020)
11:11:42.7|Debug|DiskScanService|Series folder doesn't exist: /TV/Dracula.2020
11:11:42.7|Debug|DiskScanService|[361160][Dracula (2020)] Cleaning up media files in DB
11:11:42.7|Debug|MediaFileTableCleanupService|File [/TV/Dracula.2020/Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.mkv] no longer exists on disk, removing from db
11:11:42.7|Debug|EpisodeService|Detaching episode 28056 from file.
11:11:42.7|Debug|RecycleBinProvider|Attempting to send '/TV/Dracula.2020/Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.en.srt' to recycling bin
11:11:42.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /TV/Dracula.2020/Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.en.srt
11:11:42.7|Debug|RecycleBinProvider|File has been permanently deleted: /TV/Dracula.2020/Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.en.srt
11:11:42.7|Debug|SubtitleFileService|Deleting Extra from database for episode file: [80020] Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.mkv
11:11:42.7|Debug|OtherExtraFileService|Deleting Extra from database for episode file: [80020] Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.mkv
11:11:42.7|Debug|MetadataFileService|Deleting Extra from database for episode file: [80020] Dracula.(2020).S01E01.The.Rules.of.the.Beast.PROPER.REPACK.1080p.HDTV.h264.AC3.5.1-MTB.mkv
11:11:42.8|Debug|MediaFileTableCleanupService|File [/TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.mkv] no longer exists on disk, removing from db
11:11:42.8|Debug|EpisodeService|Detaching episode 28057 from file.
11:11:42.8|Debug|RecycleBinProvider|Attempting to send '/TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.en.srt' to recycling bin
11:11:42.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.en.srt
11:11:42.8|Debug|RecycleBinProvider|File has been permanently deleted: /TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.en.srt
11:11:42.8|Debug|SubtitleFileService|Deleting Extra from database for episode file: [80022] Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.mkv
11:11:42.8|Debug|RecycleBinProvider|Attempting to send '/TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.nfo' to recycling bin
11:11:42.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.nfo
11:11:42.8|Debug|RecycleBinProvider|File has been permanently deleted: /TV/Dracula.2020/Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.nfo
11:11:42.8|Debug|OtherExtraFileService|Deleting Extra from database for episode file: [80022] Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.mkv
11:11:42.8|Debug|MetadataFileService|Deleting Extra from database for episode file: [80022] Dracula.(2020).S01E02.Blood.Vessel.1080p.HDTV.h264.AAC.5.1-MTB.mkv
11:11:42.8|Debug|MediaFileTableCleanupService|File [/TV/Dracula.2020/Dracula.(2020).S01E03.The.Dark.Compass.1080p.HDTV.h264.AC3.5.1-BRISK.mkv] no longer exists on disk, removing from db
11:11:42.8|Debug|EpisodeService|Detaching episode 28058 from file.
11:11:42.9|Debug|SubtitleFileService|Deleting Extra from database for episode file: [80175] Dracula.(2020).S01E03.The.Dark.Compass.1080p.HDTV.h264.AC3.5.1-BRISK.mkv
11:11:42.9|Debug|OtherExtraFileService|Deleting Extra from database for episode file: [80175] Dracula.(2020).S01E03.The.Dark.Compass.1080p.HDTV.h264.AC3.5.1-BRISK.mkv
11:11:42.9|Debug|MetadataFileService|Deleting Extra from database for episode file: [80175] Dracula.(2020).S01E03.The.Dark.Compass.1080p.HDTV.h264.AC3.5.1-BRISK.mkv
11:11:42.9|Info|DiskScanService|Completed scanning disk for Dracula (2020)
11:11:42.9|Debug|ExistingExtraFileService|Looking for existing extra files in /TV/Dracula.2020
11:11:42.9|Debug|DiskScanService|Scanning '/TV/Dracula.2020' for non-video files
11:11:42.9|Debug|DiskScanService|0 non-video files were found in /TV/Dracula.2020
11:11:42.9|Debug|ExistingMetadataImporter|Looking for existing metadata in /TV/Dracula.2020
11:11:42.9|Info|ExistingMetadataImporter|Found 0 existing metadata files
11:11:42.9|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /TV/Dracula.2020
11:11:42.9|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
11:11:42.9|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /TV/Dracula.2020
11:11:42.9|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
11:11:42.9|Info|ExistingExtraFileService|Found 0 extra files
11:11:42.9|Debug|CleanExtraFileService|Cleaning missing metadata files for series: Dracula (2020)
```

This seems to happen to 1-2 random series each day. Monitored, unmonitored, ended, recurring. No matter.
Was not able to find any pattern.
Sadly I also have not been able to pinpoint to a certain version as to when this behavior started either.
Has been happening for at least a couple of months according to my logs, though.

Any advice on how to further debug this would be highly appreciated.

Best,
Tasilo

**Comment by markus101** [comment] 2020-08-13 20:19
Dupe of https://github.com/Sonarr/Sonarr/issues/3846 if you have more information to add please do so there and we can reopen.

**Closed by markus101** 2020-08-13 20:19 UTC
