### ISSUE TITLE
Option to ignore releases that haven't aired

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#5113] opened 2022-08-10 21:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I've been having a problem where Sonarr is grabbing spam/malware from some (all?) of my trackers. All such files are linked episodes that haven't released yet.

### Describe the solution you'd like

My proposed solution is adding an option to ignore releases where the air date/time has not passed yet.

### Describe alternatives you've considered

Sonarr so far has not actually imported any of these fake files, but I'd like to not download them in the first place, so as not to unintentionally seed them. Once an episode has aired, there should be a release that is real and is more preferred by Sonarr using keywords or what have you. These spam files are often reported to the indexer once found and deleted, which may even happen still before the air date, reducing/negating the issue of trying to internally figure out which one to prefer.

### Anything else?

Radarr has this feature

**Comment by thezoggy** [comment] 2022-08-10 21:23
you are just trying to mask the actual issue, getting bad releases from your indexer. 

see: https://github.com/Sonarr/Sonarr/issues/5101

**Comment by bakerboy448** [comment] 2022-08-10 21:53
Get better site that don't allow malware to be uploaded and remain on the site.

this has only become an issue the last week or two with a few malicious actors releasing malicious releases

**Comment by markus101** [comment] 2022-08-10 21:57
This is ultimately a duplicate of https://github.com/Sonarr/Sonarr/issues/969 there are many valid releases that come out before the official air time, see https://github.com/Sonarr/Sonarr/issues/5109 for some recent discussion on that.

We do not have plans for an option to prevent grabbing before the air date at this time, because it's a lot more complicated than a simple option could accomplish and to handle every scenario a lot more complicated than is feasibly implemented and supported.

**Closed by markus101** 2022-08-10 21:57 UTC
Labels: needs-triage

**Comment by candle32** [comment] 2022-08-10 22:31
> you are just trying to mask the actual issue, getting bad releases from your indexer.
> 
> see: #5101

With Usenet in particular, you have issues with spam and malware even with top indexers recommended in any Usenet forum. There are no good Usenet indexers that guarantee a malware-free experience. But delaying Sonarr from grabbing episodes until they are actually released solves the issue in a practical manner.

**Comment by thezoggy** [comment] 2022-08-11 00:41
crap indexers are crap indexers. doesnt matter if its usenet or torrent. indexers that run upto date code/maintained, block/prune such things from being indexed in the first place. if your indexer is serving up the stuff, might be time to look for another indexer.

**Comment by thezoggy** [comment] 2022-08-11 19:25
some things are always a cat and mouse game. 

if your using sites that dont have any staff/moderation, arent updating code to add guards or measures.. the problem will just get worse. some sites are better than others, public torrent sites are generally about the worst of the worst.  which is right now the hot topic with all the .scr spam thats been going on.
