### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by jongregory75** [Sonarr/Sonarr#4548] opened 2021-06-22 13:40 UTC
**Is your feature request related to a problem? Please describe.**
When a user clicks on add series
Then they are given a single input which will do a series lookup by series name or tvdb id.

**Describe the solution you'd like**
When a user clicks on add series
Then they have the option to select from streaming sources ie Netflix, Disney+ etc.
When they select a streaming source
Then all of the TV Shows currently streamed will be presented.

**Describe alternatives you've considered**
https://api.watchmode.com/ has ability to make an api call which returns a list streaming services at which point you would make a 2nd call to retrieve current content based on the streaming services you select in the first query. 

Sample source response
```
[
  {
    "id": 203,
    "name": "Netflix",
    "type": "sub",
    "ios_appstore_url": "http://itunes.apple.com/app/netflix/id363590051",
    "android_playstore_url": "https://play.google.com/store/apps/details?id=com.netflix.mediaclient&amp;hl=en",
    "android_scheme": "nflx",
    "ios_scheme": "nflx",
    "regions": ["US", "CA", "GB", "AU"]
  },
  {
    "id": 157,
    "name": "Hulu",
    "type": "sub",
    "ios_appstore_url": "http://itunes.apple.com/app/hulu-plus/id376510438",
    "android_playstore_url": "https://play.google.com/store/apps/details?id=com.hulu.plus",
    "android_scheme": "hulu",
    "ios_scheme": "hulu",
    "regions": ["US"]
  }
]
```

Sample detail response
```
{
  "id": 345534,
  "title": "Game of Thrones",
  "original_title": "Game of Thrones",
  "plot_overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
  "type": "tv_series",
  "runtime_minutes": 60,
  "year": 2011,
  "end_year": 2019,
  "release_date": "2011-04-17",
  "imdb_id": "tt0944947",
  "tmdb_id": 1399,
  "tmdb_type": "tv",
  "genres": [40, 7, 39, 13, 41],
  "user_rating": 8.7,
  "critic_score": 85,
  "us_rating": "TV-MA",
  "original_language": "en",
  "similar_titles": [
    101216,
    92023,
    15551,
    6822,
    052048,
    135512,
    29319,
    110268,
    0520506,
    0515852,
    124749,
    129354,
    131293,
    17141,
    119816
  ],
  "networks":[1],
  "relevance_percentile": 98.91
}
```

**Comment by bakerboy448** [comment] 2021-06-22 13:44
Duplicate of https://github.com/Sonarr/Sonarr/issues/2972
Duplicate of https://github.com/Sonarr/Sonarr/issues/1674

**Closed by bakerboy448** 2021-06-22 13:44 UTC
