### ISSUE TITLE
Notification for webhook fails on episode import

### ISSUE THREAD

**Issue by leadwolf** [Sonarr/Sonarr#7154] opened 2024-08-29 00:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Notification fails to send to webhook for the "On File Import" event

### Expected Behavior

The notification should be sent to the webhook on file import

### Steps To Reproduce

Create a webhook notification with the "On File Import" event
Wait for an episode to be imported
See in the logs that the notification encountered an error

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.9.2278
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 127
- Database: Sqlite 3.44.2
```

### What branch are you running?

Develop

### Trace Logs?

2024-08-29 00:54:21.4|Debug|NotificationService|No tags set for this notification.
2024-08-29 00:54:21.4|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2024-08-29 00:54:21.4|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<INotification>
2024-08-29 00:54:21.4|Warn|NotificationService|Unable to send OnDownload notification to: autoscan

[v4.0.9.2278] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.Webhook.WebhookEpisodeFile..ctor(EpisodeFile episodeFile) in ./Sonarr.Core/Notifications/Webhook/WebhookEpisodeFile.cs:line 16
   at NzbDrone.Core.Notifications.Webhook.WebhookBase`1.BuildOnDownloadPayload(DownloadMessage message) in ./Sonarr.Core/Notifications/Webhook/WebhookBase.cs:line 56
   at NzbDrone.Core.Notifications.Webhook.Webhook.OnDownload(DownloadMessage message) in ./Sonarr.Core/Notifications/Webhook/Webhook.cs:line 33
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeImportedEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 199

2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent <- NotificationService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent -> HistoryService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent <- HistoryService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent -> DownloadMonitoringService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent <- DownloadMonitoringService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent -> DownloadHistoryService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent <- DownloadHistoryService
2024-08-29 00:54:21.4|Trace|EventAggregator|EpisodeImportedEvent -> CutoffController

**Comment by markus101** [comment] 2024-08-29 00:14
> I have searched the existing open and closed issues

You probably didn't even need to search this was already in the top 5 of recent issues and has a PR open for it already.

Duplicate of #7149

**Closed by markus101** 2024-08-29 00:14 UTC
Labels: needs-triage
